import { EMPTY_CHANGE_SUMMARY } from './utils';
import type { useProjectExplorerPreviewNavigation } from './useProjectExplorerPreviewNavigation';
import type { useProjectExplorerWorkspaceActions } from './useProjectExplorerWorkspaceActions';
import type { useProjectExplorerWorkspaceViewModel } from './useProjectExplorerWorkspaceViewModel';
import type { UseProjectExplorerWorkspaceModelParams } from './workspaceModelTypes';

type WorkspaceModelActions = ReturnType<typeof useProjectExplorerWorkspaceActions>;
type WorkspaceModelNavigation = ReturnType<typeof useProjectExplorerPreviewNavigation>;

export const buildWorkspaceActionsParams = ({
  project,
  client,
  state,
  pathHelpers,
  dataLoading,
  selection,
  treeStateOps,
}: UseProjectExplorerWorkspaceModelParams): Parameters<typeof useProjectExplorerWorkspaceActions>[0] => ({
  changeTracking: {
    changeSummary: state.changeSummary,
    selectedPath: state.selectedPath,
    normalizePath: pathHelpers.normalizePath,
    getParentPath: pathHelpers.getParentPath,
    rootPathNormalized: pathHelpers.rootPathNormalized,
  },
  dnd: {
    treeScrollRef: state.treeScrollRef,
    entriesMap: state.entriesMap,
    loadingPaths: state.loadingPaths,
    normalizePath: pathHelpers.normalizePath,
    toExpandedKey: pathHelpers.toExpandedKey,
    getParentPath: pathHelpers.getParentPath,
    findEntryByPath: selection.findEntryByPath,
    loadEntries: dataLoading.loadEntries,
    setExpandedPaths: state.setExpandedPaths,
  },
  treeActions: {
    client,
    selectedDirPath: selection.selectedDirPath,
    selectedEntry: selection.selectedEntry,
    selectedFilePath: state.selectedFile?.path || null,
    selectedPath: state.selectedPath,
    projectRootPath: project?.rootPath,
    projectId: project?.id,
    actionReloadPath: selection.actionReloadPath,
    normalizePath: pathHelpers.normalizePath,
    getParentPath: pathHelpers.getParentPath,
    toExpandedKey: pathHelpers.toExpandedKey,
    loadEntries: dataLoading.loadEntries,
    loadChangeSummary: dataLoading.loadChangeSummary,
    pruneDeletedPath: treeStateOps.pruneDeletedPath,
    replaceExpandedPathPrefix: treeStateOps.replaceExpandedPathPrefix,
    reloadTreeWithExpanded: treeStateOps.reloadTreeWithExpanded,
    findEntryByPath: selection.findEntryByPath,
    setExpandedPaths: state.setExpandedPaths,
    setSelectedPath: state.setSelectedPath,
    setSelectedFile: state.setSelectedFile,
    setActionLoading: state.setActionLoading,
    setActionError: state.setActionError,
    setActionMessage: state.setActionMessage,
    setMoveConflict: state.setMoveConflict,
    openFile: selection.openFile,
  },
});

export const buildWorkspaceEffectsParams = (
  {
    project,
    state,
    pathHelpers,
    dataLoading,
    logs,
  }: UseProjectExplorerWorkspaceModelParams,
  actions: Pick<WorkspaceModelActions, 'clearDragExpandTimer' | 'clearDragAutoScroll'>,
) => ({
  lifecycle: {
    projectId: project?.id,
    projectRootPath: project?.rootPath,
    toExpandedKey: pathHelpers.toExpandedKey,
    keyToPath: pathHelpers.keyToPath,
    loadEntries: dataLoading.loadEntries,
    tryLoadEntries: dataLoading.tryLoadEntries,
    loadChangeSummary: dataLoading.loadChangeSummary,
    clearDragExpandTimer: actions.clearDragExpandTimer,
    clearDragAutoScroll: actions.clearDragAutoScroll,
    resetLogsState: logs.resetLogsState,
    summaryLoadingRef: state.summaryLoadingRef,
    setEntriesMap: state.setEntriesMap,
    setExpandedPaths: state.setExpandedPaths,
    setSelectedPath: state.setSelectedPath,
    setSelectedFile: state.setSelectedFile,
    setActionMessage: state.setActionMessage,
    setActionError: state.setActionError,
    setActionLoading: state.setActionLoading,
    setContextMenu: state.setContextMenu,
    setMoveConflict: state.setMoveConflict,
    setDraggingEntryPath: state.setDraggingEntryPath,
    setDropTargetDirPath: state.setDropTargetDirPath,
    setChangeSummary: state.setChangeSummary,
    setSummaryError: state.setSummaryError,
    setLoadingSummary: state.setLoadingSummary,
    setExpandedReady: state.setExpandedReady,
    emptyChangeSummary: EMPTY_CHANGE_SUMMARY,
  },
  persistence: {
    projectId: project?.id,
    projectRootPath: project?.rootPath,
    expandedReady: state.expandedReady,
    expandedPaths: state.expandedPaths,
    showOnlyChanged: state.showOnlyChanged,
    setShowOnlyChanged: state.setShowOnlyChanged,
    workspaceTab: state.workspaceTab,
    setWorkspaceTab: state.setWorkspaceTab,
    contextMenu: state.contextMenu,
    setContextMenu: state.setContextMenu,
    isResizing: state.isResizing,
    resizeStartX: state.resizeStartX,
    resizeStartWidth: state.resizeStartWidth,
    setTreeWidth: state.setTreeWidth,
    treeWidth: state.treeWidth,
    setIsResizing: state.setIsResizing,
  },
  summaryRealtime: {
    projectId: project?.id,
    loadChangeSummary: dataLoading.loadChangeSummary,
  },
});

export const buildWorkspaceViewModelParams = (
  {
    project,
    state,
    pathHelpers,
    search,
    logs,
    selection,
    runState,
    codeNav,
    treeStateOps,
    handleGenerateRunnerScriptForContact,
  }: UseProjectExplorerWorkspaceModelParams,
  actions: WorkspaceModelActions,
  navigation: WorkspaceModelNavigation,
): Parameters<typeof useProjectExplorerWorkspaceViewModel>[0] => ({
  project,
  tree: {
    treeWidth: state.treeWidth,
    treeScrollRef: state.treeScrollRef,
    entriesMap: state.entriesMap,
    expandedPaths: state.expandedPaths,
    loadingPaths: state.loadingPaths,
    selectedPath: state.selectedPath,
    selectedEntry: selection.selectedEntry,
    draggingEntryPath: state.draggingEntryPath,
    dropTargetDirPath: state.dropTargetDirPath,
    actionLoading: state.actionLoading,
    actionReloadPath: selection.actionReloadPath,
    contextMenu: state.contextMenu,
    canConfirmCurrent: actions.canConfirmCurrent,
    showOnlyChanged: state.showOnlyChanged,
    changeSummary: state.changeSummary,
    loadingSummary: state.loadingSummary,
    summaryError: state.summaryError,
    actionMessage: state.actionMessage,
    actionError: state.actionError,
    aggregatedChangeKindByPath: actions.aggregatedChangeKindByPath,
  },
  search: {
    searchQuery: search.searchQuery,
    searchCaseSensitive: search.searchCaseSensitive,
    searchWholeWord: search.searchWholeWord,
    searchResults: search.searchResults,
    searchLoading: search.searchLoading,
    searchError: search.searchError,
    searchTruncated: search.searchTruncated,
    activeSearchHitId: search.activeSearchHitId,
    activeSearchHitIndex: search.activeSearchHitIndex,
    totalSearchHits: search.totalSearchHits,
    previewTargetLine: search.previewTargetLine,
    previewTargetLineRevision: search.previewTargetLineRevision,
    canOpenPreviousSearchHit: search.canOpenPreviousSearchHit,
    canOpenNextSearchHit: search.canOpenNextSearchHit,
  },
  preview: {
    loadingFile: state.loadingFile,
    error: state.error,
    selectedFile: state.selectedFile,
    selectedLog: logs.selectedLog,
  },
  codeNav: {
    navCapabilities: codeNav.navCapabilities,
    navCapabilitiesLoading: codeNav.navCapabilitiesLoading,
    navCapabilitiesError: codeNav.navCapabilitiesError,
    selectedToken: codeNav.selectedToken,
    selectedTokenLine: codeNav.selectedTokenLine,
    selectedTokenColumn: codeNav.selectedTokenColumn,
    navResult: codeNav.navResult,
    navRequestKind: codeNav.navRequestKind,
    navLoading: codeNav.navLoading,
    navError: codeNav.navError,
    activeNavLocationId: codeNav.activeNavLocationId,
    canGoBackFromNav: codeNav.canGoBackFromNav,
    documentSymbols: codeNav.documentSymbols,
    documentSymbolsLoading: codeNav.documentSymbolsLoading,
    documentSymbolsError: codeNav.documentSymbolsError,
  },
  run: {
    canRunFile: runState.canRunFile,
    handleRunFile: runState.handleRunFile,
    runStatus: runState.runStatus,
    runCatalogLoading: runState.runCatalogLoading,
    runCatalogError: runState.runCatalogError,
    projectMembers: runState.projectMembers,
    projectMembersLoading: runState.projectMembersLoading,
    projectMembersError: runState.projectMembersError,
    runnerScriptExists: runState.runnerScriptExists,
    runnerScriptChecking: runState.runnerScriptChecking,
    runnerScriptPath: runState.runnerScriptPath,
    runnerStartCommand: runState.runnerStartCommand,
    runnerStopCommand: runState.runnerStopCommand,
    runnerRestartCommand: runState.runnerRestartCommand,
    starting: runState.starting,
    stopping: runState.stopping,
    restarting: runState.restarting,
    runnerMessage: runState.runnerMessage,
    runnerError: runState.runnerError,
    activeRun: runState.activeRun,
    activeTerminalBusy: runState.activeTerminalBusy,
    handleRunnerStart: runState.handleRunnerStart,
    handleRunnerStop: runState.handleRunnerStop,
    handleRunnerRestart: runState.handleRunnerRestart,
    refreshRunnerState: runState.refreshRunnerState,
    handleGenerateRunnerScriptForContact,
  },
  interactions: {
    normalizePath: pathHelpers.normalizePath,
    toExpandedKey: pathHelpers.toExpandedKey,
    canDropToDirectory: actions.canDropToDirectory,
    setSelectedPath: state.setSelectedPath,
    setSelectedFile: state.setSelectedFile,
    setShowOnlyChanged: state.setShowOnlyChanged,
    setDraggingEntryPath: state.setDraggingEntryPath,
    setDropTargetDirPath: state.setDropTargetDirPath,
    setMoveConflict: state.setMoveConflict,
    setContextMenu: state.setContextMenu,
    clearDragExpandTimer: actions.clearDragExpandTimer,
    cancelDragExpandIfMatches: actions.cancelDragExpandIfMatches,
    scheduleDragExpand: actions.scheduleDragExpand,
    clearDragAutoScroll: actions.clearDragAutoScroll,
    startDragAutoScroll: actions.startDragAutoScroll,
    selectProjectRoot: selection.selectProjectRoot,
    toggleDir: treeStateOps.toggleDir,
    openFile: selection.openFile,
    handleCreateDirectory: actions.handleCreateDirectory,
    handleCreateFile: actions.handleCreateFile,
    handleRefresh: actions.handleRefresh,
    handleConfirmCurrentChanges: actions.handleConfirmCurrentChanges,
    handleConfirmAllChanges: actions.handleConfirmAllChanges,
    handleSearchQueryChange: search.setSearchQuery,
    handleSearchCaseSensitiveChange: search.setSearchCaseSensitive,
    handleSearchWholeWordChange: search.setSearchWholeWord,
    handleSearchInProject: search.runSearchQuery,
    handleClearSearch: search.clearSearch,
    handleActivateSearchHit: search.activateSearchHit,
    handleOpenSearchHit: (hit) => search.handleOpenSearchHit(hit, selection.openFile),
    handleOpenPreviousSearchHit: () => search.openPreviousSearchHit(selection.openFile),
    handleOpenNextSearchHit: () => search.openNextSearchHit(selection.openFile),
    handleTokenSelection: navigation.handlePreviewTokenSelection,
    clearTokenSelection: codeNav.clearTokenSelection,
    requestDefinition: codeNav.requestDefinition,
    requestReferences: codeNav.requestReferences,
    handleOpenNavLocation: codeNav.handleOpenNavLocation,
    goBackFromNav: codeNav.goBackFromNav,
    handleOpenDocumentSymbol: navigation.handleOpenDocumentSymbol,
    handleMoveEntryByDrop: actions.handleMoveEntryByDrop,
    handleDownloadSelected: actions.handleDownloadSelected,
    handleDeleteSelected: actions.handleDeleteSelected,
  },
});
