// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Required Notice: Copyright (c) 2025 AI Chat Team

use serde_json::{json, Value};

use super::{path_only_schema, tool};

pub(super) fn tool_definitions() -> Vec<Value> {
    vec![
        inspect_pptx_tool(),
        inspect_pptx_charts_tool(),
        replace_pptx_chart_tool(),
        inspect_pptx_table_tool(),
        render_presentation_pages_tool(),
        create_pptx_tool(),
    ]
}

fn inspect_pptx_tool() -> Value {
    tool(
        "inspect_pptx",
        "Inspect a PPTX presentation locally and report widescreen dimensions, ordered slide text previews, image relationships, table summaries, media files, and speaker-note previews.",
        path_only_schema(),
    )
}

fn inspect_pptx_charts_tool() -> Value {
    tool(
        "inspect_pptx_charts",
        "Inspect standard internally related DrawingML chart parts in true visible slide order, returning chart type, raw bar direction, radar style, scatter style, and bubble-group metadata, title, legend state and position, data-label mode, literal or formula-backed axis titles, recognized or custom per-series RGB colors, bounded line/scatter marker style/size and smoothing with raw values, formulas, bounded cached series/category/X/Y/bubble-size previews, full chart XML SHA-256, embedded-workbook metadata, and an exact edit snapshot only when the chart is byte-identical to ChatOS canonical self-contained output. External, shared, missing, unreferenced, chartEx, or over-limit chart structures fail closed.",
        json!({
            "type":"object",
            "properties":{
                "path":{"type":"string","description":"Workspace-relative source .pptx path."},
                "slide_numbers":{"type":"array","minItems":1,"maxItems":200,"uniqueItems":true,"items":{"type":"integer","minimum":1,"maximum":200},"description":"Optional one-based positions in true visible presentation order. Omit to inspect charts on every slide."}
            },
            "required":["path"],
            "additionalProperties":false
        }),
    )
}

fn replace_pptx_chart_tool() -> Value {
    tool(
        "replace_pptx_chart",
        "Replace one uniquely owned standard chart only when its XML is byte-identical to the canonical self-contained column/bar/line/pie/area/doughnut/radar/scatter/bubble form generated by ChatOS. The bounded replacement may also update per-series RGB colors and bubble sizes, canonical line/scatter marker style/size and smoothing, legend position, value/percentage data labels, and axis titles where supported. Requires the exact chart XML SHA-256 and complete edit snapshot from inspect_pptx_charts, writes a distinct PPTX, and preserves the slide frame, relationship, chart part name, and every unrelated package entry.",
        json!({
            "type":"object",
            "properties":{
                "path":{"type":"string","description":"Workspace-relative source .pptx path. The source is never modified."},
                "target_path":{"type":"string","description":"Distinct workspace-relative .pptx output path."},
                "slide_number":{"type":"integer","minimum":1,"maximum":200,"description":"One-based position in true visible presentation order."},
                "chart_number":{"type":"integer","minimum":1,"maximum":50,"description":"One-based standard chart order within the selected slide."},
                "expected_chart_xml_sha256":{"type":"string","pattern":"^[0-9a-f]{64}$","description":"Exact full chart XML SHA-256 returned at the same address by inspect_pptx_charts."},
                "expected_self_contained_edit_snapshot":self_contained_pptx_chart_schema(
                    "Complete canonical chart snapshot returned by inspect_pptx_charts. Every field is required and stale or altered snapshots fail closed.",
                    true,
                ),
                "replacement":self_contained_pptx_chart_schema(
                    "Replacement chart within the bounded self-contained column, bar, line, pie, area, doughnut, radar, scatter, or bubble contract.",
                    false,
                ),
                "overwrite":{"type":"boolean","default":false}
            },
            "required":["path","target_path","slide_number","chart_number","expected_chart_xml_sha256","expected_self_contained_edit_snapshot","replacement"],
            "additionalProperties":false
        }),
    )
}

fn inspect_pptx_table_tool() -> Value {
    tool(
        "inspect_pptx_table",
        "Inspect one DrawingML table by visible slide position and table order, returning bounded row/column cell-text previews, exact full-cell XML SHA-256 snapshots for eligible simple cells, and conservative eligibility for cell replacement, cell-format copying, and row/column structure edits.",
        json!({
            "type":"object",
            "properties":{
                "path":{"type":"string","description":"Workspace-relative source .pptx path."},
                "slide_number":{"type":"integer","minimum":1,"maximum":200,"description":"One-based position in true visible presentation order."},
                "table_number":{"type":"integer","minimum":1,"maximum":100,"description":"One-based DrawingML table order within the selected slide."}
            },
            "required":["path","slide_number","table_number"],
            "additionalProperties":false
        }),
    )
}

fn render_presentation_pages_tool() -> Value {
    tool(
        "render_presentation_pages",
        "Validate one regular non-symlink workspace PPTX, reject active, embedded, or externally connected content, convert it with the packaged manifest-verified LibreOffice runtime, and attach a bounded visible-slide range as transient PNG model input for visual QA. Rendering does not itself claim that visual review passed.",
        json!({
            "type":"object",
            "properties":{
                "path":{"type":"string","description":"Workspace-relative source .pptx path."},
                "first_slide":{"type":"integer","minimum":1,"maximum":200,"default":1,"description":"First slide in true visible presentation order."},
                "last_slide":{"type":"integer","minimum":1,"maximum":200,"description":"Inclusive final slide in true visible presentation order. At most 8 slides may be attached per call; omit to render up to 8 slides from first_slide."},
                "dpi":{"type":"integer","minimum":96,"maximum":160,"default":120},
                "timeout_seconds":{"type":"integer","minimum":15,"maximum":180,"default":120},
                "pdf_target_path":{"type":"string","description":"Optional distinct workspace-relative .pdf export after the converted PDF passes validation."},
                "overwrite":{"type":"boolean","default":false,"description":"Allow replacement only for an existing regular non-symlink PDF export target."}
            },
            "required":["path"],
            "additionalProperties":false
        }),
    )
}

fn create_pptx_tool() -> Value {
    tool(
        "create_pptx",
        "Create a bounded editable widescreen PPTX locally with title/body, title-only, section, two-column, image-right, full-image, simple rectangular table, or self-contained standard DrawingML column/bar/line/pie/area/doughnut/radar/scatter/bubble chart layouts with optional canonical RGB series colors, bounded line/scatter marker styles and smoothing, optional PNG/JPEG images, bullet lines, and speaker notes.",
        create_pptx_input_schema(),
    )
}

pub(super) fn create_pptx_input_schema() -> Value {
    let chart_schema = self_contained_pptx_chart_schema(
        "Required only for chart layout. Creates one self-contained editable standard DrawingML chart with literal cached data and no embedded workbook, external data, formulas, macros, or executable content.",
        false,
    );
    json!({
            "type":"object",
            "properties":{
                "target_path":{"type":"string","description":"Workspace-relative .pptx output path."},
                "slides":{
                    "type":"array",
                    "minItems":1,
                    "maxItems":200,
                    "items":{
                        "type":"object",
                        "properties":{
                            "title":{"type":"string","maxLength":1000},
                            "layout":{"type":"string","enum":["title_body","title_only","section","two_column","image_right","image_full","table","chart"],"default":"title_body"},
                            "body":{"type":"string","maxLength":100000,"description":"Body or subtitle text. Lines beginning with '- ' or '* ' become bullets."},
                            "left_body":{"type":"string","maxLength":100000,"description":"Left-column text for two_column layout."},
                            "right_body":{"type":"string","maxLength":100000,"description":"Right-column text for two_column layout."},
                            "notes":{"type":"string","maxLength":100000,"description":"Optional editable speaker notes."},
                            "table":{
                                "type":"object",
                                "description":"Required only for table layout. Creates one simple editable rectangular DrawingML table below the title.",
                                "properties":{
                                    "cells":{
                                        "type":"array",
                                        "minItems":1,
                                        "maxItems":50,
                                        "items":{
                                            "type":"array",
                                            "minItems":1,
                                            "maxItems":20,
                                            "items":{"type":"string","maxLength":10000}
                                        }
                                    },
                                    "header_row":{"type":"boolean","default":true,"description":"Bold and style the first row as a header."}
                                },
                                "required":["cells"],
                                "additionalProperties":false
                            },
                            "chart": chart_schema,
                            "image":{
                                "type":"object",
                                "properties":{
                                    "path":{"type":"string","description":"Workspace-relative .png, .jpg, or .jpeg file, at most 10 MiB and 40 megapixels."},
                                    "alt_text":{"type":"string","minLength":1,"maxLength":1024,"default":"Presentation image"},
                                    "fit":{"type":"string","enum":["contain","cover"],"default":"contain"}
                                },
                                "required":["path"],
                                "additionalProperties":false
                            }
                        },
                        "required":["title"],
                        "additionalProperties":false
                    }
                },
                "overwrite":{"type":"boolean","default":false}
            },
            "required":["target_path","slides"],
            "additionalProperties":false
    })
}

fn self_contained_pptx_chart_schema(description: &str, complete_snapshot: bool) -> Value {
    let required = if complete_snapshot {
        json!([
            "type",
            "title",
            "categories",
            "x_values",
            "x_axis_minimum",
            "x_axis_maximum",
            "x_axis_log_base",
            "x_axis_major_tick_mark",
            "x_axis_minor_tick_mark",
            "x_axis_major_unit",
            "x_axis_minor_unit",
            "x_axis_number_format",
            "series",
            "show_legend",
            "legend_position",
            "data_labels",
            "category_axis_title",
            "value_axis_title",
            "secondary_value_axis_title",
            "value_axis_minimum",
            "value_axis_maximum",
            "value_axis_log_base",
            "value_axis_major_tick_mark",
            "value_axis_minor_tick_mark",
            "value_axis_major_unit",
            "value_axis_minor_unit",
            "value_axis_number_format",
            "secondary_value_axis_minimum",
            "secondary_value_axis_maximum",
            "secondary_value_axis_log_base",
            "secondary_value_axis_major_tick_mark",
            "secondary_value_axis_minor_tick_mark",
            "secondary_value_axis_major_unit",
            "secondary_value_axis_minor_unit",
            "secondary_value_axis_number_format"
        ])
    } else {
        json!(["type", "series"])
    };
    let series_required = if complete_snapshot {
        json!([
            "name",
            "values",
            "value_axis",
            "color",
            "marker_style",
            "marker_size",
            "smooth",
            "bubble_sizes"
        ])
    } else {
        json!(["name", "values"])
    };
    let mut schema = json!({
        "type":"object",
        "description":description,
        "properties":{
            "type":{"type":"string","enum":["column","bar","line","pie","area","doughnut","radar","scatter","bubble"],"description":"column and bar create clustered vertical and horizontal bar charts respectively; line, pie, area, doughnut, radar, scatter, and bubble use bounded standard 2D forms. Radar uses exact standard style without markers. Scatter uses exact lineMarker style with shared numeric x_values. Bubble uses exact canonical group metadata with shared numeric x_values and one positive bubble_sizes value per point. Pie and doughnut require exactly one non-negative series with at least one positive value."},
            "title":{"type":"string","maxLength":1000,"description":"Optional title inside the chart. The slide title remains a separate editable text box."},
            "categories":{"type":["array","null"],"minItems":1,"maxItems":50,"items":{"type":"string","minLength":1,"maxLength":1000},"default":null,"description":"Required string categories for charts other than scatter or bubble. Scatter and bubble charts require null or omission."},
            "x_values":{"type":["array","null"],"minItems":1,"maxItems":50,"items":{"type":"number","minimum":-1000000000000i64,"maximum":1000000000000i64},"default":null,"description":"Required shared numeric X values for scatter and bubble charts. Other charts require null or omission."},
            "series":{
                "type":"array",
                "minItems":1,
                "maxItems":10,
                "items":{
                    "type":"object",
                    "properties":{
                        "name":{"type":"string","minLength":1,"maxLength":1000},
                        "values":{"type":"array","minItems":1,"maxItems":50,"items":{"type":"number","minimum":-1000000000000i64,"maximum":1000000000000i64}},
                        "bubble_sizes":{"type":["array","null"],"minItems":1,"maxItems":50,"items":{"type":"number","exclusiveMinimum":0,"maximum":1000000000000i64},"default":null,"description":"Required for bubble charts with exactly one finite positive size per shared x_value. Other chart types require null or omission."},
                        "value_axis":{"type":"string","enum":["primary","secondary"],"default":"primary","description":"Assign this series to the primary value axis (left for column/line/area/radar/scatter/bubble, bottom for bar) or canonical secondary value axis (right for column/line/area/radar/scatter/bubble, top for bar). Secondary is supported only for column, bar, line, area, radar, scatter, or bubble charts and requires at least one primary series."},
                        "color":{"type":["string","null"],"pattern":"^#[0-9A-Fa-f]{6}$","default":null,"description":"Optional canonical RGB series color in #RRGGBB form. Values are normalized to uppercase; line, radar, and scatter charts use the series line color while other supported charts use the series fill color."},
                        "marker_style":{"type":["string","null"],"enum":["none","circle","square","diamond","triangle",null],"default":null,"description":"Optional canonical line/scatter-series marker style. Line and scatter charts default null to circle; other charts require null or omission."},
                        "marker_size":{"type":["integer","null"],"minimum":2,"maximum":72,"default":null,"description":"Optional line/scatter-series marker size. Non-none line/scatter markers default null to 5; marker_style=none and other charts require null or omission."},
                        "smooth":{"type":["boolean","null"],"default":null,"description":"Optional canonical line/scatter-series smoothing flag. Line and scatter charts default null to false; other charts require null or omission."}
                    },
                    "required":series_required,
                    "additionalProperties":false
                }
            },
            "show_legend":{"type":"boolean","default":true},
            "legend_position":{"type":"string","enum":["right","left","top","bottom"],"default":"right","description":"Canonical legend position. When show_legend=false this must remain right so hidden legend state has one unambiguous snapshot."},
            "data_labels":{"type":"string","enum":["none","value","percentage"],"default":"none","description":"Show no data labels, numeric values, or percentages. Percentage is supported only for pie and doughnut charts."},
            "category_axis_title":{"type":"string","maxLength":1000,"default":"","description":"Optional category-axis title for column, bar, line, area, or radar charts; for scatter and bubble this is the bottom numeric X-axis title. Pie and doughnut charts reject axis titles."},
            "value_axis_title":{"type":"string","maxLength":1000,"default":"","description":"Optional primary value-axis title (left for column/line/area/radar/scatter/bubble, bottom for bar). Pie and doughnut charts reject axis titles."},
            "secondary_value_axis_title":{"type":"string","maxLength":1000,"default":"","description":"Optional secondary value-axis title (right for column/line/area/radar/scatter/bubble, top for bar). It requires at least one primary and one secondary column, bar, line, area, radar, scatter, or bubble series."},
            "value_axis_minimum":{"type":["number","null"],"minimum":-1000000000000i64,"maximum":1000000000000i64,"default":null,"description":"Optional explicit primary value-axis minimum. It must not hide any primary-axis series value and must be below value_axis_maximum when both are set."},
            "value_axis_maximum":{"type":["number","null"],"minimum":-1000000000000i64,"maximum":1000000000000i64,"default":null,"description":"Optional explicit primary value-axis maximum. It must not hide any primary-axis series value and must be above value_axis_minimum when both are set."},
            "value_axis_log_base":{"type":["number","null"],"minimum":2,"maximum":1000,"default":null,"description":"Optional logarithmic base for the primary value axis. Every primary-axis series value and every explicit primary bound must be strictly positive."},
            "value_axis_major_tick_mark":{"type":"string","enum":["none","inside","outside","cross"],"default":"none","description":"Canonical primary value-axis major tick-mark style."},
            "value_axis_minor_tick_mark":{"type":"string","enum":["none","inside","outside","cross"],"default":"none","description":"Canonical primary value-axis minor tick-mark style."},
            "value_axis_major_unit":{"type":["number","null"],"exclusiveMinimum":0,"maximum":1000000000000i64,"default":null,"description":"Optional explicit primary value-axis major unit. It must exceed value_axis_minor_unit when both are set and must not exceed an explicit minimum/maximum span."},
            "value_axis_minor_unit":{"type":["number","null"],"exclusiveMinimum":0,"maximum":1000000000000i64,"default":null,"description":"Optional explicit primary value-axis minor unit. It must remain below value_axis_major_unit when both are set and must not exceed an explicit minimum/maximum span."},
            "value_axis_number_format":{"type":"string","enum":["general","integer","decimal_1","decimal_2","thousands","thousands_2","percentage","percentage_1","scientific"],"default":"general","description":"Canonical primary value-axis number format."},
            "secondary_value_axis_minimum":{"type":["number","null"],"minimum":-1000000000000i64,"maximum":1000000000000i64,"default":null,"description":"Optional explicit secondary value-axis minimum. It requires secondary series and must not hide their values."},
            "secondary_value_axis_maximum":{"type":["number","null"],"minimum":-1000000000000i64,"maximum":1000000000000i64,"default":null,"description":"Optional explicit secondary value-axis maximum. It requires secondary series and must not hide their values."},
            "secondary_value_axis_log_base":{"type":["number","null"],"minimum":2,"maximum":1000,"default":null,"description":"Optional logarithmic base for the secondary value axis. It requires secondary series, and every secondary-axis series value and explicit secondary bound must be strictly positive."},
            "secondary_value_axis_major_tick_mark":{"type":"string","enum":["none","inside","outside","cross"],"default":"none","description":"Canonical secondary value-axis major tick-mark style. Non-none styles require secondary series."},
            "secondary_value_axis_minor_tick_mark":{"type":"string","enum":["none","inside","outside","cross"],"default":"none","description":"Canonical secondary value-axis minor tick-mark style. Non-none styles require secondary series."},
            "secondary_value_axis_major_unit":{"type":["number","null"],"exclusiveMinimum":0,"maximum":1000000000000i64,"default":null,"description":"Optional explicit secondary value-axis major unit. It requires secondary series, must exceed the secondary minor unit, and must not exceed an explicit secondary range."},
            "secondary_value_axis_minor_unit":{"type":["number","null"],"exclusiveMinimum":0,"maximum":1000000000000i64,"default":null,"description":"Optional explicit secondary value-axis minor unit. It requires secondary series, must remain below the secondary major unit, and must not exceed an explicit secondary range."},
            "secondary_value_axis_number_format":{"type":"string","enum":["general","integer","decimal_1","decimal_2","thousands","thousands_2","percentage","percentage_1","scientific"],"default":"general","description":"Canonical secondary value-axis number format. Non-general formats require secondary series."}
        },
        "required":required,
        "allOf":[
            {
                "if":{"properties":{"type":{"enum":["scatter","bubble"]}},"required":["type"]},
                "then":{"required":["x_values"]},
                "else":{"required":["categories"]}
            },
            {
                "if":{"properties":{"type":{"const":"bubble"}},"required":["type"]},
                "then":{"properties":{"series":{"items":{"required":["name","values","bubble_sizes"]}}}}
            }
        ],
        "additionalProperties":false
    });
    if let Some(Value::Object(properties)) = schema.get_mut("properties") {
        properties.insert("x_axis_minimum".to_string(), json!({"type":["number","null"],"minimum":-1000000000000i64,"maximum":1000000000000i64,"default":null,"description":"Optional explicit scatter/bubble X-axis minimum. It must include every shared x_values point and remain below x_axis_maximum when both are set. Other charts require null or omission."}));
        properties.insert("x_axis_maximum".to_string(), json!({"type":["number","null"],"minimum":-1000000000000i64,"maximum":1000000000000i64,"default":null,"description":"Optional explicit scatter/bubble X-axis maximum. It must include every shared x_values point and remain above x_axis_minimum when both are set. Other charts require null or omission."}));
        properties.insert("x_axis_log_base".to_string(), json!({"type":["number","null"],"minimum":2,"maximum":1000,"default":null,"description":"Optional logarithmic base for the scatter/bubble X axis. Every x_values point and every explicit X bound must be strictly positive. Other charts require null or omission."}));
        properties.insert("x_axis_major_tick_mark".to_string(), json!({"type":"string","enum":["none","inside","outside","cross"],"default":"none","description":"Canonical scatter/bubble X-axis major tick-mark style. Other charts require none or omission."}));
        properties.insert("x_axis_minor_tick_mark".to_string(), json!({"type":"string","enum":["none","inside","outside","cross"],"default":"none","description":"Canonical scatter/bubble X-axis minor tick-mark style. Other charts require none or omission."}));
        properties.insert("x_axis_major_unit".to_string(), json!({"type":["number","null"],"exclusiveMinimum":0,"maximum":1000000000000i64,"default":null,"description":"Optional explicit scatter/bubble X-axis major unit. It must exceed x_axis_minor_unit when both are set and must not exceed an explicit X-axis span. Other charts require null or omission."}));
        properties.insert("x_axis_minor_unit".to_string(), json!({"type":["number","null"],"exclusiveMinimum":0,"maximum":1000000000000i64,"default":null,"description":"Optional explicit scatter/bubble X-axis minor unit. It must remain below x_axis_major_unit when both are set and must not exceed an explicit X-axis span. Other charts require null or omission."}));
        properties.insert("x_axis_number_format".to_string(), json!({"type":"string","enum":["general","integer","decimal_1","decimal_2","thousands","thousands_2","percentage","percentage_1","scientific"],"default":"general","description":"Canonical scatter/bubble X-axis number format. Other charts require general or omission."}));
    }
    schema
}
