use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            MCP_MANAGEMENT_REQUIRE_SIGNED_INTERNAL_REQUESTS_CONFIG_KEY,
            "内部请求必须签名",
            "MCP Management Service 是否必须校验来自内部服务的签名请求",
            "MCP Management / Security",
            "service",
            Some("mcp-management-service"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_REQUIRE_SIGNED_INTERNAL_REQUESTS"],
            336,
            now,
        ),
        definition(
            MCP_MANAGEMENT_ASYNC_TOOL_DISPATCH_MODE_CONFIG_KEY,
            "异步工具分发模式",
            "MCP Management 对长耗时工具调用统一使用 RabbitMQ 持久化队列",
            "MCP Management / Async Tool Dispatch",
            "service",
            Some("mcp-management-service"),
            "enum",
            json!("rabbitmq"),
            None,
            None,
            &["rabbitmq"],
            "restart_required",
            &["MCP_MANAGEMENT_ASYNC_TOOL_DISPATCH_MODE"],
            340,
            now,
        ),
        definition(
            MCP_MANAGEMENT_ASYNC_TOOL_WORKER_CONCURRENCY_CONFIG_KEY,
            "异步工具 Worker 并发数",
            "MCP Management 异步工具分发消费者的并发处理数量",
            "MCP Management / Async Tool Dispatch",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(8),
            Some(1),
            Some(512),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_ASYNC_TOOL_WORKER_CONCURRENCY"],
            342,
            now,
        ),
        definition(
            MCP_MANAGEMENT_ASYNC_TOOL_RABBITMQ_URL_CONFIG_KEY,
            "RabbitMQ 连接地址",
            "MCP Management 异步工具分发使用的 RabbitMQ AMQP 连接串",
            "MCP Management / Async Tool Dispatch",
            "service",
            Some("mcp-management-service"),
            "string",
            json!(DEFAULT_LOCAL_RABBITMQ_URL),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_ASYNC_TOOL_RABBITMQ_URL"],
            346,
            now,
        ),
        definition(
            MCP_MANAGEMENT_ASYNC_TOOL_RABBITMQ_EXCHANGE_CONFIG_KEY,
            "RabbitMQ Exchange",
            "MCP Management 异步工具分发写入和消费使用的 Exchange 名称",
            "MCP Management / Async Tool Dispatch",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("mcp_management"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_ASYNC_TOOL_RABBITMQ_EXCHANGE"],
            348,
            now,
        ),
        definition(
            MCP_MANAGEMENT_INVOCATION_CANCELLATION_EXCHANGE_CONFIG_KEY,
            "Invocation 取消事件 Exchange",
            "MCP Management 在服务实例之间广播调用取消事件使用的 RabbitMQ Fanout Exchange",
            "MCP Management / Invocation Coordination",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("mcp_management.cancellations"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_INVOCATION_CANCELLATION_EXCHANGE"],
            349,
            now,
        ),
        definition(
            MCP_MANAGEMENT_ASYNC_TOOL_DISPATCH_QUEUE_CONFIG_KEY,
            "RabbitMQ Dispatch Queue",
            "MCP Management 异步工具分发消费的队列名称",
            "MCP Management / Async Tool Dispatch",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("mcp_management.async.dispatch"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_ASYNC_TOOL_DISPATCH_QUEUE"],
            350,
            now,
        ),
        definition(
            MCP_MANAGEMENT_ASYNC_TOOL_QUEUE_MAX_LENGTH_CONFIG_KEY,
            "RabbitMQ 队列最大消息数",
            "MCP Management 异步工具主队列允许积压的最大消息数量，超限时拒绝发布",
            "MCP Management / Async Tool Dispatch",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(10_000),
            Some(1),
            Some(i32::MAX as i64),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_ASYNC_TOOL_QUEUE_MAX_LENGTH"],
            3501,
            now,
        ),
        definition(
            MCP_MANAGEMENT_ASYNC_TOOL_QUEUE_MAX_BYTES_CONFIG_KEY,
            "RabbitMQ 队列最大字节数",
            "MCP Management 异步工具主队列允许积压的最大消息字节数，超限时拒绝发布",
            "MCP Management / Async Tool Dispatch",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(256_i64 * 1024 * 1024),
            Some(1_024),
            Some(i64::MAX),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_ASYNC_TOOL_QUEUE_MAX_BYTES"],
            3502,
            now,
        ),
        definition(
            MCP_MANAGEMENT_PRESSURE_QUEUE_ELEVATED_PERCENT_CONFIG_KEY,
            "MCP 队列升压百分比",
            "MCP Management 自有异步工具主队列容量使用率达到该百分比时上报 elevated",
            "MCP Management / Pressure",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(70),
            Some(1),
            Some(99),
            &[],
            "hot_reload",
            &[],
            35021,
            now,
        ),
        definition(
            MCP_MANAGEMENT_PRESSURE_QUEUE_CRITICAL_PERCENT_CONFIG_KEY,
            "MCP 队列临界百分比",
            "MCP Management 自有异步工具主队列容量使用率达到该百分比时上报 critical",
            "MCP Management / Pressure",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(90),
            Some(1),
            Some(99),
            &[],
            "hot_reload",
            &[],
            35022,
            now,
        ),
        definition(
            MCP_MANAGEMENT_PRESSURE_REPORT_INTERVAL_MS_CONFIG_KEY,
            "MCP 压力上报间隔",
            "MCP Management 刷新压力策略并上报自身队列压力信号的间隔",
            "MCP Management / Pressure",
            "service",
            Some("mcp-management-service"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "hot_reload",
            &[],
            35023,
            now,
        ),
        definition(
            MCP_MANAGEMENT_ASYNC_TOOL_RABBITMQ_RECONNECT_MS_CONFIG_KEY,
            "RabbitMQ 重连间隔（毫秒）",
            "MCP Management 工具命令消费者断线后的重连等待时间",
            "MCP Management / Async Tool Dispatch",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(3_000),
            Some(100),
            Some(60_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_ASYNC_TOOL_RABBITMQ_RECONNECT_MS"],
            3503,
            now,
        ),
        definition(
            MCP_MANAGEMENT_ASYNC_TOOL_MAX_DELIVERY_ATTEMPTS_CONFIG_KEY,
            "异步工具最大投递次数",
            "MCP Management 异步工具调用在进入失败终态或死信队列前允许的总投递次数",
            "MCP Management / Async Tool Dispatch",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(5),
            Some(1),
            Some(100),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_ASYNC_TOOL_MAX_DELIVERY_ATTEMPTS"],
            3506,
            now,
        ),
        definition(
            MCP_MANAGEMENT_ASYNC_TOOL_RETRY_DELAY_MS_CONFIG_KEY,
            "异步工具重试延迟（毫秒）",
            "MCP Management 异步工具调用发生可重试基础设施错误后的延迟重投时间",
            "MCP Management / Async Tool Dispatch",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(5_000),
            Some(100),
            Some(3_600_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_ASYNC_TOOL_RETRY_DELAY_MS"],
            3507,
            now,
        ),
        definition(
            MCP_MANAGEMENT_ASYNC_TOOL_RETRY_QUEUE_CONFIG_KEY,
            "RabbitMQ Retry Queue",
            "MCP Management 异步工具可重试消息的延迟队列名称",
            "MCP Management / Async Tool Dispatch",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("mcp_management.async.retry"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_ASYNC_TOOL_RETRY_QUEUE"],
            3508,
            now,
        ),
        definition(
            MCP_MANAGEMENT_ASYNC_TOOL_DEAD_LETTER_QUEUE_CONFIG_KEY,
            "RabbitMQ Dead Letter Queue",
            "MCP Management 异步工具无效消息或重试耗尽消息的死信队列名称",
            "MCP Management / Async Tool Dispatch",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("mcp_management.async.dlq"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_ASYNC_TOOL_DEAD_LETTER_QUEUE"],
            3509,
            now,
        ),
    ]
}
