use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            MCP_MANAGEMENT_PLUGIN_MANAGEMENT_SERVICE_BASE_URL_CONFIG_KEY,
            "Plugin Management Internal Base URL",
            "MCP Management 调用 Plugin Management 控制面时使用的强制 mTLS 地址",
            "MCP Management / Downstream",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("https://plugin-management-backend:39262"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_PLUGIN_MANAGEMENT_SERVICE_BASE_URL"],
            3612,
            now,
        ),
        definition(
            MCP_MANAGEMENT_PROJECT_SERVICE_BASE_URL_CONFIG_KEY,
            "Project Service Base URL",
            "MCP Management 调用 Project Service 时使用的基础地址",
            "MCP Management / Downstream",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("https://project-management-backend:39212"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_PROJECT_SERVICE_BASE_URL"],
            3613,
            now,
        ),
        definition(
            MCP_MANAGEMENT_TASK_RUNNER_SERVICE_BASE_URL_CONFIG_KEY,
            "Task Runner Base URL",
            "MCP Management 调用 Task Runner 时使用的基础地址",
            "MCP Management / Downstream",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("https://task-runner-backend:39092"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_TASK_RUNNER_SERVICE_BASE_URL"],
            3614,
            now,
        ),
        definition(
            MCP_MANAGEMENT_CHATOS_SERVICE_BASE_URL_CONFIG_KEY,
            "Chatos Base URL",
            "MCP Management 调用 Chatos Backend 时使用的基础地址",
            "MCP Management / Downstream",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("https://127.0.0.1:3999"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_CHATOS_SERVICE_BASE_URL"],
            3615,
            now,
        ),
        definition(
            MCP_MANAGEMENT_LOCAL_CONNECTOR_SERVICE_BASE_URL_CONFIG_KEY,
            "Local Connector Base URL",
            "MCP Management 调用 Local Connector Service 时使用的基础地址",
            "MCP Management / Downstream",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("https://127.0.0.1:39232"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_LOCAL_CONNECTOR_SERVICE_BASE_URL"],
            3616,
            now,
        ),
    ]
}
