use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            MCP_MANAGEMENT_ALLOWED_INTERNAL_CALLERS_CONFIG_KEY,
            "允许的内部调用方",
            "允许调用 MCP Management 内部接口的服务标识，使用逗号分隔",
            "MCP Management / Security",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("chatos,task-runner,project-service,configuration-center"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_ALLOWED_INTERNAL_CALLERS"],
            352,
            &now,
        ),
        secret_definition(
            MCP_MANAGEMENT_CONFIGURATION_CENTER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Configuration Center Internal Secret",
            "MCP Management 校验来自 Configuration Center 的内部签名请求时使用的专用密钥",
            "MCP Management / Security",
            "service",
            Some("mcp-management-service"),
            json!("change_me_configuration_center_mcp_management_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_CONFIGURATION_CENTER_INTERNAL_API_SECRET"],
            3521,
            &now,
        ),
        secret_definition(
            MCP_MANAGEMENT_PLUGIN_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "Plugin Management Internal Secret",
            "MCP Management 调用 Plugin Management 内部接口时使用的共享密钥",
            "MCP Management / Downstream Security",
            "service",
            Some("mcp-management-service"),
            json!("change_me_plugin_management_mcp_management_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_MCP_MANAGEMENT_INTERNAL_API_SECRET"],
            353,
            &now,
        ),
        secret_definition(
            MCP_MANAGEMENT_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Project Service Internal Secret",
            "MCP Management 调用 Project Service 内部接口时使用的共享密钥",
            "MCP Management / Downstream Security",
            "service",
            Some("mcp-management-service"),
            json!("change_me_mcp_management_project_service_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_PROJECT_SERVICE_INTERNAL_API_SECRET"],
            354,
            &now,
        ),
        secret_definition(
            MCP_MANAGEMENT_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Task Runner Internal Secret",
            "MCP Management 调用 Task Runner 内部接口时使用的共享密钥",
            "MCP Management / Downstream Security",
            "service",
            Some("mcp-management-service"),
            json!("change_me_mcp_management_task_runner_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_TASK_RUNNER_INTERNAL_API_SECRET"],
            355,
            &now,
        ),
        secret_definition(
            MCP_MANAGEMENT_CHATOS_INTERNAL_API_SECRET_CONFIG_KEY,
            "Chatos Internal Secret",
            "MCP Management 调用 Chatos Backend 内部接口时使用的共享密钥",
            "MCP Management / Downstream Security",
            "service",
            Some("mcp-management-service"),
            json!("change_me_mcp_management_chatos_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_CHATOS_INTERNAL_API_SECRET"],
            356,
            &now,
        ),
        secret_definition(
            MCP_MANAGEMENT_LOCAL_CONNECTOR_INTERNAL_API_SECRET_CONFIG_KEY,
            "Local Connector Internal Secret",
            "MCP Management 调用 Local Connector 内部接口时使用的共享密钥",
            "MCP Management / Downstream Security",
            "service",
            Some("mcp-management-service"),
            json!("change_me_mcp_management_local_connector_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_LOCAL_CONNECTOR_INTERNAL_API_SECRET"],
            357,
            &now,
        ),
        secret_definition(
            MCP_MANAGEMENT_SANDBOX_MANAGER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Sandbox Manager Internal Secret",
            "MCP Management 调用 Sandbox Manager 内部接口时使用的共享密钥",
            "MCP Management / Downstream Security",
            "service",
            Some("mcp-management-service"),
            json!("change_me_mcp_management_sandbox_manager_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_SANDBOX_MANAGER_INTERNAL_API_SECRET"],
            358,
            &now,
        ),
        secret_definition(
            MCP_MANAGEMENT_RUNTIME_GRANT_SECRET_CONFIG_KEY,
            "Runtime Grant Secret",
            "MCP Management 为 runtime session / grant 签发授权令牌时使用的共享密钥",
            "MCP Management / Runtime Security",
            "service",
            Some("mcp-management-service"),
            json!("change_me_mcp_management_runtime_grant_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_RUNTIME_GRANT_SECRET"],
            359,
            &now,
        ),
        secret_definition(
            MCP_MANAGEMENT_RUNTIME_SESSION_ENCRYPTION_SECRET_CONFIG_KEY,
            "Runtime Session Encryption Secret",
            "MCP Management 持久化 runtime session 快照时使用的加密密钥",
            "MCP Management / Runtime Security",
            "service",
            Some("mcp-management-service"),
            json!("change_me_mcp_management_runtime_session_encryption_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_RUNTIME_SESSION_ENCRYPTION_SECRET"],
            360,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_HOST_CONFIG_KEY,
            "监听地址",
            "MCP Management Service 监听的 IP 地址",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("127.0.0.1"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_HOST"],
            3600,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_PORT_CONFIG_KEY,
            "监听端口",
            "MCP Management Service 监听的端口号",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(39280),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_PORT"],
            3600,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_INTERNAL_MTLS_PORT_CONFIG_KEY,
            "内部 mTLS 监听端口",
            "MCP Management 内部控制面强制 mTLS 监听端口",
            "MCP Management / Runtime Security",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(39282),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_INTERNAL_MTLS_PORT"],
            3601,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_OTLP_ENDPOINT_CONFIG_KEY,
            "OTLP Endpoint",
            "MCP Management OpenTelemetry trace exporter 使用的 OTLP gRPC 地址",
            "MCP Management / Observability",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("http://tempo:4317"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_OTEL_EXPORTER_OTLP_ENDPOINT"],
            3602,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_OTLP_TRACE_SAMPLE_RATIO_CONFIG_KEY,
            "Trace Sample Ratio",
            "MCP Management 根链路按 Trace ID 采样的比例",
            "MCP Management / Observability",
            "service",
            Some("mcp-management-service"),
            "number",
            json!(0.1),
            Some(0),
            Some(1),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_OTEL_TRACE_SAMPLE_RATIO"],
            3603,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_OTLP_EXPORT_TIMEOUT_MS_CONFIG_KEY,
            "OTLP Export Timeout",
            "MCP Management 导出一批 trace 的超时毫秒数",
            "MCP Management / Observability",
            "service",
            Some("mcp-management-service"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(60_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_OTEL_EXPORT_TIMEOUT_MS"],
            3604,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_DATABASE_URL_CONFIG_KEY,
            "Runtime Session Database URL",
            "MCP Management 存储 runtime session 时使用的数据库连接串",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("mongodb://127.0.0.1:27017/mcp_management_service"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_DATABASE_URL"],
            3600,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_EMBEDDED_WORK_DIR_CONFIG_KEY,
            "Embedded Work Dir",
            "MCP Management 嵌入式 runtime/provider 临时工作目录",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("/tmp/chatos-mcp-management"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_EMBEDDED_WORK_DIR"],
            3600,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_DOWNSTREAM_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "下游请求超时（毫秒）",
            "MCP Management 调用下游内部服务时使用的默认超时时间",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(60_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_DOWNSTREAM_REQUEST_TIMEOUT_MS"],
            3601,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_PROJECT_SERVICE_TOOL_TIMEOUT_MS_CONFIG_KEY,
            "Project Service 工具超时（毫秒）",
            "MCP Management 调用 Project Service 执行 Harness 工具时允许的最长等待时间",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "duration_ms",
            json!(3 * 60 * 1_000),
            Some(1_000),
            Some(2 * 60 * 60 * 1_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_PROJECT_SERVICE_TOOL_TIMEOUT_MS"],
            36011,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_EXTERNAL_HTTP_TOOL_TIMEOUT_MS_CONFIG_KEY,
            "外部 HTTP 工具超时（毫秒）",
            "MCP Management 执行 external_http 工具时允许的最长等待时间",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "duration_ms",
            json!(60_000),
            Some(1_000),
            Some(10 * 60 * 1_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_EXTERNAL_HTTP_TOOL_TIMEOUT_MS"],
            3602,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_RUNTIME_SESSION_TTL_SECONDS_CONFIG_KEY,
            "Runtime Session TTL（秒）",
            "MCP Management runtime session 在存储中的保留时长",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(30 * 60),
            Some(5 * 60),
            Some(2 * 60 * 60),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_RUNTIME_SESSION_TTL_SECONDS"],
            3603,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_RUNTIME_SESSION_CACHE_MAX_ENTRIES_CONFIG_KEY,
            "Runtime Session 缓存条目上限",
            "MCP Management 单实例内存中保留的 Runtime Session 主快照数量上限",
            "MCP Management / Runtime Cache",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(2_048),
            Some(1),
            Some(100_000),
            &[],
            "restart_required",
            &[],
            3603,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_RUNTIME_SESSION_CACHE_MAX_BYTES_CONFIG_KEY,
            "Runtime Session 缓存字节上限",
            "MCP Management 单实例 Runtime Session 主快照缓存的估算总字节上限",
            "MCP Management / Runtime Cache",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(32 * 1024 * 1024),
            Some(1024 * 1024),
            Some(2 * 1024 * 1024 * 1024),
            &[],
            "restart_required",
            &[],
            3603,
            &now,
        ),
        secret_definition(
            MCP_MANAGEMENT_INVOCATION_QUOTA_VALKEY_URL_CONFIG_KEY,
            "Invocation 配额 Valkey URL",
            "MCP Management 原子占用和释放 Runtime Invocation 四级配额使用的 Valkey 地址",
            "MCP Management / Invocation Quota",
            "service",
            Some("mcp-management-service"),
            json!("redis://:change_me_valkey_password@127.0.0.1:6379/0"),
            "restart_required",
            &[],
            36031,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_INVOCATION_QUOTA_KEY_PREFIX_CONFIG_KEY,
            "Invocation 配额键前缀",
            "MCP Management Runtime Invocation 分布式配额键使用的命名空间前缀",
            "MCP Management / Invocation Quota",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("chatos:mcp-management:invocation-quota"),
            None,
            None,
            &[],
            "restart_required",
            &[],
            36032,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_INVOCATION_TENANT_ACTIVE_LIMIT_CONFIG_KEY,
            "租户活跃 Invocation 上限",
            "单个租户允许同时占用的 Runtime Invocation 数量上限",
            "MCP Management / Invocation Quota",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(2_000),
            Some(1),
            Some(1_000_000),
            &[],
            "restart_required",
            &[],
            36033,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_INVOCATION_USER_ACTIVE_LIMIT_CONFIG_KEY,
            "用户活跃 Invocation 上限",
            "单个用户允许同时占用的 Runtime Invocation 数量上限",
            "MCP Management / Invocation Quota",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(200),
            Some(1),
            Some(1_000_000),
            &[],
            "restart_required",
            &[],
            36034,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_INVOCATION_PROJECT_ACTIVE_LIMIT_CONFIG_KEY,
            "项目活跃 Invocation 上限",
            "单个项目允许同时占用的 Runtime Invocation 数量上限",
            "MCP Management / Invocation Quota",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(100),
            Some(1),
            Some(1_000_000),
            &[],
            "restart_required",
            &[],
            36035,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_INVOCATION_DEVICE_ACTIVE_LIMIT_CONFIG_KEY,
            "设备活跃 Invocation 上限",
            "单个本地设备允许同时占用的 Runtime Invocation 数量上限；无设备绑定的云端调用不占用设备维度",
            "MCP Management / Invocation Quota",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(50),
            Some(1),
            Some(1_000_000),
            &[],
            "restart_required",
            &[],
            36036,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_SANDBOX_TOOL_TIMEOUT_MS_CONFIG_KEY,
            "Sandbox 工具超时（毫秒）",
            "MCP Management 调用 sandbox-manager 执行普通工具时的超时时间",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "duration_ms",
            json!(3 * 60 * 1_000),
            Some(1_000),
            Some(2 * 60 * 60 * 1_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_SANDBOX_TOOL_TIMEOUT_MS"],
            3604,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_SANDBOX_IMAGE_TOOL_TIMEOUT_MS_CONFIG_KEY,
            "Sandbox 镜像工具超时（毫秒）",
            "MCP Management 调用 sandbox-manager 执行镜像相关工具时的超时时间",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "duration_ms",
            json!(2 * 60 * 60 * 1_000),
            Some(30_000),
            Some(3 * 60 * 60 * 1_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_SANDBOX_IMAGE_TOOL_TIMEOUT_MS"],
            3605,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_TASK_RUNNER_TOOL_TIMEOUT_MS_CONFIG_KEY,
            "Task Runner 工具超时（毫秒）",
            "MCP Management 调用 Task Runner 执行工具时的超时时间",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "duration_ms",
            json!(3 * 60 * 1_000),
            Some(1_000),
            Some(2 * 60 * 60 * 1_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_TASK_RUNNER_TOOL_TIMEOUT_MS"],
            3606,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_TASK_RUNNER_ASK_USER_TOOL_TIMEOUT_MS_CONFIG_KEY,
            "Task Runner Ask User 超时（毫秒）",
            "MCP Management 通过 Task Runner 发起 ask_user 工具时的等待上限",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "duration_ms",
            json!(86_700_000),
            Some(86_400_000),
            Some(7 * 24 * 60 * 60 * 1_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_TASK_RUNNER_ASK_USER_TOOL_TIMEOUT_MS"],
            3607,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_CHATOS_ASK_USER_TOOL_TIMEOUT_MS_CONFIG_KEY,
            "Chatos Ask User 超时（毫秒）",
            "MCP Management 通过 Chatos 发起 ask_user 工具时的等待上限",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "duration_ms",
            json!(86_700_000),
            Some(86_400_000),
            Some(7 * 24 * 60 * 60 * 1_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_CHATOS_ASK_USER_TOOL_TIMEOUT_MS"],
            3608,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_CHATOS_BROWSER_TOOL_TIMEOUT_MS_CONFIG_KEY,
            "Chatos Browser 工具超时（毫秒）",
            "MCP Management 调用 Chatos browser 工具时的等待上限",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "duration_ms",
            json!(120_000),
            Some(30_000),
            Some(10 * 60 * 1_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_CHATOS_BROWSER_TOOL_TIMEOUT_MS"],
            3609,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_PROVIDER_RESPONSE_LIMIT_BYTES_CONFIG_KEY,
            "Provider 响应大小上限（字节）",
            "MCP Management 接收外部 provider 原始响应时允许的最大字节数",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "integer",
            json!(2 * 1024 * 1024),
            Some(64 * 1024),
            Some(16 * 1024 * 1024),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_PROVIDER_RESPONSE_LIMIT_BYTES"],
            3610,
            &now,
        ),
        definition(
            MCP_MANAGEMENT_PUBLIC_BASE_URL_CONFIG_KEY,
            "对外访问基础地址",
            "MCP Management 生成 runtime / callback 链接时使用的公网基础地址",
            "MCP Management / Runtime",
            "service",
            Some("mcp-management-service"),
            "string",
            json!("http://127.0.0.1:39280"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_PUBLIC_BASE_URL"],
            3611,
            &now,
        ),
    ]
}
