use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            "chatos.ai.max_output_tokens",
            "最大输出 Tokens",
            "单次模型回复最大输出 Tokens，空值表示模型默认",
            "Chat OS / AI",
            "service",
            Some("chatos-backend"),
            "integer",
            Value::Null,
            Some(1),
            Some(1_000_000),
            &[],
            "next_request",
            &["CHAT_MAX_TOKENS"],
            110,
            now,
        ),
        definition(
            "chatos.task.follow_up_max_rounds",
            "任务后置检查轮数",
            "任务准备结束时最多继续检查的轮数",
            "Chat OS / Task",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(3),
            Some(0),
            Some(100),
            &[],
            "next_request",
            &["TASK_FOLLOW_UP_MAX_ROUNDS"],
            120,
            now,
        ),
        definition(
            "chatos.conversation.history_limit",
            "历史消息数量",
            "请求模型时读取的历史消息数量",
            "Chat OS / Conversation",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(20),
            Some(1),
            Some(1000),
            &[],
            "next_request",
            &["HISTORY_LIMIT"],
            130,
            now,
        ),
        definition(
            "chatos.attachment.total_max_bytes",
            "附件总大小上限",
            "单次消息所有附件原始文件大小之和",
            "Chat OS / Attachment",
            "service",
            Some("chatos-backend"),
            "bytes",
            json!(20 * 1024 * 1024),
            Some(1),
            Some(1024 * 1024 * 1024),
            &[],
            "hot_reload",
            &["ATTACHMENT_TOTAL_MAX_BYTES"],
            140,
            now,
        ),
        definition(
            "chatos.ui.terminal_enabled",
            "显示终端入口",
            "是否在 Chat OS 中显示终端菜单和视图",
            "Chat OS / UI",
            "service",
            Some("chatos-backend"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "hot_reload",
            &["TERMINAL_UI_ENABLED"],
            150,
            now,
        ),
        definition(
            CHATOS_NODE_ENV_CONFIG_KEY,
            "Node Env",
            "Chatos Backend 当前运行环境",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            "enum",
            json!("development"),
            None,
            None,
            &["development", "staging", "test", "production"],
            "restart_required",
            &["NODE_ENV"],
            160,
            now,
        ),
        definition(
            CHATOS_HOST_CONFIG_KEY,
            "Host",
            "Chatos Backend HTTP 服务监听地址",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            "string",
            json!("0.0.0.0"),
            None,
            None,
            &[],
            "restart_required",
            &["HOST"],
            160,
            now,
        ),
        definition(
            CHATOS_BACKEND_PORT_CONFIG_KEY,
            "Port",
            "Chatos Backend HTTP 服务监听端口",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(3997),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["BACKEND_PORT"],
            160,
            now,
        ),
        definition(
            CHATOS_INTERNAL_MTLS_PORT_CONFIG_KEY,
            "Internal mTLS Port",
            "Chatos Backend 内部服务接口的强制 mTLS 监听端口",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(3999),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["CHATOS_INTERNAL_MTLS_PORT"],
            160,
            now,
        ),
        secret_definition(
            CHATOS_DATABASE_URL_CONFIG_KEY,
            "Database URL",
            "Chatos Backend 主数据库 MongoDB 连接串",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            json!("mongodb://admin:admin@127.0.0.1:27017/chatos?authSource=admin"),
            "restart_required",
            &["MONGODB_CONNECTION_STRING"],
            161,
            now,
        ),
        definition(
            CHATOS_MONGODB_DATABASE_CONFIG_KEY,
            "MongoDB Database",
            "Chatos Backend 主数据库名称",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            "string",
            json!("chatos"),
            None,
            None,
            &[],
            "restart_required",
            &["MONGODB_DB"],
            162,
            now,
        ),
        secret_definition(
            CHATOS_LEGACY_AUTH_DATABASE_URL_CONFIG_KEY,
            "Legacy Auth Database URL",
            "Chatos Backend 迁移历史认证数据使用的 MongoDB 连接串",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            json!("mongodb://admin:admin@127.0.0.1:27017/admin?authSource=admin"),
            "restart_required",
            &["LEGACY_AUTH_MONGODB_URI"],
            163,
            now,
        ),
        definition(
            CHATOS_LEGACY_AUTH_MONGODB_DATABASE_CONFIG_KEY,
            "Legacy Auth MongoDB Database",
            "Chatos Backend 历史认证数据所在数据库名称",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            "string",
            json!("legacy_auth"),
            None,
            None,
            &[],
            "restart_required",
            &["LEGACY_AUTH_MONGODB_DATABASE"],
            164,
            now,
        ),
        definition(
            CHATOS_USER_SERVICE_BASE_URL_CONFIG_KEY,
            "User Service Base URL",
            "Chatos Backend 调用 User Service 时使用的基础地址",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "string",
            json!("http://127.0.0.1:39190"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_USER_SERVICE_BASE_URL"],
            161,
            now,
        ),
        definition(
            CHATOS_USER_SERVICE_INTERNAL_BASE_URL_CONFIG_KEY,
            "User Service Internal Base URL",
            "Chatos Cloud Agent 后台执行通过 mTLS 调用 User Service 时使用的内部地址",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "string",
            json!("https://user-service-backend:39192"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_USER_SERVICE_INTERNAL_BASE_URL"],
            1611,
            now,
        ),
        secret_definition(
            CHATOS_USER_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "User Service Internal Secret",
            "Chatos Cloud Agent 后台按任务所属用户读取模型运行配置时使用的服务身份密钥",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            json!("change_me_chatos_user_service_secret"),
            "restart_required",
            &["CHATOS_USER_SERVICE_INTERNAL_API_SECRET"],
            1612,
            now,
        ),
        definition(
            CHATOS_USER_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "User Service Request Timeout",
            "Chatos Backend 调用 User Service 时使用的请求超时毫秒数",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["CHATOS_USER_SERVICE_REQUEST_TIMEOUT_MS"],
            162,
            now,
        ),
        definition(
            CHATOS_PROJECT_SERVICE_BASE_URL_CONFIG_KEY,
            "Project Service Base URL",
            "Chatos Backend 调用 Project Service 时使用的基础地址",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "string",
            json!("http://127.0.0.1:39210"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_PROJECT_SERVICE_BASE_URL"],
            163,
            now,
        ),
        definition(
            CHATOS_PROJECT_SERVICE_INTERNAL_BASE_URL_CONFIG_KEY,
            "Project Service Internal Base URL",
            "Chatos Backend 调用 Project Service 内部接口时使用的强制 mTLS 地址",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            "string",
            json!("https://project-management-backend:39212"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_PROJECT_SERVICE_INTERNAL_BASE_URL"],
            164,
            now,
        ),
        definition(
            CHATOS_PROJECT_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Project Service Request Timeout",
            "Chatos Backend 调用 Project Service 内部接口时使用的请求超时毫秒数",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(30_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["CHATOS_PROJECT_SERVICE_REQUEST_TIMEOUT_MS"],
            164,
            now,
        ),
        secret_definition(
            CHATOS_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Project Service Internal Secret",
            "Chatos Backend 调用 Project Service 内部接口时使用的共享密钥",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            json!("change_me_chatos_project_service_secret"),
            "restart_required",
            &["CHATOS_PROJECT_SERVICE_INTERNAL_API_SECRET"],
            165,
            now,
        ),
        definition(
            CHATOS_TASK_RUNNER_BASE_URL_CONFIG_KEY,
            "Task Runner Base URL",
            "Chatos Backend 调用 Task Runner 时使用的基础地址",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "string",
            json!("http://127.0.0.1:39090"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_TASK_RUNNER_BASE_URL"],
            166,
            now,
        ),
        definition(
            CHATOS_TASK_RUNNER_INTERNAL_BASE_URL_CONFIG_KEY,
            "Task Runner Internal Base URL",
            "Chatos Backend 调用 Task Runner 内部控制面时使用的强制 mTLS 地址",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            "string",
            json!("https://task-runner-backend:39092"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_TASK_RUNNER_INTERNAL_BASE_URL"],
            167,
            now,
        ),
        secret_definition(
            CHATOS_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Task Runner Internal Secret",
            "Chatos Backend 调用 Task Runner 内部接口时使用的共享密钥",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            json!("change_me_chatos_task_runner_internal_secret"),
            "restart_required",
            &["CHATOS_TASK_RUNNER_INTERNAL_API_SECRET"],
            167,
            now,
        ),
        definition(
            CHATOS_TASK_RUNNER_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Task Runner Request Timeout",
            "Chatos Backend 调用 Task Runner 时使用的请求超时毫秒数",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(30_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["CHATOS_TASK_RUNNER_REQUEST_TIMEOUT_MS"],
            168,
            now,
        ),
        secret_definition(
            CHATOS_MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "MCP Management Internal Secret",
            "Chatos Backend 调用 MCP Management 内部接口时使用的共享密钥",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            json!("change_me_mcp_management_chatos_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_CHATOS_INTERNAL_API_SECRET"],
            169,
            now,
        ),
        secret_definition(
            CHATOS_PLUGIN_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "Plugin Management Internal Secret",
            "Chatos Backend 调用 Plugin Management 内部接口时使用的专用密钥",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            json!("change_me_plugin_management_chatos_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_CHATOS_INTERNAL_API_SECRET"],
            169,
            now,
        ),
        definition(
            CHATOS_LOCAL_CONNECTOR_SERVICE_BASE_URL_CONFIG_KEY,
            "Local Connector Service Base URL",
            "Chatos Backend 调用 Local Connector 时使用的基础地址",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "string",
            json!("https://127.0.0.1:39232"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_LOCAL_CONNECTOR_SERVICE_BASE_URL"],
            170,
            now,
        ),
        secret_definition(
            CHATOS_LOCAL_CONNECTOR_INTERNAL_API_SECRET_CONFIG_KEY,
            "Local Connector Internal Secret",
            "Chatos Backend 调用 Local Connector 内部接口时使用的共享密钥",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            json!("change_me_chatos_local_connector_secret"),
            "restart_required",
            &["CHATOS_LOCAL_CONNECTOR_INTERNAL_API_SECRET"],
            171,
            now,
        ),
        definition(
            CHATOS_LOCAL_CONNECTOR_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Local Connector Request Timeout",
            "Chatos Backend 调用 Local Connector 时使用的请求超时毫秒数",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(30_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["CHATOS_LOCAL_CONNECTOR_SERVICE_REQUEST_TIMEOUT_MS"],
            172,
            now,
        ),
        definition(
            CHATOS_MEMORY_ENGINE_BASE_URL_CONFIG_KEY,
            "Memory Engine Base URL",
            "Chatos Backend 调用 Memory Engine 时使用的基础地址",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "string",
            json!("https://memory-engine-backend:7083/api/memory-engine/v1"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_MEMORY_ENGINE_BASE_URL"],
            173,
            now,
        ),
        secret_definition(
            CHATOS_MEMORY_ENGINE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Memory Engine Internal Secret",
            "Chatos Backend 签发 Memory Engine 内部短期 token 时使用的调用方专属密钥",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            json!("change_me_chatos_memory_engine_secret"),
            "restart_required",
            &["CHATOS_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            174,
            now,
        ),
        definition(
            CHATOS_MEMORY_ENGINE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Memory Engine Request Timeout",
            "Chatos Backend 调用 Memory Engine 时使用的请求超时毫秒数",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["CHATOS_MEMORY_ENGINE_REQUEST_TIMEOUT_MS"],
            175,
            now,
        ),
    ]
}
