use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        nullable_secret_definition(
            CHATOS_OPENAI_API_KEY_CONFIG_KEY,
            "OpenAI API Key",
            "Chatos Backend 默认模型调用使用的 OpenAI API Key，空值表示未配置全局密钥",
            "Chat OS / AI",
            "service",
            Some("chatos-backend"),
            Value::Null,
            "restart_required",
            &["OPENAI_API_KEY"],
            176,
            now,
        ),
        definition(
            CHATOS_OPENAI_BASE_URL_CONFIG_KEY,
            "OpenAI Base URL",
            "Chatos Backend 默认模型调用使用的 OpenAI API 基础地址",
            "Chat OS / AI",
            "service",
            Some("chatos-backend"),
            "string",
            json!("https://api.openai.com/v1"),
            None,
            None,
            &[],
            "restart_required",
            &["OPENAI_BASE_URL"],
            177,
            now,
        ),
        definition(
            CHATOS_SUMMARY_ENABLED_CONFIG_KEY,
            "摘要总开关",
            "是否启用会话摘要能力",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["SUMMARY_ENABLED"],
            178,
            now,
        ),
        definition(
            CHATOS_SUMMARY_MESSAGE_LIMIT_CONFIG_KEY,
            "摘要消息阈值",
            "达到该消息数后才会触发摘要判断",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(40),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["SUMMARY_MESSAGE_LIMIT"],
            179,
            now,
        ),
        definition(
            CHATOS_SUMMARY_MAX_CONTEXT_TOKENS_CONFIG_KEY,
            "摘要上下文上限",
            "摘要生成时允许送入模型的最大上下文 Tokens",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(6_000),
            Some(1),
            Some(10_000_000),
            &[],
            "restart_required",
            &["SUMMARY_MAX_CONTEXT_TOKENS"],
            180,
            now,
        ),
        definition(
            CHATOS_SUMMARY_KEEP_LAST_N_CONFIG_KEY,
            "摘要保留尾消息数",
            "生成摘要后仍保留在上下文中的最近消息条数",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(6),
            Some(0),
            Some(10_000),
            &[],
            "restart_required",
            &["SUMMARY_KEEP_LAST_N"],
            181,
            now,
        ),
        definition(
            CHATOS_SUMMARY_TARGET_TOKENS_CONFIG_KEY,
            "摘要目标 Tokens",
            "单次摘要输出的目标 Tokens",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(700),
            Some(1),
            Some(1_000_000),
            &[],
            "restart_required",
            &["SUMMARY_TARGET_TOKENS"],
            182,
            now,
        ),
        definition(
            CHATOS_SUMMARY_MERGE_TARGET_TOKENS_CONFIG_KEY,
            "摘要合并目标 Tokens",
            "摘要合并阶段的目标输出 Tokens",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(700),
            Some(1),
            Some(1_000_000),
            &[],
            "restart_required",
            &["SUMMARY_MERGE_TARGET_TOKENS"],
            183,
            now,
        ),
        definition(
            CHATOS_SUMMARY_TEMPERATURE_CONFIG_KEY,
            "摘要 Temperature",
            "摘要模型请求使用的 temperature，使用字符串形式保存小数",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "string",
            json!("0.2"),
            None,
            None,
            &[],
            "restart_required",
            &["SUMMARY_TEMPERATURE"],
            184,
            now,
        ),
        definition(
            CHATOS_SUMMARY_COOLDOWN_SECONDS_CONFIG_KEY,
            "摘要冷却时间",
            "两次摘要触发之间至少间隔的秒数",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(60),
            Some(0),
            Some(86_400),
            &[],
            "restart_required",
            &["SUMMARY_COOLDOWN_SECONDS"],
            185,
            now,
        ),
        definition(
            CHATOS_DYNAMIC_SUMMARY_ENABLED_CONFIG_KEY,
            "动态摘要开关",
            "是否启用基于上下文长度的动态摘要策略",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["DYNAMIC_SUMMARY_ENABLED"],
            186,
            now,
        ),
        definition(
            CHATOS_SUMMARY_BISECT_ENABLED_CONFIG_KEY,
            "摘要二分开关",
            "是否允许在长上下文摘要时采用二分策略",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["SUMMARY_BISECT_ENABLED"],
            187,
            now,
        ),
        definition(
            CHATOS_SUMMARY_BISECT_MAX_DEPTH_CONFIG_KEY,
            "摘要二分最大深度",
            "摘要二分策略允许递归拆分的最大深度",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(6),
            Some(1),
            Some(128),
            &[],
            "restart_required",
            &["SUMMARY_BISECT_MAX_DEPTH"],
            188,
            now,
        ),
        definition(
            CHATOS_SUMMARY_BISECT_MIN_MESSAGES_CONFIG_KEY,
            "摘要二分最小消息数",
            "只有消息数达到该阈值时才会进入摘要二分流程",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(4),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["SUMMARY_BISECT_MIN_MESSAGES"],
            189,
            now,
        ),
        definition(
            CHATOS_SUMMARY_RETRY_ON_CONTEXT_OVERFLOW_CONFIG_KEY,
            "上下文溢出自动重试",
            "摘要请求因上下文溢出失败时是否自动缩减并重试",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["SUMMARY_RETRY_ON_CONTEXT_OVERFLOW"],
            190,
            now,
        ),
        secret_definition(
            CHATOS_AUTH_JWT_SECRET_CONFIG_KEY,
            "JWT 签名密钥",
            "Chatos Backend 签发与校验访问令牌使用的主密钥",
            "Chat OS / Auth",
            "service",
            Some("chatos-backend"),
            json!("dev-only-change-me-please"),
            "restart_required",
            &["AUTH_JWT_SECRET"],
            191,
            now,
        ),
        nullable_secret_definition(
            CHATOS_AUTH_COMPAT_SECRET_CONFIG_KEY,
            "JWT 兼容密钥",
            "兼容历史令牌校验时使用的附加密钥，空值表示禁用",
            "Chat OS / Auth",
            "service",
            Some("chatos-backend"),
            Value::Null,
            "restart_required",
            &["AUTH_COMPAT_SECRET"],
            192,
            now,
        ),
        definition(
            CHATOS_AUTH_ACCESS_TOKEN_TTL_SECONDS_CONFIG_KEY,
            "访问令牌 TTL",
            "访问令牌默认有效期，单位秒",
            "Chat OS / Auth",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(43_200),
            Some(60),
            Some(31_536_000),
            &[],
            "restart_required",
            &["AUTH_ACCESS_TOKEN_TTL_SECONDS"],
            193,
            now,
        ),
        definition(
            CHATOS_LOG_MAX_FILES_CONFIG_KEY,
            "日志保留策略",
            "Chatos Backend 使用的日志文件保留策略，例如 7d",
            "Chat OS / Logging",
            "service",
            Some("chatos-backend"),
            "string",
            json!("7d"),
            None,
            None,
            &[],
            "restart_required",
            &["LOG_MAX_FILES"],
            193,
            now,
        ),
        definition(
            CHATOS_OTLP_ENDPOINT_CONFIG_KEY,
            "OTLP Endpoint",
            "ChatOS OpenTelemetry trace exporter 使用的 OTLP gRPC 地址",
            "Chat OS / Observability",
            "service",
            Some("chatos-backend"),
            "string",
            json!("http://tempo:4317"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_OTEL_EXPORTER_OTLP_ENDPOINT"],
            194,
            now,
        ),
        definition(
            CHATOS_OTLP_TRACE_SAMPLE_RATIO_CONFIG_KEY,
            "Trace Sample Ratio",
            "ChatOS 根链路按 Trace ID 采样的比例",
            "Chat OS / Observability",
            "service",
            Some("chatos-backend"),
            "number",
            json!(0.1),
            Some(0),
            Some(1),
            &[],
            "restart_required",
            &["CHATOS_OTEL_TRACE_SAMPLE_RATIO"],
            195,
            now,
        ),
        definition(
            CHATOS_OTLP_EXPORT_TIMEOUT_MS_CONFIG_KEY,
            "OTLP Export Timeout",
            "ChatOS 导出一批 trace 的超时毫秒数",
            "Chat OS / Observability",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(60_000),
            &[],
            "restart_required",
            &["CHATOS_OTEL_EXPORT_TIMEOUT_MS"],
            196,
            now,
        ),
        definition(
            CHATOS_CORS_ORIGINS_CONFIG_KEY,
            "CORS Origins",
            "Chatos Backend 允许的跨域来源列表，使用逗号分隔，支持 *",
            "Chat OS / HTTP",
            "service",
            Some("chatos-backend"),
            "string",
            json!("*"),
            None,
            None,
            &[],
            "restart_required",
            &["CORS_ORIGINS"],
            193,
            now,
        ),
        definition(
            CHATOS_MCP_RESULT_RABBITMQ_URL_CONFIG_KEY,
            "MCP 结果 RabbitMQ 地址",
            "Chatos Backend 消费 MCP 异步调用结果事件使用的 AMQP 地址",
            "Chat OS / MCP Queue",
            "service",
            Some("chatos-backend"),
            "string",
            json!(DEFAULT_LOCAL_RABBITMQ_URL),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_MCP_RESULT_RABBITMQ_URL"],
            194,
            now,
        ),
        definition(
            CHATOS_MCP_RESULT_QUEUE_PREFIX_CONFIG_KEY,
            "MCP 结果队列前缀",
            "Chatos Backend 按实例创建共享 MCP 结果消费队列使用的名称前缀",
            "Chat OS / MCP Queue",
            "service",
            Some("chatos-backend"),
            "string",
            json!("chatos.mcp.results"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_MCP_RESULT_QUEUE_PREFIX"],
            196,
            now,
        ),
        nullable_definition(
            CHATOS_PLUGIN_UI_PARENT_ORIGIN_CONFIG_KEY,
            "插件 UI 宿主 Origin",
            "插件 UI 被嵌入的上层应用 Origin，空值表示未启用插件 UI 远程资源",
            "Chat OS / Plugin UI",
            "service",
            Some("chatos-backend"),
            "string",
            Value::Null,
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_PLUGIN_UI_PARENT_ORIGIN"],
            194,
            now,
        ),
        nullable_definition(
            CHATOS_PLUGIN_UI_RESOURCE_ORIGIN_CONFIG_KEY,
            "插件 UI 资源 Origin",
            "插件 UI 远程资源所在 Origin，空值表示未启用插件 UI 远程资源",
            "Chat OS / Plugin UI",
            "service",
            Some("chatos-backend"),
            "string",
            Value::Null,
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_PLUGIN_UI_RESOURCE_ORIGIN"],
            195,
            now,
        ),
        definition(
            CHATOS_MEMORY_ENGINE_ACTIVE_SUMMARY_TRIGGER_TIMEOUT_MS_CONFIG_KEY,
            "主动摘要触发超时",
            "触发 Memory Engine 主动摘要任务时使用的请求超时毫秒数",
            "Chat OS / Memory Engine",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ACTIVE_SUMMARY_TRIGGER_TIMEOUT_MS"],
            196,
            now,
        ),
        definition(
            CHATOS_MEMORY_ENGINE_ACTIVE_SUMMARY_POLL_INTERVAL_MS_CONFIG_KEY,
            "主动摘要轮询间隔",
            "轮询 Memory Engine 主动摘要状态时的间隔毫秒数",
            "Chat OS / Memory Engine",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(10_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ACTIVE_SUMMARY_POLL_INTERVAL_MS"],
            197,
            now,
        ),
        definition(
            CHATOS_MEMORY_ENGINE_ACTIVE_SUMMARY_POLL_TIMEOUT_MS_CONFIG_KEY,
            "主动摘要轮询超时",
            "等待 Memory Engine 主动摘要完成时的总超时毫秒数",
            "Chat OS / Memory Engine",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(120_000),
            Some(10_000),
            Some(3_600_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ACTIVE_SUMMARY_POLL_TIMEOUT_MS"],
            198,
            now,
        ),
    ]
}
