use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            "shared.logging.level",
            "日志级别",
            "服务默认日志级别",
            "日志",
            "shared",
            None,
            "enum",
            json!("info"),
            None,
            None,
            &["trace", "debug", "info", "warn", "error"],
            "restart_required",
            &["LOG_LEVEL"],
            30,
            &now,
        ),
        definition(
            PLATFORM_PRESSURE_LEVEL_CONFIG_KEY,
            "平台压力等级",
            "配置中心发布的权威平台压力状态；业务服务不得自行窥探其他服务队列推断全局压力",
            "Platform / Pressure",
            "shared",
            None,
            "enum",
            json!("normal"),
            None,
            None,
            &["normal", "elevated", "critical"],
            "hot_reload",
            &[],
            40,
            &now,
        ),
        definition(
            PLATFORM_PRESSURE_CONTROLLER_ENABLED_CONFIG_KEY,
            "启用自动压力控制器",
            "由配置中心聚合服务压力信号并自动发布权威平台压力等级",
            "Platform / Pressure",
            "shared",
            None,
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "hot_reload",
            &[],
            41,
            &now,
        ),
        definition(
            PLATFORM_PRESSURE_CONTROLLER_INTERVAL_MS_CONFIG_KEY,
            "压力控制器检查间隔",
            "配置中心重新聚合服务压力信号的间隔",
            "Platform / Pressure",
            "shared",
            None,
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(60_000),
            &[],
            "hot_reload",
            &[],
            42,
            &now,
        ),
        definition(
            PLATFORM_PRESSURE_SIGNAL_TTL_SECONDS_CONFIG_KEY,
            "压力信号有效期",
            "超过该时间未更新的服务压力信号不参与平台压力判定",
            "Platform / Pressure",
            "shared",
            None,
            "integer",
            json!(30),
            Some(5),
            Some(600),
            &[],
            "hot_reload",
            &[],
            43,
            &now,
        ),
        definition(
            PLATFORM_PRESSURE_ESCALATION_STABLE_SECONDS_CONFIG_KEY,
            "压力升级稳定窗口",
            "候选压力等级持续达到该时间后才升级权威等级",
            "Platform / Pressure",
            "shared",
            None,
            "integer",
            json!(5),
            Some(0),
            Some(300),
            &[],
            "hot_reload",
            &[],
            44,
            &now,
        ),
        definition(
            PLATFORM_PRESSURE_RECOVERY_STABLE_SECONDS_CONFIG_KEY,
            "压力恢复稳定窗口",
            "候选压力下降持续达到该时间后才降低权威等级，避免抖动",
            "Platform / Pressure",
            "shared",
            None,
            "integer",
            json!(60),
            Some(5),
            Some(3_600),
            &[],
            "hot_reload",
            &[],
            45,
            &now,
        ),
        definition(
            AGENT_MAX_ITERATIONS_CONFIG_KEY,
            "Agent 最大迭代次数",
            "所有系统 Agent 单次执行的模型工具循环迭代上限",
            "Agent / Runtime",
            "shared",
            None,
            "integer",
            json!(DEFAULT_AGENT_MAX_ITERATIONS),
            Some(1),
            Some(5000),
            &[],
            "next_request",
            &[],
            100,
            &now,
        ),
        definition(
            SHARED_PLUGIN_MANAGEMENT_SERVICE_URL_CONFIG_KEY,
            "Plugin Management Public Service URL",
            "内部服务调用 Plugin Management 用户 Bearer API 时使用的公网监听地址",
            "Shared / Downstream",
            "shared",
            None,
            "string",
            json!("http://127.0.0.1:39260"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_URL"],
            101,
            &now,
        ),
        definition(
            SHARED_PLUGIN_MANAGEMENT_SERVICE_INTERNAL_URL_CONFIG_KEY,
            "Plugin Management Internal Service URL",
            "内部服务调用 Plugin Management 控制面时使用的强制 mTLS 地址",
            "Shared / Downstream",
            "shared",
            None,
            "string",
            json!("https://plugin-management-backend:39262"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_INTERNAL_URL"],
            1011,
            &now,
        ),
        definition(
            SHARED_PLUGIN_MANAGEMENT_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Plugin Management Request Timeout",
            "内部服务调用 Plugin Management 时使用的请求超时毫秒数",
            "Shared / Downstream",
            "shared",
            None,
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_REQUEST_TIMEOUT_MS"],
            102,
            &now,
        ),
        definition(
            SHARED_MCP_MANAGEMENT_SERVICE_BASE_URL_CONFIG_KEY,
            "MCP Management Internal Base URL",
            "内部服务调用 MCP Management 控制面时使用的强制 mTLS 地址",
            "Shared / Downstream",
            "shared",
            None,
            "string",
            json!("https://mcp-management-service-backend:39282"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_SERVICE_BASE_URL"],
            103,
            &now,
        ),
        definition(
            SHARED_MCP_MANAGEMENT_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "MCP Management Control Request Timeout",
            "内部服务调用 MCP Management 控制面接口的请求超时毫秒数",
            "Shared / Downstream",
            "shared",
            None,
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_REQUEST_TIMEOUT_MS"],
            104,
            &now,
        ),
    ]
}
