// Generated by scripts/sync-daisyui-registry.mjs from the official MIT-licensed daisyUI v5.7.28 documentation.
import type { DomRegistryEntry } from './types';
export const DAISYUI_REGISTRY_ENTRIES = [
  {
    "slug": "accordion",
    "title": "Accordion",
    "description": "Accordion is used for showing and hiding content but only one item can stay open at a time.",
    "demos": [
      {
        "id": "accordion-1",
        "label": "Accordion using radio inputs"
      },
      {
        "id": "accordion-2",
        "label": "Accordion using details"
      },
      {
        "id": "accordion-3",
        "label": "Accordion with arrow icon"
      },
      {
        "id": "accordion-4",
        "label": "Accordion with plus/minus icon"
      },
      {
        "id": "accordion-5",
        "label": "Using Accordion and Join together"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/accordion/"
  },
  {
    "slug": "alert",
    "title": "Alert",
    "description": "Alert informs users about important events.",
    "demos": [
      {
        "id": "alert-1",
        "label": "Alert"
      },
      {
        "id": "alert-2",
        "label": "Info color"
      },
      {
        "id": "alert-3",
        "label": "Success color"
      },
      {
        "id": "alert-4",
        "label": "Warning color"
      },
      {
        "id": "alert-5",
        "label": "Error color"
      },
      {
        "id": "alert-6",
        "label": "Alert soft style"
      },
      {
        "id": "alert-7",
        "label": "Alert outline style"
      },
      {
        "id": "alert-8",
        "label": "Alert dash style"
      },
      {
        "id": "alert-9",
        "label": "Alert with buttons + responsive"
      },
      {
        "id": "alert-10",
        "label": "Alert with title and description"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/alert/"
  },
  {
    "slug": "aura",
    "title": "Aura",
    "description": "Aura is a border light effect that can wrap around any component. It is a great way to add a cool, eye-catching visual effect to your components. Aura is useful for the most important button, card, or div that you want to highlight.",
    "demos": [
      {
        "id": "aura-1",
        "label": "Aura"
      },
      {
        "id": "aura-2",
        "label": "Aura around a button"
      },
      {
        "id": "aura-3",
        "label": "Aura dual"
      },
      {
        "id": "aura-4",
        "label": "Aura rainbow"
      },
      {
        "id": "aura-5",
        "label": "Aura holo"
      },
      {
        "id": "aura-6",
        "label": "Aura glow"
      },
      {
        "id": "aura-7",
        "label": "Aura gold"
      },
      {
        "id": "aura-8",
        "label": "Aura silver"
      },
      {
        "id": "aura-9",
        "label": "Aura with custom color"
      },
      {
        "id": "aura-10",
        "label": "Aura with custom color and custom background color"
      },
      {
        "id": "aura-11",
        "label": "Aura rainbow around a pricing card"
      },
      {
        "id": "aura-12",
        "label": "Aura sizes"
      },
      {
        "id": "aura-13",
        "label": "Aura with custom animation duration"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/aura/"
  },
  {
    "slug": "avatar",
    "title": "Avatar",
    "description": "Avatars are used to show a thumbnail representation of an individual or business in the interface.",
    "demos": [
      {
        "id": "avatar-1",
        "label": "Avatar"
      },
      {
        "id": "avatar-2",
        "label": "Avatar in custom sizes"
      },
      {
        "id": "avatar-3",
        "label": "Avatar rounded"
      },
      {
        "id": "avatar-4",
        "label": "Avatar with mask"
      },
      {
        "id": "avatar-5",
        "label": "Avatar group"
      },
      {
        "id": "avatar-6",
        "label": "Avatar group with counter"
      },
      {
        "id": "avatar-7",
        "label": "Avatar with ring"
      },
      {
        "id": "avatar-8",
        "label": "Avatar with presence indicator"
      },
      {
        "id": "avatar-9",
        "label": "Avatar placeholder"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/avatar/"
  },
  {
    "slug": "badge",
    "title": "Badge",
    "description": "Badges are used to inform the user of the status of specific data.",
    "demos": [
      {
        "id": "badge-1",
        "label": "Badge"
      },
      {
        "id": "badge-2",
        "label": "Badge sizes"
      },
      {
        "id": "badge-3",
        "label": "Badge with colors"
      },
      {
        "id": "badge-4",
        "label": "Badge with soft style"
      },
      {
        "id": "badge-5",
        "label": "Badge with outline style"
      },
      {
        "id": "badge-6",
        "label": "Badge with dash style"
      },
      {
        "id": "badge-7",
        "label": "neutral badge with outline or dash style"
      },
      {
        "id": "badge-8",
        "label": "Badge ghost"
      },
      {
        "id": "badge-9",
        "label": "Empty badge"
      },
      {
        "id": "badge-10",
        "label": "Badge with icon"
      },
      {
        "id": "badge-11",
        "label": "Badge in a text"
      },
      {
        "id": "badge-12",
        "label": "Badge in a button"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/badge/"
  },
  {
    "slug": "breadcrumbs",
    "title": "Breadcrumbs",
    "description": "Breadcrumbs helps users to navigate through the website.",
    "demos": [
      {
        "id": "breadcrumbs-1",
        "label": "Breadcrumbs"
      },
      {
        "id": "breadcrumbs-2",
        "label": "Breadcrumbs with icons"
      },
      {
        "id": "breadcrumbs-3",
        "label": "Breadcrumbs with max-width"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/breadcrumbs/"
  },
  {
    "slug": "button",
    "title": "Button",
    "description": "Buttons allow the user to take actions or make choices.",
    "demos": [
      {
        "id": "button-1",
        "label": "Button"
      },
      {
        "id": "button-2",
        "label": "Button sizes"
      },
      {
        "id": "button-3",
        "label": "Responsive button"
      },
      {
        "id": "button-4",
        "label": "Buttons colors"
      },
      {
        "id": "button-5",
        "label": "Soft buttons"
      },
      {
        "id": "button-6",
        "label": "Outline buttons"
      },
      {
        "id": "button-7",
        "label": "Dash buttons"
      },
      {
        "id": "button-8",
        "label": "neutral button with outline or dash style"
      },
      {
        "id": "button-9",
        "label": "Active buttons"
      },
      {
        "id": "button-10",
        "label": "Buttons ghost and button link"
      },
      {
        "id": "button-11",
        "label": "Wide button"
      },
      {
        "id": "button-12",
        "label": "Buttons with any HTML tags"
      },
      {
        "id": "button-13",
        "label": "Disabled buttons"
      },
      {
        "id": "button-14",
        "label": "Square button and circle button"
      },
      {
        "id": "button-15",
        "label": "Button with Icon"
      },
      {
        "id": "button-16",
        "label": "Button block"
      },
      {
        "id": "button-17",
        "label": "Button with loading spinner"
      },
      {
        "id": "button-18",
        "label": "Login buttons"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/button/"
  },
  {
    "slug": "calendar",
    "title": "Calendar",
    "description": "Calendar includes styles for different calendar libraries.",
    "demos": [
      {
        "id": "calendar-1",
        "label": "Cally calendar example"
      },
      {
        "id": "calendar-2",
        "label": "Cally date picker example"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/calendar/",
    "previewHeight": 360
  },
  {
    "slug": "card",
    "title": "Card",
    "description": "Cards are used to group and display content in a way that is easily readable.",
    "demos": [
      {
        "id": "card-1",
        "label": "Card"
      },
      {
        "id": "card-2",
        "label": "Pricing Card"
      },
      {
        "id": "card-3",
        "label": "Card sizes"
      },
      {
        "id": "card-4",
        "label": "Card with a card-border"
      },
      {
        "id": "card-5",
        "label": "Card with a dash border"
      },
      {
        "id": "card-6",
        "label": "Card with badge"
      },
      {
        "id": "card-7",
        "label": "Card with bottom image"
      },
      {
        "id": "card-8",
        "label": "Card with centered content and paddings"
      },
      {
        "id": "card-9",
        "label": "Card with image overlay"
      },
      {
        "id": "card-10",
        "label": "Card with no image"
      },
      {
        "id": "card-11",
        "label": "Card with custom color"
      },
      {
        "id": "card-12",
        "label": "Centered card with neutral color"
      },
      {
        "id": "card-13",
        "label": "Card with action on top"
      },
      {
        "id": "card-14",
        "label": "Card with image on side"
      },
      {
        "id": "card-15",
        "label": "Responsive card (vertical on small screen, horizontal on large screen)"
      },
      {
        "id": "card-16",
        "label": "Selectable cards"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/card/"
  },
  {
    "slug": "carousel",
    "title": "Carousel",
    "description": "Carousel show images or content in a scrollable area.",
    "demos": [
      {
        "id": "carousel-1",
        "label": "Snap to start (default)"
      },
      {
        "id": "carousel-2",
        "label": "Snap to center"
      },
      {
        "id": "carousel-3",
        "label": "Snap to end"
      },
      {
        "id": "carousel-4",
        "label": "Carousel with full width items"
      },
      {
        "id": "carousel-5",
        "label": "Vertical carousel"
      },
      {
        "id": "carousel-6",
        "label": "Carousel with half width items"
      },
      {
        "id": "carousel-7",
        "label": "Full-bleed carousel"
      },
      {
        "id": "carousel-8",
        "label": "Carousel with indicator buttons"
      },
      {
        "id": "carousel-9",
        "label": "Carousel with next/prev buttons"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/carousel/",
    "previewHeight": 340,
    "previewSpan": "wide"
  },
  {
    "slug": "chat",
    "title": "Chat bubble",
    "description": "Chat bubbles are used to show one line of conversation and all its data, including the author image, author name, time, etc.",
    "demos": [
      {
        "id": "chat-1",
        "label": "chat-start and chat-end"
      },
      {
        "id": "chat-2",
        "label": "Chat with image"
      },
      {
        "id": "chat-3",
        "label": "Chat with image, header and footer"
      },
      {
        "id": "chat-4",
        "label": "Chat with header and footer"
      },
      {
        "id": "chat-5",
        "label": "Chat Bubble with colors"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/chat/"
  },
  {
    "slug": "checkbox",
    "title": "Checkbox",
    "description": "Checkboxes are used to select or deselect a value.",
    "demos": [
      {
        "id": "checkbox-1",
        "label": "Checkbox"
      },
      {
        "id": "checkbox-2",
        "label": "With fieldset and label"
      },
      {
        "id": "checkbox-3",
        "label": "Sizes"
      },
      {
        "id": "checkbox-4",
        "label": "Colors"
      },
      {
        "id": "checkbox-5",
        "label": "Disabled"
      },
      {
        "id": "checkbox-6",
        "label": "Indeterminate"
      },
      {
        "id": "checkbox-7",
        "label": "Checkbox with custom colors"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/checkbox/"
  },
  {
    "slug": "collapse",
    "title": "Collapse",
    "description": "Collapse is used for showing and hiding content.",
    "demos": [
      {
        "id": "collapse-1",
        "label": "Collapse with focus"
      },
      {
        "id": "collapse-2",
        "label": "Collapse with checkbox"
      },
      {
        "id": "collapse-3",
        "label": "Collapse with checkbox and close on click outside"
      },
      {
        "id": "collapse-4",
        "label": "Collapse using details and summary tag"
      },
      {
        "id": "collapse-5",
        "label": "Without border and background color"
      },
      {
        "id": "collapse-6",
        "label": "With arrow icon"
      },
      {
        "id": "collapse-7",
        "label": "With arrow plus/minus icon"
      },
      {
        "id": "collapse-8",
        "label": "Moving collapse icon to the start"
      },
      {
        "id": "collapse-9",
        "label": "Force open"
      },
      {
        "id": "collapse-10",
        "label": "Force close"
      },
      {
        "id": "collapse-11",
        "label": "Custom colors for collapse that works with focus"
      },
      {
        "id": "collapse-12",
        "label": "Custom colors for collapse that works with checkbox"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/collapse/"
  },
  {
    "slug": "countdown",
    "title": "Countdown",
    "description": "Countdown gives you a transition effect when you change a number between 0 to 999.",
    "demos": [
      {
        "id": "countdown-1",
        "label": "Countdown"
      },
      {
        "id": "countdown-2",
        "label": "Large text with 2 digits"
      },
      {
        "id": "countdown-3",
        "label": "Clock countdown"
      },
      {
        "id": "countdown-4",
        "label": "Clock countdown with colons"
      },
      {
        "id": "countdown-5",
        "label": "Large text with labels"
      },
      {
        "id": "countdown-6",
        "label": "Large text with labels under"
      },
      {
        "id": "countdown-7",
        "label": "In boxes"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/countdown/"
  },
  {
    "slug": "diff",
    "title": "Diff",
    "description": "Diff component shows a side-by-side comparison of two items.",
    "demos": [
      {
        "id": "diff-1",
        "label": "Diff"
      },
      {
        "id": "diff-2",
        "label": "Diff text"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/diff/",
    "previewHeight": 320,
    "previewSpan": "wide"
  },
  {
    "slug": "divider",
    "title": "Divider",
    "description": "Divider will be used to separate content vertically or horizontally.",
    "demos": [
      {
        "id": "divider-1",
        "label": "Divider"
      },
      {
        "id": "divider-2",
        "label": "Divider horizontal"
      },
      {
        "id": "divider-3",
        "label": "Divider with no text"
      },
      {
        "id": "divider-4",
        "label": "responsive (lg:divider-horizontal)"
      },
      {
        "id": "divider-5",
        "label": "Divider with colors"
      },
      {
        "id": "divider-6",
        "label": "Divider in different positions"
      },
      {
        "id": "divider-7",
        "label": "Divider in different positions (horizontal)"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/divider/"
  },
  {
    "slug": "dock",
    "title": "Dock",
    "description": "Dock (also know as Bottom navigation or Bottom bar) is a UI element that provides navigation options to the user. Dock sticks to the bottom of the screen.",
    "demos": [
      {
        "id": "dock-1",
        "label": "Dock"
      },
      {
        "id": "dock-2",
        "label": "Dock Extra Small size"
      },
      {
        "id": "dock-3",
        "label": "Dock Small size"
      },
      {
        "id": "dock-4",
        "label": "Dock Medium size"
      },
      {
        "id": "dock-5",
        "label": "Dock Large size"
      },
      {
        "id": "dock-6",
        "label": "Dock Extra Large size"
      },
      {
        "id": "dock-7",
        "label": "Dock with custom colors"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/dock/",
    "previewHeight": 250,
    "previewSpan": "wide"
  },
  {
    "slug": "drawer",
    "title": "Drawer sidebar",
    "description": "Drawer is a grid layout that can show/hide a sidebar on the left or right side of the page.",
    "demos": [
      {
        "id": "drawer-1",
        "label": "Drawer sidebar"
      },
      {
        "id": "drawer-2",
        "label": "Navbar menu for desktop + sidebar drawer for mobile"
      },
      {
        "id": "drawer-3",
        "label": "Responsive: Sidebar is always visible on large screen, can be toggled on small screen"
      },
      {
        "id": "drawer-4",
        "label": "Responsive collapsible Icon-only drawer sidebar. Using is-drawer-close and is-drawer-open"
      },
      {
        "id": "drawer-5",
        "label": "Drawer sidebar that opens from right side of page"
      }
    ],
    "layout": "fill",
    "docsUrl": "https://daisyui.com/components/drawer/",
    "previewHeight": 390,
    "previewSpan": "wide"
  },
  {
    "slug": "dropdown",
    "title": "Dropdown",
    "description": "Dropdown can open a menu or any other element when the button is clicked.",
    "demos": [
      {
        "id": "dropdown-1",
        "label": "Dropdown using details and summary"
      },
      {
        "id": "dropdown-2",
        "label": "Dropdown using popover API and anchor positioning"
      },
      {
        "id": "dropdown-3",
        "label": "Dropdown menu"
      },
      {
        "id": "dropdown-4",
        "label": "Dropdown / aligns to start of button horizontally"
      },
      {
        "id": "dropdown-5",
        "label": "Dropdown / aligns to end of button horizontally"
      },
      {
        "id": "dropdown-6",
        "label": "Dropdown / aligns to center of button horizontally"
      },
      {
        "id": "dropdown-7",
        "label": "Dropdown top"
      },
      {
        "id": "dropdown-8",
        "label": "Dropdown top / aligns to center of button horizontally"
      },
      {
        "id": "dropdown-9",
        "label": "Dropdown top / aligns to end of button horizontally"
      },
      {
        "id": "dropdown-10",
        "label": "Dropdown bottom (default)"
      },
      {
        "id": "dropdown-11",
        "label": "Dropdown bottom (default) / aligns to center of button horizontally"
      },
      {
        "id": "dropdown-12",
        "label": "Dropdown bottom (default) / aligns to end of button horizontally"
      },
      {
        "id": "dropdown-13",
        "label": "Dropdown left"
      },
      {
        "id": "dropdown-14",
        "label": "Dropdown left / aligns to center of button vertically"
      },
      {
        "id": "dropdown-15",
        "label": "Dropdown left / aligns to end of button vertically"
      },
      {
        "id": "dropdown-16",
        "label": "Dropdown right"
      },
      {
        "id": "dropdown-17",
        "label": "Dropdown right / aligns to end of button vertically"
      },
      {
        "id": "dropdown-18",
        "label": "Dropdown right / aligns to center of button vertically"
      },
      {
        "id": "dropdown-19",
        "label": "Dropdown on hover"
      },
      {
        "id": "dropdown-20",
        "label": "Force open"
      },
      {
        "id": "dropdown-21",
        "label": "Force close"
      },
      {
        "id": "dropdown-22",
        "label": "Card as dropdown"
      },
      {
        "id": "dropdown-23",
        "label": "Dropdown in navbar"
      },
      {
        "id": "dropdown-24",
        "label": "Helper dropdown"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/dropdown/",
    "previewHeight": 330
  },
  {
    "slug": "fab",
    "title": "FAB / Speed Dial",
    "description": "FAB (Floating Action Button) stays in the bottom corner of screen. It includes a focusable and accessible element with button role. Clicking or focusing it shows additional buttons (known as Speed Dial buttons) in a vertical arrangement or a flower shape (quarter circle).",
    "demos": [
      {
        "id": "fab-1",
        "label": "FAB and Speed Dial (vertical)"
      },
      {
        "id": "fab-2",
        "label": "FAB and Speed Dial with SVG icons"
      },
      {
        "id": "fab-3",
        "label": "FAB and Speed Dial with labels"
      },
      {
        "id": "fab-4",
        "label": "FAB and Speed Dial with rectangle buttons"
      },
      {
        "id": "fab-5",
        "label": "FAB and Speed Dial with labels and fab-close button"
      },
      {
        "id": "fab-6",
        "label": "FAB and Speed Dial with labels and fab-main-action Button"
      },
      {
        "id": "fab-7",
        "label": "A single FAB (Floating Action Button)"
      },
      {
        "id": "fab-8",
        "label": "FAB Flower and Speed Dial"
      },
      {
        "id": "fab-9",
        "label": "FAB Flower without a main action button"
      },
      {
        "id": "fab-10",
        "label": "FAB and Flower Speed Dial with SVG icons"
      },
      {
        "id": "fab-11",
        "label": "FAB and Flower Speed Dial with tooltip"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/fab/",
    "previewHeight": 340
  },
  {
    "slug": "fieldset",
    "title": "Fieldset",
    "description": "Fieldset is a container for grouping related form elements. It includes fieldset-legend as a title and label as a description.",
    "demos": [
      {
        "id": "fieldset-1",
        "label": "Fieldset fieldset-legend and label"
      },
      {
        "id": "fieldset-2",
        "label": "Fieldset with background and border"
      },
      {
        "id": "fieldset-3",
        "label": "Fieldset with multiple inputs"
      },
      {
        "id": "fieldset-4",
        "label": "Fieldset with multiple join items"
      },
      {
        "id": "fieldset-5",
        "label": "Login form with fieldset"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/fieldset/"
  },
  {
    "slug": "file-input",
    "title": "File Input",
    "description": "File Input is an input field for uploading files.",
    "demos": [
      {
        "id": "file-input-1",
        "label": "File input"
      },
      {
        "id": "file-input-2",
        "label": "File input ghost"
      },
      {
        "id": "file-input-3",
        "label": "With fieldset and label"
      },
      {
        "id": "file-input-4",
        "label": "Sizes"
      },
      {
        "id": "file-input-5",
        "label": "Primary color"
      },
      {
        "id": "file-input-6",
        "label": "Disabled"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/file-input/"
  },
  {
    "slug": "filter",
    "title": "Filter",
    "description": "Filter is a group of radio buttons. Choosing one of the options will hide the others and shows a reset button next to the chosen option.",
    "demos": [
      {
        "id": "filter-1",
        "label": "Filter using HTML form, radio buttons and reset button"
      },
      {
        "id": "filter-2",
        "label": "Filter without HTML form"
      },
      {
        "id": "filter-3",
        "label": "Filter using HTML form, checkboxes, and a reset button"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/filter/"
  },
  {
    "slug": "footer",
    "title": "Footer",
    "description": "Footer can contain logo, copyright notice, and links to other pages.",
    "demos": [
      {
        "id": "footer-1",
        "label": "Footer (vertical by default, horizontal for sm and up)"
      },
      {
        "id": "footer-2",
        "label": "Footer with a logo section"
      },
      {
        "id": "footer-3",
        "label": "Footer with a form"
      },
      {
        "id": "footer-4",
        "label": "Footer with logo and social icons"
      },
      {
        "id": "footer-5",
        "label": "Footer with copyright text"
      },
      {
        "id": "footer-6",
        "label": "Footer with copyright text and social icons"
      },
      {
        "id": "footer-7",
        "label": "Footer with links and social icons"
      },
      {
        "id": "footer-8",
        "label": "Footer with 2 rows"
      },
      {
        "id": "footer-9",
        "label": "Centered footer with logo and social icons"
      },
      {
        "id": "footer-10",
        "label": "Centered footer with social icons"
      },
      {
        "id": "footer-11",
        "label": "Two footer"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/footer/",
    "previewHeight": 360,
    "previewSpan": "wide"
  },
  {
    "slug": "hero",
    "title": "Hero",
    "description": "Hero is a component for displaying a large box or image with a title and description.",
    "demos": [
      {
        "id": "hero-1",
        "label": "Centered hero"
      },
      {
        "id": "hero-2",
        "label": "Hero with figure"
      },
      {
        "id": "hero-3",
        "label": "Hero with figure but reverse order"
      },
      {
        "id": "hero-4",
        "label": "Hero with form"
      },
      {
        "id": "hero-5",
        "label": "Hero with overlay image"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/hero/",
    "previewHeight": 380,
    "previewSpan": "wide"
  },
  {
    "slug": "hover-3d",
    "title": "Hover 3D Card",
    "description": "Hover 3D is a wrapper component that adds a 3D hover effect to its content. When we hover over the component, it tilts and rotates based on the mouse position, creating an interactive 3D effect.",
    "demos": [
      {
        "id": "hover-3d-1",
        "label": "3D image hover effect"
      },
      {
        "id": "hover-3d-2",
        "label": "3D card hover effect"
      },
      {
        "id": "hover-3d-3",
        "label": "3D hover effect for image gallery"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/hover-3d/"
  },
  {
    "slug": "hover-gallery",
    "title": "Hover Gallery",
    "description": "Hover Gallery is container of images. The first image is visible by default and when we hover it horizontally, other images show up. Hover Gallery is useful for product cards in ecommerce sites, portfolios or in image galleries. Hover Gallery can include up to 10 images.",
    "demos": [
      {
        "id": "hover-gallery-1",
        "label": "Hover Gallery"
      },
      {
        "id": "hover-gallery-2",
        "label": "Hover Gallery in a card"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/hover-gallery/",
    "previewHeight": 360,
    "previewSpan": "wide"
  },
  {
    "slug": "indicator",
    "title": "Indicator",
    "description": "Indicators are used to place an element on the corner of another element.",
    "demos": [
      {
        "id": "indicator-1",
        "label": "Status Indicator"
      },
      {
        "id": "indicator-2",
        "label": "Badge as indicator"
      },
      {
        "id": "indicator-3",
        "label": "for button"
      },
      {
        "id": "indicator-4",
        "label": "for tab"
      },
      {
        "id": "indicator-5",
        "label": "for avatar"
      },
      {
        "id": "indicator-6",
        "label": "for an input"
      },
      {
        "id": "indicator-7",
        "label": "A button as an indicator for a card"
      },
      {
        "id": "indicator-8",
        "label": "in center of an image"
      },
      {
        "id": "indicator-9",
        "label": "indicator-top (default) indicator-start"
      },
      {
        "id": "indicator-10",
        "label": "indicator-top (default) indicator-center"
      },
      {
        "id": "indicator-11",
        "label": "indicator-top (default) indicator-end (default)"
      },
      {
        "id": "indicator-12",
        "label": "indicator-middle indicator-start"
      },
      {
        "id": "indicator-13",
        "label": "indicator-middle indicator-center"
      },
      {
        "id": "indicator-14",
        "label": "indicator-middle indicator-end (default)"
      },
      {
        "id": "indicator-15",
        "label": "indicator-bottom indicator-start"
      },
      {
        "id": "indicator-16",
        "label": "indicator-bottom indicator-center"
      },
      {
        "id": "indicator-17",
        "label": "indicator-bottom indicator-end (default)"
      },
      {
        "id": "indicator-18",
        "label": "multiple indicators"
      },
      {
        "id": "indicator-19",
        "label": "Responsive"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/indicator/"
  },
  {
    "slug": "input",
    "title": "Text Input",
    "description": "Text Input is a simple input field.",
    "demos": [
      {
        "id": "input-1",
        "label": "Text input"
      },
      {
        "id": "input-2",
        "label": "Text input with text label inside"
      },
      {
        "id": "input-3",
        "label": "Ghost style"
      },
      {
        "id": "input-4",
        "label": "With fieldset and fieldset-legend"
      },
      {
        "id": "input-5",
        "label": "With fieldset and label"
      },
      {
        "id": "input-6",
        "label": "Input colors"
      },
      {
        "id": "input-7",
        "label": "Sizes"
      },
      {
        "id": "input-8",
        "label": "Disabled"
      },
      {
        "id": "input-9",
        "label": "Text input with data list suggestion"
      },
      {
        "id": "input-10",
        "label": "Date input"
      },
      {
        "id": "input-11",
        "label": "Time input"
      },
      {
        "id": "input-12",
        "label": "datetime-local input"
      },
      {
        "id": "input-13",
        "label": "Username text input with icon and validator"
      },
      {
        "id": "input-14",
        "label": "Search input with icon"
      },
      {
        "id": "input-15",
        "label": "Email input with icon and validator"
      },
      {
        "id": "input-16",
        "label": "Email input with icon, validator, button, join"
      },
      {
        "id": "input-17",
        "label": "Password input with icon and validator"
      },
      {
        "id": "input-18",
        "label": "Number input with validator"
      },
      {
        "id": "input-19",
        "label": "Telephone number input with icon and validator"
      },
      {
        "id": "input-20",
        "label": "URL with icon and validator"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/input/"
  },
  {
    "slug": "join",
    "title": "Join (group items)",
    "description": "Join is a container for grouping multiple items, it can be used to group buttons, inputs, etc. Join applies border radius to the first and last item. Join can be used to create a horizontal or vertical list of items.",
    "demos": [
      {
        "id": "join-1",
        "label": "Join"
      },
      {
        "id": "join-2",
        "label": "Group items vertically"
      },
      {
        "id": "join-3",
        "label": "Responsive: it's vertical on small screen and horizontal on large screen"
      },
      {
        "id": "join-4",
        "label": "With extra elements in the group"
      },
      {
        "id": "join-5",
        "label": "Custom border radius"
      },
      {
        "id": "join-6",
        "label": "Join radio inputs with btn style"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/join/"
  },
  {
    "slug": "kbd",
    "title": "Kbd",
    "description": "Kbd is used to display keyboard shortcuts.",
    "demos": [
      {
        "id": "kbd-1",
        "label": "Kbd"
      },
      {
        "id": "kbd-2",
        "label": "Kbd sizes"
      },
      {
        "id": "kbd-3",
        "label": "In text"
      },
      {
        "id": "kbd-4",
        "label": "Key combination"
      },
      {
        "id": "kbd-5",
        "label": "Function Keys"
      },
      {
        "id": "kbd-6",
        "label": "A full keyboard"
      },
      {
        "id": "kbd-7",
        "label": "Arrow Keys"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/kbd/"
  },
  {
    "slug": "label",
    "title": "Label",
    "description": "Label is used to provide a name or title for an input field. Label can be placed before or after the field.",
    "demos": [
      {
        "id": "label-1",
        "label": "Label for input"
      },
      {
        "id": "label-2",
        "label": "Label for input at the end"
      },
      {
        "id": "label-3",
        "label": "Label for select"
      },
      {
        "id": "label-4",
        "label": "Label for date input"
      },
      {
        "id": "label-5",
        "label": "Floating Label"
      },
      {
        "id": "label-6",
        "label": "Floating Label with Different Sizes"
      },
      {
        "id": "label-7",
        "label": "Responsive Size Floating Label"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/label/"
  },
  {
    "slug": "link",
    "title": "Link",
    "description": "Link adds the missing underline style to links.",
    "demos": [
      {
        "id": "link-1",
        "label": "Link"
      },
      {
        "id": "link-2",
        "label": "Link"
      },
      {
        "id": "link-3",
        "label": "Primary color"
      },
      {
        "id": "link-4",
        "label": "Secondary color"
      },
      {
        "id": "link-5",
        "label": "Accent color"
      },
      {
        "id": "link-6",
        "label": "Success color"
      },
      {
        "id": "link-7",
        "label": "Info color"
      },
      {
        "id": "link-8",
        "label": "Warning color"
      },
      {
        "id": "link-9",
        "label": "Error color"
      },
      {
        "id": "link-10",
        "label": "Show underline only on hover"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/link/"
  },
  {
    "slug": "list",
    "title": "List",
    "description": "List is a vertical layout to display information in rows.",
    "demos": [
      {
        "id": "list-1",
        "label": "List (second column grows - default)"
      },
      {
        "id": "list-2",
        "label": "List (third column grows)"
      },
      {
        "id": "list-3",
        "label": "List (third column wraps to next row)"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/list/",
    "previewHeight": 420,
    "previewSpan": "wide"
  },
  {
    "slug": "loading",
    "title": "Loading",
    "description": "Loading shows an animation to indicate that something is loading.",
    "demos": [
      {
        "id": "loading-1",
        "label": "Loading spinner"
      },
      {
        "id": "loading-2",
        "label": "Loading dots"
      },
      {
        "id": "loading-3",
        "label": "Loading ring"
      },
      {
        "id": "loading-4",
        "label": "Loading ball"
      },
      {
        "id": "loading-5",
        "label": "Loading bars"
      },
      {
        "id": "loading-6",
        "label": "Loading infinity"
      },
      {
        "id": "loading-7",
        "label": "Loading with colors"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/loading/"
  },
  {
    "slug": "mask",
    "title": "Mask",
    "description": "Mask crops the content of the element to common shapes.",
    "demos": [
      {
        "id": "mask-1",
        "label": "Squircle"
      },
      {
        "id": "mask-2",
        "label": "Heart"
      },
      {
        "id": "mask-3",
        "label": "Hexagon"
      },
      {
        "id": "mask-4",
        "label": "Hexagon-2 (horizontal hexagon)"
      },
      {
        "id": "mask-5",
        "label": "Decagon"
      },
      {
        "id": "mask-6",
        "label": "Pentagon"
      },
      {
        "id": "mask-7",
        "label": "Diamond"
      },
      {
        "id": "mask-8",
        "label": "Circle"
      },
      {
        "id": "mask-9",
        "label": "Star"
      },
      {
        "id": "mask-10",
        "label": "Star-2 (bold star)"
      },
      {
        "id": "mask-11",
        "label": "Triangle (pointing top)"
      },
      {
        "id": "mask-12",
        "label": "Triangle-2 (pointing down)"
      },
      {
        "id": "mask-13",
        "label": "Triangle-3 (pointing left)"
      },
      {
        "id": "mask-14",
        "label": "Triangle-4 (pointing right)"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/mask/"
  },
  {
    "slug": "megamenu",
    "title": "Megamenu",
    "description": "A megamenu is a large, horizontal menu where each item opens a popover to show a large block of navigation links. Megamenu must be used once, on top of the page. Inside each popover, you can use a daisyUI menu, or any custom content. Megamenu fits better on large screens only, and for small screens, you can hide the megamenu and show the content in a dropdown or a drawer.",
    "demos": [
      {
        "id": "megamenu-1",
        "label": "Responsive megamenu with small vertical menus"
      },
      {
        "id": "megamenu-2",
        "label": "Megamenu with wide popovers and horizontal menus"
      },
      {
        "id": "megamenu-3",
        "label": "Megamenu with a menus and lots of links"
      },
      {
        "id": "megamenu-4",
        "label": "Megamenu in a navbar"
      },
      {
        "id": "megamenu-5",
        "label": "megamenu without arrows"
      },
      {
        "id": "megamenu-6",
        "label": "Megamenu in different sizes"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/megamenu/",
    "previewHeight": 420,
    "previewSpan": "wide"
  },
  {
    "slug": "menu",
    "title": "Menu",
    "description": "Menu is used to display a list of links vertically or horizontally.",
    "demos": [
      {
        "id": "menu-1",
        "label": "Menu"
      },
      {
        "id": "menu-2",
        "label": "Responsive: vertical on small screen, horizontal on large screen"
      },
      {
        "id": "menu-3",
        "label": "Paged menu with nested submenus"
      },
      {
        "id": "menu-4",
        "label": "Menu with icon only"
      },
      {
        "id": "menu-5",
        "label": "Menu with icon only (horizontal)"
      },
      {
        "id": "menu-6",
        "label": "Menu with icon only with tooltip"
      },
      {
        "id": "menu-7",
        "label": "Menu with icon only (horizontal) with tooltip"
      },
      {
        "id": "menu-8",
        "label": "Menu sizes"
      },
      {
        "id": "menu-9",
        "label": "Menu with disabled items"
      },
      {
        "id": "menu-10",
        "label": "Menu with icons"
      },
      {
        "id": "menu-11",
        "label": "Menu with icons and badge (responsive)"
      },
      {
        "id": "menu-12",
        "label": "Menu without padding and border radius"
      },
      {
        "id": "menu-13",
        "label": "Menu with title"
      },
      {
        "id": "menu-14",
        "label": "Menu with title as a parent"
      },
      {
        "id": "menu-15",
        "label": "Submenu"
      },
      {
        "id": "menu-16",
        "label": "Collapsible submenu"
      },
      {
        "id": "menu-17",
        "label": "Collapsible submenu that works with class names"
      },
      {
        "id": "menu-18",
        "label": "File tree"
      },
      {
        "id": "menu-19",
        "label": "Menu with active item"
      },
      {
        "id": "menu-20",
        "label": "Horizontal menu"
      },
      {
        "id": "menu-21",
        "label": "Horizontal submenu"
      },
      {
        "id": "menu-22",
        "label": "Mega menu with submenu (responsive)"
      },
      {
        "id": "menu-23",
        "label": "Collapsible with submenu (responsive)"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/menu/",
    "previewHeight": 430
  },
  {
    "slug": "mockup-browser",
    "title": "Browser mockup",
    "description": "Browser mockup shows a box that looks like a browser window.",
    "demos": [
      {
        "id": "mockup-browser-1",
        "label": "browser mockup with border"
      },
      {
        "id": "mockup-browser-2",
        "label": "browser mockup with background color"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/mockup-browser/",
    "previewHeight": 350,
    "previewSpan": "wide"
  },
  {
    "slug": "mockup-code",
    "title": "Code mockup",
    "description": "Code mockup is used to show a block of code in a box that looks like a code editor.",
    "demos": [
      {
        "id": "mockup-code-1",
        "label": "mockup code with line prefix"
      },
      {
        "id": "mockup-code-2",
        "label": "Multi line"
      },
      {
        "id": "mockup-code-3",
        "label": "Highlighted line"
      },
      {
        "id": "mockup-code-4",
        "label": "Long line will scroll"
      },
      {
        "id": "mockup-code-5",
        "label": "Without prefix"
      },
      {
        "id": "mockup-code-6",
        "label": "With color"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/mockup-code/",
    "previewHeight": 330,
    "previewSpan": "wide"
  },
  {
    "slug": "mockup-phone",
    "title": "Phone mockup",
    "description": "Phone mockup shows a mockup of an iPhone.",
    "demos": [
      {
        "id": "mockup-phone-1",
        "label": "iPhone mockup"
      },
      {
        "id": "mockup-phone-2",
        "label": "With color and wallpaper"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/mockup-phone/",
    "previewHeight": 590
  },
  {
    "slug": "mockup-window",
    "title": "Window mockup",
    "description": "Window mockup shows a box that looks like an operating system window.",
    "demos": [
      {
        "id": "mockup-window-1",
        "label": "window mockup with border"
      },
      {
        "id": "mockup-window-2",
        "label": "window mockup with background color"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/mockup-window/",
    "previewHeight": 350,
    "previewSpan": "wide"
  },
  {
    "slug": "modal",
    "title": "Modal",
    "description": "Modal is used to show a dialog or a box when you click a button.",
    "demos": [
      {
        "id": "modal-1",
        "label": "Dialog modal"
      },
      {
        "id": "modal-2",
        "label": "Dialog modal, closes when clicked outside"
      },
      {
        "id": "modal-3",
        "label": "Dialog modal with a close button at corner"
      },
      {
        "id": "modal-4",
        "label": "Dialog modal with custom width"
      },
      {
        "id": "modal-5",
        "label": "Responsive"
      },
      {
        "id": "modal-6",
        "label": "Popover modal"
      },
      {
        "id": "modal-7",
        "label": "Popover modal closes when clicked outside"
      },
      {
        "id": "modal-8",
        "label": "Modal using checkbox"
      },
      {
        "id": "modal-9",
        "label": "Modal that closes when clicked outside"
      },
      {
        "id": "modal-10",
        "label": "Modal using anchor link"
      }
    ],
    "layout": "fill",
    "docsUrl": "https://daisyui.com/components/modal/",
    "previewHeight": 380,
    "previewSpan": "wide"
  },
  {
    "slug": "navbar",
    "title": "Navbar",
    "description": "Navbar is used to show a navigation bar on the top of the page.",
    "demos": [
      {
        "id": "navbar-1",
        "label": "Navbar with title only"
      },
      {
        "id": "navbar-2",
        "label": "Navbar with title and icon"
      },
      {
        "id": "navbar-3",
        "label": "Navbar with icon at start and end"
      },
      {
        "id": "navbar-4",
        "label": "Navbar with menu and submenu"
      },
      {
        "id": "navbar-5",
        "label": "Navbar with search input and dropdown"
      },
      {
        "id": "navbar-6",
        "label": "Navbar with icon, indicator and dropdown"
      },
      {
        "id": "navbar-7",
        "label": "Navbar with dropdown, center logo and icon"
      },
      {
        "id": "navbar-8",
        "label": "Responsive (dropdown menu on small screen, center menu on large screen)"
      },
      {
        "id": "navbar-9",
        "label": "Responsive (collapse on small screen, full content on large screen)"
      },
      {
        "id": "navbar-10",
        "label": "Navbar with colors"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/navbar/",
    "previewHeight": 260,
    "previewSpan": "wide"
  },
  {
    "slug": "otp",
    "title": "OTP",
    "description": "OTP (One-Time Password) component for inputting verification codes. It's usually 4 to 6 digits long and is used for two-factor authentication (2FA) or passwordless login.",
    "demos": [
      {
        "id": "otp-1",
        "label": "OTP"
      },
      {
        "id": "otp-2",
        "label": "OTP with 6 digits"
      },
      {
        "id": "otp-3",
        "label": "OTP joined"
      },
      {
        "id": "otp-4",
        "label": "OTP with different sizes"
      },
      {
        "id": "otp-5",
        "label": "OTP with different colors"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/otp/"
  },
  {
    "slug": "pagination",
    "title": "Pagination",
    "description": "Pagination is a group of buttons that allow the user to navigate between a set of related content.",
    "demos": [
      {
        "id": "pagination-1",
        "label": "Pagination with an active button"
      },
      {
        "id": "pagination-2",
        "label": "Sizes"
      },
      {
        "id": "pagination-3",
        "label": "With a disabled button"
      },
      {
        "id": "pagination-4",
        "label": "Extra small buttons"
      },
      {
        "id": "pagination-5",
        "label": "Nex/Prev outline buttons with equal width"
      },
      {
        "id": "pagination-6",
        "label": "Using radio inputs"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/pagination/"
  },
  {
    "slug": "progress",
    "title": "Progress",
    "description": "Progress bar can be used to show the progress of a task or to show the passing of time.",
    "demos": [
      {
        "id": "progress-1",
        "label": "Progress"
      },
      {
        "id": "progress-2",
        "label": "Primary color"
      },
      {
        "id": "progress-3",
        "label": "Secondary color"
      },
      {
        "id": "progress-4",
        "label": "Accent color"
      },
      {
        "id": "progress-5",
        "label": "Neutral color"
      },
      {
        "id": "progress-6",
        "label": "Info color"
      },
      {
        "id": "progress-7",
        "label": "Success color"
      },
      {
        "id": "progress-8",
        "label": "Warning color"
      },
      {
        "id": "progress-9",
        "label": "Error color"
      },
      {
        "id": "progress-10",
        "label": "Indeterminate (without value)"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/progress/"
  },
  {
    "slug": "radial-progress",
    "title": "Radial progress",
    "description": "Radial progress can be used to show the progress of a task or to show the passing of time.",
    "demos": [
      {
        "id": "radial-progress-1",
        "label": "Radial progress"
      },
      {
        "id": "radial-progress-2",
        "label": "Different values"
      },
      {
        "id": "radial-progress-3",
        "label": "Custom color"
      },
      {
        "id": "radial-progress-4",
        "label": "With background color and border"
      },
      {
        "id": "radial-progress-5",
        "label": "Custom size and custom thickness"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/radial-progress/"
  },
  {
    "slug": "radio",
    "title": "Radio",
    "description": "Radio buttons allow the user to select one option from a set.",
    "demos": [
      {
        "id": "radio-1",
        "label": "Radio"
      },
      {
        "id": "radio-2",
        "label": "Radio sizes"
      },
      {
        "id": "radio-3",
        "label": "Neutral color"
      },
      {
        "id": "radio-4",
        "label": "Primary color"
      },
      {
        "id": "radio-5",
        "label": "Secondary color"
      },
      {
        "id": "radio-6",
        "label": "Accent color"
      },
      {
        "id": "radio-7",
        "label": "Success color"
      },
      {
        "id": "radio-8",
        "label": "Warning color"
      },
      {
        "id": "radio-9",
        "label": "Info color"
      },
      {
        "id": "radio-10",
        "label": "Error color"
      },
      {
        "id": "radio-11",
        "label": "Disabled"
      },
      {
        "id": "radio-12",
        "label": "Radio with custom colors"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/radio/"
  },
  {
    "slug": "range",
    "title": "Range slider",
    "description": "Range slider is used to select a value by sliding a handle.",
    "demos": [
      {
        "id": "range-1",
        "label": "Range"
      },
      {
        "id": "range-2",
        "label": "With steps and measure"
      },
      {
        "id": "range-3",
        "label": "Neutral color"
      },
      {
        "id": "range-4",
        "label": "Primary color"
      },
      {
        "id": "range-5",
        "label": "Secondary color"
      },
      {
        "id": "range-6",
        "label": "Accent color"
      },
      {
        "id": "range-7",
        "label": "Success color"
      },
      {
        "id": "range-8",
        "label": "Warning color"
      },
      {
        "id": "range-9",
        "label": "Info color"
      },
      {
        "id": "range-10",
        "label": "Error color"
      },
      {
        "id": "range-11",
        "label": "Sizes"
      },
      {
        "id": "range-12",
        "label": "Range with custom color and no fill"
      },
      {
        "id": "range-13",
        "label": "Vertical"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/range/"
  },
  {
    "slug": "rating",
    "title": "Rating",
    "description": "Rating is a set of radio buttons that allow the user to rate something.",
    "demos": [
      {
        "id": "rating-1",
        "label": "Rating"
      },
      {
        "id": "rating-2",
        "label": "Read-only Rating"
      },
      {
        "id": "rating-3",
        "label": "mask-star-2 with warning color"
      },
      {
        "id": "rating-4",
        "label": "mask-heart with multiple colors"
      },
      {
        "id": "rating-5",
        "label": "mask-star-2 with green-500 color"
      },
      {
        "id": "rating-6",
        "label": "Sizes"
      },
      {
        "id": "rating-7",
        "label": "with rating-hidden"
      },
      {
        "id": "rating-8",
        "label": "half stars"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/rating/"
  },
  {
    "slug": "select",
    "title": "Select",
    "description": "Select is used to pick a value from a list of options.",
    "demos": [
      {
        "id": "select-1",
        "label": "Select"
      },
      {
        "id": "select-2",
        "label": "Ghost (no background)"
      },
      {
        "id": "select-3",
        "label": "With fieldset and labels"
      },
      {
        "id": "select-4",
        "label": "Primary color"
      },
      {
        "id": "select-5",
        "label": "Secondary color"
      },
      {
        "id": "select-6",
        "label": "Accent color"
      },
      {
        "id": "select-7",
        "label": "Neutral color"
      },
      {
        "id": "select-8",
        "label": "Info color"
      },
      {
        "id": "select-9",
        "label": "Success color"
      },
      {
        "id": "select-10",
        "label": "Warning color"
      },
      {
        "id": "select-11",
        "label": "Error color"
      },
      {
        "id": "select-12",
        "label": "Sizes"
      },
      {
        "id": "select-13",
        "label": "Disabled"
      },
      {
        "id": "select-14",
        "label": "Using OS native style for the options dropdown"
      },
      {
        "id": "select-15",
        "label": "Select with custom dropdown height"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/select/"
  },
  {
    "slug": "skeleton",
    "title": "Skeleton",
    "description": "Skeleton is a component that can be used to show a loading state of a component.",
    "demos": [
      {
        "id": "skeleton-1",
        "label": "Skeleton"
      },
      {
        "id": "skeleton-2",
        "label": "Skeleton - circle with content"
      },
      {
        "id": "skeleton-3",
        "label": "Skeleton - rectangle with content"
      },
      {
        "id": "skeleton-4",
        "label": "skeleton-text - animated gradient text"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/skeleton/"
  },
  {
    "slug": "stack",
    "title": "Stack",
    "description": "Stack visually puts elements on top of each other.",
    "demos": [
      {
        "id": "stack-1",
        "label": "3 divs in a stack"
      },
      {
        "id": "stack-2",
        "label": "stacked images"
      },
      {
        "id": "stack-3",
        "label": "stacked cards"
      },
      {
        "id": "stack-4",
        "label": "stacked cards (top direction)"
      },
      {
        "id": "stack-5",
        "label": "stacked cards (start direction)"
      },
      {
        "id": "stack-6",
        "label": "stacked cards (end direction)"
      },
      {
        "id": "stack-7",
        "label": "stacked cards with shadow"
      },
      {
        "id": "stack-8",
        "label": "stacked cards"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/stack/"
  },
  {
    "slug": "stat",
    "title": "Stat",
    "description": "Stat is used to show numbers and data in a block.",
    "demos": [
      {
        "id": "stat-1",
        "label": "Stat"
      },
      {
        "id": "stat-2",
        "label": "Stat with icons or image"
      },
      {
        "id": "stat-3",
        "label": "Stat"
      },
      {
        "id": "stat-4",
        "label": "Centered items"
      },
      {
        "id": "stat-5",
        "label": "Vertical"
      },
      {
        "id": "stat-6",
        "label": "Responsive (vertical on small screen, horizontal on large screen)"
      },
      {
        "id": "stat-7",
        "label": "With custom colors and button"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/stat/",
    "previewHeight": 300,
    "previewSpan": "wide"
  },
  {
    "slug": "status",
    "title": "Status",
    "description": "Status is a really small icon to visually show the current status of an element, like online, offline, error, etc.",
    "demos": [
      {
        "id": "status-1",
        "label": "Status"
      },
      {
        "id": "status-2",
        "label": "Status sizes"
      },
      {
        "id": "status-3",
        "label": "Status with colors"
      },
      {
        "id": "status-4",
        "label": "Status with ping animation"
      },
      {
        "id": "status-5",
        "label": "Status with bounce animation"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/status/"
  },
  {
    "slug": "steps",
    "title": "Steps",
    "description": "Steps can be used to show a list of steps in a process.",
    "demos": [
      {
        "id": "steps-1",
        "label": "Horizontal"
      },
      {
        "id": "steps-2",
        "label": "Vertical"
      },
      {
        "id": "steps-3",
        "label": "responsive (vertical on small screen, horizontal on large screen)"
      },
      {
        "id": "steps-4",
        "label": "With custom content in step-icon"
      },
      {
        "id": "steps-5",
        "label": "With data-content"
      },
      {
        "id": "steps-6",
        "label": "Custom colors"
      },
      {
        "id": "steps-7",
        "label": "With scrollable wrapper"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/steps/"
  },
  {
    "slug": "swap",
    "title": "Swap",
    "description": "Swap allows you to toggle the visibility of two elements using a checkbox or a class name.",
    "demos": [
      {
        "id": "swap-1",
        "label": "Swap text"
      },
      {
        "id": "swap-2",
        "label": "Swap volume icons"
      },
      {
        "id": "swap-3",
        "label": "Swap icons with rotate effect"
      },
      {
        "id": "swap-4",
        "label": "Hamburger button"
      },
      {
        "id": "swap-5",
        "label": "Swap icons with flip effect"
      },
      {
        "id": "swap-6",
        "label": "Activate using class name instead of checkbox"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/swap/"
  },
  {
    "slug": "tab",
    "title": "Tabs",
    "description": "Tabs can be used to show a list of links in a tabbed format.",
    "demos": [
      {
        "id": "tab-1",
        "label": "tabs"
      },
      {
        "id": "tab-2",
        "label": "tabs-border"
      },
      {
        "id": "tab-3",
        "label": "tabs-lift"
      },
      {
        "id": "tab-4",
        "label": "tabs-box"
      },
      {
        "id": "tab-5",
        "label": "tabs-box using radio inputs"
      },
      {
        "id": "tab-6",
        "label": "Sizes"
      },
      {
        "id": "tab-7",
        "label": "radio tabs-border + tab content"
      },
      {
        "id": "tab-8",
        "label": "radio tabs-lift + tab content"
      },
      {
        "id": "tab-9",
        "label": "radio tabs-lift with icons + tab content"
      },
      {
        "id": "tab-10",
        "label": "radio tabs-lift + tab content on bottom"
      },
      {
        "id": "tab-11",
        "label": "radio tabs-box + tab content"
      },
      {
        "id": "tab-12",
        "label": "tabs-box with a horizontal scroll when there's no space"
      },
      {
        "id": "tab-13",
        "label": "Tabs with custom color"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/tab/"
  },
  {
    "slug": "table",
    "title": "Table",
    "description": "Table can be used to show a list of data in a table format.",
    "demos": [
      {
        "id": "table-1",
        "label": "Table"
      },
      {
        "id": "table-2",
        "label": "Table with border and background"
      },
      {
        "id": "table-3",
        "label": "Table with an active row"
      },
      {
        "id": "table-4",
        "label": "Table with a row that highlights on hover"
      },
      {
        "id": "table-5",
        "label": "Zebra"
      },
      {
        "id": "table-6",
        "label": "Table with visual elements"
      },
      {
        "id": "table-7",
        "label": "Table xs"
      },
      {
        "id": "table-8",
        "label": "Table with pinned-rows"
      },
      {
        "id": "table-9",
        "label": "Table with pinned-rows and pinned-cols"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/table/",
    "previewHeight": 350,
    "previewSpan": "wide"
  },
  {
    "slug": "text-rotate",
    "title": "Text Rotate",
    "description": "Text Rotate can show up to 6 lines of text, one at a time, with an infinite loop animation. Duration is 10 seconds by default. The animation will pause on hover.",
    "demos": [
      {
        "id": "text-rotate-1",
        "label": "Text Rotate"
      },
      {
        "id": "text-rotate-2",
        "label": "Rotating 6 words"
      },
      {
        "id": "text-rotate-3",
        "label": "Rotating words in a sentence"
      },
      {
        "id": "text-rotate-4",
        "label": "Rotating 3 words with custom duration"
      },
      {
        "id": "text-rotate-5",
        "label": "Custom line height"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/text-rotate/"
  },
  {
    "slug": "textarea",
    "title": "Textarea",
    "description": "Textarea allows users to enter text in multiple lines.",
    "demos": [
      {
        "id": "textarea-1",
        "label": "Textarea"
      },
      {
        "id": "textarea-2",
        "label": "Ghost (no background)"
      },
      {
        "id": "textarea-3",
        "label": "With form control and labels"
      },
      {
        "id": "textarea-4",
        "label": "Textarea colors"
      },
      {
        "id": "textarea-5",
        "label": "Sizes"
      },
      {
        "id": "textarea-6",
        "label": "Disabled"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/textarea/"
  },
  {
    "slug": "theme-controller",
    "title": "Theme Controller",
    "description": "If a checked checkbox input or a checked radio input with theme-controller class exists in the page, The page will have the same theme as that input's value.",
    "demos": [
      {
        "id": "theme-controller-1",
        "label": "Theme Controller using a toggle"
      },
      {
        "id": "theme-controller-2",
        "label": "Theme Controller using a checkbox"
      },
      {
        "id": "theme-controller-3",
        "label": "Theme Controller using a swap"
      },
      {
        "id": "theme-controller-4",
        "label": "Theme Controller using a toggle with text"
      },
      {
        "id": "theme-controller-5",
        "label": "Theme Controller using a toggle with icons"
      },
      {
        "id": "theme-controller-6",
        "label": "Theme Controller using a toggle with icons inside"
      },
      {
        "id": "theme-controller-7",
        "label": "Theme Controller using a toggle with custom colors"
      },
      {
        "id": "theme-controller-8",
        "label": "Theme Controller using a radio input"
      },
      {
        "id": "theme-controller-9",
        "label": "Theme Controller using a radio button"
      },
      {
        "id": "theme-controller-10",
        "label": "Theme Controller using a dropdown"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/theme-controller/"
  },
  {
    "slug": "timeline",
    "title": "Timeline",
    "description": "Timeline component shows a list of events in chronological order.",
    "demos": [
      {
        "id": "timeline-1",
        "label": "Timeline with text on both sides and icon"
      },
      {
        "id": "timeline-2",
        "label": "Timeline with bottom side only"
      },
      {
        "id": "timeline-3",
        "label": "Timeline with top side only"
      },
      {
        "id": "timeline-4",
        "label": "Timeline with different sides"
      },
      {
        "id": "timeline-5",
        "label": "Timeline with colorful lines"
      },
      {
        "id": "timeline-6",
        "label": "Timeline without icons"
      },
      {
        "id": "timeline-7",
        "label": "Vertical timeline with text on both sides and icon"
      },
      {
        "id": "timeline-8",
        "label": "Vertical timeline with right side only"
      },
      {
        "id": "timeline-9",
        "label": "Vertical timeline with left side only"
      },
      {
        "id": "timeline-10",
        "label": "Vertical timeline with different sides"
      },
      {
        "id": "timeline-11",
        "label": "Vertical timeline with colorful lines"
      },
      {
        "id": "timeline-12",
        "label": "Vertical timeline without icons"
      },
      {
        "id": "timeline-13",
        "label": "Responsive: vertical by default, horizontal on large screen"
      },
      {
        "id": "timeline-14",
        "label": "Timeline with icon snapped to the start"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/timeline/",
    "previewHeight": 440,
    "previewSpan": "wide"
  },
  {
    "slug": "toast",
    "title": "Toast",
    "description": "Toast is a wrapper to stack elements, positioned on the corner of page.",
    "demos": [
      {
        "id": "toast-1",
        "label": "toast with alert inside"
      },
      {
        "id": "toast-2",
        "label": "toast-top toast-start"
      },
      {
        "id": "toast-3",
        "label": "toast-top toast-center"
      },
      {
        "id": "toast-4",
        "label": "toast-top toast-end"
      },
      {
        "id": "toast-5",
        "label": "toast-start toast-middle"
      },
      {
        "id": "toast-6",
        "label": "toast-center toast-middle"
      },
      {
        "id": "toast-7",
        "label": "toast-end toast-middle"
      },
      {
        "id": "toast-8",
        "label": "toast-start toast-bottom (default)"
      },
      {
        "id": "toast-9",
        "label": "toast-center toast-bottom (default)"
      },
      {
        "id": "toast-10",
        "label": "toast-end (default) toast-bottom (default)"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/toast/",
    "previewHeight": 330
  },
  {
    "slug": "toggle",
    "title": "Toggle",
    "description": "Toggle is a checkbox that is styled to look like a switch button.",
    "demos": [
      {
        "id": "toggle-1",
        "label": "Toggle (switch)"
      },
      {
        "id": "toggle-2",
        "label": "With fieldset and label"
      },
      {
        "id": "toggle-3",
        "label": "Sizes"
      },
      {
        "id": "toggle-4",
        "label": "Colors"
      },
      {
        "id": "toggle-5",
        "label": "Disabled"
      },
      {
        "id": "toggle-6",
        "label": "Indeterminate"
      },
      {
        "id": "toggle-7",
        "label": "Toggle with icons inside"
      },
      {
        "id": "toggle-8",
        "label": "Toggle with custom colors"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/toggle/"
  },
  {
    "slug": "tooltip",
    "title": "Tooltip",
    "description": "Tooltip can be used to show a message when hovering over an element.",
    "demos": [
      {
        "id": "tooltip-1",
        "label": "Tooltip"
      },
      {
        "id": "tooltip-2",
        "label": "Tooltip with tooltip-content"
      },
      {
        "id": "tooltip-3",
        "label": "Force open"
      },
      {
        "id": "tooltip-4",
        "label": "Top"
      },
      {
        "id": "tooltip-5",
        "label": "Bottom"
      },
      {
        "id": "tooltip-6",
        "label": "Left"
      },
      {
        "id": "tooltip-7",
        "label": "Right"
      },
      {
        "id": "tooltip-8",
        "label": "Primary color"
      },
      {
        "id": "tooltip-9",
        "label": "Secondary color"
      },
      {
        "id": "tooltip-10",
        "label": "Accent color"
      },
      {
        "id": "tooltip-11",
        "label": "Info color"
      },
      {
        "id": "tooltip-12",
        "label": "Success color"
      },
      {
        "id": "tooltip-13",
        "label": "Warning color"
      },
      {
        "id": "tooltip-14",
        "label": "Error color"
      },
      {
        "id": "tooltip-15",
        "label": "Responsive tooltip. only show for large screen"
      },
      {
        "id": "tooltip-16",
        "label": "Responsive tooltip position"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/tooltip/"
  },
  {
    "slug": "validator",
    "title": "Validator",
    "description": "Validator class changes the color of form elements to error or success based on input's validation rules.",
    "demos": [
      {
        "id": "validator-1",
        "label": "Validator"
      },
      {
        "id": "validator-2",
        "label": "Validator and validator-hint"
      },
      {
        "id": "validator-3",
        "label": "Password requirement validator"
      },
      {
        "id": "validator-4",
        "label": "Username requirement validator"
      },
      {
        "id": "validator-5",
        "label": "Phone Number requirement validator"
      },
      {
        "id": "validator-6",
        "label": "URL input requirement validator"
      },
      {
        "id": "validator-7",
        "label": "Date input requirement validator"
      },
      {
        "id": "validator-8",
        "label": "Number input requirement validator"
      },
      {
        "id": "validator-9",
        "label": "Checkbox requirement validator"
      },
      {
        "id": "validator-10",
        "label": "Toggle requirement validator"
      },
      {
        "id": "validator-11",
        "label": "Select requirement validator"
      },
      {
        "id": "validator-12",
        "label": "Form requirement validator"
      }
    ],
    "layout": "intrinsic",
    "docsUrl": "https://daisyui.com/components/validator/"
  }
] as const satisfies readonly DomRegistryEntry[];
export const DAISYUI_REGISTRY_BY_SLUG = Object.fromEntries(DAISYUI_REGISTRY_ENTRIES.map((entry) => [entry.slug, entry])) as Record<string, DomRegistryEntry>;
