// Generated by scripts/sync-magicui-registry.mjs from the official MIT-licensed Magic UI public registry.
import type { ReactRegistryEntry } from './types';
export const MAGICUI_REGISTRY_ENTRIES = [
  {
    "slug": "magic-card",
    "title": "Magic Card",
    "description": "A spotlight effect that follows your mouse cursor and highlights borders on hover.",
    "rootPath": "./vendor/magicui/registry/magicui/magic-card.tsx",
    "rootExport": "MagicCard",
    "previewPath": "./vendor/magicui/registry/example/magic-card-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-magic-card-magic-card-demo",
        "label": "Magic Card Demo",
        "path": "./vendor/magicui/registry/example/magic-card-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/magic-card"
  },
  {
    "slug": "android",
    "title": "Android",
    "description": "A mockup of an Android device.",
    "rootPath": "./vendor/magicui/registry/magicui/android.tsx",
    "rootExport": "Android",
    "previewPath": "./vendor/magicui/registry/example/android-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-android-android-demo",
        "label": "Android Demo",
        "path": "./vendor/magicui/registry/example/android-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-android-android-demo-2",
        "label": "Android Demo 2",
        "path": "./vendor/magicui/registry/example/android-demo-2.tsx",
        "export": "default"
      },
      {
        "id": "magic-android-android-demo-3",
        "label": "Android Demo 3",
        "path": "./vendor/magicui/registry/example/android-demo-3.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/android"
  },
  {
    "slug": "warp-background",
    "title": "Warp Background",
    "description": "A card with a time warping background effect.",
    "rootPath": "./vendor/magicui/registry/magicui/warp-background.tsx",
    "rootExport": "WarpBackground",
    "previewPath": "./vendor/magicui/registry/example/warp-background-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-warp-background-warp-background-demo",
        "label": "Warp Background Demo",
        "path": "./vendor/magicui/registry/example/warp-background-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/warp-background"
  },
  {
    "slug": "line-shadow-text",
    "title": "Line Shadow Text",
    "description": "A text component with a moving line shadow.",
    "rootPath": "./vendor/magicui/registry/magicui/line-shadow-text.tsx",
    "rootExport": "LineShadowText",
    "previewPath": "./vendor/magicui/registry/example/line-shadow-text-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-line-shadow-text-line-shadow-text-demo",
        "label": "Line Shadow Text Demo",
        "path": "./vendor/magicui/registry/example/line-shadow-text-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/line-shadow-text"
  },
  {
    "slug": "aurora-text",
    "title": "Aurora Text",
    "description": "A beautiful aurora text effect",
    "rootPath": "./vendor/magicui/registry/magicui/aurora-text.tsx",
    "rootExport": "AuroraText",
    "previewPath": "./vendor/magicui/registry/example/aurora-text-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-aurora-text-aurora-text-demo",
        "label": "Aurora Text Demo",
        "path": "./vendor/magicui/registry/example/aurora-text-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/aurora-text"
  },
  {
    "slug": "morphing-text",
    "title": "Morphing Text",
    "description": "A dynamic text morphing component for Magic UI.",
    "rootPath": "./vendor/magicui/registry/magicui/morphing-text.tsx",
    "rootExport": "MorphingText",
    "previewPath": "./vendor/magicui/registry/example/morphing-text-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-morphing-text-morphing-text-demo",
        "label": "Morphing Text Demo",
        "path": "./vendor/magicui/registry/example/morphing-text-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/morphing-text"
  },
  {
    "slug": "scroll-progress",
    "title": "Scroll Progress",
    "description": "Animated Scroll Progress for your pages",
    "rootPath": "./vendor/magicui/registry/magicui/scroll-progress.tsx",
    "rootExport": "ScrollProgress",
    "previewPath": "./vendor/magicui/registry/example/scroll-progress-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-scroll-progress-scroll-progress-demo",
        "label": "Scroll Progress Demo",
        "path": "./vendor/magicui/registry/example/scroll-progress-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/scroll-progress"
  },
  {
    "slug": "lens",
    "title": "Lens",
    "description": "A interactive component that enables zooming into images, videos and other elements.",
    "rootPath": "./vendor/magicui/registry/magicui/lens.tsx",
    "rootExport": "Lens",
    "previewPath": "./vendor/magicui/registry/example/lens-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-lens-lens-demo",
        "label": "Lens Demo",
        "path": "./vendor/magicui/registry/example/lens-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-lens-lens-demo-2",
        "label": "Lens Demo 2",
        "path": "./vendor/magicui/registry/example/lens-demo-2.tsx",
        "export": "default"
      },
      {
        "id": "magic-lens-lens-demo-3",
        "label": "Lens Demo 3",
        "path": "./vendor/magicui/registry/example/lens-demo-3.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/lens"
  },
  {
    "slug": "pointer",
    "title": "Pointer",
    "description": "A component that displays a pointer when hovering over an element",
    "rootPath": "./vendor/magicui/registry/magicui/pointer.tsx",
    "rootExport": "Pointer",
    "previewPath": "./vendor/magicui/registry/example/pointer-demo-1.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-pointer-pointer-demo-1",
        "label": "Pointer Demo 1",
        "path": "./vendor/magicui/registry/example/pointer-demo-1.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/pointer"
  },
  {
    "slug": "smooth-cursor",
    "title": "smooth-cursor",
    "description": "A customizable, physics-based smooth cursor animation component with spring animations and rotation effects",
    "rootPath": "./vendor/magicui/registry/magicui/smooth-cursor.tsx",
    "rootExport": "SmoothCursor",
    "previewPath": "./vendor/magicui/registry/example/smooth-cursor-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-smooth-cursor-smooth-cursor-demo",
        "label": "Smooth Cursor Demo",
        "path": "./vendor/magicui/registry/example/smooth-cursor-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/smooth-cursor"
  },
  {
    "slug": "progressive-blur",
    "title": "Progressive Blur",
    "description": "The Progressive Blur component adds a smooth blur gradient effect to scrollable content, indicating more content below or above.",
    "rootPath": "./vendor/magicui/registry/magicui/progressive-blur.tsx",
    "rootExport": "ProgressiveBlur",
    "previewPath": "./vendor/magicui/registry/example/progressive-blur-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-progressive-blur-progressive-blur-demo",
        "label": "Progressive Blur Demo",
        "path": "./vendor/magicui/registry/example/progressive-blur-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/progressive-blur"
  },
  {
    "slug": "neon-gradient-card",
    "title": "Neon Gradient Card",
    "description": "A beautiful neon card effect",
    "rootPath": "./vendor/magicui/registry/magicui/neon-gradient-card.tsx",
    "rootExport": "NeonGradientCard",
    "previewPath": "./vendor/magicui/registry/example/neon-gradient-card-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-neon-gradient-card-neon-gradient-card-demo",
        "label": "Neon Gradient Card Demo",
        "path": "./vendor/magicui/registry/example/neon-gradient-card-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/neon-gradient-card"
  },
  {
    "slug": "meteors",
    "title": "Meteors",
    "description": "A meteor shower effect.",
    "rootPath": "./vendor/magicui/registry/magicui/meteors.tsx",
    "rootExport": "Meteors",
    "previewPath": "./vendor/magicui/registry/example/meteors-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-meteors-meteors-demo",
        "label": "Meteors Demo",
        "path": "./vendor/magicui/registry/example/meteors-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/meteors"
  },
  {
    "slug": "grid-pattern",
    "title": "Grid Pattern",
    "description": "A background grid pattern made with SVGs, fully customizable using Tailwind CSS.",
    "rootPath": "./vendor/magicui/registry/magicui/grid-pattern.tsx",
    "rootExport": "GridPattern",
    "previewPath": "./vendor/magicui/registry/example/grid-pattern-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-grid-pattern-grid-pattern-demo",
        "label": "Grid Pattern Demo",
        "path": "./vendor/magicui/registry/example/grid-pattern-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-grid-pattern-grid-pattern-linear-gradient",
        "label": "Grid Pattern Linear Gradient",
        "path": "./vendor/magicui/registry/example/grid-pattern-linear-gradient.tsx",
        "export": "default"
      },
      {
        "id": "magic-grid-pattern-grid-pattern-dashed",
        "label": "Grid Pattern Dashed",
        "path": "./vendor/magicui/registry/example/grid-pattern-dashed.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/grid-pattern"
  },
  {
    "slug": "striped-pattern",
    "title": "Striped Pattern",
    "description": "A background striped pattern made with SVGs, fully customizable using Tailwind CSS.",
    "rootPath": "./vendor/magicui/registry/magicui/striped-pattern.tsx",
    "rootExport": "StripedPattern",
    "previewPath": "./vendor/magicui/registry/example/striped-pattern-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-striped-pattern-striped-pattern-demo",
        "label": "Striped Pattern Demo",
        "path": "./vendor/magicui/registry/example/striped-pattern-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-striped-pattern-striped-pattern-left",
        "label": "Striped Pattern (Left)",
        "path": "./vendor/magicui/registry/example/striped-pattern-left.tsx",
        "export": "default"
      },
      {
        "id": "magic-striped-pattern-striped-pattern-right",
        "label": "Striped Pattern (Right)",
        "path": "./vendor/magicui/registry/example/striped-pattern-right.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/striped-pattern"
  },
  {
    "slug": "interactive-grid-pattern",
    "title": "Interactive Grid Pattern",
    "description": "A interactive background grid pattern made with SVGs, fully customizable using Tailwind CSS.",
    "rootPath": "./vendor/magicui/registry/magicui/interactive-grid-pattern.tsx",
    "rootExport": "InteractiveGridPattern",
    "previewPath": "./vendor/magicui/registry/example/interactive-grid-pattern-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-interactive-grid-pattern-interactive-grid-pattern-demo",
        "label": "Interactive Grid Pattern Demo",
        "path": "./vendor/magicui/registry/example/interactive-grid-pattern-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-interactive-grid-pattern-interactive-grid-pattern-demo-2",
        "label": "Interactive Grid Pattern Demo 2",
        "path": "./vendor/magicui/registry/example/interactive-grid-pattern-demo-2.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/interactive-grid-pattern"
  },
  {
    "slug": "dot-pattern",
    "title": "Dot Pattern",
    "description": "A background dot pattern made with SVGs, fully customizable using Tailwind CSS.",
    "rootPath": "./vendor/magicui/registry/magicui/dot-pattern.tsx",
    "rootExport": "DotPattern",
    "previewPath": "./vendor/magicui/registry/example/dot-pattern-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-dot-pattern-dot-pattern-demo",
        "label": "Dot Pattern Demo",
        "path": "./vendor/magicui/registry/example/dot-pattern-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-dot-pattern-dot-pattern-linear-gradient",
        "label": "Dot Pattern Linear Gradient",
        "path": "./vendor/magicui/registry/example/dot-pattern-linear-gradient.tsx",
        "export": "default"
      },
      {
        "id": "magic-dot-pattern-dot-pattern-with-glow-effect",
        "label": "Dot Pattern with glow effect",
        "path": "./vendor/magicui/registry/example/dot-pattern-with-glow-effect.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/dot-pattern"
  },
  {
    "slug": "flickering-grid",
    "title": "Flickering Grid",
    "description": "A flickering grid background made with SVGs, fully customizable using Tailwind CSS.",
    "rootPath": "./vendor/magicui/registry/magicui/flickering-grid.tsx",
    "rootExport": "FlickeringGrid",
    "previewPath": "./vendor/magicui/registry/example/flickering-grid-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-flickering-grid-flickering-grid-demo",
        "label": "Flickering Grid Demo",
        "path": "./vendor/magicui/registry/example/flickering-grid-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-flickering-grid-flickering-grid-rounded-demo",
        "label": "Flickering Grid Rounded Demo",
        "path": "./vendor/magicui/registry/example/flickering-grid-rounded-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/flickering-grid"
  },
  {
    "slug": "hero-video-dialog",
    "title": "Hero Video Dialog",
    "description": "A hero video dialog component.",
    "rootPath": "./vendor/magicui/registry/magicui/hero-video-dialog.tsx",
    "rootExport": "HeroVideoDialog",
    "previewPath": "./vendor/magicui/registry/example/hero-video-dialog-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-hero-video-dialog-hero-video-dialog-demo",
        "label": "Hero Video Dialog Demo",
        "path": "./vendor/magicui/registry/example/hero-video-dialog-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-hero-video-dialog-hero-video-dialog-demo-top-in-bottom-out",
        "label": "Hero Video Dialog Top In Bottom Out Demo",
        "path": "./vendor/magicui/registry/example/hero-video-dialog-demo-top-in-bottom-out.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/hero-video-dialog"
  },
  {
    "slug": "code-comparison",
    "title": "Code Comparison",
    "description": "A component which compares two code snippets.",
    "rootPath": "./vendor/magicui/registry/magicui/code-comparison.tsx",
    "rootExport": "CodeComparison",
    "previewPath": "./vendor/magicui/registry/example/code-comparison-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-code-comparison-code-comparison-demo",
        "label": "Code Comparison Demo",
        "path": "./vendor/magicui/registry/example/code-comparison-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/code-comparison"
  },
  {
    "slug": "marquee",
    "title": "Marquee",
    "description": "An infinite scrolling component that can be used to display text, images, or videos.",
    "rootPath": "./vendor/magicui/registry/magicui/marquee.tsx",
    "rootExport": "Marquee",
    "previewPath": "./vendor/magicui/registry/example/marquee-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-marquee-marquee-demo",
        "label": "Marquee Demo",
        "path": "./vendor/magicui/registry/example/marquee-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-marquee-marquee-demo-vertical",
        "label": "Marquee Vertical Demo",
        "path": "./vendor/magicui/registry/example/marquee-demo-vertical.tsx",
        "export": "default"
      },
      {
        "id": "magic-marquee-marquee-logos",
        "label": "Marquee Logos",
        "path": "./vendor/magicui/registry/example/marquee-logos.tsx",
        "export": "default"
      },
      {
        "id": "magic-marquee-marquee-3d",
        "label": "Marquee 3D",
        "path": "./vendor/magicui/registry/example/marquee-3d.tsx",
        "export": "default"
      },
      {
        "id": "magic-marquee-bento-demo",
        "label": "Bento Demo",
        "path": "./vendor/magicui/registry/example/bento-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/marquee"
  },
  {
    "slug": "glyph-matrix",
    "title": "Glyph Matrix",
    "description": "An animated grid of subtly shifting glyphs with fade effect and theme support.",
    "rootPath": "./vendor/magicui/registry/magicui/glyph-matrix.tsx",
    "rootExport": "GlyphMatrix",
    "previewPath": "./vendor/magicui/registry/magicui/glyph-matrix.tsx",
    "previewExport": "GlyphMatrix",
    "demos": [],
    "acceptsChildren": false,
    "docsUrl": "https://magicui.design/docs/components/glyph-matrix"
  },
  {
    "slug": "globe",
    "title": "Globe",
    "description": "An autorotating, interactive, and highly performant globe made using WebGL.",
    "rootPath": "./vendor/magicui/registry/magicui/globe.tsx",
    "rootExport": "Globe",
    "previewPath": "./vendor/magicui/registry/example/globe-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-globe-globe-demo",
        "label": "Globe Demo",
        "path": "./vendor/magicui/registry/example/globe-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/globe"
  },
  {
    "slug": "shimmer-button",
    "title": "Shimmer Button",
    "description": "A button with a shimmering light which travels around the perimeter.",
    "rootPath": "./vendor/magicui/registry/magicui/shimmer-button.tsx",
    "rootExport": "ShimmerButton",
    "previewPath": "./vendor/magicui/registry/example/shimmer-button-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-shimmer-button-shimmer-button-demo",
        "label": "Shimmer Button Demo",
        "path": "./vendor/magicui/registry/example/shimmer-button-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/shimmer-button"
  },
  {
    "slug": "tweet-card",
    "title": "Tweet Card",
    "description": "A card that displays a tweet with the author's name, handle, and profile picture.",
    "rootPath": "./vendor/magicui/registry/magicui/tweet-card.tsx",
    "rootExport": "TweetSkeleton",
    "previewPath": "./vendor/magicui/registry/example/tweet-card-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-tweet-card-tweet-card-demo",
        "label": "Tweet Card Demo",
        "path": "./vendor/magicui/registry/example/tweet-card-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-tweet-card-tweet-card-images",
        "label": "Tweet Card Images",
        "path": "./vendor/magicui/registry/example/tweet-card-images.tsx",
        "export": "default"
      },
      {
        "id": "magic-tweet-card-tweet-card-meta-preview",
        "label": "Tweet Card Meta Preview",
        "path": "./vendor/magicui/registry/example/tweet-card-meta-preview.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/tweet-card"
  },
  {
    "slug": "client-tweet-card",
    "title": "Client Tweet Card",
    "description": "A client-side version of the tweet card that displays a tweet with the author's name, handle, and profile picture.",
    "rootPath": "./vendor/magicui/registry/magicui/client-tweet-card.tsx",
    "rootExport": "ClientTweetCard",
    "previewPath": "./vendor/magicui/registry/magicui/client-tweet-card.tsx",
    "previewExport": "ClientTweetCard",
    "demos": [],
    "acceptsChildren": false,
    "docsUrl": "https://magicui.design/docs/components/client-tweet-card"
  },
  {
    "slug": "bento-grid",
    "title": "Bento Grid",
    "description": "Bento grid is a layout used to showcase the features of a product in a simple and elegant way.",
    "rootPath": "./vendor/magicui/registry/magicui/bento-grid.tsx",
    "previewPath": "./vendor/magicui/registry/example/bento-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-bento-grid-bento-demo",
        "label": "Bento Demo",
        "path": "./vendor/magicui/registry/example/bento-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-bento-grid-bento-demo-vertical",
        "label": "Bento Vertical Demo",
        "path": "./vendor/magicui/registry/example/bento-demo-vertical.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/bento-grid"
  },
  {
    "slug": "particles",
    "title": "Particles",
    "description": "Particles are a fun way to add some visual flair to your website. They can be used to create a sense of depth, movement, and interactivity.",
    "rootPath": "./vendor/magicui/registry/magicui/particles.tsx",
    "rootExport": "Particles",
    "previewPath": "./vendor/magicui/registry/example/particles-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-particles-particles-demo",
        "label": "Particles Demo",
        "path": "./vendor/magicui/registry/example/particles-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/particles"
  },
  {
    "slug": "number-ticker",
    "title": "Number Ticker",
    "description": "Animate numbers to count up or down to a target number",
    "rootPath": "./vendor/magicui/registry/magicui/number-ticker.tsx",
    "rootExport": "NumberTicker",
    "previewPath": "./vendor/magicui/registry/example/number-ticker-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-number-ticker-number-ticker-demo",
        "label": "Number Ticker Demo",
        "path": "./vendor/magicui/registry/example/number-ticker-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-number-ticker-number-ticker-demo-2",
        "label": "Number Ticker Demo 2",
        "path": "./vendor/magicui/registry/example/number-ticker-demo-2.tsx",
        "export": "default"
      },
      {
        "id": "magic-number-ticker-number-ticker-decimal-demo",
        "label": "Number Ticker Decimal Demo",
        "path": "./vendor/magicui/registry/example/number-ticker-decimal-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/number-ticker"
  },
  {
    "slug": "ripple",
    "title": "Ripple",
    "description": "An animated ripple effect typically used behind elements to emphasize them.",
    "rootPath": "./vendor/magicui/registry/magicui/ripple.tsx",
    "rootExport": "Ripple",
    "previewPath": "./vendor/magicui/registry/example/ripple-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-ripple-ripple-demo",
        "label": "Ripple Demo",
        "path": "./vendor/magicui/registry/example/ripple-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/ripple"
  },
  {
    "slug": "retro-grid",
    "title": "Retro Grid",
    "description": "An animated scrolling retro grid effect",
    "rootPath": "./vendor/magicui/registry/magicui/retro-grid.tsx",
    "rootExport": "RetroGrid",
    "previewPath": "./vendor/magicui/registry/example/retro-grid-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-retro-grid-retro-grid-demo",
        "label": "Retro Grid Demo",
        "path": "./vendor/magicui/registry/example/retro-grid-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/retro-grid"
  },
  {
    "slug": "animated-list",
    "title": "Animated List",
    "description": "A list that animates each item in sequence with a delay. Used to showcase notifications or events on your landing page.",
    "rootPath": "./vendor/magicui/registry/magicui/animated-list.tsx",
    "rootExport": "AnimatedListItem",
    "previewPath": "./vendor/magicui/registry/example/animated-list-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-animated-list-animated-list-demo",
        "label": "Animated List Demo",
        "path": "./vendor/magicui/registry/example/animated-list-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/animated-list"
  },
  {
    "slug": "animated-shiny-text",
    "title": "Animated Shiny Text",
    "description": "A light glare effect which pans across text making it appear as if it is shimmering.",
    "rootPath": "./vendor/magicui/registry/magicui/animated-shiny-text.tsx",
    "rootExport": "AnimatedShinyText",
    "previewPath": "./vendor/magicui/registry/example/animated-shiny-text-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-animated-shiny-text-animated-shiny-text-demo",
        "label": "Animated Shiny Text Demo",
        "path": "./vendor/magicui/registry/example/animated-shiny-text-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/animated-shiny-text"
  },
  {
    "slug": "animated-grid-pattern",
    "title": "Animated Grid Pattern",
    "description": "A animated background grid pattern made with SVGs, fully customizable using Tailwind CSS.",
    "rootPath": "./vendor/magicui/registry/magicui/animated-grid-pattern.tsx",
    "rootExport": "AnimatedGridPattern",
    "previewPath": "./vendor/magicui/registry/example/animated-grid-pattern-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-animated-grid-pattern-animated-grid-pattern-demo",
        "label": "Animated Grid Pattern Demo",
        "path": "./vendor/magicui/registry/example/animated-grid-pattern-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/animated-grid-pattern"
  },
  {
    "slug": "border-beam",
    "title": "Border Beam",
    "description": "An animated beam of light which travels along the border of its container.",
    "rootPath": "./vendor/magicui/registry/magicui/border-beam.tsx",
    "rootExport": "BorderBeam",
    "previewPath": "./vendor/magicui/registry/example/border-beam-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-border-beam-border-beam-demo",
        "label": "Border Beam Demo",
        "path": "./vendor/magicui/registry/example/border-beam-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-border-beam-border-beam-demo-2",
        "label": "Border Beam Demo",
        "path": "./vendor/magicui/registry/example/border-beam-demo-2.tsx",
        "export": "default"
      },
      {
        "id": "magic-border-beam-border-beam-demo-3",
        "label": "Border Beam Demo 3",
        "path": "./vendor/magicui/registry/example/border-beam-demo-3.tsx",
        "export": "default"
      },
      {
        "id": "magic-border-beam-border-beam-demo-4",
        "label": "Border Beam Demo 4",
        "path": "./vendor/magicui/registry/example/border-beam-demo-4.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/border-beam"
  },
  {
    "slug": "animated-beam",
    "title": "Animated Beam",
    "description": "An animated beam of light which travels along a path. Useful for showcasing the integration features of a website.",
    "rootPath": "./vendor/magicui/registry/magicui/animated-beam.tsx",
    "rootExport": "AnimatedBeam",
    "previewPath": "./vendor/magicui/registry/example/animated-beam-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-animated-beam-animated-beam-demo",
        "label": "Animated Beam Demo",
        "path": "./vendor/magicui/registry/example/animated-beam-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-animated-beam-animated-beam-unidirectional",
        "label": "Animated Beam Unidirectional",
        "path": "./vendor/magicui/registry/example/animated-beam-unidirectional.tsx",
        "export": "default"
      },
      {
        "id": "magic-animated-beam-animated-beam-bidirectional",
        "label": "Animated Beam Bidirectional",
        "path": "./vendor/magicui/registry/example/animated-beam-bidirectional.tsx",
        "export": "default"
      },
      {
        "id": "magic-animated-beam-animated-beam-multiple-inputs",
        "label": "Animated Beam Multiple Inputs",
        "path": "./vendor/magicui/registry/example/animated-beam-multiple-inputs.tsx",
        "export": "default"
      },
      {
        "id": "magic-animated-beam-animated-beam-multiple-outputs",
        "label": "Animated Beam Multiple Outputs",
        "path": "./vendor/magicui/registry/example/animated-beam-multiple-outputs.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/animated-beam"
  },
  {
    "slug": "text-reveal",
    "title": "Text Reveal",
    "description": "Fade in text as you scroll down the page.",
    "rootPath": "./vendor/magicui/registry/magicui/text-reveal.tsx",
    "rootExport": "TextReveal",
    "previewPath": "./vendor/magicui/registry/example/text-reveal-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-text-reveal-text-reveal-demo",
        "label": "Text Reveal Demo",
        "path": "./vendor/magicui/registry/example/text-reveal-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/text-reveal"
  },
  {
    "slug": "hyper-text",
    "title": "Hyper Text",
    "description": "A text animation that scrambles letters before revealing the final text.",
    "rootPath": "./vendor/magicui/registry/magicui/hyper-text.tsx",
    "rootExport": "HyperText",
    "previewPath": "./vendor/magicui/registry/example/hyper-text-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-hyper-text-hyper-text-demo",
        "label": "Hyper Text Demo",
        "path": "./vendor/magicui/registry/example/hyper-text-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/hyper-text"
  },
  {
    "slug": "animated-gradient-text",
    "title": "Animated Gradient Text",
    "description": "An animated gradient background which transitions between colors for text.",
    "rootPath": "./vendor/magicui/registry/magicui/animated-gradient-text.tsx",
    "rootExport": "AnimatedGradientText",
    "previewPath": "./vendor/magicui/registry/example/animated-gradient-text-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-animated-gradient-text-animated-gradient-text-demo",
        "label": "Animated Gradient Text Demo",
        "path": "./vendor/magicui/registry/example/animated-gradient-text-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-animated-gradient-text-animated-gradient-text-demo-2",
        "label": "Animated Gradient Text Demo 2",
        "path": "./vendor/magicui/registry/example/animated-gradient-text-demo-2.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/animated-gradient-text"
  },
  {
    "slug": "orbiting-circles",
    "title": "Orbiting Circles",
    "description": "A collection of circles which move in orbit along a circular path",
    "rootPath": "./vendor/magicui/registry/magicui/orbiting-circles.tsx",
    "rootExport": "OrbitingCircles",
    "previewPath": "./vendor/magicui/registry/example/orbiting-circles-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-orbiting-circles-orbiting-circles-demo",
        "label": "Orbiting Circles Demo",
        "path": "./vendor/magicui/registry/example/orbiting-circles-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/orbiting-circles"
  },
  {
    "slug": "dock",
    "title": "Dock",
    "description": "An implementation of the MacOS dock using react + tailwindcss + motion",
    "rootPath": "./vendor/magicui/registry/magicui/dock.tsx",
    "previewPath": "./vendor/magicui/registry/example/dock-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-dock-dock-demo",
        "label": "Dock Demo",
        "path": "./vendor/magicui/registry/example/dock-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-dock-dock-demo-2",
        "label": "Dock Demo 2",
        "path": "./vendor/magicui/registry/example/dock-demo-2.tsx",
        "export": "default"
      },
      {
        "id": "magic-dock-dock-demo-3",
        "label": "Dock Demo 3",
        "path": "./vendor/magicui/registry/example/dock-demo-3.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/dock"
  },
  {
    "slug": "word-rotate",
    "title": "Word Rotate",
    "description": "A vertical rotation of words",
    "rootPath": "./vendor/magicui/registry/magicui/word-rotate.tsx",
    "rootExport": "WordRotate",
    "previewPath": "./vendor/magicui/registry/example/word-rotate-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-word-rotate-word-rotate-demo",
        "label": "Word Rotate Demo",
        "path": "./vendor/magicui/registry/example/word-rotate-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/word-rotate"
  },
  {
    "slug": "avatar-circles",
    "title": "Avatar Circles",
    "description": "Overlapping circles of avatars.",
    "rootPath": "./vendor/magicui/registry/magicui/avatar-circles.tsx",
    "rootExport": "AvatarCircles",
    "previewPath": "./vendor/magicui/registry/example/avatar-circles-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-avatar-circles-avatar-circles-demo",
        "label": "Avatar Circles Demo",
        "path": "./vendor/magicui/registry/example/avatar-circles-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/avatar-circles"
  },
  {
    "slug": "typing-animation",
    "title": "Typing Animation",
    "description": "Characters appearing in typed animation",
    "rootPath": "./vendor/magicui/registry/magicui/typing-animation.tsx",
    "rootExport": "TypingAnimation",
    "previewPath": "./vendor/magicui/registry/example/typing-animation-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-typing-animation-typing-animation-demo",
        "label": "Typing Animation Demo",
        "path": "./vendor/magicui/registry/example/typing-animation-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/typing-animation"
  },
  {
    "slug": "sparkles-text",
    "title": "Sparkles Text",
    "description": "A dynamic text that generates continuous sparkles with smooth transitions, perfect for highlighting text with animated stars.",
    "rootPath": "./vendor/magicui/registry/magicui/sparkles-text.tsx",
    "rootExport": "SparklesText",
    "previewPath": "./vendor/magicui/registry/example/sparkles-text-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-sparkles-text-sparkles-text-demo",
        "label": "Sparkles Text Demo",
        "path": "./vendor/magicui/registry/example/sparkles-text-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/sparkles-text"
  },
  {
    "slug": "spinning-text",
    "title": "Spinning Text",
    "description": "The Spinning Text component animates text in a circular motion with customizable speed, direction, color, and transitions for dynamic and engaging effects.",
    "rootPath": "./vendor/magicui/registry/magicui/spinning-text.tsx",
    "rootExport": "SpinningText",
    "previewPath": "./vendor/magicui/registry/example/spinning-text-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-spinning-text-spinning-text-demo",
        "label": "Spinning Text Demo",
        "path": "./vendor/magicui/registry/example/spinning-text-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-spinning-text-spinning-text-demo-2",
        "label": "Spinning Text Demo 2",
        "path": "./vendor/magicui/registry/example/spinning-text-demo-2.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/spinning-text"
  },
  {
    "slug": "comic-text",
    "title": "Comic Text",
    "description": "Comic text animation",
    "rootPath": "./vendor/magicui/registry/magicui/comic-text.tsx",
    "rootExport": "ComicText",
    "previewPath": "./vendor/magicui/registry/example/comic-text-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-comic-text-comic-text-demo",
        "label": "Comic Text Demo",
        "path": "./vendor/magicui/registry/example/comic-text-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/comic-text"
  },
  {
    "slug": "icon-cloud",
    "title": "Icon Cloud",
    "description": "An interactive 3D tag cloud component",
    "rootPath": "./vendor/magicui/registry/magicui/icon-cloud.tsx",
    "rootExport": "IconCloud",
    "previewPath": "./vendor/magicui/registry/example/icon-cloud-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-icon-cloud-icon-cloud-demo",
        "label": "Icon Cloud Demo",
        "path": "./vendor/magicui/registry/example/icon-cloud-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-icon-cloud-icon-cloud-demo-2",
        "label": "Icon Cloud Demo 2",
        "path": "./vendor/magicui/registry/example/icon-cloud-demo-2.tsx",
        "export": "default"
      },
      {
        "id": "magic-icon-cloud-icon-cloud-demo-3",
        "label": "Icon Cloud Demo 3",
        "path": "./vendor/magicui/registry/example/icon-cloud-demo-3.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/icon-cloud"
  },
  {
    "slug": "text-animate",
    "title": "Text Animate",
    "description": "A text animation component that animates text using a variety of different animations.",
    "rootPath": "./vendor/magicui/registry/magicui/text-animate.tsx",
    "rootExport": "TextAnimate",
    "previewPath": "./vendor/magicui/registry/example/text-animate-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-text-animate-text-animate-demo",
        "label": "Text Animate Demo",
        "path": "./vendor/magicui/registry/example/text-animate-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-text-animate-text-animate-demo-2",
        "label": "Text Animate Demo 2",
        "path": "./vendor/magicui/registry/example/text-animate-demo-2.tsx",
        "export": "default"
      },
      {
        "id": "magic-text-animate-text-animate-demo-3",
        "label": "Text Animate Demo 3",
        "path": "./vendor/magicui/registry/example/text-animate-demo-3.tsx",
        "export": "default"
      },
      {
        "id": "magic-text-animate-text-animate-demo-4",
        "label": "Text Animate Demo 4",
        "path": "./vendor/magicui/registry/example/text-animate-demo-4.tsx",
        "export": "default"
      },
      {
        "id": "magic-text-animate-text-animate-demo-5",
        "label": "Text Animate Demo 5",
        "path": "./vendor/magicui/registry/example/text-animate-demo-5.tsx",
        "export": "default"
      },
      {
        "id": "magic-text-animate-text-animate-demo-6",
        "label": "Text Animate Demo 6",
        "path": "./vendor/magicui/registry/example/text-animate-demo-6.tsx",
        "export": "default"
      },
      {
        "id": "magic-text-animate-text-animate-demo-7",
        "label": "Text Animate Demo 7",
        "path": "./vendor/magicui/registry/example/text-animate-demo-7.tsx",
        "export": "default"
      },
      {
        "id": "magic-text-animate-text-animate-demo-8",
        "label": "Text Animate Demo 8",
        "path": "./vendor/magicui/registry/example/text-animate-demo-8.tsx",
        "export": "default"
      },
      {
        "id": "magic-text-animate-text-animate-demo-9",
        "label": "Text Animate Demo 9",
        "path": "./vendor/magicui/registry/example/text-animate-demo-9.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/text-animate"
  },
  {
    "slug": "scroll-based-velocity",
    "title": "Scroll Based Velocity",
    "description": "Scrolling text whose speed changes based on scroll speed",
    "rootPath": "./vendor/magicui/registry/magicui/scroll-based-velocity.tsx",
    "rootExport": "ScrollVelocityContainer",
    "previewPath": "./vendor/magicui/registry/example/scroll-based-velocity-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-scroll-based-velocity-scroll-based-velocity-demo",
        "label": "Scroll Based Velocity Demo",
        "path": "./vendor/magicui/registry/example/scroll-based-velocity-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-scroll-based-velocity-scroll-based-velocity-images-demo",
        "label": "Scroll Based Velocity Images",
        "path": "./vendor/magicui/registry/example/scroll-based-velocity-images-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/scroll-based-velocity"
  },
  {
    "slug": "shiny-button",
    "title": "Shiny Button",
    "description": "A shiny button component with dynamic styles in the dark mode or light mode.",
    "rootPath": "./vendor/magicui/registry/magicui/shiny-button.tsx",
    "rootExport": "ShinyButton",
    "previewPath": "./vendor/magicui/registry/example/shiny-button-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-shiny-button-shiny-button-demo",
        "label": "Shiny Button Demo",
        "path": "./vendor/magicui/registry/example/shiny-button-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/shiny-button"
  },
  {
    "slug": "shine-border",
    "title": "Shine Border",
    "description": "Shine border is an animated background border effect.",
    "rootPath": "./vendor/magicui/registry/magicui/shine-border.tsx",
    "rootExport": "ShineBorder",
    "previewPath": "./vendor/magicui/registry/example/shine-border-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-shine-border-shine-border-demo",
        "label": "Shine Border Demo",
        "path": "./vendor/magicui/registry/example/shine-border-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-shine-border-shine-border-demo-2",
        "label": "Shine Border Demo 2",
        "path": "./vendor/magicui/registry/example/shine-border-demo-2.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/shine-border"
  },
  {
    "slug": "animated-circular-progress-bar",
    "title": "Animated Circular Progress Bar",
    "description": "Animated Circular Progress Bar is a component that displays a circular gauge with a percentage value.",
    "rootPath": "./vendor/magicui/registry/magicui/animated-circular-progress-bar.tsx",
    "rootExport": "AnimatedCircularProgressBar",
    "previewPath": "./vendor/magicui/registry/example/animated-circular-progress-bar-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-animated-circular-progress-bar-animated-circular-316a341e",
        "label": "Animated Circular Progress Bar Demo",
        "path": "./vendor/magicui/registry/example/animated-circular-progress-bar-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/animated-circular-progress-bar"
  },
  {
    "slug": "confetti",
    "title": "Confetti",
    "description": "Confetti animations are best used to delight your users when something special happens",
    "rootPath": "./vendor/magicui/registry/magicui/confetti.tsx",
    "rootExport": "Confetti",
    "previewPath": "./vendor/magicui/registry/example/confetti-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-confetti-confetti-demo",
        "label": "Confetti Demo",
        "path": "./vendor/magicui/registry/example/confetti-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-confetti-confetti-basic-cannon",
        "label": "Confetti Basic Cannon",
        "path": "./vendor/magicui/registry/example/confetti-basic-cannon.tsx",
        "export": "default"
      },
      {
        "id": "magic-confetti-confetti-random-direction",
        "label": "Confetti Random Direction",
        "path": "./vendor/magicui/registry/example/confetti-random-direction.tsx",
        "export": "default"
      },
      {
        "id": "magic-confetti-confetti-fireworks",
        "label": "Confetti Fireworks",
        "path": "./vendor/magicui/registry/example/confetti-fireworks.tsx",
        "export": "default"
      },
      {
        "id": "magic-confetti-confetti-stars",
        "label": "Confetti Stars",
        "path": "./vendor/magicui/registry/example/confetti-stars.tsx",
        "export": "default"
      },
      {
        "id": "magic-confetti-confetti-side-cannons",
        "label": "Confetti Side Cannons",
        "path": "./vendor/magicui/registry/example/confetti-side-cannons.tsx",
        "export": "default"
      },
      {
        "id": "magic-confetti-confetti-custom-shapes",
        "label": "Confetti Custom Shapes",
        "path": "./vendor/magicui/registry/example/confetti-custom-shapes.tsx",
        "export": "default"
      },
      {
        "id": "magic-confetti-confetti-emoji",
        "label": "Confetti Emoji",
        "path": "./vendor/magicui/registry/example/confetti-emoji.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/confetti"
  },
  {
    "slug": "animated-subscribe-button",
    "title": "Animated Subscribe Button",
    "description": "An animated subscribe button useful for showing a micro animation from intial to final result.",
    "rootPath": "./vendor/magicui/registry/magicui/animated-subscribe-button.tsx",
    "rootExport": "AnimatedSubscribeButton",
    "previewPath": "./vendor/magicui/registry/magicui/animated-subscribe-button.tsx",
    "previewExport": "AnimatedSubscribeButton",
    "demos": [],
    "acceptsChildren": true,
    "docsUrl": "https://magicui.design/docs/components/animated-subscribe-button"
  },
  {
    "slug": "cool-mode",
    "title": "Cool Mode",
    "description": "Cool mode effect for buttons, links, and other DOMs",
    "rootPath": "./vendor/magicui/registry/magicui/cool-mode.tsx",
    "rootExport": "CoolMode",
    "previewPath": "./vendor/magicui/registry/example/cool-mode-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-cool-mode-cool-mode-demo",
        "label": "Cool Mode Demo",
        "path": "./vendor/magicui/registry/example/cool-mode-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-cool-mode-cool-mode-custom",
        "label": "Cool Mode Custom",
        "path": "./vendor/magicui/registry/example/cool-mode-custom.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/cool-mode"
  },
  {
    "slug": "pulsating-button",
    "title": "Pulsating Button",
    "description": "An animated pulsating button useful for capturing attention of users.",
    "rootPath": "./vendor/magicui/registry/magicui/pulsating-button.tsx",
    "rootExport": "PulsatingButton",
    "previewPath": "./vendor/magicui/registry/example/pulsating-button-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-pulsating-button-pulsating-button-demo",
        "label": "Pulsating Button Demo",
        "path": "./vendor/magicui/registry/example/pulsating-button-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/pulsating-button"
  },
  {
    "slug": "ripple-button",
    "title": "Ripple Button",
    "description": "An animated button with ripple useful for user engagement.",
    "rootPath": "./vendor/magicui/registry/magicui/ripple-button.tsx",
    "rootExport": "RippleButton",
    "previewPath": "./vendor/magicui/registry/example/ripple-button-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-ripple-button-ripple-button-demo",
        "label": "Ripple Button Demo",
        "path": "./vendor/magicui/registry/example/ripple-button-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/ripple-button"
  },
  {
    "slug": "file-tree",
    "title": "File Tree",
    "description": "A component used to showcase the folder and file structure of a directory.",
    "rootPath": "./vendor/magicui/registry/magicui/file-tree.tsx",
    "previewPath": "./vendor/magicui/registry/example/file-tree-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-file-tree-file-tree-demo",
        "label": "File Tree Demo",
        "path": "./vendor/magicui/registry/example/file-tree-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/file-tree"
  },
  {
    "slug": "blur-fade",
    "title": "Blur Fade",
    "description": "Blur fade in and out animation. Used to smoothly fade in and out content.",
    "rootPath": "./vendor/magicui/registry/magicui/blur-fade.tsx",
    "rootExport": "BlurFade",
    "previewPath": "./vendor/magicui/registry/example/blur-fade-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-blur-fade-blur-fade-demo",
        "label": "Blur Fade Demo",
        "path": "./vendor/magicui/registry/example/blur-fade-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-blur-fade-blur-fade-text-demo",
        "label": "Blur Fade Text Demo",
        "path": "./vendor/magicui/registry/example/blur-fade-text-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/blur-fade"
  },
  {
    "slug": "safari",
    "title": "Safari",
    "description": "A safari browser mockup to showcase your website.",
    "rootPath": "./vendor/magicui/registry/magicui/safari.tsx",
    "rootExport": "Safari",
    "previewPath": "./vendor/magicui/registry/example/safari-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-safari-safari-demo",
        "label": "Safari Demo",
        "path": "./vendor/magicui/registry/example/safari-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-safari-safari-demo-2",
        "label": "Safari Demo 2",
        "path": "./vendor/magicui/registry/example/safari-demo-2.tsx",
        "export": "default"
      },
      {
        "id": "magic-safari-safari-demo-3",
        "label": "Safari Demo 3",
        "path": "./vendor/magicui/registry/example/safari-demo-3.tsx",
        "export": "default"
      },
      {
        "id": "magic-safari-safari-demo-4",
        "label": "Safari Demo 4",
        "path": "./vendor/magicui/registry/example/safari-demo-4.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/safari"
  },
  {
    "slug": "rainbow-button",
    "title": "Rainbow Button",
    "description": "An animated button with a rainbow effect.",
    "rootPath": "./vendor/magicui/registry/magicui/rainbow-button.tsx",
    "previewPath": "./vendor/magicui/registry/example/rainbow-button-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-rainbow-button-rainbow-button-demo",
        "label": "Rainbow Button Demo",
        "path": "./vendor/magicui/registry/example/rainbow-button-demo.tsx",
        "export": "default"
      },
      {
        "id": "magic-rainbow-button-rainbow-button-demo-2",
        "label": "Rainbow Button Demo 2",
        "path": "./vendor/magicui/registry/example/rainbow-button-demo-2.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/rainbow-button"
  },
  {
    "slug": "interactive-hover-button",
    "title": "interactive-hover-button",
    "description": "",
    "rootPath": "./vendor/magicui/registry/magicui/interactive-hover-button.tsx",
    "rootExport": "InteractiveHoverButton",
    "previewPath": "./vendor/magicui/registry/example/interactive-hover-button-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-interactive-hover-button-interactive-hover-button-demo",
        "label": "Interactive Hover Button Demo",
        "path": "./vendor/magicui/registry/example/interactive-hover-button-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/interactive-hover-button"
  },
  {
    "slug": "terminal",
    "title": "Terminal",
    "description": "A terminal component",
    "rootPath": "./vendor/magicui/registry/magicui/terminal.tsx",
    "rootExport": "AnimatedSpan",
    "previewPath": "./vendor/magicui/registry/example/terminal-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-terminal-terminal-demo",
        "label": "Terminal Demo",
        "path": "./vendor/magicui/registry/example/terminal-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/terminal"
  },
  {
    "slug": "video-text",
    "title": "Video Text",
    "description": "A component that displays text with a video playing in the background.",
    "rootPath": "./vendor/magicui/registry/magicui/video-text.tsx",
    "rootExport": "VideoText",
    "previewPath": "./vendor/magicui/registry/example/video-text-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-video-text-video-text-demo",
        "label": "Video Text Demo",
        "path": "./vendor/magicui/registry/example/video-text-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/video-text"
  },
  {
    "slug": "pixel-image",
    "title": "Pixel Image",
    "description": "A component that displays an image with a pixelated effect, creating a retro aesthetic.",
    "rootPath": "./vendor/magicui/registry/magicui/pixel-image.tsx",
    "rootExport": "PixelImage",
    "previewPath": "./vendor/magicui/registry/example/pixel-image-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-pixel-image-pixel-image-demo",
        "label": "Pixel Image Demo",
        "path": "./vendor/magicui/registry/example/pixel-image-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/pixel-image"
  },
  {
    "slug": "highlighter",
    "title": "Highlighter",
    "description": "A text highlighter that mimics the effect of a human-drawn marker stroke.",
    "rootPath": "./vendor/magicui/registry/magicui/highlighter.tsx",
    "rootExport": "Highlighter",
    "previewPath": "./vendor/magicui/registry/example/highlighter-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-highlighter-highlighter-demo",
        "label": "Highlighter Demo",
        "path": "./vendor/magicui/registry/example/highlighter-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/highlighter"
  },
  {
    "slug": "animated-theme-toggler",
    "title": "Theme Toggler",
    "description": "A component for theme changing animation.",
    "rootPath": "./vendor/magicui/registry/magicui/animated-theme-toggler.tsx",
    "rootExport": "AnimatedThemeToggler",
    "previewPath": "./vendor/magicui/registry/example/animated-theme-toggler-demo.tsx",
    "previewExport": "default",
    "demos": [
      {
        "id": "magic-animated-theme-toggler-animated-theme-toggler-demo",
        "label": "Animated Theme Toggler Demo",
        "path": "./vendor/magicui/registry/example/animated-theme-toggler-demo.tsx",
        "export": "default"
      }
    ],
    "docsUrl": "https://magicui.design/docs/components/animated-theme-toggler"
  }
] as const satisfies readonly ReactRegistryEntry[];
export const MAGICUI_REGISTRY_BY_SLUG = Object.fromEntries(MAGICUI_REGISTRY_ENTRIES.map((entry) => [entry.slug, entry])) as Record<string, ReactRegistryEntry>;
export const MAGICUI_REGISTRY_MODULES = {
  "./vendor/magicui/registry/example/android-demo-2.tsx": () => import("./vendor/magicui/registry/example/android-demo-2.tsx"),
  "./vendor/magicui/registry/example/android-demo-3.tsx": () => import("./vendor/magicui/registry/example/android-demo-3.tsx"),
  "./vendor/magicui/registry/example/android-demo.tsx": () => import("./vendor/magicui/registry/example/android-demo.tsx"),
  "./vendor/magicui/registry/example/animated-beam-bidirectional.tsx": () => import("./vendor/magicui/registry/example/animated-beam-bidirectional.tsx"),
  "./vendor/magicui/registry/example/animated-beam-demo.tsx": () => import("./vendor/magicui/registry/example/animated-beam-demo.tsx"),
  "./vendor/magicui/registry/example/animated-beam-multiple-inputs.tsx": () => import("./vendor/magicui/registry/example/animated-beam-multiple-inputs.tsx"),
  "./vendor/magicui/registry/example/animated-beam-multiple-outputs.tsx": () => import("./vendor/magicui/registry/example/animated-beam-multiple-outputs.tsx"),
  "./vendor/magicui/registry/example/animated-beam-unidirectional.tsx": () => import("./vendor/magicui/registry/example/animated-beam-unidirectional.tsx"),
  "./vendor/magicui/registry/example/animated-circular-progress-bar-demo.tsx": () => import("./vendor/magicui/registry/example/animated-circular-progress-bar-demo.tsx"),
  "./vendor/magicui/registry/example/animated-gradient-text-demo-2.tsx": () => import("./vendor/magicui/registry/example/animated-gradient-text-demo-2.tsx"),
  "./vendor/magicui/registry/example/animated-gradient-text-demo.tsx": () => import("./vendor/magicui/registry/example/animated-gradient-text-demo.tsx"),
  "./vendor/magicui/registry/example/animated-grid-pattern-demo.tsx": () => import("./vendor/magicui/registry/example/animated-grid-pattern-demo.tsx"),
  "./vendor/magicui/registry/example/animated-list-demo.tsx": () => import("./vendor/magicui/registry/example/animated-list-demo.tsx"),
  "./vendor/magicui/registry/example/animated-shiny-text-demo.tsx": () => import("./vendor/magicui/registry/example/animated-shiny-text-demo.tsx"),
  "./vendor/magicui/registry/example/animated-theme-toggler-demo.tsx": () => import("./vendor/magicui/registry/example/animated-theme-toggler-demo.tsx"),
  "./vendor/magicui/registry/example/aurora-text-demo.tsx": () => import("./vendor/magicui/registry/example/aurora-text-demo.tsx"),
  "./vendor/magicui/registry/example/avatar-circles-demo.tsx": () => import("./vendor/magicui/registry/example/avatar-circles-demo.tsx"),
  "./vendor/magicui/registry/example/bento-demo-vertical.tsx": () => import("./vendor/magicui/registry/example/bento-demo-vertical.tsx"),
  "./vendor/magicui/registry/example/bento-demo.tsx": () => import("./vendor/magicui/registry/example/bento-demo.tsx"),
  "./vendor/magicui/registry/example/blur-fade-demo.tsx": () => import("./vendor/magicui/registry/example/blur-fade-demo.tsx"),
  "./vendor/magicui/registry/example/blur-fade-text-demo.tsx": () => import("./vendor/magicui/registry/example/blur-fade-text-demo.tsx"),
  "./vendor/magicui/registry/example/border-beam-demo-2.tsx": () => import("./vendor/magicui/registry/example/border-beam-demo-2.tsx"),
  "./vendor/magicui/registry/example/border-beam-demo-3.tsx": () => import("./vendor/magicui/registry/example/border-beam-demo-3.tsx"),
  "./vendor/magicui/registry/example/border-beam-demo-4.tsx": () => import("./vendor/magicui/registry/example/border-beam-demo-4.tsx"),
  "./vendor/magicui/registry/example/border-beam-demo.tsx": () => import("./vendor/magicui/registry/example/border-beam-demo.tsx"),
  "./vendor/magicui/registry/example/code-comparison-demo.tsx": () => import("./vendor/magicui/registry/example/code-comparison-demo.tsx"),
  "./vendor/magicui/registry/example/comic-text-demo.tsx": () => import("./vendor/magicui/registry/example/comic-text-demo.tsx"),
  "./vendor/magicui/registry/example/confetti-basic-cannon.tsx": () => import("./vendor/magicui/registry/example/confetti-basic-cannon.tsx"),
  "./vendor/magicui/registry/example/confetti-custom-shapes.tsx": () => import("./vendor/magicui/registry/example/confetti-custom-shapes.tsx"),
  "./vendor/magicui/registry/example/confetti-demo.tsx": () => import("./vendor/magicui/registry/example/confetti-demo.tsx"),
  "./vendor/magicui/registry/example/confetti-emoji.tsx": () => import("./vendor/magicui/registry/example/confetti-emoji.tsx"),
  "./vendor/magicui/registry/example/confetti-fireworks.tsx": () => import("./vendor/magicui/registry/example/confetti-fireworks.tsx"),
  "./vendor/magicui/registry/example/confetti-random-direction.tsx": () => import("./vendor/magicui/registry/example/confetti-random-direction.tsx"),
  "./vendor/magicui/registry/example/confetti-side-cannons.tsx": () => import("./vendor/magicui/registry/example/confetti-side-cannons.tsx"),
  "./vendor/magicui/registry/example/confetti-stars.tsx": () => import("./vendor/magicui/registry/example/confetti-stars.tsx"),
  "./vendor/magicui/registry/example/cool-mode-custom.tsx": () => import("./vendor/magicui/registry/example/cool-mode-custom.tsx"),
  "./vendor/magicui/registry/example/cool-mode-demo.tsx": () => import("./vendor/magicui/registry/example/cool-mode-demo.tsx"),
  "./vendor/magicui/registry/example/dock-demo-2.tsx": () => import("./vendor/magicui/registry/example/dock-demo-2.tsx"),
  "./vendor/magicui/registry/example/dock-demo-3.tsx": () => import("./vendor/magicui/registry/example/dock-demo-3.tsx"),
  "./vendor/magicui/registry/example/dock-demo.tsx": () => import("./vendor/magicui/registry/example/dock-demo.tsx"),
  "./vendor/magicui/registry/example/dot-pattern-demo.tsx": () => import("./vendor/magicui/registry/example/dot-pattern-demo.tsx"),
  "./vendor/magicui/registry/example/dot-pattern-linear-gradient.tsx": () => import("./vendor/magicui/registry/example/dot-pattern-linear-gradient.tsx"),
  "./vendor/magicui/registry/example/dot-pattern-with-glow-effect.tsx": () => import("./vendor/magicui/registry/example/dot-pattern-with-glow-effect.tsx"),
  "./vendor/magicui/registry/example/file-tree-demo.tsx": () => import("./vendor/magicui/registry/example/file-tree-demo.tsx"),
  "./vendor/magicui/registry/example/flickering-grid-demo.tsx": () => import("./vendor/magicui/registry/example/flickering-grid-demo.tsx"),
  "./vendor/magicui/registry/example/flickering-grid-rounded-demo.tsx": () => import("./vendor/magicui/registry/example/flickering-grid-rounded-demo.tsx"),
  "./vendor/magicui/registry/example/globe-demo.tsx": () => import("./vendor/magicui/registry/example/globe-demo.tsx"),
  "./vendor/magicui/registry/example/grid-pattern-dashed.tsx": () => import("./vendor/magicui/registry/example/grid-pattern-dashed.tsx"),
  "./vendor/magicui/registry/example/grid-pattern-demo.tsx": () => import("./vendor/magicui/registry/example/grid-pattern-demo.tsx"),
  "./vendor/magicui/registry/example/grid-pattern-linear-gradient.tsx": () => import("./vendor/magicui/registry/example/grid-pattern-linear-gradient.tsx"),
  "./vendor/magicui/registry/example/hero-video-dialog-demo-top-in-bottom-out.tsx": () => import("./vendor/magicui/registry/example/hero-video-dialog-demo-top-in-bottom-out.tsx"),
  "./vendor/magicui/registry/example/hero-video-dialog-demo.tsx": () => import("./vendor/magicui/registry/example/hero-video-dialog-demo.tsx"),
  "./vendor/magicui/registry/example/highlighter-demo.tsx": () => import("./vendor/magicui/registry/example/highlighter-demo.tsx"),
  "./vendor/magicui/registry/example/hyper-text-demo.tsx": () => import("./vendor/magicui/registry/example/hyper-text-demo.tsx"),
  "./vendor/magicui/registry/example/icon-cloud-demo-2.tsx": () => import("./vendor/magicui/registry/example/icon-cloud-demo-2.tsx"),
  "./vendor/magicui/registry/example/icon-cloud-demo-3.tsx": () => import("./vendor/magicui/registry/example/icon-cloud-demo-3.tsx"),
  "./vendor/magicui/registry/example/icon-cloud-demo.tsx": () => import("./vendor/magicui/registry/example/icon-cloud-demo.tsx"),
  "./vendor/magicui/registry/example/interactive-grid-pattern-demo-2.tsx": () => import("./vendor/magicui/registry/example/interactive-grid-pattern-demo-2.tsx"),
  "./vendor/magicui/registry/example/interactive-grid-pattern-demo.tsx": () => import("./vendor/magicui/registry/example/interactive-grid-pattern-demo.tsx"),
  "./vendor/magicui/registry/example/interactive-hover-button-demo.tsx": () => import("./vendor/magicui/registry/example/interactive-hover-button-demo.tsx"),
  "./vendor/magicui/registry/example/lens-demo-2.tsx": () => import("./vendor/magicui/registry/example/lens-demo-2.tsx"),
  "./vendor/magicui/registry/example/lens-demo-3.tsx": () => import("./vendor/magicui/registry/example/lens-demo-3.tsx"),
  "./vendor/magicui/registry/example/lens-demo.tsx": () => import("./vendor/magicui/registry/example/lens-demo.tsx"),
  "./vendor/magicui/registry/example/line-shadow-text-demo.tsx": () => import("./vendor/magicui/registry/example/line-shadow-text-demo.tsx"),
  "./vendor/magicui/registry/example/magic-card-demo.tsx": () => import("./vendor/magicui/registry/example/magic-card-demo.tsx"),
  "./vendor/magicui/registry/example/marquee-3d.tsx": () => import("./vendor/magicui/registry/example/marquee-3d.tsx"),
  "./vendor/magicui/registry/example/marquee-demo-vertical.tsx": () => import("./vendor/magicui/registry/example/marquee-demo-vertical.tsx"),
  "./vendor/magicui/registry/example/marquee-demo.tsx": () => import("./vendor/magicui/registry/example/marquee-demo.tsx"),
  "./vendor/magicui/registry/example/marquee-logos.tsx": () => import("./vendor/magicui/registry/example/marquee-logos.tsx"),
  "./vendor/magicui/registry/example/meteors-demo.tsx": () => import("./vendor/magicui/registry/example/meteors-demo.tsx"),
  "./vendor/magicui/registry/example/morphing-text-demo.tsx": () => import("./vendor/magicui/registry/example/morphing-text-demo.tsx"),
  "./vendor/magicui/registry/example/neon-gradient-card-demo.tsx": () => import("./vendor/magicui/registry/example/neon-gradient-card-demo.tsx"),
  "./vendor/magicui/registry/example/number-ticker-decimal-demo.tsx": () => import("./vendor/magicui/registry/example/number-ticker-decimal-demo.tsx"),
  "./vendor/magicui/registry/example/number-ticker-demo-2.tsx": () => import("./vendor/magicui/registry/example/number-ticker-demo-2.tsx"),
  "./vendor/magicui/registry/example/number-ticker-demo.tsx": () => import("./vendor/magicui/registry/example/number-ticker-demo.tsx"),
  "./vendor/magicui/registry/example/orbiting-circles-demo.tsx": () => import("./vendor/magicui/registry/example/orbiting-circles-demo.tsx"),
  "./vendor/magicui/registry/example/particles-demo.tsx": () => import("./vendor/magicui/registry/example/particles-demo.tsx"),
  "./vendor/magicui/registry/example/pixel-image-demo.tsx": () => import("./vendor/magicui/registry/example/pixel-image-demo.tsx"),
  "./vendor/magicui/registry/example/pointer-demo-1.tsx": () => import("./vendor/magicui/registry/example/pointer-demo-1.tsx"),
  "./vendor/magicui/registry/example/progressive-blur-demo.tsx": () => import("./vendor/magicui/registry/example/progressive-blur-demo.tsx"),
  "./vendor/magicui/registry/example/pulsating-button-demo.tsx": () => import("./vendor/magicui/registry/example/pulsating-button-demo.tsx"),
  "./vendor/magicui/registry/example/rainbow-button-demo-2.tsx": () => import("./vendor/magicui/registry/example/rainbow-button-demo-2.tsx"),
  "./vendor/magicui/registry/example/rainbow-button-demo.tsx": () => import("./vendor/magicui/registry/example/rainbow-button-demo.tsx"),
  "./vendor/magicui/registry/example/retro-grid-demo.tsx": () => import("./vendor/magicui/registry/example/retro-grid-demo.tsx"),
  "./vendor/magicui/registry/example/ripple-button-demo.tsx": () => import("./vendor/magicui/registry/example/ripple-button-demo.tsx"),
  "./vendor/magicui/registry/example/ripple-demo.tsx": () => import("./vendor/magicui/registry/example/ripple-demo.tsx"),
  "./vendor/magicui/registry/example/safari-demo-2.tsx": () => import("./vendor/magicui/registry/example/safari-demo-2.tsx"),
  "./vendor/magicui/registry/example/safari-demo-3.tsx": () => import("./vendor/magicui/registry/example/safari-demo-3.tsx"),
  "./vendor/magicui/registry/example/safari-demo-4.tsx": () => import("./vendor/magicui/registry/example/safari-demo-4.tsx"),
  "./vendor/magicui/registry/example/safari-demo.tsx": () => import("./vendor/magicui/registry/example/safari-demo.tsx"),
  "./vendor/magicui/registry/example/scroll-based-velocity-demo.tsx": () => import("./vendor/magicui/registry/example/scroll-based-velocity-demo.tsx"),
  "./vendor/magicui/registry/example/scroll-based-velocity-images-demo.tsx": () => import("./vendor/magicui/registry/example/scroll-based-velocity-images-demo.tsx"),
  "./vendor/magicui/registry/example/scroll-progress-demo.tsx": () => import("./vendor/magicui/registry/example/scroll-progress-demo.tsx"),
  "./vendor/magicui/registry/example/shimmer-button-demo.tsx": () => import("./vendor/magicui/registry/example/shimmer-button-demo.tsx"),
  "./vendor/magicui/registry/example/shine-border-demo-2.tsx": () => import("./vendor/magicui/registry/example/shine-border-demo-2.tsx"),
  "./vendor/magicui/registry/example/shine-border-demo.tsx": () => import("./vendor/magicui/registry/example/shine-border-demo.tsx"),
  "./vendor/magicui/registry/example/shiny-button-demo.tsx": () => import("./vendor/magicui/registry/example/shiny-button-demo.tsx"),
  "./vendor/magicui/registry/example/smooth-cursor-demo.tsx": () => import("./vendor/magicui/registry/example/smooth-cursor-demo.tsx"),
  "./vendor/magicui/registry/example/sparkles-text-demo.tsx": () => import("./vendor/magicui/registry/example/sparkles-text-demo.tsx"),
  "./vendor/magicui/registry/example/spinning-text-demo-2.tsx": () => import("./vendor/magicui/registry/example/spinning-text-demo-2.tsx"),
  "./vendor/magicui/registry/example/spinning-text-demo.tsx": () => import("./vendor/magicui/registry/example/spinning-text-demo.tsx"),
  "./vendor/magicui/registry/example/striped-pattern-demo.tsx": () => import("./vendor/magicui/registry/example/striped-pattern-demo.tsx"),
  "./vendor/magicui/registry/example/striped-pattern-left.tsx": () => import("./vendor/magicui/registry/example/striped-pattern-left.tsx"),
  "./vendor/magicui/registry/example/striped-pattern-right.tsx": () => import("./vendor/magicui/registry/example/striped-pattern-right.tsx"),
  "./vendor/magicui/registry/example/terminal-demo.tsx": () => import("./vendor/magicui/registry/example/terminal-demo.tsx"),
  "./vendor/magicui/registry/example/text-animate-demo-2.tsx": () => import("./vendor/magicui/registry/example/text-animate-demo-2.tsx"),
  "./vendor/magicui/registry/example/text-animate-demo-3.tsx": () => import("./vendor/magicui/registry/example/text-animate-demo-3.tsx"),
  "./vendor/magicui/registry/example/text-animate-demo-4.tsx": () => import("./vendor/magicui/registry/example/text-animate-demo-4.tsx"),
  "./vendor/magicui/registry/example/text-animate-demo-5.tsx": () => import("./vendor/magicui/registry/example/text-animate-demo-5.tsx"),
  "./vendor/magicui/registry/example/text-animate-demo-6.tsx": () => import("./vendor/magicui/registry/example/text-animate-demo-6.tsx"),
  "./vendor/magicui/registry/example/text-animate-demo-7.tsx": () => import("./vendor/magicui/registry/example/text-animate-demo-7.tsx"),
  "./vendor/magicui/registry/example/text-animate-demo-8.tsx": () => import("./vendor/magicui/registry/example/text-animate-demo-8.tsx"),
  "./vendor/magicui/registry/example/text-animate-demo-9.tsx": () => import("./vendor/magicui/registry/example/text-animate-demo-9.tsx"),
  "./vendor/magicui/registry/example/text-animate-demo.tsx": () => import("./vendor/magicui/registry/example/text-animate-demo.tsx"),
  "./vendor/magicui/registry/example/text-reveal-demo.tsx": () => import("./vendor/magicui/registry/example/text-reveal-demo.tsx"),
  "./vendor/magicui/registry/example/tweet-card-demo.tsx": () => import("./vendor/magicui/registry/example/tweet-card-demo.tsx"),
  "./vendor/magicui/registry/example/tweet-card-images.tsx": () => import("./vendor/magicui/registry/example/tweet-card-images.tsx"),
  "./vendor/magicui/registry/example/tweet-card-meta-preview.tsx": () => import("./vendor/magicui/registry/example/tweet-card-meta-preview.tsx"),
  "./vendor/magicui/registry/example/typing-animation-demo.tsx": () => import("./vendor/magicui/registry/example/typing-animation-demo.tsx"),
  "./vendor/magicui/registry/example/video-text-demo.tsx": () => import("./vendor/magicui/registry/example/video-text-demo.tsx"),
  "./vendor/magicui/registry/example/warp-background-demo.tsx": () => import("./vendor/magicui/registry/example/warp-background-demo.tsx"),
  "./vendor/magicui/registry/example/word-rotate-demo.tsx": () => import("./vendor/magicui/registry/example/word-rotate-demo.tsx"),
  "./vendor/magicui/registry/magicui/android.tsx": () => import("./vendor/magicui/registry/magicui/android.tsx"),
  "./vendor/magicui/registry/magicui/animated-beam.tsx": () => import("./vendor/magicui/registry/magicui/animated-beam.tsx"),
  "./vendor/magicui/registry/magicui/animated-circular-progress-bar.tsx": () => import("./vendor/magicui/registry/magicui/animated-circular-progress-bar.tsx"),
  "./vendor/magicui/registry/magicui/animated-gradient-text.tsx": () => import("./vendor/magicui/registry/magicui/animated-gradient-text.tsx"),
  "./vendor/magicui/registry/magicui/animated-grid-pattern.tsx": () => import("./vendor/magicui/registry/magicui/animated-grid-pattern.tsx"),
  "./vendor/magicui/registry/magicui/animated-list.tsx": () => import("./vendor/magicui/registry/magicui/animated-list.tsx"),
  "./vendor/magicui/registry/magicui/animated-shiny-text.tsx": () => import("./vendor/magicui/registry/magicui/animated-shiny-text.tsx"),
  "./vendor/magicui/registry/magicui/animated-subscribe-button.tsx": () => import("./vendor/magicui/registry/magicui/animated-subscribe-button.tsx"),
  "./vendor/magicui/registry/magicui/animated-theme-toggler.tsx": () => import("./vendor/magicui/registry/magicui/animated-theme-toggler.tsx"),
  "./vendor/magicui/registry/magicui/aurora-text.tsx": () => import("./vendor/magicui/registry/magicui/aurora-text.tsx"),
  "./vendor/magicui/registry/magicui/avatar-circles.tsx": () => import("./vendor/magicui/registry/magicui/avatar-circles.tsx"),
  "./vendor/magicui/registry/magicui/bento-grid.tsx": () => import("./vendor/magicui/registry/magicui/bento-grid.tsx"),
  "./vendor/magicui/registry/magicui/blur-fade.tsx": () => import("./vendor/magicui/registry/magicui/blur-fade.tsx"),
  "./vendor/magicui/registry/magicui/border-beam.tsx": () => import("./vendor/magicui/registry/magicui/border-beam.tsx"),
  "./vendor/magicui/registry/magicui/client-tweet-card.tsx": () => import("./vendor/magicui/registry/magicui/client-tweet-card.tsx"),
  "./vendor/magicui/registry/magicui/code-comparison.tsx": () => import("./vendor/magicui/registry/magicui/code-comparison.tsx"),
  "./vendor/magicui/registry/magicui/comic-text.tsx": () => import("./vendor/magicui/registry/magicui/comic-text.tsx"),
  "./vendor/magicui/registry/magicui/confetti.tsx": () => import("./vendor/magicui/registry/magicui/confetti.tsx"),
  "./vendor/magicui/registry/magicui/cool-mode.tsx": () => import("./vendor/magicui/registry/magicui/cool-mode.tsx"),
  "./vendor/magicui/registry/magicui/dock.tsx": () => import("./vendor/magicui/registry/magicui/dock.tsx"),
  "./vendor/magicui/registry/magicui/dot-pattern.tsx": () => import("./vendor/magicui/registry/magicui/dot-pattern.tsx"),
  "./vendor/magicui/registry/magicui/file-tree.tsx": () => import("./vendor/magicui/registry/magicui/file-tree.tsx"),
  "./vendor/magicui/registry/magicui/flickering-grid.tsx": () => import("./vendor/magicui/registry/magicui/flickering-grid.tsx"),
  "./vendor/magicui/registry/magicui/globe.tsx": () => import("./vendor/magicui/registry/magicui/globe.tsx"),
  "./vendor/magicui/registry/magicui/glyph-matrix.tsx": () => import("./vendor/magicui/registry/magicui/glyph-matrix.tsx"),
  "./vendor/magicui/registry/magicui/grid-pattern.tsx": () => import("./vendor/magicui/registry/magicui/grid-pattern.tsx"),
  "./vendor/magicui/registry/magicui/hero-video-dialog.tsx": () => import("./vendor/magicui/registry/magicui/hero-video-dialog.tsx"),
  "./vendor/magicui/registry/magicui/highlighter.tsx": () => import("./vendor/magicui/registry/magicui/highlighter.tsx"),
  "./vendor/magicui/registry/magicui/hyper-text.tsx": () => import("./vendor/magicui/registry/magicui/hyper-text.tsx"),
  "./vendor/magicui/registry/magicui/icon-cloud.tsx": () => import("./vendor/magicui/registry/magicui/icon-cloud.tsx"),
  "./vendor/magicui/registry/magicui/interactive-grid-pattern.tsx": () => import("./vendor/magicui/registry/magicui/interactive-grid-pattern.tsx"),
  "./vendor/magicui/registry/magicui/interactive-hover-button.tsx": () => import("./vendor/magicui/registry/magicui/interactive-hover-button.tsx"),
  "./vendor/magicui/registry/magicui/lens.tsx": () => import("./vendor/magicui/registry/magicui/lens.tsx"),
  "./vendor/magicui/registry/magicui/line-shadow-text.tsx": () => import("./vendor/magicui/registry/magicui/line-shadow-text.tsx"),
  "./vendor/magicui/registry/magicui/magic-card.tsx": () => import("./vendor/magicui/registry/magicui/magic-card.tsx"),
  "./vendor/magicui/registry/magicui/marquee.tsx": () => import("./vendor/magicui/registry/magicui/marquee.tsx"),
  "./vendor/magicui/registry/magicui/meteors.tsx": () => import("./vendor/magicui/registry/magicui/meteors.tsx"),
  "./vendor/magicui/registry/magicui/morphing-text.tsx": () => import("./vendor/magicui/registry/magicui/morphing-text.tsx"),
  "./vendor/magicui/registry/magicui/neon-gradient-card.tsx": () => import("./vendor/magicui/registry/magicui/neon-gradient-card.tsx"),
  "./vendor/magicui/registry/magicui/number-ticker.tsx": () => import("./vendor/magicui/registry/magicui/number-ticker.tsx"),
  "./vendor/magicui/registry/magicui/orbiting-circles.tsx": () => import("./vendor/magicui/registry/magicui/orbiting-circles.tsx"),
  "./vendor/magicui/registry/magicui/particles.tsx": () => import("./vendor/magicui/registry/magicui/particles.tsx"),
  "./vendor/magicui/registry/magicui/pixel-image.tsx": () => import("./vendor/magicui/registry/magicui/pixel-image.tsx"),
  "./vendor/magicui/registry/magicui/pointer.tsx": () => import("./vendor/magicui/registry/magicui/pointer.tsx"),
  "./vendor/magicui/registry/magicui/progressive-blur.tsx": () => import("./vendor/magicui/registry/magicui/progressive-blur.tsx"),
  "./vendor/magicui/registry/magicui/pulsating-button.tsx": () => import("./vendor/magicui/registry/magicui/pulsating-button.tsx"),
  "./vendor/magicui/registry/magicui/rainbow-button.tsx": () => import("./vendor/magicui/registry/magicui/rainbow-button.tsx"),
  "./vendor/magicui/registry/magicui/retro-grid.tsx": () => import("./vendor/magicui/registry/magicui/retro-grid.tsx"),
  "./vendor/magicui/registry/magicui/ripple-button.tsx": () => import("./vendor/magicui/registry/magicui/ripple-button.tsx"),
  "./vendor/magicui/registry/magicui/ripple.tsx": () => import("./vendor/magicui/registry/magicui/ripple.tsx"),
  "./vendor/magicui/registry/magicui/safari.tsx": () => import("./vendor/magicui/registry/magicui/safari.tsx"),
  "./vendor/magicui/registry/magicui/scroll-based-velocity.tsx": () => import("./vendor/magicui/registry/magicui/scroll-based-velocity.tsx"),
  "./vendor/magicui/registry/magicui/scroll-progress.tsx": () => import("./vendor/magicui/registry/magicui/scroll-progress.tsx"),
  "./vendor/magicui/registry/magicui/shimmer-button.tsx": () => import("./vendor/magicui/registry/magicui/shimmer-button.tsx"),
  "./vendor/magicui/registry/magicui/shine-border.tsx": () => import("./vendor/magicui/registry/magicui/shine-border.tsx"),
  "./vendor/magicui/registry/magicui/shiny-button.tsx": () => import("./vendor/magicui/registry/magicui/shiny-button.tsx"),
  "./vendor/magicui/registry/magicui/smooth-cursor.tsx": () => import("./vendor/magicui/registry/magicui/smooth-cursor.tsx"),
  "./vendor/magicui/registry/magicui/sparkles-text.tsx": () => import("./vendor/magicui/registry/magicui/sparkles-text.tsx"),
  "./vendor/magicui/registry/magicui/spinning-text.tsx": () => import("./vendor/magicui/registry/magicui/spinning-text.tsx"),
  "./vendor/magicui/registry/magicui/striped-pattern.tsx": () => import("./vendor/magicui/registry/magicui/striped-pattern.tsx"),
  "./vendor/magicui/registry/magicui/terminal.tsx": () => import("./vendor/magicui/registry/magicui/terminal.tsx"),
  "./vendor/magicui/registry/magicui/text-animate.tsx": () => import("./vendor/magicui/registry/magicui/text-animate.tsx"),
  "./vendor/magicui/registry/magicui/text-reveal.tsx": () => import("./vendor/magicui/registry/magicui/text-reveal.tsx"),
  "./vendor/magicui/registry/magicui/tweet-card.tsx": () => import("./vendor/magicui/registry/magicui/tweet-card.tsx"),
  "./vendor/magicui/registry/magicui/typing-animation.tsx": () => import("./vendor/magicui/registry/magicui/typing-animation.tsx"),
  "./vendor/magicui/registry/magicui/video-text.tsx": () => import("./vendor/magicui/registry/magicui/video-text.tsx"),
  "./vendor/magicui/registry/magicui/warp-background.tsx": () => import("./vendor/magicui/registry/magicui/warp-background.tsx"),
  "./vendor/magicui/registry/magicui/word-rotate.tsx": () => import("./vendor/magicui/registry/magicui/word-rotate.tsx")
};
