use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            CONFIGURATION_CENTER_MEMORY_ENGINE_BASE_URL_CONFIG_KEY,
            "Memory Engine Base URL",
            "Configuration Center 执行队列运维操作时调用 Memory Engine 的内部地址",
            "Configuration Center / Downstream",
            "service",
            Some("configuration-center"),
            "string",
            json!("https://memory-engine-backend:7083/api/memory-engine/v1"),
            None,
            None,
            &[],
            "immediate",
            &["CONFIGURATION_CENTER_MEMORY_ENGINE_BASE_URL"],
            357,
            now,
        ),
        definition(
            CONFIGURATION_CENTER_PLUGIN_MANAGEMENT_BASE_URL_CONFIG_KEY,
            "Plugin Management Base URL",
            "Configuration Center 执行队列运维操作时调用 Plugin Management 的内部地址",
            "Configuration Center / Downstream",
            "service",
            Some("configuration-center"),
            "string",
            json!("http://127.0.0.1:9080/api/plugin"),
            None,
            None,
            &[],
            "immediate",
            &[],
            358,
            now,
        ),
        definition(
            CONFIGURATION_CENTER_MCP_MANAGEMENT_BASE_URL_CONFIG_KEY,
            "MCP Management Base URL",
            "Configuration Center 执行队列运维操作时调用 MCP Management 的内部地址",
            "Configuration Center / Downstream",
            "service",
            Some("configuration-center"),
            "string",
            json!("https://mcp-management-service-backend:39282"),
            None,
            None,
            &[],
            "immediate",
            &["CONFIGURATION_CENTER_MCP_MANAGEMENT_BASE_URL"],
            359,
            now,
        ),
    ]
}
