use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            LOCAL_CONNECTOR_REQUIRE_SIGNED_INTERNAL_REQUESTS_CONFIG_KEY,
            "内部请求必须签名",
            "Local Connector Service 是否必须校验来自平台内部服务的签名请求",
            "Local Connector / Security",
            "service",
            Some("local-connector-service"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_REQUIRE_SIGNED_INTERNAL_REQUESTS"],
            315,
            now,
        ),
        secret_definition(
            LOCAL_CONNECTOR_CHATOS_INTERNAL_API_SECRET_CONFIG_KEY,
            "Chatos Internal Secret",
            "Local Connector Service 校验来自 Chatos Backend 的内部签名请求时使用的共享密钥",
            "Local Connector / Security",
            "service",
            Some("local-connector-service"),
            json!("change_me_chatos_local_connector_secret"),
            "restart_required",
            &["CHATOS_LOCAL_CONNECTOR_INTERNAL_API_SECRET"],
            316,
            now,
        ),
        secret_definition(
            LOCAL_CONNECTOR_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Project Service Internal Secret",
            "Local Connector Service 校验来自 Project Service 的内部签名请求时使用的共享密钥",
            "Local Connector / Security",
            "service",
            Some("local-connector-service"),
            json!("change_me_project_service_local_connector_secret"),
            "restart_required",
            &["PROJECT_SERVICE_LOCAL_CONNECTOR_INTERNAL_API_SECRET"],
            318,
            now,
        ),
        secret_definition(
            LOCAL_CONNECTOR_MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "MCP Management Internal Secret",
            "Local Connector Service 校验来自 MCP Management 的内部签名请求时使用的共享密钥",
            "Local Connector / Security",
            "service",
            Some("local-connector-service"),
            json!("change_me_mcp_management_local_connector_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_LOCAL_CONNECTOR_INTERNAL_API_SECRET"],
            319,
            now,
        ),
        secret_definition(
            LOCAL_CONNECTOR_PLUGIN_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "Plugin Management Internal Secret",
            "Local Connector Service 调用 Plugin Management 内部接口时使用的专用密钥",
            "Local Connector / Downstream Security",
            "service",
            Some("local-connector-service"),
            json!("change_me_plugin_management_local_connector_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_LOCAL_CONNECTOR_SERVICE_INTERNAL_API_SECRET"],
            319,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_HOST_CONFIG_KEY,
            "Host",
            "Local Connector Service HTTP 服务监听地址",
            "Local Connector / Runtime",
            "service",
            Some("local-connector-service"),
            "string",
            json!("127.0.0.1"),
            None,
            None,
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_SERVICE_HOST"],
            319,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_PORT_CONFIG_KEY,
            "Port",
            "Local Connector Service HTTP 服务监听端口",
            "Local Connector / Runtime",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(39230),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_SERVICE_PORT"],
            319,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_INTERNAL_MTLS_PORT_CONFIG_KEY,
            "Internal mTLS Port",
            "Local Connector Service 强制双向 TLS 的内部服务监听端口",
            "Local Connector / Runtime",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(39232),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_INTERNAL_MTLS_PORT"],
            319,
            now,
        ),
        secret_definition(
            LOCAL_CONNECTOR_DATABASE_URL_CONFIG_KEY,
            "Database URL",
            "Local Connector Service 连接 MongoDB 使用的连接串",
            "Local Connector / Runtime",
            "service",
            Some("local-connector-service"),
            json!("mongodb://admin:admin@127.0.0.1:27018/local_connector_service?authSource=admin"),
            "restart_required",
            &["LOCAL_CONNECTOR_DATABASE_URL"],
            319,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_USER_SERVICE_BASE_URL_CONFIG_KEY,
            "User Service Base URL",
            "Local Connector Service 调用 User Service 时使用的基础地址",
            "Local Connector / Downstream",
            "service",
            Some("local-connector-service"),
            "string",
            json!("http://127.0.0.1:39190"),
            None,
            None,
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_USER_SERVICE_BASE_URL"],
            319,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_USER_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "User Service Request Timeout",
            "Local Connector Service 调用 User Service 时使用的请求超时毫秒数",
            "Local Connector / Downstream",
            "service",
            Some("local-connector-service"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_USER_SERVICE_REQUEST_TIMEOUT_MS"],
            319,
            now,
        ),
        nullable_definition(
            LOCAL_CONNECTOR_PUBLIC_BASE_URL_CONFIG_KEY,
            "Public Base URL",
            "Local Connector Service 对外暴露给本地客户端和托管 requirements bundle 的公网基础地址",
            "Local Connector / Public",
            "service",
            Some("local-connector-service"),
            "string",
            Value::Null,
            None,
            None,
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_PUBLIC_BASE_URL"],
            319,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_RELAY_SIGNING_KEY_PATH_CONFIG_KEY,
            "Relay 签名私钥路径",
            "Local Connector Service 用于对下发给本地客户端的命令进行 Ed25519 签名的私钥文件路径",
            "Local Connector / Security",
            "service",
            Some("local-connector-service"),
            "string",
            json!("/var/lib/chatos/local-connector/relay-signing-key.pk8"),
            None,
            None,
            &[],
            "restart_required",
            &[],
            320,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_RELAY_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Relay Request Timeout",
            "Local Connector Service 转发普通 relay 请求到本地客户端时使用的超时毫秒数",
            "Local Connector / Relay",
            "service",
            Some("local-connector-service"),
            "duration_ms",
            json!(30_000),
            Some(1_000),
            Some(10 * 60 * 1_000),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_RELAY_REQUEST_TIMEOUT_MS"],
            321,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_RELAY_SIGNING_KEY_ID_CONFIG_KEY,
            "Relay 签名 Key ID",
            "Local Connector Service 当前使用的 relay 命令签名 Key ID",
            "Local Connector / Security",
            "service",
            Some("local-connector-service"),
            "string",
            json!("relay-key-1"),
            None,
            None,
            &[],
            "restart_required",
            &[],
            322,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_PLUGIN_HOOK_RELAY_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Plugin Hook Relay Timeout",
            "Local Connector Service 向本地客户端转发插件 Hook 事件时使用的超时毫秒数",
            "Local Connector / Relay",
            "service",
            Some("local-connector-service"),
            "duration_ms",
            json!(5 * 60 * 1_000 + 15_000),
            Some(30_000),
            Some(10 * 60 * 1_000),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_PLUGIN_HOOK_RELAY_REQUEST_TIMEOUT_MS"],
            323,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_REMOTE_CONTROL_REQUIRE_SIGNED_CONFIG_KEY,
            "远控命令必须签名",
            "本地客户端是否必须拒绝未带平台签名的远控命令",
            "Local Connector / Security",
            "service",
            Some("local-connector-service"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "next_request",
            &[],
            324,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_REMOTE_CONTROL_SIGNATURE_MAX_SKEW_SECONDS_CONFIG_KEY,
            "远控签名最大时间偏差（秒）",
            "本地客户端接受平台远控命令签名的最大时间偏差窗口",
            "Local Connector / Security",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(300),
            Some(30),
            Some(3600),
            &[],
            "next_request",
            &[],
            326,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_DEVICE_CONNECT_SIGNATURE_MAX_SKEW_SECONDS_CONFIG_KEY,
            "设备接入签名最大时间偏差（秒）",
            "Local Connector Service 校验设备接入签名时允许的最大时间偏差窗口",
            "Local Connector / Device Connect",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(300),
            Some(30),
            Some(3600),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_DEVICE_SIGNATURE_MAX_SKEW_SECONDS"],
            327,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_REQUIRE_DEVICE_CONNECT_SIGNATURE_CONFIG_KEY,
            "设备接入必须签名",
            "Local Connector Service 是否必须校验设备接入请求签名",
            "Local Connector / Device Connect",
            "service",
            Some("local-connector-service"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_REQUIRE_DEVICE_CONNECT_SIGNATURE"],
            327,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_REMOTE_CONTROL_TRUSTED_RELAY_PUBLIC_KEYS_CONFIG_KEY,
            "远控签名信任公钥集合",
            "本地客户端信任的平台 relay 签名公钥集合，格式为 {\"<key-id>\": \"ed25519:<base64url-public-key>\"}",
            "Local Connector / Security",
            "service",
            Some("local-connector-service"),
            "json",
            json!({}),
            None,
            None,
            &[],
            "next_request",
            &[],
            328,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_ACTIVE_SESSION_LEASE_TTL_SECONDS_CONFIG_KEY,
            "Active Session Lease TTL",
            "Local Connector Service 为活跃设备会话保留租约时长（秒）",
            "Local Connector / Device Connect",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(90),
            Some(30),
            Some(600),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_ACTIVE_SESSION_LEASE_TTL_SECONDS"],
            329,
            now,
        ),
        secret_definition(
            LOCAL_CONNECTOR_VALKEY_URL_CONFIG_KEY,
            "Valkey URL",
            "Local Connector Service 保存防重放 nonce 和设备实例路由状态的 Valkey 地址",
            "Local Connector / Coordination",
            "service",
            Some("local-connector-service"),
            json!("redis://:change_me_valkey_password@127.0.0.1:6379/0"),
            "restart_required",
            &["LOCAL_CONNECTOR_VALKEY_URL"],
            3291,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_VALKEY_KEY_PREFIX_CONFIG_KEY,
            "Valkey Key Prefix",
            "Local Connector Service 共享协调键使用的命名空间前缀",
            "Local Connector / Coordination",
            "service",
            Some("local-connector-service"),
            "string",
            json!("chatos:local-connector"),
            None,
            None,
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_VALKEY_KEY_PREFIX"],
            3292,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_DEVICE_PRESENCE_TTL_SECONDS_CONFIG_KEY,
            "Device Presence TTL",
            "Local Connector 设备到服务实例路由租约的 TTL（秒），必须不小于 Mongo active session 租约",
            "Local Connector / Coordination",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(120),
            Some(30),
            Some(600),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_DEVICE_PRESENCE_TTL_SECONDS"],
            3293,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_VALKEY_RECONNECT_MS_CONFIG_KEY,
            "Valkey Reconnect Delay",
            "Local Connector 实例控制订阅断线后的重连等待毫秒数",
            "Local Connector / Coordination",
            "service",
            Some("local-connector-service"),
            "duration_ms",
            json!(2_000),
            Some(100),
            Some(60_000),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_VALKEY_RECONNECT_MS"],
            3294,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_RELAY_CORRELATION_GRACE_SECONDS_CONFIG_KEY,
            "Relay Correlation Grace TTL",
            "Local Connector relay 请求超时之外保留 correlation metadata 的额外秒数",
            "Local Connector / Coordination",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(30),
            Some(5),
            Some(600),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_RELAY_CORRELATION_GRACE_SECONDS"],
            3295,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_RELAY_DELIVERY_ACK_TIMEOUT_MS_CONFIG_KEY,
            "Relay Delivery Ack Timeout",
            "跨实例 relay send 等待 owner 实例确认已写入本地 WebSocket outbound channel 的超时毫秒数",
            "Local Connector / Coordination",
            "service",
            Some("local-connector-service"),
            "duration_ms",
            json!(3_000),
            Some(100),
            Some(10_000),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_RELAY_DELIVERY_ACK_TIMEOUT_MS"],
            3296,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_TERMINAL_SUBSCRIBER_TTL_SECONDS_CONFIG_KEY,
            "Terminal Subscriber TTL",
            "终端 WebSocket 订阅实例在 Valkey 中的路由租约 TTL（秒），只保存实例元数据，不保存终端正文",
            "Local Connector / Coordination",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(60),
            Some(15),
            Some(600),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_TERMINAL_SUBSCRIBER_TTL_SECONDS"],
            3297,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_TERMINAL_SUBSCRIBER_REFRESH_SECONDS_CONFIG_KEY,
            "Terminal Subscriber Refresh",
            "终端 WebSocket 订阅实例刷新 Valkey 路由租约的周期（秒），必须小于订阅 TTL",
            "Local Connector / Coordination",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(20),
            Some(5),
            Some(300),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_TERMINAL_SUBSCRIBER_REFRESH_SECONDS"],
            3298,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_RELAY_MAX_PENDING_REQUESTS_PER_DEVICE_CONFIG_KEY,
            "每设备 Pending Relay 上限",
            "Local Connector Service 为单个设备保留的待响应 relay 请求上限",
            "Local Connector / Relay",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(256),
            Some(1),
            Some(100_000),
            &[],
            "restart_required",
            &[],
            330,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_MANAGED_REQUIREMENTS_BUNDLE_TTL_SECONDS_CONFIG_KEY,
            "Managed Requirements Bundle TTL",
            "Local Connector Service 签发 managed requirements bundle 时使用的默认有效期（秒）",
            "Local Connector / Managed Requirements",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(24 * 60 * 60),
            Some(300),
            Some(7 * 24 * 60 * 60),
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_MANAGED_REQUIREMENTS_BUNDLE_TTL_SECONDS"],
            331,
            now,
        ),
        nullable_definition(
            LOCAL_CONNECTOR_MANAGED_REQUIREMENTS_TOML_PATH_CONFIG_KEY,
            "Managed Requirements TOML 路径",
            "Local Connector Service 生成 managed requirements bundle 时读取的 TOML 文件路径",
            "Local Connector / Managed Requirements",
            "service",
            Some("local-connector-service"),
            "string",
            Value::Null,
            None,
            None,
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_MANAGED_REQUIREMENTS_TOML_PATH"],
            332,
            now,
        ),
        nullable_definition(
            LOCAL_CONNECTOR_MANAGED_REQUIREMENTS_SIGNING_KEY_PATH_CONFIG_KEY,
            "Managed Requirements 签名私钥路径",
            "Local Connector Service 对 managed requirements bundle 进行签名时使用的私钥文件路径",
            "Local Connector / Managed Requirements",
            "service",
            Some("local-connector-service"),
            "string",
            Value::Null,
            None,
            None,
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_MANAGED_REQUIREMENTS_SIGNING_KEY_PATH"],
            333,
            now,
        ),
        nullable_definition(
            LOCAL_CONNECTOR_MANAGED_REQUIREMENTS_SIGNING_KEY_ID_CONFIG_KEY,
            "Managed Requirements 签名 Key ID",
            "Local Connector Service 对 managed requirements bundle 签名时附带的 key id",
            "Local Connector / Managed Requirements",
            "service",
            Some("local-connector-service"),
            "string",
            Value::Null,
            None,
            None,
            &[],
            "restart_required",
            &["LOCAL_CONNECTOR_MANAGED_REQUIREMENTS_SIGNING_KEY_ID"],
            334,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_TERMINAL_MAX_EVENT_BYTES_CONFIG_KEY,
            "Terminal 单事件字节预算",
            "Local Connector Service 接受并转发的单个 terminal 事件最大字节数；超限事件会被丢弃并改发错误提示",
            "Local Connector / Terminal",
            "service",
            Some("local-connector-service"),
            "bytes",
            json!(131_072),
            Some(1024),
            Some(8 * 1024 * 1024),
            &[],
            "restart_required",
            &[],
            332,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_TERMINAL_EVENT_CHANNEL_CAPACITY_CONFIG_KEY,
            "Terminal 事件队列容量",
            "Local Connector Service 单个 terminal session 的内存广播队列容量",
            "Local Connector / Terminal",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(1024),
            Some(1),
            Some(65_536),
            &[],
            "restart_required",
            &[],
            334,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_TERMINAL_MAX_ACTIVE_SESSIONS_CONFIG_KEY,
            "Terminal 活动会话上限",
            "单个 Local Connector Service 实例允许保留的活动 terminal session 最大数量",
            "Local Connector / Terminal",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(10_000),
            Some(1),
            Some(1_000_000),
            &[],
            "next_request",
            &[],
            335,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_TERMINAL_NEW_SESSION_SOFT_LIMIT_CONFIG_KEY,
            "Terminal 新会话软阈值",
            "活动 terminal session 达到该阈值后暂停创建新 session；已有 session 和订阅继续工作，该值不得超过活动会话硬上限",
            "Local Connector / Terminal",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(8_000),
            Some(1),
            Some(1_000_000),
            &[],
            "next_request",
            &[],
            3351,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_TERMINAL_MAX_SUBSCRIBERS_PER_SESSION_CONFIG_KEY,
            "Terminal 单会话订阅上限",
            "单个 Local Connector Service 实例允许同一 terminal session 保留的 WebSocket 订阅最大数量",
            "Local Connector / Terminal",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(64),
            Some(1),
            Some(10_000),
            &[],
            "next_request",
            &[],
            336,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_PRESSURE_PENDING_RELAY_ELEVATED_CONFIG_KEY,
            "Relay 待处理升压阈值",
            "单个 Local Connector Service 实例待处理 relay 请求达到该值时上报 elevated",
            "Local Connector / Pressure",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(1_000),
            Some(1),
            Some(10_000_000),
            &[],
            "hot_reload",
            &[],
            3361,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_PRESSURE_PENDING_RELAY_CRITICAL_CONFIG_KEY,
            "Relay 待处理临界阈值",
            "单个 Local Connector Service 实例待处理 relay 请求达到该值时上报 critical",
            "Local Connector / Pressure",
            "service",
            Some("local-connector-service"),
            "integer",
            json!(5_000),
            Some(2),
            Some(100_000_000),
            &[],
            "hot_reload",
            &[],
            3362,
            now,
        ),
        definition(
            LOCAL_CONNECTOR_PRESSURE_REPORT_INTERVAL_MS_CONFIG_KEY,
            "Local Connector 压力上报间隔",
            "Local Connector 刷新压力策略并上报自身运行压力信号的间隔",
            "Local Connector / Pressure",
            "service",
            Some("local-connector-service"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "hot_reload",
            &[],
            3363,
            now,
        ),
    ]
}
