use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            MEMORY_ENGINE_REQUIRE_SIGNED_INTERNAL_REQUESTS_CONFIG_KEY,
            "内部请求必须签名",
            "Memory Engine 是否必须校验来自内部服务的签名请求",
            "Memory Engine / Security",
            "service",
            Some("memory-engine"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_REQUIRE_SIGNED_INTERNAL_REQUESTS"],
            358,
            &now,
        ),
        secret_definition(
            MEMORY_ENGINE_CHATOS_INTERNAL_API_SECRET_CONFIG_KEY,
            "Chatos Internal Secret",
            "Memory Engine 校验来自 Chatos Backend 的内部签名请求时使用的共享密钥",
            "Memory Engine / Security",
            "service",
            Some("memory-engine"),
            json!("change_me_chatos_memory_engine_secret"),
            "restart_required",
            &["CHATOS_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            359,
            &now,
        ),
        secret_definition(
            MEMORY_ENGINE_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Task Runner Internal Secret",
            "Memory Engine 校验来自 Task Runner 的内部签名请求时使用的共享密钥",
            "Memory Engine / Security",
            "service",
            Some("memory-engine"),
            json!("change_me_task_runner_memory_engine_secret"),
            "restart_required",
            &["TASK_RUNNER_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            360,
            &now,
        ),
        secret_definition(
            MEMORY_ENGINE_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Project Service Internal Secret",
            "Memory Engine 校验来自 Project Service 的内部签名请求时使用的共享密钥",
            "Memory Engine / Security",
            "service",
            Some("memory-engine"),
            json!("change_me_project_service_memory_engine_secret"),
            "restart_required",
            &["PROJECT_SERVICE_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            361,
            &now,
        ),
        secret_definition(
            MEMORY_ENGINE_USER_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "User Service Internal Secret",
            "Memory Engine 校验来自 User Service 的内部签名请求时使用的共享密钥",
            "Memory Engine / Security",
            "service",
            Some("memory-engine"),
            json!("change_me_user_service_memory_engine_secret"),
            "restart_required",
            &["USER_SERVICE_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            362,
            &now,
        ),
        secret_definition(
            MEMORY_ENGINE_CONFIGURATION_CENTER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Configuration Center Internal Secret",
            "Memory Engine 校验来自 Configuration Center 队列运维请求时使用的专用密钥",
            "Memory Engine / Security",
            "service",
            Some("memory-engine"),
            json!("change_me_configuration_center_memory_engine_secret"),
            "restart_required",
            &["CONFIGURATION_CENTER_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            363,
            &now,
        ),
        secret_definition(
            MEMORY_ENGINE_PLUGIN_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "Plugin Management Internal Secret",
            "Memory Engine 调用 Plugin Management 内部接口时使用的专用密钥",
            "Memory Engine / Downstream Security",
            "service",
            Some("memory-engine"),
            json!("change_me_plugin_management_memory_engine_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            363,
            &now,
        ),
        definition(
            MEMORY_ENGINE_HOST_CONFIG_KEY,
            "Host",
            "Memory Engine HTTP 服务监听地址",
            "Memory Engine / Runtime",
            "service",
            Some("memory-engine"),
            "string",
            json!("0.0.0.0"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_HOST"],
            3630,
            &now,
        ),
        definition(
            MEMORY_ENGINE_PORT_CONFIG_KEY,
            "Port",
            "Memory Engine HTTP 服务监听端口",
            "Memory Engine / Runtime",
            "service",
            Some("memory-engine"),
            "integer",
            json!(7081),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_PORT"],
            3630,
            &now,
        ),
        definition(
            MEMORY_ENGINE_INTERNAL_MTLS_PORT_CONFIG_KEY,
            "Internal mTLS Port",
            "Memory Engine 内部控制面强制 mTLS 监听端口",
            "Memory Engine / Runtime",
            "service",
            Some("memory-engine"),
            "integer",
            json!(7083),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_INTERNAL_MTLS_PORT"],
            3630,
            &now,
        ),
        secret_definition(
            MEMORY_ENGINE_MONGODB_URI_CONFIG_KEY,
            "MongoDB URI",
            "Memory Engine 连接 MongoDB 使用的连接串",
            "Memory Engine / Runtime",
            "service",
            Some("memory-engine"),
            json!("mongodb://admin:admin@127.0.0.1:27018/admin"),
            "restart_required",
            &["MEMORY_ENGINE_MONGODB_URI"],
            3630,
            &now,
        ),
        definition(
            MEMORY_ENGINE_MONGODB_DATABASE_CONFIG_KEY,
            "MongoDB Database",
            "Memory Engine 使用的 MongoDB database 名称",
            "Memory Engine / Runtime",
            "service",
            Some("memory-engine"),
            "string",
            json!("memory_engine"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_MONGODB_DATABASE"],
            3630,
            &now,
        ),
        definition(
            MEMORY_ENGINE_USER_SERVICE_BASE_URL_CONFIG_KEY,
            "User Service Base URL",
            "Memory Engine 调用 User Service 时使用的基础地址",
            "Memory Engine / Downstream",
            "service",
            Some("memory-engine"),
            "string",
            json!("http://127.0.0.1:39190"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_USER_SERVICE_BASE_URL"],
            3631,
            &now,
        ),
        definition(
            MEMORY_ENGINE_USER_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "User Service 请求超时（毫秒）",
            "Memory Engine 调用 User Service 时使用的超时时间",
            "Memory Engine / Downstream",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(60_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_USER_SERVICE_REQUEST_TIMEOUT_MS"],
            3632,
            &now,
        ),
        definition(
            MEMORY_ENGINE_AI_REQUEST_TIMEOUT_SECS_CONFIG_KEY,
            "AI 请求超时（秒）",
            "Memory Engine 调用上游模型服务时使用的超时时间",
            "Memory Engine / AI",
            "service",
            Some("memory-engine"),
            "integer",
            json!(60),
            Some(5),
            Some(600),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_AI_TIMEOUT_SECS"],
            3633,
            &now,
        ),
        nullable_secret_definition(
            MEMORY_ENGINE_OPENAI_API_KEY_CONFIG_KEY,
            "OpenAI API Key",
            "Memory Engine 默认调用 OpenAI 兼容模型服务时使用的 API Key，留空表示仅使用用户自定义 profile key",
            "Memory Engine / AI",
            "service",
            Some("memory-engine"),
            Value::Null,
            "restart_required",
            &["MEMORY_ENGINE_OPENAI_API_KEY"],
            3634,
            &now,
        ),
        definition(
            MEMORY_ENGINE_OPENAI_BASE_URL_CONFIG_KEY,
            "OpenAI Base URL",
            "Memory Engine 默认调用的 OpenAI 兼容服务基础地址",
            "Memory Engine / AI",
            "service",
            Some("memory-engine"),
            "string",
            json!("https://api.openai.com/v1"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_OPENAI_BASE_URL"],
            3635,
            &now,
        ),
        definition(
            MEMORY_ENGINE_OPENAI_MODEL_CONFIG_KEY,
            "OpenAI 默认模型",
            "Memory Engine 默认使用的模型名称",
            "Memory Engine / AI",
            "service",
            Some("memory-engine"),
            "string",
            json!("gpt-4o-mini"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_OPENAI_MODEL"],
            3636,
            &now,
        ),
        definition(
            MEMORY_ENGINE_OPENAI_TEMPERATURE_CONFIG_KEY,
            "OpenAI Temperature",
            "Memory Engine 默认模型请求使用的 temperature 值，使用字符串形式保存小数",
            "Memory Engine / AI",
            "service",
            Some("memory-engine"),
            "string",
            json!("0.2"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_OPENAI_TEMPERATURE"],
            3637,
            &now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_ENABLED_CONFIG_KEY,
            "启用 Worker",
            "Memory Engine 是否启用后台 worker 处理摘要与记忆任务",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_ENABLED"],
            3638,
            &now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_INTERVAL_SECS_CONFIG_KEY,
            "Worker 恢复检查间隔（秒）",
            "Memory Engine worker 执行 rollup、subject memory 与低频异常恢复检查的间隔；摘要正常执行由 MQ 事件触发",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(30),
            Some(3),
            Some(3600),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_INTERVAL_SECS"],
            3639,
            &now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_MAX_THREADS_PER_TICK_CONFIG_KEY,
            "单轮最大线程数",
            "Memory Engine worker 每轮最多处理的线程数量",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(10),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_MAX_THREADS_PER_TICK"],
            3640,
            &now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_SUMMARY_CONCURRENCY_CONFIG_KEY,
            "摘要并发数",
            "Memory Engine worker 处理 summary 任务时的并发数",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(4),
            Some(1),
            Some(1024),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_SUMMARY_CONCURRENCY"],
            3641,
            &now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_PRESSURE_SUMMARY_CONCURRENCY_CONFIG_KEY,
            "压力状态摘要并发数",
            "平台压力为 elevated 或 critical 时 Memory Engine 保留的 summary 消费并发数",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(1),
            Some(1),
            Some(1024),
            &[],
            "hot_reload",
            &[],
            3642,
            &now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_PRESSURE_REFRESH_INTERVAL_MS_CONFIG_KEY,
            "压力状态刷新间隔",
            "Memory Engine 从配置中心严格刷新平台压力状态的间隔",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "hot_reload",
            &[],
            3643,
            &now,
        ),
        definition(
            MEMORY_ENGINE_PRESSURE_QUEUE_ELEVATED_MESSAGES_CONFIG_KEY,
            "Memory 队列升压阈值",
            "Memory Engine 自有主队列 ready 消息总数达到该值时上报 elevated",
            "Memory Engine / Pressure",
            "service",
            Some("memory-engine"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000_000),
            &[],
            "hot_reload",
            &[],
            3644,
            &now,
        ),
        definition(
            MEMORY_ENGINE_PRESSURE_QUEUE_CRITICAL_MESSAGES_CONFIG_KEY,
            "Memory 队列临界阈值",
            "Memory Engine 自有主队列 ready 消息总数达到该值时上报 critical",
            "Memory Engine / Pressure",
            "service",
            Some("memory-engine"),
            "integer",
            json!(1_000),
            Some(2),
            Some(100_000_000),
            &[],
            "hot_reload",
            &[],
            3645,
            &now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_ROLLUP_CONCURRENCY_CONFIG_KEY,
            "Rollup 并发数",
            "Memory Engine worker 处理 rollup 任务时的并发数",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(3),
            Some(1),
            Some(1024),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_ROLLUP_CONCURRENCY"],
            3646,
            &now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_SUBJECT_MEMORY_CONCURRENCY_CONFIG_KEY,
            "Subject Memory 并发数",
            "Memory Engine worker 处理 subject memory 任务时的并发数",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(2),
            Some(1),
            Some(1024),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_SUBJECT_MEMORY_CONCURRENCY"],
            3647,
            &now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_RECONCILE_CONCURRENCY_CONFIG_KEY,
            "Reconcile 并发数",
            "Memory Engine worker 处理 reconcile 任务时的并发数",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(2),
            Some(1),
            Some(1024),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_RECONCILE_CONCURRENCY"],
            3648,
            &now,
        ),
        definition(
            MEMORY_ENGINE_RABBITMQ_URL_CONFIG_KEY,
            "RabbitMQ 连接地址",
            "Memory Engine 摘要事件队列连接 RabbitMQ 使用的 AMQP 地址",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "string",
            json!(DEFAULT_LOCAL_RABBITMQ_URL),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_RABBITMQ_URL"],
            3645,
            &now,
        ),
        definition(
            MEMORY_ENGINE_RABBITMQ_EXCHANGE_CONFIG_KEY,
            "RabbitMQ Exchange",
            "Memory Engine 事件队列使用的共享 RabbitMQ Exchange",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "string",
            json!("memory_engine"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_RABBITMQ_EXCHANGE"],
            3646,
            &now,
        ),
        definition(
            MEMORY_ENGINE_RABBITMQ_RECONNECT_DELAY_MS_CONFIG_KEY,
            "RabbitMQ 重连等待时间",
            "Memory Engine 队列消费者连接中断后再次连接 RabbitMQ 的等待毫秒数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(3_000),
            Some(100),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_RABBITMQ_RECONNECT_DELAY_MS"],
            3647,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUMMARY_QUEUE_CONFIG_KEY,
            "摘要任务队列名",
            "记录写入达到摘要阈值后投递线程 ID 的共享 RabbitMQ 队列",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "string",
            json!("memory_engine.summary.requested"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUMMARY_QUEUE"],
            3647,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUMMARY_RETRY_QUEUE_CONFIG_KEY,
            "摘要延迟重试队列名",
            "摘要执行失败后等待 RabbitMQ 再次触发的共享延迟队列",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "string",
            json!("memory_engine.summary.requested.retry"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUMMARY_RETRY_QUEUE"],
            3648,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUMMARY_DEAD_LETTER_QUEUE_CONFIG_KEY,
            "摘要死信队列名",
            "摘要事件超过最大投递次数后保存毒消息的共享 RabbitMQ 队列",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "string",
            json!("memory_engine.summary.requested.dead"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUMMARY_DEAD_LETTER_QUEUE"],
            3649,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUMMARY_MAX_DELIVERY_ATTEMPTS_CONFIG_KEY,
            "摘要最大投递次数",
            "摘要事件进入死信队列前允许的最大失败投递次数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(8),
            Some(1),
            Some(100),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUMMARY_MAX_DELIVERY_ATTEMPTS"],
            3650,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUMMARY_RETRY_DELAY_MS_CONFIG_KEY,
            "摘要重试等待时间",
            "摘要执行失败后由 RabbitMQ 延迟再次触发的等待毫秒数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUMMARY_RETRY_DELAY_MS"],
            3651,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUMMARY_OUTBOX_RECONCILE_MS_CONFIG_KEY,
            "摘要 Outbox 补偿间隔",
            "低频补偿发布异常遗留的摘要事件，不用于正常摘要任务发现",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUMMARY_OUTBOX_RECONCILE_MS"],
            3652,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUMMARY_OUTBOX_BATCH_SIZE_CONFIG_KEY,
            "摘要 Outbox 补偿批次",
            "单轮最多补偿发布的摘要事件数量",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUMMARY_OUTBOX_BATCH_SIZE"],
            3653,
            &now,
        ),
        definition(
            MEMORY_ENGINE_RECORD_SYNC_LEASE_TIMEOUT_SECS_CONFIG_KEY,
            "记录同步租约超时",
            "批量记录同步异常退出后，允许低频恢复流程接管计数修复的等待秒数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(300),
            Some(30),
            Some(86_400),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_RECORD_SYNC_LEASE_TIMEOUT_SECS"],
            3654,
            &now,
        ),
        definition(
            MEMORY_ENGINE_ROLLUP_LOCK_TIMEOUT_SECS_CONFIG_KEY,
            "Rollup 抢占锁超时",
            "同一线程 rollup Worker 异常退出后允许其它事件重新认领的等待秒数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(300),
            Some(30),
            Some(86_400),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ROLLUP_LOCK_TIMEOUT_SECS"],
            3655,
            &now,
        ),
        definition(
            MEMORY_ENGINE_ROLLUP_QUEUE_CONFIG_KEY,
            "Rollup 任务队列名",
            "摘要完成后投递摘要 ID 的共享 RabbitMQ 队列",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "string",
            json!("memory_engine.rollup.requested"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ROLLUP_QUEUE"],
            3656,
            &now,
        ),
        definition(
            MEMORY_ENGINE_ROLLUP_RETRY_QUEUE_CONFIG_KEY,
            "Rollup 延迟重试队列名",
            "Rollup 执行失败后等待 RabbitMQ 再次触发的共享延迟队列",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "string",
            json!("memory_engine.rollup.requested.retry"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ROLLUP_RETRY_QUEUE"],
            3657,
            &now,
        ),
        definition(
            MEMORY_ENGINE_ROLLUP_DEAD_LETTER_QUEUE_CONFIG_KEY,
            "Rollup 死信队列名",
            "Rollup 事件超过最大投递次数后保存毒消息的共享 RabbitMQ 队列",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "string",
            json!("memory_engine.rollup.requested.dead"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ROLLUP_DEAD_LETTER_QUEUE"],
            3658,
            &now,
        ),
        definition(
            MEMORY_ENGINE_ROLLUP_MAX_DELIVERY_ATTEMPTS_CONFIG_KEY,
            "Rollup 最大投递次数",
            "Rollup 事件进入死信队列前允许的最大失败投递次数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(8),
            Some(1),
            Some(100),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ROLLUP_MAX_DELIVERY_ATTEMPTS"],
            3659,
            &now,
        ),
        definition(
            MEMORY_ENGINE_ROLLUP_RETRY_DELAY_MS_CONFIG_KEY,
            "Rollup 重试等待时间",
            "Rollup 执行失败后由 RabbitMQ 延迟再次触发的等待毫秒数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ROLLUP_RETRY_DELAY_MS"],
            3660,
            &now,
        ),
        definition(
            MEMORY_ENGINE_ROLLUP_OUTBOX_RECONCILE_MS_CONFIG_KEY,
            "Rollup Outbox 补偿间隔",
            "低频补偿发布异常遗留的 Rollup 事件，不用于正常任务发现",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(30_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ROLLUP_OUTBOX_RECONCILE_MS"],
            3661,
            &now,
        ),
        definition(
            MEMORY_ENGINE_ROLLUP_OUTBOX_BATCH_SIZE_CONFIG_KEY,
            "Rollup Outbox 补偿批次",
            "单轮最多补偿发布的 Rollup 事件数量",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ROLLUP_OUTBOX_BATCH_SIZE"],
            3662,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUBJECT_MEMORY_QUEUE_CONFIG_KEY,
            "主体记忆任务队列名",
            "摘要来源事件和主体记忆 scope 任务共用的 RabbitMQ 队列",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "string",
            json!("memory_engine.subject_memory.requested"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUBJECT_MEMORY_QUEUE"],
            3663,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUBJECT_MEMORY_RETRY_QUEUE_CONFIG_KEY,
            "主体记忆延迟重试队列名",
            "主体记忆事件执行失败后等待 RabbitMQ 再次触发的共享延迟队列",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "string",
            json!("memory_engine.subject_memory.requested.retry"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUBJECT_MEMORY_RETRY_QUEUE"],
            3664,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUBJECT_MEMORY_DEAD_LETTER_QUEUE_CONFIG_KEY,
            "主体记忆死信队列名",
            "主体记忆事件超过最大投递次数后保存毒消息的共享 RabbitMQ 队列",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "string",
            json!("memory_engine.subject_memory.requested.dead"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUBJECT_MEMORY_DEAD_LETTER_QUEUE"],
            3665,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUBJECT_MEMORY_MAX_DELIVERY_ATTEMPTS_CONFIG_KEY,
            "主体记忆最大投递次数",
            "主体记忆事件进入死信队列前允许的最大失败投递次数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(8),
            Some(1),
            Some(100),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUBJECT_MEMORY_MAX_DELIVERY_ATTEMPTS"],
            3666,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUBJECT_MEMORY_RETRY_DELAY_MS_CONFIG_KEY,
            "主体记忆重试等待时间",
            "主体记忆事件执行失败后由 RabbitMQ 延迟再次触发的等待毫秒数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUBJECT_MEMORY_RETRY_DELAY_MS"],
            3667,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUBJECT_MEMORY_OUTBOX_RECONCILE_MS_CONFIG_KEY,
            "主体记忆 Outbox 补偿间隔",
            "低频补偿异常遗留事件和跨文档扇出中断，不用于正常任务发现",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(30_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUBJECT_MEMORY_OUTBOX_RECONCILE_MS"],
            3668,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUBJECT_MEMORY_OUTBOX_BATCH_SIZE_CONFIG_KEY,
            "主体记忆 Outbox 补偿批次",
            "单轮最多补偿发布的主体记忆来源和 scope 事件数量",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUBJECT_MEMORY_OUTBOX_BATCH_SIZE"],
            3669,
            &now,
        ),
        definition(
            MEMORY_ENGINE_SUBJECT_MEMORY_LOCK_TIMEOUT_SECS_CONFIG_KEY,
            "主体记忆 scope 抢占锁超时",
            "同一主体记忆 scope Worker 异常退出后允许其它事件重新认领的等待秒数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(300),
            Some(30),
            Some(86_400),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUBJECT_MEMORY_LOCK_TIMEOUT_SECS"],
            3670,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_REQUIRE_SIGNED_INTERNAL_REQUESTS_CONFIG_KEY,
            "内部请求必须签名",
            "Sandbox Manager 是否必须校验来自内部服务的签名请求",
            "Sandbox Manager / Security",
            "service",
            Some("sandbox-manager"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_REQUIRE_SIGNED_INTERNAL_REQUESTS"],
            364,
            &now,
        ),
        secret_definition(
            SANDBOX_MANAGER_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Task Runner Internal Secret",
            "Sandbox Manager 校验来自 Task Runner 的内部签名请求时使用的共享密钥",
            "Sandbox Manager / Security",
            "service",
            Some("sandbox-manager"),
            json!("change_me_task_runner_sandbox_manager_secret"),
            "restart_required",
            &["TASK_RUNNER_SANDBOX_MANAGER_INTERNAL_API_SECRET"],
            365,
            &now,
        ),
        secret_definition(
            SANDBOX_MANAGER_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Project Service Internal Secret",
            "Sandbox Manager 校验来自 Project Service 的内部签名请求时使用的共享密钥",
            "Sandbox Manager / Security",
            "service",
            Some("sandbox-manager"),
            json!("change_me_project_service_sandbox_manager_secret"),
            "restart_required",
            &["PROJECT_SERVICE_SANDBOX_MANAGER_INTERNAL_API_SECRET"],
            366,
            &now,
        ),
        secret_definition(
            SANDBOX_MANAGER_MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "MCP Management Internal Secret",
            "Sandbox Manager 校验来自 MCP Management 的内部签名请求时使用的共享密钥",
            "Sandbox Manager / Security",
            "service",
            Some("sandbox-manager"),
            json!("change_me_mcp_management_sandbox_manager_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_SANDBOX_MANAGER_INTERNAL_API_SECRET"],
            367,
            &now,
        ),
        secret_definition(
            SANDBOX_MANAGER_AGENT_TOKEN_SECRET_CONFIG_KEY,
            "Sandbox Manager Agent Token Secret",
            "Sandbox Agent 与 Sandbox Manager 之间签发与校验代理 token 使用的共享密钥",
            "Sandbox Manager / Security",
            "service",
            Some("sandbox-manager"),
            json!(DEFAULT_SANDBOX_MANAGER_AGENT_TOKEN_SECRET),
            "restart_required",
            &["SANDBOX_MANAGER_AGENT_TOKEN_SECRET"],
            371,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_FRONTEND_PROXY_CLIENT_ID_CONFIG_KEY,
            "Sandbox Console Proxy Client ID",
            "Sandbox Manager 控制台反向代理使用的受管访问客户端标识",
            "Sandbox Manager / Frontend",
            "service",
            Some("sandbox-manager"),
            "string",
            json!("sandbox-manager-frontend"),
            None,
            None,
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_FRONTEND_PROXY_CLIENT_ID"],
            37101,
            &now,
        ),
        secret_definition(
            SANDBOX_MANAGER_FRONTEND_PROXY_CLIENT_KEY_CONFIG_KEY,
            "Sandbox Console Proxy Client Key",
            "Sandbox Manager 控制台反向代理使用的受管访问客户端密钥",
            "Sandbox Manager / Frontend",
            "service",
            Some("sandbox-manager"),
            json!("change_me_sandbox_manager_frontend_proxy_client_key"),
            "restart_required",
            &["SANDBOX_MANAGER_FRONTEND_PROXY_CLIENT_KEY"],
            37102,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_REQUIRE_AUTH_CONFIG_KEY,
            "启用接口认证",
            "Sandbox Manager 是否启用真实用户、权限受限 access client 与内部服务签名认证",
            "Sandbox Manager / Runtime",
            "service",
            Some("sandbox-manager"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_REQUIRE_AUTH"],
            3711,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_USER_SERVICE_BASE_URL_CONFIG_KEY,
            "User Service Base URL",
            "Sandbox Manager 调用 User Service 时使用的基础地址",
            "Sandbox Manager / Downstream",
            "service",
            Some("sandbox-manager"),
            "string",
            json!("http://127.0.0.1:39190"),
            None,
            None,
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_USER_SERVICE_BASE_URL"],
            3712,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_USER_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "User Service 请求超时（毫秒）",
            "Sandbox Manager 调用 User Service 时使用的超时时间",
            "Sandbox Manager / Downstream",
            "service",
            Some("sandbox-manager"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(60_000),
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_USER_SERVICE_REQUEST_TIMEOUT_MS"],
            3713,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_SYSTEM_CLIENT_MAX_LEASE_TTL_SECONDS_CONFIG_KEY,
            "System Client 最大租约 TTL（秒）",
            "Sandbox Manager 内置系统客户端能够申请的最大租约时长",
            "Sandbox Manager / Security",
            "service",
            Some("sandbox-manager"),
            "integer",
            json!(7_200),
            Some(60),
            Some(7 * 24 * 60 * 60),
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_SYSTEM_CLIENT_MAX_LEASE_TTL_SECONDS"],
            3718,
            &now,
        ),
    ]
}
