use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        secret_definition(
            PLUGIN_MANAGEMENT_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Task Runner Internal Secret",
            "Plugin Management 调用 Task Runner 内部接口时使用的共享密钥",
            "Plugin Management / Downstream Security",
            "service",
            Some("plugin-management-service"),
            json!("change_me_plugin_management_task_runner_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_TASK_RUNNER_INTERNAL_API_SECRET"],
            361,
            now,
        ),
        secret_definition(
            PLUGIN_MANAGEMENT_CHATOS_INTERNAL_API_SECRET_CONFIG_KEY,
            "Chatos Internal Secret",
            "Plugin Management 校验来自 Chatos Backend 的内部签名请求时使用的专用密钥",
            "Plugin Management / Downstream Security",
            "service",
            Some("plugin-management-service"),
            json!("change_me_plugin_management_chatos_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_CHATOS_INTERNAL_API_SECRET"],
            361,
            now,
        ),
        secret_definition(
            PLUGIN_MANAGEMENT_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Project Service Internal Secret",
            "Plugin Management 调用 Project Service 内部接口时使用的共享密钥",
            "Plugin Management / Downstream Security",
            "service",
            Some("plugin-management-service"),
            json!("change_me_plugin_management_project_service_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_PROJECT_SERVICE_INTERNAL_API_SECRET"],
            362,
            now,
        ),
        secret_definition(
            PLUGIN_MANAGEMENT_LOCAL_CONNECTOR_INTERNAL_API_SECRET_CONFIG_KEY,
            "Local Connector Internal Secret",
            "Plugin Management 调用 Local Connector 内部接口时使用的共享密钥",
            "Plugin Management / Downstream Security",
            "service",
            Some("plugin-management-service"),
            json!("change_me_plugin_management_local_connector_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_LOCAL_CONNECTOR_SERVICE_INTERNAL_API_SECRET"],
            363,
            now,
        ),
        secret_definition(
            PLUGIN_MANAGEMENT_MEMORY_ENGINE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Memory Engine Internal Secret",
            "Plugin Management 调用 Memory Engine 内部接口时使用的共享密钥",
            "Plugin Management / Downstream Security",
            "service",
            Some("plugin-management-service"),
            json!("change_me_plugin_management_memory_engine_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            364,
            now,
        ),
        secret_definition(
            PLUGIN_MANAGEMENT_MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "MCP Management Internal Secret",
            "Plugin Management 调用 MCP Management 内部接口时使用的共享密钥",
            "Plugin Management / Downstream Security",
            "service",
            Some("plugin-management-service"),
            json!("change_me_plugin_management_mcp_management_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_MCP_MANAGEMENT_INTERNAL_API_SECRET"],
            365,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_REQUIRE_SIGNED_INTERNAL_REQUESTS_CONFIG_KEY,
            "内部请求必须签名",
            "Plugin Management 是否必须校验来自内部服务的签名请求",
            "Plugin Management / Security",
            "service",
            Some("plugin-management-service"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_REQUIRE_SIGNED_INTERNAL_REQUESTS"],
            368,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_SERVICE_USER_SERVICE_BASE_URL_CONFIG_KEY,
            "User Service Base URL",
            "Plugin Management 调用 User Service 时使用的基础地址",
            "Plugin Management / Downstream",
            "service",
            Some("plugin-management-service"),
            "string",
            json!("http://127.0.0.1:39190"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_USER_SERVICE_BASE_URL"],
            369,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_SERVICE_USER_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "User Service Request Timeout",
            "Plugin Management 调用 User Service 时使用的请求超时毫秒数",
            "Plugin Management / Downstream",
            "service",
            Some("plugin-management-service"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_USER_SERVICE_REQUEST_TIMEOUT_MS"],
            370,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_TASK_RUNNER_BASE_URL_CONFIG_KEY,
            "Task Runner Base URL",
            "Plugin Management 调用 Task Runner 时使用的基础地址",
            "Plugin Management / Downstream",
            "service",
            Some("plugin-management-service"),
            "string",
            json!("http://127.0.0.1:39090"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_TASK_RUNNER_BASE_URL"],
            371,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_HOST_CONFIG_KEY,
            "监听地址",
            "Plugin Management Service 监听的 IP 地址",
            "Plugin Management / Runtime",
            "service",
            Some("plugin-management-service"),
            "string",
            json!("127.0.0.1"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_HOST"],
            371,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_PORT_CONFIG_KEY,
            "监听端口",
            "Plugin Management Service 监听的端口号",
            "Plugin Management / Runtime",
            "service",
            Some("plugin-management-service"),
            "integer",
            json!(39260),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_PORT"],
            371,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_INTERNAL_MTLS_PORT_CONFIG_KEY,
            "内部 mTLS 监听端口",
            "Plugin Management 内部控制面强制客户端证书的 HTTPS 监听端口",
            "Plugin Management / Runtime",
            "service",
            Some("plugin-management-service"),
            "integer",
            json!(39262),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_INTERNAL_MTLS_PORT"],
            3711,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_DATABASE_URL_CONFIG_KEY,
            "Database URL",
            "Plugin Management Service 使用的数据库连接串",
            "Plugin Management / Runtime",
            "service",
            Some("plugin-management-service"),
            "string",
            json!(
                "mongodb://admin:admin@127.0.0.1:27018/plugin_management_service?authSource=admin"
            ),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_DATABASE_URL"],
            371,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_MONGODB_DATABASE_CONFIG_KEY,
            "MongoDB Database",
            "Plugin Management Service 使用的 MongoDB 数据库名",
            "Plugin Management / Runtime",
            "service",
            Some("plugin-management-service"),
            "string",
            json!("plugin_management_service"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_MONGODB_DATABASE"],
            371,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CORS_ORIGINS_CONFIG_KEY,
            "CORS Origins",
            "Plugin Management Backend 允许的跨域来源列表，使用逗号分隔",
            "Plugin Management / HTTP",
            "service",
            Some("plugin-management-service"),
            "string",
            json!("http://127.0.0.1:39261,http://localhost:39261"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CORS_ORIGINS"],
            371,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_LOCAL_CONNECTOR_CHECK_TTL_SECONDS_CONFIG_KEY,
            "Local Connector Check TTL",
            "Plugin Management 缓存 Local Connector 可用性检查结果的有效期（秒）",
            "Plugin Management / Local Connector",
            "service",
            Some("plugin-management-service"),
            "integer",
            json!(60),
            Some(15),
            Some(600),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_LOCAL_CONNECTOR_CHECK_TTL_SECONDS"],
            378,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_LOCAL_CONNECTOR_MAX_TOOL_SNAPSHOT_BYTES_CONFIG_KEY,
            "Local Connector Tool Snapshot Max Bytes",
            "Plugin Management 接收和缓存 Local Connector 工具快照时允许的最大字节数",
            "Plugin Management / Local Connector",
            "service",
            Some("plugin-management-service"),
            "bytes",
            json!(512 * 1024),
            Some(16 * 1024),
            Some(4 * 1024 * 1024),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_LOCAL_CONNECTOR_MAX_TOOL_SNAPSHOT_BYTES"],
            379,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_SYNC_ENABLED_CONFIG_KEY,
            "Catalog Sync Enabled",
            "Plugin Management 是否启用插件目录自动同步",
            "Plugin Management / Catalog",
            "service",
            Some("plugin-management-service"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_SYNC_ENABLED"],
            380,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_SYNC_INTERVAL_SECONDS_CONFIG_KEY,
            "Catalog Sync Interval",
            "Plugin Management 自动同步插件目录的间隔（秒）",
            "Plugin Management / Catalog",
            "service",
            Some("plugin-management-service"),
            "integer",
            json!(15 * 60),
            Some(60),
            Some(24 * 60 * 60),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_SYNC_INTERVAL_SECONDS"],
            381,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Catalog Request Timeout",
            "Plugin Management 拉取插件目录时使用的请求超时毫秒数",
            "Plugin Management / Catalog",
            "service",
            Some("plugin-management-service"),
            "duration_ms",
            json!(30_000),
            Some(1_000),
            Some(5 * 60 * 1_000),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_REQUEST_TIMEOUT_MS"],
            382,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_MAX_BYTES_CONFIG_KEY,
            "Catalog Max Bytes",
            "Plugin Management 读取插件目录响应时允许的最大字节数",
            "Plugin Management / Catalog",
            "service",
            Some("plugin-management-service"),
            "bytes",
            json!(8 * 1024 * 1024),
            Some(256 * 1024),
            Some(12 * 1024 * 1024),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_MAX_BYTES"],
            383,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_ARTIFACT_STORAGE_DIR_CONFIG_KEY,
            "Plugin Artifact Storage Directory",
            "Plugin Management 保存已上传 npm 插件包、元数据与平台托管签名密钥的目录",
            "Plugin Management / Artifact",
            "service",
            Some("plugin-management-service"),
            "string",
            json!(".chatos/plugin-artifacts"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_ARTIFACT_STORAGE_DIR"],
            384,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_ARTIFACT_PUBLIC_BASE_URL_CONFIG_KEY,
            "Plugin Artifact Public Base URL",
            "Local Connector Client 下载平台托管插件包时使用的 HTTPS 公网基础地址",
            "Plugin Management / Artifact",
            "service",
            Some("plugin-management-service"),
            "string",
            json!("https://plugin.jgoool.com"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_ARTIFACT_PUBLIC_BASE_URL"],
            385,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_ARTIFACT_MAX_BYTES_CONFIG_KEY,
            "Plugin Artifact Max Bytes",
            "Plugin Management 单个 npm 插件包允许的最大字节数",
            "Plugin Management / Artifact",
            "service",
            Some("plugin-management-service"),
            "bytes",
            json!(128 * 1024 * 1024),
            Some(1024 * 1024),
            Some(256 * 1024 * 1024),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_ARTIFACT_MAX_BYTES"],
            386,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_PRESSURE_QUEUE_ELEVATED_MESSAGES_CONFIG_KEY,
            "Plugin 队列升压阈值",
            "Plugin Management 自有 Catalog Sync 主队列 ready 消息达到该值时上报 elevated",
            "Plugin Management / Pressure",
            "service",
            Some("plugin-management-service"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000_000),
            &[],
            "hot_reload",
            &[],
            3831,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_PRESSURE_QUEUE_CRITICAL_MESSAGES_CONFIG_KEY,
            "Plugin 队列临界阈值",
            "Plugin Management 自有 Catalog Sync 主队列 ready 消息达到该值时上报 critical",
            "Plugin Management / Pressure",
            "service",
            Some("plugin-management-service"),
            "integer",
            json!(1_000),
            Some(2),
            Some(100_000_000),
            &[],
            "hot_reload",
            &[],
            3832,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_PRESSURE_REPORT_INTERVAL_MS_CONFIG_KEY,
            "Plugin 压力上报间隔",
            "Plugin Management 刷新压力策略并上报自身队列压力信号的间隔",
            "Plugin Management / Pressure",
            "service",
            Some("plugin-management-service"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "hot_reload",
            &[],
            3833,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_RABBITMQ_URL_CONFIG_KEY,
            "Catalog RabbitMQ URL",
            "Plugin Management Catalog Sync 事件队列使用的 AMQP 地址",
            "Plugin Management / Catalog Queue",
            "service",
            Some("plugin-management-service"),
            "string",
            json!(DEFAULT_LOCAL_RABBITMQ_URL),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_RABBITMQ_URL"],
            390,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_RABBITMQ_EXCHANGE_CONFIG_KEY,
            "Catalog RabbitMQ Exchange",
            "Plugin Management Catalog Sync 使用的共享命令交换机",
            "Plugin Management / Catalog Queue",
            "service",
            Some("plugin-management-service"),
            "string",
            json!("chatos.command"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_RABBITMQ_EXCHANGE"],
            391,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_QUEUE_CONFIG_KEY,
            "Catalog Sync Queue",
            "Plugin Management Catalog Sync 共享主队列",
            "Plugin Management / Catalog Queue",
            "service",
            Some("plugin-management-service"),
            "string",
            json!("plugin.catalog.sync"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_QUEUE"],
            392,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_RETRY_QUEUE_CONFIG_KEY,
            "Catalog Sync Retry Queue",
            "Plugin Management Catalog Sync 失败事件使用的 TTL 延迟重试队列",
            "Plugin Management / Catalog Queue",
            "service",
            Some("plugin-management-service"),
            "string",
            json!("plugin.catalog.sync.retry"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_RETRY_QUEUE"],
            393,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_SCHEDULE_QUEUE_CONFIG_KEY,
            "Catalog Sync Schedule Queue",
            "Plugin Management Catalog Sync 下一周期事件使用的 TTL 调度队列",
            "Plugin Management / Catalog Queue",
            "service",
            Some("plugin-management-service"),
            "string",
            json!("plugin.catalog.sync.schedule"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_SCHEDULE_QUEUE"],
            394,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_DEAD_LETTER_QUEUE_CONFIG_KEY,
            "Catalog Sync Dead Letter Queue",
            "Plugin Management Catalog Sync 重试耗尽后的共享死信队列",
            "Plugin Management / Catalog Queue",
            "service",
            Some("plugin-management-service"),
            "string",
            json!("plugin.catalog.sync.dlq"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_DEAD_LETTER_QUEUE"],
            395,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_MAX_DELIVERY_ATTEMPTS_CONFIG_KEY,
            "Catalog Sync Max Delivery Attempts",
            "Plugin Management Catalog Sync 单个事件进入 DLQ 前允许的最大投递次数",
            "Plugin Management / Catalog Queue",
            "service",
            Some("plugin-management-service"),
            "integer",
            json!(5),
            Some(1),
            Some(100),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_MAX_DELIVERY_ATTEMPTS"],
            396,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_RETRY_DELAY_MS_CONFIG_KEY,
            "Catalog Sync Retry Delay",
            "Plugin Management Catalog Sync 失败事件再次投递前的延迟毫秒数",
            "Plugin Management / Catalog Queue",
            "service",
            Some("plugin-management-service"),
            "duration_ms",
            json!(30_000),
            Some(100),
            Some(24 * 60 * 60 * 1_000),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_RETRY_DELAY_MS"],
            397,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_RABBITMQ_RECONNECT_MS_CONFIG_KEY,
            "Catalog RabbitMQ Reconnect Delay",
            "Plugin Management Catalog Sync 消费者断线后重连的等待毫秒数",
            "Plugin Management / Catalog Queue",
            "service",
            Some("plugin-management-service"),
            "duration_ms",
            json!(2_000),
            Some(100),
            Some(60_000),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_RABBITMQ_RECONNECT_MS"],
            398,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_CONSUMER_CONCURRENCY_CONFIG_KEY,
            "Catalog Sync Consumer Concurrency",
            "Plugin Management 同时处理 Catalog Sync 事件的消费者数量",
            "Plugin Management / Catalog Queue",
            "service",
            Some("plugin-management-service"),
            "integer",
            json!(2),
            Some(1),
            Some(64),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_CONSUMER_CONCURRENCY"],
            399,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_OUTBOX_RECONCILE_MS_CONFIG_KEY,
            "Catalog Sync Outbox Reconcile Interval",
            "Plugin Management 补发异常遗留 Catalog Sync Outbox 的低频周期毫秒数",
            "Plugin Management / Catalog Queue",
            "service",
            Some("plugin-management-service"),
            "duration_ms",
            json!(60_000),
            Some(1_000),
            Some(24 * 60 * 60 * 1_000),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_OUTBOX_RECONCILE_MS"],
            400,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_OUTBOX_BATCH_SIZE_CONFIG_KEY,
            "Catalog Sync Outbox Batch Size",
            "Plugin Management 每轮补偿最多处理的 Catalog Sync Outbox 数量",
            "Plugin Management / Catalog Queue",
            "service",
            Some("plugin-management-service"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_OUTBOX_BATCH_SIZE"],
            401,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_CATALOG_SYNC_LOCK_TIMEOUT_SECONDS_CONFIG_KEY,
            "Catalog Sync Lock Timeout",
            "Plugin Management 单个 Marketplace Catalog Sync 分布式租约超时秒数",
            "Plugin Management / Catalog Queue",
            "service",
            Some("plugin-management-service"),
            "integer",
            json!(60 * 60),
            Some(30),
            Some(60 * 60),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_CATALOG_SYNC_LOCK_TIMEOUT_SECONDS"],
            402,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_SUPER_ADMIN_USERNAME_CONFIG_KEY,
            "Super Admin Username",
            "Plugin Management 启动时自动确保存在的超级管理员用户名",
            "Plugin Management / Bootstrap",
            "service",
            Some("plugin-management-service"),
            "string",
            json!("admin"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_SUPER_ADMIN_USERNAME"],
            384,
            now,
        ),
        secret_definition(
            PLUGIN_MANAGEMENT_SUPER_ADMIN_PASSWORD_CONFIG_KEY,
            "Super Admin Password",
            "Plugin Management 启动时自动确保存在的超级管理员密码",
            "Plugin Management / Bootstrap",
            "service",
            Some("plugin-management-service"),
            json!("admin123456"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_SUPER_ADMIN_PASSWORD"],
            385,
            now,
        ),
        definition(
            PLUGIN_MANAGEMENT_SEED_SYSTEM_RESOURCES_CONFIG_KEY,
            "Seed System Resources",
            "Plugin Management 启动时是否自动写入系统级默认资源",
            "Plugin Management / Bootstrap",
            "service",
            Some("plugin-management-service"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_SEED_SYSTEM_RESOURCES"],
            386,
            now,
        ),
    ]
}
