use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            PROJECT_SERVICE_REQUIRE_SIGNED_INTERNAL_REQUESTS_CONFIG_KEY,
            "内部请求必须签名",
            "Project Service 是否必须校验来自内部服务的签名请求",
            "Project Service / Security",
            "service",
            Some("project-service"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["PROJECT_SERVICE_REQUIRE_SIGNED_INTERNAL_REQUESTS"],
            352,
            &now,
        ),
        secret_definition(
            PROJECT_SERVICE_CHATOS_INTERNAL_API_SECRET_CONFIG_KEY,
            "Chatos Internal Secret",
            "Project Service 校验来自 Chatos Backend 的内部签名请求时使用的共享密钥",
            "Project Service / Security",
            "service",
            Some("project-service"),
            json!("change_me_chatos_project_service_secret"),
            "restart_required",
            &["CHATOS_PROJECT_SERVICE_INTERNAL_API_SECRET"],
            353,
            &now,
        ),
        secret_definition(
            PROJECT_SERVICE_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Task Runner Internal Secret",
            "Project Service 校验来自 Task Runner 的内部签名请求时使用的共享密钥",
            "Project Service / Security",
            "service",
            Some("project-service"),
            json!("change_me_task_runner_project_service_secret"),
            "restart_required",
            &["TASK_RUNNER_PROJECT_SERVICE_INTERNAL_API_SECRET"],
            354,
            &now,
        ),
        secret_definition(
            PROJECT_SERVICE_SELF_INTERNAL_API_SECRET_CONFIG_KEY,
            "Project Service Self Secret",
            "Project Service 校验来自自身内部同步调用时使用的共享密钥",
            "Project Service / Security",
            "service",
            Some("project-service"),
            json!("change_me_project_service_self_secret"),
            "restart_required",
            &["PROJECT_SERVICE_SELF_INTERNAL_API_SECRET"],
            355,
            &now,
        ),
        secret_definition(
            PROJECT_SERVICE_MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "MCP Management Internal Secret",
            "Project Service 校验来自 MCP Management 的内部签名请求时使用的共享密钥",
            "Project Service / Security",
            "service",
            Some("project-service"),
            json!("change_me_mcp_management_project_service_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_PROJECT_SERVICE_INTERNAL_API_SECRET"],
            356,
            &now,
        ),
        secret_definition(
            PROJECT_SERVICE_PLUGIN_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "Plugin Management Internal Secret",
            "Project Service 调用 Plugin Management 内部接口时使用的专用密钥",
            "Project Service / Downstream Security",
            "service",
            Some("project-service"),
            json!("change_me_plugin_management_project_service_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_PROJECT_SERVICE_INTERNAL_API_SECRET"],
            356,
            &now,
        ),
        secret_definition(
            PROJECT_SERVICE_USER_SERVICE_INTERNAL_SECRET_CONFIG_KEY,
            "User Service Internal Secret",
            "Project Service 调用 User Service 内部接口时使用的共享密钥",
            "Project Service / Downstream Security",
            "service",
            Some("project-service"),
            json!("change_me_project_service_user_service_secret"),
            "restart_required",
            &["PROJECT_SERVICE_USER_SERVICE_INTERNAL_SECRET"],
            357,
            &now,
        ),
        definition(
            PROJECT_SERVICE_OTLP_ENDPOINT_CONFIG_KEY,
            "OTLP Endpoint",
            "Project Service OpenTelemetry trace exporter 使用的 OTLP gRPC 地址",
            "Project Service / Observability",
            "service",
            Some("project-service"),
            "string",
            json!("http://tempo:4317"),
            None,
            None,
            &[],
            "restart_required",
            &["PROJECT_SERVICE_OTEL_EXPORTER_OTLP_ENDPOINT"],
            358,
            &now,
        ),
        definition(
            PROJECT_SERVICE_OTLP_TRACE_SAMPLE_RATIO_CONFIG_KEY,
            "Trace Sample Ratio",
            "Project Service 根链路按 Trace ID 采样的比例",
            "Project Service / Observability",
            "service",
            Some("project-service"),
            "number",
            json!(0.1),
            Some(0),
            Some(1),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_OTEL_TRACE_SAMPLE_RATIO"],
            359,
            &now,
        ),
        definition(
            PROJECT_SERVICE_OTLP_EXPORT_TIMEOUT_MS_CONFIG_KEY,
            "OTLP Export Timeout",
            "Project Service 导出一批 trace 的超时毫秒数",
            "Project Service / Observability",
            "service",
            Some("project-service"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(60_000),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_OTEL_EXPORT_TIMEOUT_MS"],
            360,
            &now,
        ),
        definition(
            PROJECT_SERVICE_HOST_CONFIG_KEY,
            "Host",
            "Project Service HTTP 服务监听地址",
            "Project Service / Runtime",
            "service",
            Some("project-service"),
            "string",
            json!("127.0.0.1"),
            None,
            None,
            &[],
            "restart_required",
            &["PROJECT_SERVICE_HOST"],
            357,
            &now,
        ),
        definition(
            PROJECT_SERVICE_PORT_CONFIG_KEY,
            "Port",
            "Project Service HTTP 服务监听端口",
            "Project Service / Runtime",
            "service",
            Some("project-service"),
            "integer",
            json!(39210),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_PORT"],
            357,
            &now,
        ),
        definition(
            PROJECT_SERVICE_INTERNAL_MTLS_PORT_CONFIG_KEY,
            "Internal mTLS Port",
            "Project Service 内部接口强制 mTLS 监听端口",
            "Project Service / Runtime Security",
            "service",
            Some("project-service"),
            "integer",
            json!(39212),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_INTERNAL_MTLS_PORT"],
            358,
            &now,
        ),
        secret_definition(
            PROJECT_SERVICE_DATABASE_URL_CONFIG_KEY,
            "Database URL",
            "Project Service 连接 MongoDB 使用的连接串",
            "Project Service / Runtime",
            "service",
            Some("project-service"),
            json!(
                "mongodb://admin:admin@127.0.0.1:27018/project_management_service?authSource=admin"
            ),
            "restart_required",
            &["PROJECT_SERVICE_DATABASE_URL"],
            357,
            &now,
        ),
        definition(
            PROJECT_SERVICE_MCP_RESULT_RABBITMQ_URL_CONFIG_KEY,
            "MCP Result RabbitMQ URL",
            "Project Service 消费 MCP 异步调用结果事件使用的 AMQP 地址",
            "Project Service / MCP Queue",
            "service",
            Some("project-service"),
            "string",
            json!(DEFAULT_LOCAL_RABBITMQ_URL),
            None,
            None,
            &[],
            "restart_required",
            &["PROJECT_SERVICE_MCP_RESULT_RABBITMQ_URL"],
            357,
            &now,
        ),
        definition(
            PROJECT_SERVICE_MCP_RESULT_QUEUE_PREFIX_CONFIG_KEY,
            "MCP Result Queue Prefix",
            "Project Service 按实例创建 MCP 异步结果消费队列使用的名称前缀",
            "Project Service / MCP Queue",
            "service",
            Some("project-service"),
            "string",
            json!("project_service.mcp.results"),
            None,
            None,
            &[],
            "restart_required",
            &["PROJECT_SERVICE_MCP_RESULT_QUEUE_PREFIX"],
            357,
            &now,
        ),
        definition(
            PROJECT_SERVICE_USER_SERVICE_BASE_URL_CONFIG_KEY,
            "User Service Base URL",
            "Project Service 调用 User Service 时使用的基础地址",
            "Project Service / Downstream",
            "service",
            Some("project-service"),
            "string",
            json!("http://127.0.0.1:39190"),
            None,
            None,
            &[],
            "restart_required",
            &["PROJECT_SERVICE_USER_SERVICE_BASE_URL"],
            358,
            &now,
        ),
        definition(
            PROJECT_SERVICE_USER_SERVICE_INTERNAL_BASE_URL_CONFIG_KEY,
            "User Service Internal Base URL",
            "Project Service 调用 User Service 内部接口时使用的强制 mTLS 地址",
            "Project Service / Downstream Security",
            "service",
            Some("project-service"),
            "string",
            json!("https://user-service-backend:39192"),
            None,
            None,
            &[],
            "restart_required",
            &["PROJECT_SERVICE_USER_SERVICE_INTERNAL_BASE_URL"],
            358,
            &now,
        ),
        definition(
            PROJECT_SERVICE_USER_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "User Service Request Timeout",
            "Project Service 调用 User Service 时使用的请求超时毫秒数",
            "Project Service / Downstream",
            "service",
            Some("project-service"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_USER_SERVICE_REQUEST_TIMEOUT_MS"],
            359,
            &now,
        ),
        secret_definition(
            PROJECT_SERVICE_TASK_RUNNER_INTERNAL_SECRET_CONFIG_KEY,
            "Task Runner Internal Secret",
            "Project Service 调用 Task Runner 内部接口时使用的共享密钥",
            "Project Service / Downstream Security",
            "service",
            Some("project-service"),
            json!("change_me_project_service_task_runner_secret"),
            "restart_required",
            &["PROJECT_SERVICE_TASK_RUNNER_INTERNAL_SECRET"],
            360,
            &now,
        ),
        definition(
            PROJECT_SERVICE_TASK_RUNNER_BASE_URL_CONFIG_KEY,
            "Task Runner Base URL",
            "Project Service 调用 Task Runner 时使用的基础地址",
            "Project Service / Downstream",
            "service",
            Some("project-service"),
            "string",
            json!("https://task-runner-backend:39092"),
            None,
            None,
            &[],
            "restart_required",
            &["PROJECT_SERVICE_TASK_RUNNER_BASE_URL"],
            361,
            &now,
        ),
        definition(
            PROJECT_SERVICE_TASK_RUNNER_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Task Runner Request Timeout",
            "Project Service 调用 Task Runner 时使用的请求超时毫秒数",
            "Project Service / Downstream",
            "service",
            Some("project-service"),
            "duration_ms",
            json!(10_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_TASK_RUNNER_REQUEST_TIMEOUT_MS"],
            362,
            &now,
        ),
        secret_definition(
            PROJECT_SERVICE_SYNC_SECRET_CONFIG_KEY,
            "Project Sync Secret",
            "Project Service 校验旧版 Task Runner 同步调用时使用的共享密钥",
            "Project Service / Security",
            "service",
            Some("project-service"),
            json!("change_me_project_sync_secret"),
            "restart_required",
            &["PROJECT_SERVICE_SYNC_SECRET"],
            363,
            &now,
        ),
        definition(
            PROJECT_SERVICE_LOCAL_CONNECTOR_SERVICE_BASE_URL_CONFIG_KEY,
            "Local Connector Service Base URL",
            "Project Service 调用 Local Connector 时使用的基础地址",
            "Project Service / Downstream",
            "service",
            Some("project-service"),
            "string",
            json!("https://127.0.0.1:39232"),
            None,
            None,
            &[],
            "restart_required",
            &["PROJECT_SERVICE_LOCAL_CONNECTOR_SERVICE_BASE_URL"],
            364,
            &now,
        ),
        definition(
            PROJECT_SERVICE_LOCAL_CONNECTOR_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Local Connector Request Timeout",
            "Project Service 调用 Local Connector 时使用的请求超时毫秒数",
            "Project Service / Downstream",
            "service",
            Some("project-service"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_LOCAL_CONNECTOR_SERVICE_REQUEST_TIMEOUT_MS"],
            365,
            &now,
        ),
        definition(
            PROJECT_SERVICE_MEMORY_ENGINE_BASE_URL_CONFIG_KEY,
            "Memory Engine Base URL",
            "Project Service 调用 Memory Engine 时使用的基础地址",
            "Project Service / Downstream",
            "service",
            Some("project-service"),
            "string",
            json!("https://memory-engine-backend:7083/api/memory-engine/v1"),
            None,
            None,
            &[],
            "restart_required",
            &["PROJECT_SERVICE_MEMORY_ENGINE_BASE_URL"],
            366,
            &now,
        ),
        secret_definition(
            PROJECT_SERVICE_MEMORY_ENGINE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Memory Engine Internal Secret",
            "Project Service 签发 Memory Engine 内部短期 token 时使用的调用方专属密钥",
            "Project Service / Downstream Security",
            "service",
            Some("project-service"),
            json!("change_me_project_service_memory_engine_secret"),
            "restart_required",
            &["PROJECT_SERVICE_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            367,
            &now,
        ),
        definition(
            PROJECT_SERVICE_MEMORY_ENGINE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Memory Engine Request Timeout",
            "Project Service 调用 Memory Engine 时使用的请求超时毫秒数",
            "Project Service / Downstream",
            "service",
            Some("project-service"),
            "duration_ms",
            json!(30_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_MEMORY_ENGINE_REQUEST_TIMEOUT_MS"],
            368,
            &now,
        ),
        definition(
            PROJECT_SERVICE_SANDBOX_MANAGER_BASE_URL_CONFIG_KEY,
            "Sandbox Manager Base URL",
            "Project Service 调用 Sandbox Manager 时使用的基础地址",
            "Project Service / Downstream",
            "service",
            Some("project-service"),
            "string",
            json!("https://sandbox-manager-backend:8097"),
            None,
            None,
            &[],
            "restart_required",
            &["PROJECT_SERVICE_SANDBOX_MANAGER_BASE_URL"],
            369,
            &now,
        ),
        definition(
            PROJECT_SERVICE_SANDBOX_MANAGER_CLIENT_ID_CONFIG_KEY,
            "Sandbox Manager Client ID",
            "Project Service 调用 Sandbox Manager 内部接口时使用的 client id",
            "Project Service / Downstream Security",
            "service",
            Some("project-service"),
            "string",
            json!("project-service"),
            None,
            None,
            &[],
            "restart_required",
            &["PROJECT_SERVICE_SANDBOX_MANAGER_CLIENT_ID"],
            370,
            &now,
        ),
        secret_definition(
            PROJECT_SERVICE_SANDBOX_MANAGER_CLIENT_KEY_CONFIG_KEY,
            "Sandbox Manager Client Key",
            "Project Service 调用 Sandbox Manager 内部接口时使用的 client key",
            "Project Service / Downstream Security",
            "service",
            Some("project-service"),
            json!("change_me_project_service_sandbox_manager_secret"),
            "restart_required",
            &["PROJECT_SERVICE_SANDBOX_MANAGER_CLIENT_KEY"],
            371,
            &now,
        ),
        definition(
            PROJECT_SERVICE_SANDBOX_IMAGE_MCP_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Sandbox Image MCP Request Timeout",
            "Project Service 通过 Sandbox Manager / 镜像 MCP 执行长耗时镜像操作时的超时毫秒数",
            "Project Service / Downstream",
            "service",
            Some("project-service"),
            "duration_ms",
            json!(2 * 60 * 60 * 1_000),
            Some(10_000),
            Some(3 * 60 * 60 * 1_000),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_SANDBOX_IMAGE_MCP_REQUEST_TIMEOUT_MS"],
            372,
            &now,
        ),
        definition(
            PROJECT_SERVICE_CLOUD_PROJECT_IMPORT_ENABLED_CONFIG_KEY,
            "启用云项目导入",
            "Project Service 是否允许创建和导入云端项目",
            "Project Service / Cloud Import",
            "service",
            Some("project-service"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["PROJECT_SERVICE_CLOUD_PROJECT_IMPORT_ENABLED"],
            373,
            &now,
        ),
        definition(
            PROJECT_SERVICE_CLOUD_PROJECT_MAX_ZIP_BYTES_CONFIG_KEY,
            "云项目 Zip 大小上限",
            "Project Service 接收云项目压缩包时允许的最大字节数",
            "Project Service / Cloud Import",
            "service",
            Some("project-service"),
            "integer",
            json!(200 * 1024 * 1024),
            Some(1),
            Some(100 * 1024 * 1024 * 1024),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_CLOUD_PROJECT_MAX_ZIP_BYTES"],
            373,
            &now,
        ),
        definition(
            PROJECT_SERVICE_CLOUD_PROJECT_MAX_UNPACKED_BYTES_CONFIG_KEY,
            "云项目解包大小上限",
            "Project Service 解包云项目后允许的最大总字节数",
            "Project Service / Cloud Import",
            "service",
            Some("project-service"),
            "integer",
            json!(1024 * 1024 * 1024),
            Some(1),
            Some(500 * 1024 * 1024 * 1024),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_CLOUD_PROJECT_MAX_UNPACKED_BYTES"],
            373,
            &now,
        ),
        definition(
            PROJECT_SERVICE_CLOUD_PROJECT_MAX_FILES_CONFIG_KEY,
            "云项目文件数上限",
            "Project Service 导入云项目时允许的最大文件数",
            "Project Service / Cloud Import",
            "service",
            Some("project-service"),
            "integer",
            json!(20_000),
            Some(1),
            Some(10_000_000),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_CLOUD_PROJECT_MAX_FILES"],
            373,
            &now,
        ),
        definition(
            PROJECT_SERVICE_CLOUD_PROJECT_GIT_TIMEOUT_MS_CONFIG_KEY,
            "Cloud Project Git Timeout",
            "Project Service 进行云端项目导入和 Git 拉取时使用的超时毫秒数",
            "Project Service / Cloud Import",
            "service",
            Some("project-service"),
            "duration_ms",
            json!(120_000),
            Some(1_000),
            Some(3_600_000),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_CLOUD_PROJECT_GIT_TIMEOUT_MS"],
            373,
            &now,
        ),
        definition(
            PROJECT_SERVICE_ENVIRONMENT_ANALYSIS_TIMEOUT_MS_CONFIG_KEY,
            "Environment Analysis Timeout",
            "Project Service 单次项目运行环境分析允许执行的最长毫秒数，超时后任务失败关闭",
            "Project Service / Environment Analysis",
            "service",
            Some("project-service"),
            "duration_ms",
            json!(30 * 60 * 1_000),
            Some(60_000),
            Some(3 * 60 * 60 * 1_000),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_ENVIRONMENT_ANALYSIS_TIMEOUT_MS"],
            374,
            &now,
        ),
        definition(
            PROJECT_SERVICE_ENVIRONMENT_ANALYSIS_STALE_AFTER_MS_CONFIG_KEY,
            "Environment Analysis Stale Threshold",
            "Project Service 判定持久化环境分析状态已失去执行者并转为失败的最大静默毫秒数",
            "Project Service / Environment Analysis",
            "service",
            Some("project-service"),
            "duration_ms",
            json!(35 * 60 * 1_000),
            Some(60_000),
            Some(4 * 60 * 60 * 1_000),
            &[],
            "restart_required",
            &["PROJECT_SERVICE_ENVIRONMENT_ANALYSIS_STALE_AFTER_MS"],
            375,
            &now,
        ),
        definition(
            CONFIGURATION_CENTER_MEMORY_ENGINE_BASE_URL_CONFIG_KEY,
            "Memory Engine Base URL",
            "Configuration Center 执行队列运维操作时调用 Memory Engine 的内部地址",
            "Configuration Center / Downstream",
            "service",
            Some("configuration-center"),
            "string",
            json!("https://memory-engine-backend:7083/api/memory-engine/v1"),
            None,
            None,
            &[],
            "immediate",
            &["CONFIGURATION_CENTER_MEMORY_ENGINE_BASE_URL"],
            357,
            &now,
        ),
        definition(
            CONFIGURATION_CENTER_PLUGIN_MANAGEMENT_BASE_URL_CONFIG_KEY,
            "Plugin Management Base URL",
            "Configuration Center 执行队列运维操作时调用 Plugin Management 的内部地址",
            "Configuration Center / Downstream",
            "service",
            Some("configuration-center"),
            "string",
            json!("http://127.0.0.1:9080/api/plugin"),
            None,
            None,
            &[],
            "immediate",
            &[],
            358,
            &now,
        ),
        definition(
            CONFIGURATION_CENTER_MCP_MANAGEMENT_BASE_URL_CONFIG_KEY,
            "MCP Management Base URL",
            "Configuration Center 执行队列运维操作时调用 MCP Management 的内部地址",
            "Configuration Center / Downstream",
            "service",
            Some("configuration-center"),
            "string",
            json!("https://mcp-management-service-backend:39282"),
            None,
            None,
            &[],
            "immediate",
            &["CONFIGURATION_CENTER_MCP_MANAGEMENT_BASE_URL"],
            359,
            &now,
        ),
        secret_definition(
            CONFIGURATION_CENTER_MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "MCP Management Internal Secret",
            "Configuration Center 调用 MCP Management 队列运维接口时使用的专用签名密钥",
            "Configuration Center / Downstream Security",
            "service",
            Some("configuration-center"),
            json!("change_me_configuration_center_mcp_management_secret"),
            "immediate",
            &[],
            3591,
            &now,
        ),
    ]
}
