use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            SANDBOX_MANAGER_POOL_MAX_ACTIVE_CONFIG_KEY,
            "沙箱池活跃上限",
            "Sandbox Manager 全局同时活跃的沙箱租约上限；与 Task Runner Worker 并发是两层独立限制",
            "Sandbox Manager / Pool",
            "service",
            Some("sandbox-manager"),
            "integer",
            json!(5),
            Some(1),
            Some(1024),
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_POOL_MAX_ACTIVE"],
            300,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_POOL_MAX_PENDING_CONFIG_KEY,
            "沙箱池排队上限",
            "Sandbox Manager 自身等待沙箱租约的请求上限；不包含仍在 Task Runner 队列中的 Run",
            "Sandbox Manager / Pool",
            "service",
            Some("sandbox-manager"),
            "integer",
            json!(50),
            Some(0),
            Some(100_000),
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_POOL_MAX_PENDING"],
            310,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_LEASE_TTL_SECONDS_CONFIG_KEY,
            "沙箱租约 TTL（秒）",
            "Sandbox Manager 默认发放给沙箱租约的时长，超时后可回收",
            "Sandbox Manager / Pool",
            "service",
            Some("sandbox-manager"),
            "integer",
            json!(7_200),
            Some(60),
            Some(86_400),
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_LEASE_TTL_SECONDS"],
            311,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_CLEANUP_INTERVAL_SECONDS_CONFIG_KEY,
            "清理轮询间隔（秒）",
            "Sandbox Manager 清理过期租约和失效环境的轮询间隔",
            "Sandbox Manager / Pool",
            "service",
            Some("sandbox-manager"),
            "integer",
            json!(30),
            Some(5),
            Some(3600),
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_CLEANUP_INTERVAL_SECONDS"],
            312,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_DOCKER_MAINTENANCE_ENABLED_CONFIG_KEY,
            "启用 Docker 维护",
            "Sandbox Manager 是否执行 Docker 构建缓存清理等后台维护任务",
            "Sandbox Manager / Docker",
            "service",
            Some("sandbox-manager"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_DOCKER_MAINTENANCE_ENABLED"],
            313,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_DOCKER_BUILD_CACHE_MAX_USED_SPACE_CONFIG_KEY,
            "Docker 构建缓存最大使用量",
            "Sandbox Manager 触发 Docker 构建缓存维护时允许保留的最大缓存占用，例如 32gb",
            "Sandbox Manager / Docker",
            "service",
            Some("sandbox-manager"),
            "string",
            json!("32gb"),
            None,
            None,
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_DOCKER_BUILD_CACHE_MAX_USED_SPACE"],
            314,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_DOCKER_BUILD_CACHE_RESERVED_SPACE_CONFIG_KEY,
            "Docker 构建缓存保留空间",
            "Sandbox Manager 触发 Docker 构建缓存维护时希望额外保留的空间，例如 8gb",
            "Sandbox Manager / Docker",
            "service",
            Some("sandbox-manager"),
            "string",
            json!("8gb"),
            None,
            None,
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_DOCKER_BUILD_CACHE_RESERVED_SPACE"],
            315,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_DOCKER_BUILD_CACHE_TIMEOUT_SECS_CONFIG_KEY,
            "Docker 构建缓存维护超时（秒）",
            "Sandbox Manager 执行 Docker 构建缓存维护命令时的超时秒数",
            "Sandbox Manager / Docker",
            "service",
            Some("sandbox-manager"),
            "integer",
            json!(180),
            Some(30),
            Some(86_400),
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_DOCKER_BUILD_CACHE_TIMEOUT_SECS"],
            316,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_HOST_CONFIG_KEY,
            "Host",
            "Sandbox Manager HTTP 服务监听地址",
            "Sandbox Manager / Runtime",
            "service",
            Some("sandbox-manager"),
            "string",
            json!("127.0.0.1"),
            None,
            None,
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_HOST"],
            316,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_PORT_CONFIG_KEY,
            "Port",
            "Sandbox Manager HTTP 服务监听端口",
            "Sandbox Manager / Runtime",
            "service",
            Some("sandbox-manager"),
            "integer",
            json!(8095),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_PORT"],
            316,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_INTERNAL_MTLS_PORT_CONFIG_KEY,
            "Internal mTLS Port",
            "Sandbox Manager 内部控制面强制 mTLS 监听端口",
            "Sandbox Manager / Runtime",
            "service",
            Some("sandbox-manager"),
            "integer",
            json!(8097),
            Some(1),
            Some(65_535),
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_INTERNAL_MTLS_PORT"],
            3161,
            &now,
        ),
        secret_definition(
            SANDBOX_MANAGER_DATABASE_URL_CONFIG_KEY,
            "Database URL",
            "Sandbox Manager 连接 MongoDB 使用的连接串",
            "Sandbox Manager / Runtime",
            "service",
            Some("sandbox-manager"),
            json!("mongodb://admin:admin@127.0.0.1:27018/sandbox_manager_service?authSource=admin"),
            "restart_required",
            &["SANDBOX_MANAGER_DATABASE_URL"],
            316,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_MONGODB_DATABASE_CONFIG_KEY,
            "MongoDB Database",
            "Sandbox Manager 当前使用的 MongoDB database 名称",
            "Sandbox Manager / Runtime",
            "service",
            Some("sandbox-manager"),
            "string",
            json!("sandbox_manager_service"),
            None,
            None,
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_MONGODB_DATABASE"],
            316,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_AGENT_PORT_CONFIG_KEY,
            "Agent Port",
            "Sandbox Manager 为沙箱内 agent 暴露的端口",
            "Sandbox Manager / Runtime",
            "service",
            Some("sandbox-manager"),
            "integer",
            json!(49_888),
            Some(0),
            Some(65535),
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_AGENT_PORT"],
            316,
            &now,
        ),
    ]
}
