use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            "shared.logging.level",
            "日志级别",
            "服务默认日志级别",
            "日志",
            "shared",
            None,
            "enum",
            json!("info"),
            None,
            None,
            &["trace", "debug", "info", "warn", "error"],
            "restart_required",
            &["LOG_LEVEL"],
            30,
            now,
        ),
        definition(
            PLATFORM_PRESSURE_LEVEL_CONFIG_KEY,
            "平台压力等级",
            "配置中心发布的权威平台压力状态；业务服务不得自行窥探其他服务队列推断全局压力",
            "Platform / Pressure",
            "shared",
            None,
            "enum",
            json!("normal"),
            None,
            None,
            &["normal", "elevated", "critical"],
            "hot_reload",
            &[],
            40,
            now,
        ),
        definition(
            PLATFORM_PRESSURE_CONTROLLER_ENABLED_CONFIG_KEY,
            "启用自动压力控制器",
            "由配置中心聚合服务压力信号并自动发布权威平台压力等级",
            "Platform / Pressure",
            "shared",
            None,
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "hot_reload",
            &[],
            41,
            now,
        ),
        definition(
            PLATFORM_PRESSURE_CONTROLLER_INTERVAL_MS_CONFIG_KEY,
            "压力控制器检查间隔",
            "配置中心重新聚合服务压力信号的间隔",
            "Platform / Pressure",
            "shared",
            None,
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(60_000),
            &[],
            "hot_reload",
            &[],
            42,
            now,
        ),
        definition(
            PLATFORM_PRESSURE_SIGNAL_TTL_SECONDS_CONFIG_KEY,
            "压力信号有效期",
            "超过该时间未更新的服务压力信号不参与平台压力判定",
            "Platform / Pressure",
            "shared",
            None,
            "integer",
            json!(30),
            Some(5),
            Some(600),
            &[],
            "hot_reload",
            &[],
            43,
            now,
        ),
        definition(
            PLATFORM_PRESSURE_ESCALATION_STABLE_SECONDS_CONFIG_KEY,
            "压力升级稳定窗口",
            "候选压力等级持续达到该时间后才升级权威等级",
            "Platform / Pressure",
            "shared",
            None,
            "integer",
            json!(5),
            Some(0),
            Some(300),
            &[],
            "hot_reload",
            &[],
            44,
            now,
        ),
        definition(
            PLATFORM_PRESSURE_RECOVERY_STABLE_SECONDS_CONFIG_KEY,
            "压力恢复稳定窗口",
            "候选压力下降持续达到该时间后才降低权威等级，避免抖动",
            "Platform / Pressure",
            "shared",
            None,
            "integer",
            json!(60),
            Some(5),
            Some(3_600),
            &[],
            "hot_reload",
            &[],
            45,
            now,
        ),
        definition(
            AGENT_MAX_ITERATIONS_CONFIG_KEY,
            "Agent 最大迭代次数",
            "所有系统 Agent 单次执行的模型工具循环迭代上限",
            "Agent / Runtime",
            "shared",
            None,
            "integer",
            json!(DEFAULT_AGENT_MAX_ITERATIONS),
            Some(1),
            Some(5000),
            &[],
            "next_request",
            &[],
            100,
            now,
        ),
        definition(
            AGENT_MAX_REQUEST_RETRIES_CONFIG_KEY,
            "Agent 单次请求重试次数",
            "本机 Agent 单次模型请求遇到可重试故障时的最大重试次数",
            "Agent / Runtime",
            "shared",
            None,
            "integer",
            json!(DEFAULT_AGENT_MAX_REQUEST_RETRIES),
            Some(0),
            Some(10),
            &[],
            "next_run",
            &[],
            110,
            now,
        ),
        definition(
            AGENT_REQUEST_TIMEOUT_SECONDS_CONFIG_KEY,
            "Agent 流式静默超时",
            "本机 Agent 等待模型首包或相邻流式数据块的最长秒数",
            "Agent / Runtime",
            "shared",
            None,
            "integer",
            json!(DEFAULT_AGENT_REQUEST_TIMEOUT_SECONDS),
            Some(5),
            Some(1_800),
            &[],
            "next_run",
            &[],
            111,
            now,
        ),
        definition(
            AGENT_RUN_TIMEOUT_SECONDS_CONFIG_KEY,
            "Agent 整次运行时限",
            "本机 Agent 单次运行的绝对时限秒数",
            "Agent / Runtime",
            "shared",
            None,
            "integer",
            json!(DEFAULT_AGENT_RUN_TIMEOUT_SECONDS),
            Some(10),
            Some(86_400),
            &[],
            "next_run",
            &[],
            112,
            now,
        ),
        definition(
            AGENT_MAX_NO_PROGRESS_ROUNDS_CONFIG_KEY,
            "Agent 无进展暂停阈值",
            "本机 Agent 连续没有产生进展达到该轮数时暂停运行",
            "Agent / Runtime",
            "shared",
            None,
            "integer",
            json!(DEFAULT_AGENT_MAX_NO_PROGRESS_ROUNDS),
            Some(1),
            Some(100),
            &[],
            "next_run",
            &[],
            113,
            now,
        ),
        definition(
            AGENT_CONTEXT_WINDOW_TOKENS_CONFIG_KEY,
            "Agent 上下文窗口预算",
            "本机 Agent 开始或恢复运行时允许使用的上下文 token 预算",
            "Agent / Runtime",
            "shared",
            None,
            "integer",
            json!(DEFAULT_AGENT_CONTEXT_WINDOW_TOKENS),
            Some(2_048),
            Some(2_000_000),
            &[],
            "next_run",
            &[],
            114,
            now,
        ),
        definition(
            AGENT_OUTPUT_RESERVE_TOKENS_CONFIG_KEY,
            "Agent 输出预留 Token",
            "本机 Agent 为单次模型输出预留的 token 数量，必须小于上下文窗口预算",
            "Agent / Runtime",
            "shared",
            None,
            "integer",
            json!(DEFAULT_AGENT_OUTPUT_RESERVE_TOKENS),
            Some(256),
            Some(1_999_999),
            &[],
            "next_run",
            &[],
            115,
            now,
        ),
        definition(
            LOCAL_TASK_EXECUTION_MAX_ITERATIONS_CONFIG_KEY,
            "本地任务执行最大迭代次数",
            "Local Agent Host 的任务执行 profile 单次模型工具循环迭代上限",
            "Local Agent / Task Execution",
            "shared",
            None,
            "integer",
            json!(DEFAULT_LOCAL_TASK_EXECUTION_MAX_ITERATIONS),
            Some(2),
            Some(5_000),
            &[],
            "next_run",
            &[],
            120,
            now,
        ),
        definition(
            LOCAL_TASK_EXECUTION_REVIEW_READ_ONLY_ITERATIONS_CONFIG_KEY,
            "只读迭代检查阈值",
            "本地任务连续只读迭代达到该次数后触发进展检查",
            "Local Agent / Task Execution",
            "shared",
            None,
            "integer",
            json!(DEFAULT_LOCAL_TASK_EXECUTION_REVIEW_READ_ONLY_ITERATIONS),
            Some(1),
            Some(100),
            &[],
            "next_run",
            &[],
            121,
            now,
        ),
        definition(
            LOCAL_TASK_EXECUTION_REVIEW_MISSING_READ_FAILURES_CONFIG_KEY,
            "缺少目标读取检查阈值",
            "本地任务缺少目标文件读取达到该次数后触发进展检查",
            "Local Agent / Task Execution",
            "shared",
            None,
            "integer",
            json!(DEFAULT_LOCAL_TASK_EXECUTION_REVIEW_MISSING_READ_FAILURES),
            Some(1),
            Some(100),
            &[],
            "next_run",
            &[],
            122,
            now,
        ),
        definition(
            LOCAL_TASK_EXECUTION_REVIEW_REPEAT_INTERVAL_CONFIG_KEY,
            "重复检查间隔",
            "本地任务持续无进展时再次触发检查前的迭代间隔",
            "Local Agent / Task Execution",
            "shared",
            None,
            "integer",
            json!(DEFAULT_LOCAL_TASK_EXECUTION_REVIEW_REPEAT_INTERVAL),
            Some(1),
            Some(100),
            &[],
            "next_run",
            &[],
            123,
            now,
        ),
        definition(
            LOCAL_TASK_EXECUTION_PROMPT_CACHE_ENABLED_CONFIG_KEY,
            "启用本地任务 Prompt Cache",
            "允许 Local Agent Host 的任务执行 profile 使用模型 Prompt Cache",
            "Local Agent / Task Execution",
            "shared",
            None,
            "boolean",
            json!(DEFAULT_LOCAL_TASK_EXECUTION_PROMPT_CACHE_ENABLED),
            None,
            None,
            &[],
            "next_run",
            &[],
            124,
            now,
        ),
        definition(
            LOCAL_TASK_EXECUTION_PROMPT_CACHE_RETENTION_ENABLED_CONFIG_KEY,
            "保留本地任务 Prompt Cache",
            "允许 Local Agent Host 在任务继续执行时复用 Prompt Cache",
            "Local Agent / Task Execution",
            "shared",
            None,
            "boolean",
            json!(DEFAULT_LOCAL_TASK_EXECUTION_PROMPT_CACHE_RETENTION_ENABLED),
            None,
            None,
            &[],
            "next_run",
            &[],
            125,
            now,
        ),
        definition(
            SHARED_PLUGIN_MANAGEMENT_SERVICE_URL_CONFIG_KEY,
            "Plugin Management Public Service URL",
            "内部服务调用 Plugin Management 用户 Bearer API 时使用的公网监听地址",
            "Shared / Downstream",
            "shared",
            None,
            "string",
            json!("http://127.0.0.1:39260"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_URL"],
            101,
            now,
        ),
        definition(
            SHARED_PLUGIN_MANAGEMENT_SERVICE_INTERNAL_URL_CONFIG_KEY,
            "Plugin Management Internal Service URL",
            "内部服务调用 Plugin Management 控制面时使用的强制 mTLS 地址",
            "Shared / Downstream",
            "shared",
            None,
            "string",
            json!("https://plugin-management-backend:39262"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_INTERNAL_URL"],
            1011,
            now,
        ),
        definition(
            SHARED_PLUGIN_MANAGEMENT_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Plugin Management Request Timeout",
            "内部服务调用 Plugin Management 时使用的请求超时毫秒数",
            "Shared / Downstream",
            "shared",
            None,
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_REQUEST_TIMEOUT_MS"],
            102,
            now,
        ),
    ]
}
