use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            "shared.logging.level",
            "日志级别",
            "服务默认日志级别",
            "日志",
            "shared",
            None,
            "enum",
            json!("info"),
            None,
            None,
            &["trace", "debug", "info", "warn", "error"],
            "restart_required",
            &["LOG_LEVEL"],
            30,
            &now,
        ),
        definition(
            PLATFORM_PRESSURE_LEVEL_CONFIG_KEY,
            "平台压力等级",
            "配置中心发布的权威平台压力状态；业务服务不得自行窥探其他服务队列推断全局压力",
            "Platform / Pressure",
            "shared",
            None,
            "enum",
            json!("normal"),
            None,
            None,
            &["normal", "elevated", "critical"],
            "hot_reload",
            &[],
            40,
            &now,
        ),
        definition(
            PLATFORM_PRESSURE_CONTROLLER_ENABLED_CONFIG_KEY,
            "启用自动压力控制器",
            "由配置中心聚合服务压力信号并自动发布权威平台压力等级",
            "Platform / Pressure",
            "shared",
            None,
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "hot_reload",
            &[],
            41,
            &now,
        ),
        definition(
            PLATFORM_PRESSURE_CONTROLLER_INTERVAL_MS_CONFIG_KEY,
            "压力控制器检查间隔",
            "配置中心重新聚合服务压力信号的间隔",
            "Platform / Pressure",
            "shared",
            None,
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(60_000),
            &[],
            "hot_reload",
            &[],
            42,
            &now,
        ),
        definition(
            PLATFORM_PRESSURE_SIGNAL_TTL_SECONDS_CONFIG_KEY,
            "压力信号有效期",
            "超过该时间未更新的服务压力信号不参与平台压力判定",
            "Platform / Pressure",
            "shared",
            None,
            "integer",
            json!(30),
            Some(5),
            Some(600),
            &[],
            "hot_reload",
            &[],
            43,
            &now,
        ),
        definition(
            PLATFORM_PRESSURE_ESCALATION_STABLE_SECONDS_CONFIG_KEY,
            "压力升级稳定窗口",
            "候选压力等级持续达到该时间后才升级权威等级",
            "Platform / Pressure",
            "shared",
            None,
            "integer",
            json!(5),
            Some(0),
            Some(300),
            &[],
            "hot_reload",
            &[],
            44,
            &now,
        ),
        definition(
            PLATFORM_PRESSURE_RECOVERY_STABLE_SECONDS_CONFIG_KEY,
            "压力恢复稳定窗口",
            "候选压力下降持续达到该时间后才降低权威等级，避免抖动",
            "Platform / Pressure",
            "shared",
            None,
            "integer",
            json!(60),
            Some(5),
            Some(3_600),
            &[],
            "hot_reload",
            &[],
            45,
            &now,
        ),
        definition(
            AGENT_MAX_ITERATIONS_CONFIG_KEY,
            "Agent 最大迭代次数",
            "所有系统 Agent 单次执行的模型工具循环迭代上限",
            "Agent / Runtime",
            "shared",
            None,
            "integer",
            json!(DEFAULT_AGENT_MAX_ITERATIONS),
            Some(1),
            Some(5000),
            &[],
            "next_request",
            &[],
            100,
            &now,
        ),
        definition(
            SHARED_PLUGIN_MANAGEMENT_SERVICE_URL_CONFIG_KEY,
            "Plugin Management Public Service URL",
            "内部服务调用 Plugin Management 用户 Bearer API 时使用的公网监听地址",
            "Shared / Downstream",
            "shared",
            None,
            "string",
            json!("http://127.0.0.1:39260"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_URL"],
            101,
            &now,
        ),
        definition(
            SHARED_PLUGIN_MANAGEMENT_SERVICE_INTERNAL_URL_CONFIG_KEY,
            "Plugin Management Internal Service URL",
            "内部服务调用 Plugin Management 控制面时使用的强制 mTLS 地址",
            "Shared / Downstream",
            "shared",
            None,
            "string",
            json!("https://plugin-management-backend:39262"),
            None,
            None,
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_SERVICE_INTERNAL_URL"],
            1011,
            &now,
        ),
        definition(
            SHARED_PLUGIN_MANAGEMENT_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Plugin Management Request Timeout",
            "内部服务调用 Plugin Management 时使用的请求超时毫秒数",
            "Shared / Downstream",
            "shared",
            None,
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["PLUGIN_MANAGEMENT_REQUEST_TIMEOUT_MS"],
            102,
            &now,
        ),
        definition(
            SHARED_MCP_MANAGEMENT_SERVICE_BASE_URL_CONFIG_KEY,
            "MCP Management Internal Base URL",
            "内部服务调用 MCP Management 控制面时使用的强制 mTLS 地址",
            "Shared / Downstream",
            "shared",
            None,
            "string",
            json!("https://mcp-management-service-backend:39282"),
            None,
            None,
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_SERVICE_BASE_URL"],
            103,
            &now,
        ),
        definition(
            SHARED_MCP_MANAGEMENT_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "MCP Management Control Request Timeout",
            "内部服务调用 MCP Management 控制面接口的请求超时毫秒数",
            "Shared / Downstream",
            "shared",
            None,
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["MCP_MANAGEMENT_REQUEST_TIMEOUT_MS"],
            104,
            &now,
        ),
        definition(
            "chatos.ai.max_output_tokens",
            "最大输出 Tokens",
            "单次模型回复最大输出 Tokens，空值表示模型默认",
            "Chat OS / AI",
            "service",
            Some("chatos-backend"),
            "integer",
            Value::Null,
            Some(1),
            Some(1_000_000),
            &[],
            "next_request",
            &["CHAT_MAX_TOKENS"],
            110,
            &now,
        ),
        definition(
            "chatos.task.follow_up_max_rounds",
            "任务后置检查轮数",
            "任务准备结束时最多继续检查的轮数",
            "Chat OS / Task",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(3),
            Some(0),
            Some(100),
            &[],
            "next_request",
            &["TASK_FOLLOW_UP_MAX_ROUNDS"],
            120,
            &now,
        ),
        definition(
            "chatos.conversation.history_limit",
            "历史消息数量",
            "请求模型时读取的历史消息数量",
            "Chat OS / Conversation",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(20),
            Some(1),
            Some(1000),
            &[],
            "next_request",
            &["HISTORY_LIMIT"],
            130,
            &now,
        ),
        definition(
            "chatos.attachment.total_max_bytes",
            "附件总大小上限",
            "单次消息所有附件原始文件大小之和",
            "Chat OS / Attachment",
            "service",
            Some("chatos-backend"),
            "bytes",
            json!(20 * 1024 * 1024),
            Some(1),
            Some(1024 * 1024 * 1024),
            &[],
            "hot_reload",
            &["ATTACHMENT_TOTAL_MAX_BYTES"],
            140,
            &now,
        ),
        definition(
            "chatos.ui.terminal_enabled",
            "显示终端入口",
            "是否在 Chat OS 中显示终端菜单和视图",
            "Chat OS / UI",
            "service",
            Some("chatos-backend"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "hot_reload",
            &["TERMINAL_UI_ENABLED"],
            150,
            &now,
        ),
        definition(
            CHATOS_LOCAL_PROJECT_CREATION_CONFIG_KEY,
            "显示本地项目入口",
            "是否在 Chat OS 桌面端的新建项目界面显示 Local Connector 本地项目入口",
            "Chat OS / UI",
            "service",
            Some("chatos-backend"),
            "boolean",
            json!(false),
            None,
            None,
            &[],
            "hot_reload",
            &["LOCAL_PROJECT_CREATION_ENABLED"],
            160,
            &now,
        ),
        definition(
            CHATOS_NODE_ENV_CONFIG_KEY,
            "Node Env",
            "Chatos Backend 当前运行环境",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            "enum",
            json!("development"),
            None,
            None,
            &["development", "staging", "test", "production"],
            "restart_required",
            &["NODE_ENV"],
            160,
            &now,
        ),
        definition(
            CHATOS_HOST_CONFIG_KEY,
            "Host",
            "Chatos Backend HTTP 服务监听地址",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            "string",
            json!("0.0.0.0"),
            None,
            None,
            &[],
            "restart_required",
            &["HOST"],
            160,
            &now,
        ),
        definition(
            CHATOS_BACKEND_PORT_CONFIG_KEY,
            "Port",
            "Chatos Backend HTTP 服务监听端口",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(3997),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["BACKEND_PORT"],
            160,
            &now,
        ),
        definition(
            CHATOS_INTERNAL_MTLS_PORT_CONFIG_KEY,
            "Internal mTLS Port",
            "Chatos Backend 内部服务接口的强制 mTLS 监听端口",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(3999),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["CHATOS_INTERNAL_MTLS_PORT"],
            160,
            &now,
        ),
        secret_definition(
            CHATOS_DATABASE_URL_CONFIG_KEY,
            "Database URL",
            "Chatos Backend 主数据库 MongoDB 连接串",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            json!("mongodb://admin:admin@127.0.0.1:27017/chatos?authSource=admin"),
            "restart_required",
            &["MONGODB_CONNECTION_STRING"],
            161,
            &now,
        ),
        definition(
            CHATOS_MONGODB_DATABASE_CONFIG_KEY,
            "MongoDB Database",
            "Chatos Backend 主数据库名称",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            "string",
            json!("chatos"),
            None,
            None,
            &[],
            "restart_required",
            &["MONGODB_DB"],
            162,
            &now,
        ),
        secret_definition(
            CHATOS_LEGACY_AUTH_DATABASE_URL_CONFIG_KEY,
            "Legacy Auth Database URL",
            "Chatos Backend 迁移历史认证数据使用的 MongoDB 连接串",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            json!("mongodb://admin:admin@127.0.0.1:27017/admin?authSource=admin"),
            "restart_required",
            &["LEGACY_AUTH_MONGODB_URI"],
            163,
            &now,
        ),
        definition(
            CHATOS_LEGACY_AUTH_MONGODB_DATABASE_CONFIG_KEY,
            "Legacy Auth MongoDB Database",
            "Chatos Backend 历史认证数据所在数据库名称",
            "Chat OS / Runtime",
            "service",
            Some("chatos-backend"),
            "string",
            json!("legacy_auth"),
            None,
            None,
            &[],
            "restart_required",
            &["LEGACY_AUTH_MONGODB_DATABASE"],
            164,
            &now,
        ),
        definition(
            CHATOS_USER_SERVICE_BASE_URL_CONFIG_KEY,
            "User Service Base URL",
            "Chatos Backend 调用 User Service 时使用的基础地址",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "string",
            json!("http://127.0.0.1:39190"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_USER_SERVICE_BASE_URL"],
            161,
            &now,
        ),
        definition(
            CHATOS_USER_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "User Service Request Timeout",
            "Chatos Backend 调用 User Service 时使用的请求超时毫秒数",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["CHATOS_USER_SERVICE_REQUEST_TIMEOUT_MS"],
            162,
            &now,
        ),
        definition(
            CHATOS_PROJECT_SERVICE_BASE_URL_CONFIG_KEY,
            "Project Service Base URL",
            "Chatos Backend 调用 Project Service 时使用的基础地址",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "string",
            json!("http://127.0.0.1:39210"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_PROJECT_SERVICE_BASE_URL"],
            163,
            &now,
        ),
        definition(
            CHATOS_PROJECT_SERVICE_INTERNAL_BASE_URL_CONFIG_KEY,
            "Project Service Internal Base URL",
            "Chatos Backend 调用 Project Service 内部接口时使用的强制 mTLS 地址",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            "string",
            json!("https://project-management-backend:39212"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_PROJECT_SERVICE_INTERNAL_BASE_URL"],
            164,
            &now,
        ),
        definition(
            CHATOS_PROJECT_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Project Service Request Timeout",
            "Chatos Backend 调用 Project Service 内部接口时使用的请求超时毫秒数",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(30_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["CHATOS_PROJECT_SERVICE_REQUEST_TIMEOUT_MS"],
            164,
            &now,
        ),
        secret_definition(
            CHATOS_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Project Service Internal Secret",
            "Chatos Backend 调用 Project Service 内部接口时使用的共享密钥",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            json!("change_me_chatos_project_service_secret"),
            "restart_required",
            &["CHATOS_PROJECT_SERVICE_INTERNAL_API_SECRET"],
            165,
            &now,
        ),
        definition(
            CHATOS_TASK_RUNNER_BASE_URL_CONFIG_KEY,
            "Task Runner Base URL",
            "Chatos Backend 调用 Task Runner 时使用的基础地址",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "string",
            json!("http://127.0.0.1:39090"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_TASK_RUNNER_BASE_URL"],
            166,
            &now,
        ),
        definition(
            CHATOS_TASK_RUNNER_INTERNAL_BASE_URL_CONFIG_KEY,
            "Task Runner Internal Base URL",
            "Chatos Backend 调用 Task Runner 内部控制面时使用的强制 mTLS 地址",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            "string",
            json!("https://task-runner-backend:39092"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_TASK_RUNNER_INTERNAL_BASE_URL"],
            167,
            &now,
        ),
        secret_definition(
            CHATOS_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Task Runner Internal Secret",
            "Chatos Backend 调用 Task Runner 内部接口时使用的共享密钥",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            json!("change_me_chatos_task_runner_internal_secret"),
            "restart_required",
            &["CHATOS_TASK_RUNNER_INTERNAL_API_SECRET"],
            167,
            &now,
        ),
        definition(
            CHATOS_TASK_RUNNER_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Task Runner Request Timeout",
            "Chatos Backend 调用 Task Runner 时使用的请求超时毫秒数",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(30_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["CHATOS_TASK_RUNNER_REQUEST_TIMEOUT_MS"],
            168,
            &now,
        ),
        secret_definition(
            CHATOS_MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "MCP Management Internal Secret",
            "Chatos Backend 调用 MCP Management 内部接口时使用的共享密钥",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            json!("change_me_mcp_management_chatos_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_CHATOS_INTERNAL_API_SECRET"],
            169,
            &now,
        ),
        secret_definition(
            CHATOS_PLUGIN_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "Plugin Management Internal Secret",
            "Chatos Backend 调用 Plugin Management 内部接口时使用的专用密钥",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            json!("change_me_plugin_management_chatos_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_CHATOS_INTERNAL_API_SECRET"],
            169,
            &now,
        ),
        definition(
            CHATOS_LOCAL_CONNECTOR_SERVICE_BASE_URL_CONFIG_KEY,
            "Local Connector Service Base URL",
            "Chatos Backend 调用 Local Connector 时使用的基础地址",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "string",
            json!("https://127.0.0.1:39232"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_LOCAL_CONNECTOR_SERVICE_BASE_URL"],
            170,
            &now,
        ),
        secret_definition(
            CHATOS_LOCAL_CONNECTOR_INTERNAL_API_SECRET_CONFIG_KEY,
            "Local Connector Internal Secret",
            "Chatos Backend 调用 Local Connector 内部接口时使用的共享密钥",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            json!("change_me_chatos_local_connector_secret"),
            "restart_required",
            &["CHATOS_LOCAL_CONNECTOR_INTERNAL_API_SECRET"],
            171,
            &now,
        ),
        definition(
            CHATOS_LOCAL_CONNECTOR_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Local Connector Request Timeout",
            "Chatos Backend 调用 Local Connector 时使用的请求超时毫秒数",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(30_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["CHATOS_LOCAL_CONNECTOR_SERVICE_REQUEST_TIMEOUT_MS"],
            172,
            &now,
        ),
        definition(
            CHATOS_MEMORY_ENGINE_BASE_URL_CONFIG_KEY,
            "Memory Engine Base URL",
            "Chatos Backend 调用 Memory Engine 时使用的基础地址",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "string",
            json!("https://memory-engine-backend:7083/api/memory-engine/v1"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_MEMORY_ENGINE_BASE_URL"],
            173,
            &now,
        ),
        secret_definition(
            CHATOS_MEMORY_ENGINE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Memory Engine Internal Secret",
            "Chatos Backend 签发 Memory Engine 内部短期 token 时使用的调用方专属密钥",
            "Chat OS / Downstream Security",
            "service",
            Some("chatos-backend"),
            json!("change_me_chatos_memory_engine_secret"),
            "restart_required",
            &["CHATOS_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            174,
            &now,
        ),
        definition(
            CHATOS_MEMORY_ENGINE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Memory Engine Request Timeout",
            "Chatos Backend 调用 Memory Engine 时使用的请求超时毫秒数",
            "Chat OS / Downstream",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["CHATOS_MEMORY_ENGINE_REQUEST_TIMEOUT_MS"],
            175,
            &now,
        ),
        nullable_secret_definition(
            CHATOS_OPENAI_API_KEY_CONFIG_KEY,
            "OpenAI API Key",
            "Chatos Backend 默认模型调用使用的 OpenAI API Key，空值表示未配置全局密钥",
            "Chat OS / AI",
            "service",
            Some("chatos-backend"),
            Value::Null,
            "restart_required",
            &["OPENAI_API_KEY"],
            176,
            &now,
        ),
        definition(
            CHATOS_OPENAI_BASE_URL_CONFIG_KEY,
            "OpenAI Base URL",
            "Chatos Backend 默认模型调用使用的 OpenAI API 基础地址",
            "Chat OS / AI",
            "service",
            Some("chatos-backend"),
            "string",
            json!("https://api.openai.com/v1"),
            None,
            None,
            &[],
            "restart_required",
            &["OPENAI_BASE_URL"],
            177,
            &now,
        ),
        definition(
            CHATOS_SUMMARY_ENABLED_CONFIG_KEY,
            "摘要总开关",
            "是否启用会话摘要能力",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["SUMMARY_ENABLED"],
            178,
            &now,
        ),
        definition(
            CHATOS_SUMMARY_MESSAGE_LIMIT_CONFIG_KEY,
            "摘要消息阈值",
            "达到该消息数后才会触发摘要判断",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(40),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["SUMMARY_MESSAGE_LIMIT"],
            179,
            &now,
        ),
        definition(
            CHATOS_SUMMARY_MAX_CONTEXT_TOKENS_CONFIG_KEY,
            "摘要上下文上限",
            "摘要生成时允许送入模型的最大上下文 Tokens",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(6_000),
            Some(1),
            Some(10_000_000),
            &[],
            "restart_required",
            &["SUMMARY_MAX_CONTEXT_TOKENS"],
            180,
            &now,
        ),
        definition(
            CHATOS_SUMMARY_KEEP_LAST_N_CONFIG_KEY,
            "摘要保留尾消息数",
            "生成摘要后仍保留在上下文中的最近消息条数",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(6),
            Some(0),
            Some(10_000),
            &[],
            "restart_required",
            &["SUMMARY_KEEP_LAST_N"],
            181,
            &now,
        ),
        definition(
            CHATOS_SUMMARY_TARGET_TOKENS_CONFIG_KEY,
            "摘要目标 Tokens",
            "单次摘要输出的目标 Tokens",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(700),
            Some(1),
            Some(1_000_000),
            &[],
            "restart_required",
            &["SUMMARY_TARGET_TOKENS"],
            182,
            &now,
        ),
        definition(
            CHATOS_SUMMARY_MERGE_TARGET_TOKENS_CONFIG_KEY,
            "摘要合并目标 Tokens",
            "摘要合并阶段的目标输出 Tokens",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(700),
            Some(1),
            Some(1_000_000),
            &[],
            "restart_required",
            &["SUMMARY_MERGE_TARGET_TOKENS"],
            183,
            &now,
        ),
        definition(
            CHATOS_SUMMARY_TEMPERATURE_CONFIG_KEY,
            "摘要 Temperature",
            "摘要模型请求使用的 temperature，使用字符串形式保存小数",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "string",
            json!("0.2"),
            None,
            None,
            &[],
            "restart_required",
            &["SUMMARY_TEMPERATURE"],
            184,
            &now,
        ),
        definition(
            CHATOS_SUMMARY_COOLDOWN_SECONDS_CONFIG_KEY,
            "摘要冷却时间",
            "两次摘要触发之间至少间隔的秒数",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(60),
            Some(0),
            Some(86_400),
            &[],
            "restart_required",
            &["SUMMARY_COOLDOWN_SECONDS"],
            185,
            &now,
        ),
        definition(
            CHATOS_DYNAMIC_SUMMARY_ENABLED_CONFIG_KEY,
            "动态摘要开关",
            "是否启用基于上下文长度的动态摘要策略",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["DYNAMIC_SUMMARY_ENABLED"],
            186,
            &now,
        ),
        definition(
            CHATOS_SUMMARY_BISECT_ENABLED_CONFIG_KEY,
            "摘要二分开关",
            "是否允许在长上下文摘要时采用二分策略",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["SUMMARY_BISECT_ENABLED"],
            187,
            &now,
        ),
        definition(
            CHATOS_SUMMARY_BISECT_MAX_DEPTH_CONFIG_KEY,
            "摘要二分最大深度",
            "摘要二分策略允许递归拆分的最大深度",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(6),
            Some(1),
            Some(128),
            &[],
            "restart_required",
            &["SUMMARY_BISECT_MAX_DEPTH"],
            188,
            &now,
        ),
        definition(
            CHATOS_SUMMARY_BISECT_MIN_MESSAGES_CONFIG_KEY,
            "摘要二分最小消息数",
            "只有消息数达到该阈值时才会进入摘要二分流程",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(4),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["SUMMARY_BISECT_MIN_MESSAGES"],
            189,
            &now,
        ),
        definition(
            CHATOS_SUMMARY_RETRY_ON_CONTEXT_OVERFLOW_CONFIG_KEY,
            "上下文溢出自动重试",
            "摘要请求因上下文溢出失败时是否自动缩减并重试",
            "Chat OS / Summary",
            "service",
            Some("chatos-backend"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["SUMMARY_RETRY_ON_CONTEXT_OVERFLOW"],
            190,
            &now,
        ),
        secret_definition(
            CHATOS_AUTH_JWT_SECRET_CONFIG_KEY,
            "JWT 签名密钥",
            "Chatos Backend 签发与校验访问令牌使用的主密钥",
            "Chat OS / Auth",
            "service",
            Some("chatos-backend"),
            json!("dev-only-change-me-please"),
            "restart_required",
            &["AUTH_JWT_SECRET"],
            191,
            &now,
        ),
        nullable_secret_definition(
            CHATOS_AUTH_COMPAT_SECRET_CONFIG_KEY,
            "JWT 兼容密钥",
            "兼容历史令牌校验时使用的附加密钥，空值表示禁用",
            "Chat OS / Auth",
            "service",
            Some("chatos-backend"),
            Value::Null,
            "restart_required",
            &["AUTH_COMPAT_SECRET"],
            192,
            &now,
        ),
        definition(
            CHATOS_AUTH_ACCESS_TOKEN_TTL_SECONDS_CONFIG_KEY,
            "访问令牌 TTL",
            "访问令牌默认有效期，单位秒",
            "Chat OS / Auth",
            "service",
            Some("chatos-backend"),
            "integer",
            json!(43_200),
            Some(60),
            Some(31_536_000),
            &[],
            "restart_required",
            &["AUTH_ACCESS_TOKEN_TTL_SECONDS"],
            193,
            &now,
        ),
        definition(
            CHATOS_LOG_MAX_FILES_CONFIG_KEY,
            "日志保留策略",
            "Chatos Backend 使用的日志文件保留策略，例如 7d",
            "Chat OS / Logging",
            "service",
            Some("chatos-backend"),
            "string",
            json!("7d"),
            None,
            None,
            &[],
            "restart_required",
            &["LOG_MAX_FILES"],
            193,
            &now,
        ),
        definition(
            CHATOS_OTLP_ENDPOINT_CONFIG_KEY,
            "OTLP Endpoint",
            "ChatOS OpenTelemetry trace exporter 使用的 OTLP gRPC 地址",
            "Chat OS / Observability",
            "service",
            Some("chatos-backend"),
            "string",
            json!("http://tempo:4317"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_OTEL_EXPORTER_OTLP_ENDPOINT"],
            194,
            &now,
        ),
        definition(
            CHATOS_OTLP_TRACE_SAMPLE_RATIO_CONFIG_KEY,
            "Trace Sample Ratio",
            "ChatOS 根链路按 Trace ID 采样的比例",
            "Chat OS / Observability",
            "service",
            Some("chatos-backend"),
            "number",
            json!(0.1),
            Some(0),
            Some(1),
            &[],
            "restart_required",
            &["CHATOS_OTEL_TRACE_SAMPLE_RATIO"],
            195,
            &now,
        ),
        definition(
            CHATOS_OTLP_EXPORT_TIMEOUT_MS_CONFIG_KEY,
            "OTLP Export Timeout",
            "ChatOS 导出一批 trace 的超时毫秒数",
            "Chat OS / Observability",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(60_000),
            &[],
            "restart_required",
            &["CHATOS_OTEL_EXPORT_TIMEOUT_MS"],
            196,
            &now,
        ),
        definition(
            CHATOS_CORS_ORIGINS_CONFIG_KEY,
            "CORS Origins",
            "Chatos Backend 允许的跨域来源列表，使用逗号分隔，支持 *",
            "Chat OS / HTTP",
            "service",
            Some("chatos-backend"),
            "string",
            json!("*"),
            None,
            None,
            &[],
            "restart_required",
            &["CORS_ORIGINS"],
            193,
            &now,
        ),
        definition(
            CHATOS_MCP_RESULT_RABBITMQ_URL_CONFIG_KEY,
            "MCP 结果 RabbitMQ 地址",
            "Chatos Backend 消费 MCP 异步调用结果事件使用的 AMQP 地址",
            "Chat OS / MCP Queue",
            "service",
            Some("chatos-backend"),
            "string",
            json!(DEFAULT_LOCAL_RABBITMQ_URL),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_MCP_RESULT_RABBITMQ_URL"],
            194,
            &now,
        ),
        definition(
            CHATOS_MCP_RESULT_QUEUE_PREFIX_CONFIG_KEY,
            "MCP 结果队列前缀",
            "Chatos Backend 按实例创建共享 MCP 结果消费队列使用的名称前缀",
            "Chat OS / MCP Queue",
            "service",
            Some("chatos-backend"),
            "string",
            json!("chatos.mcp.results"),
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_MCP_RESULT_QUEUE_PREFIX"],
            196,
            &now,
        ),
        nullable_definition(
            CHATOS_PLUGIN_UI_PARENT_ORIGIN_CONFIG_KEY,
            "插件 UI 宿主 Origin",
            "插件 UI 被嵌入的上层应用 Origin，空值表示未启用插件 UI 远程资源",
            "Chat OS / Plugin UI",
            "service",
            Some("chatos-backend"),
            "string",
            Value::Null,
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_PLUGIN_UI_PARENT_ORIGIN"],
            194,
            &now,
        ),
        nullable_definition(
            CHATOS_PLUGIN_UI_RESOURCE_ORIGIN_CONFIG_KEY,
            "插件 UI 资源 Origin",
            "插件 UI 远程资源所在 Origin，空值表示未启用插件 UI 远程资源",
            "Chat OS / Plugin UI",
            "service",
            Some("chatos-backend"),
            "string",
            Value::Null,
            None,
            None,
            &[],
            "restart_required",
            &["CHATOS_PLUGIN_UI_RESOURCE_ORIGIN"],
            195,
            &now,
        ),
        definition(
            CHATOS_MEMORY_ENGINE_ACTIVE_SUMMARY_TRIGGER_TIMEOUT_MS_CONFIG_KEY,
            "主动摘要触发超时",
            "触发 Memory Engine 主动摘要任务时使用的请求超时毫秒数",
            "Chat OS / Memory Engine",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ACTIVE_SUMMARY_TRIGGER_TIMEOUT_MS"],
            196,
            &now,
        ),
        definition(
            CHATOS_MEMORY_ENGINE_ACTIVE_SUMMARY_POLL_INTERVAL_MS_CONFIG_KEY,
            "主动摘要轮询间隔",
            "轮询 Memory Engine 主动摘要状态时的间隔毫秒数",
            "Chat OS / Memory Engine",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(10_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ACTIVE_SUMMARY_POLL_INTERVAL_MS"],
            197,
            &now,
        ),
        definition(
            CHATOS_MEMORY_ENGINE_ACTIVE_SUMMARY_POLL_TIMEOUT_MS_CONFIG_KEY,
            "主动摘要轮询超时",
            "等待 Memory Engine 主动摘要完成时的总超时毫秒数",
            "Chat OS / Memory Engine",
            "service",
            Some("chatos-backend"),
            "duration_ms",
            json!(120_000),
            Some(10_000),
            Some(3_600_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ACTIVE_SUMMARY_POLL_TIMEOUT_MS"],
            198,
            &now,
        ),
    ]
}
