use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            TASK_RUNNER_MAX_ITERATIONS_CONFIG_KEY,
            "任务执行最大迭代次数",
            "单次 Task Run 允许的模型与工具循环总次数；最后两轮会自动关闭工具并强制收尾",
            "Task Runner / Execution",
            "shared",
            None,
            "integer",
            json!(DEFAULT_AGENT_MAX_ITERATIONS),
            Some(2),
            Some(5000),
            &[],
            "next_run",
            &[],
            200,
            &now,
        ),
        definition(
            TASK_RUNNER_REVIEW_READ_ONLY_ITERATIONS_CONFIG_KEY,
            "复盘触发：只读迭代次数",
            "Task Run 连续多少轮没有真实工程改动时触发一次自动复盘；不会禁用工具",
            "Task Runner / Execution",
            "shared",
            None,
            "integer",
            json!(DEFAULT_TASK_RUNNER_REVIEW_READ_ONLY_ITERATIONS),
            Some(1),
            Some(5000),
            &[],
            "next_run",
            &[],
            202,
            &now,
        ),
        definition(
            TASK_RUNNER_REVIEW_MISSING_READ_FAILURES_CONFIG_KEY,
            "复盘触发：缺失文件读取次数",
            "Task Run 连续读取不存在文件达到该次数时触发自动复盘；不会禁用读取工具",
            "Task Runner / Execution",
            "shared",
            None,
            "integer",
            json!(DEFAULT_TASK_RUNNER_REVIEW_MISSING_READ_FAILURES),
            Some(1),
            Some(5000),
            &[],
            "next_run",
            &[],
            204,
            &now,
        ),
        definition(
            TASK_RUNNER_REVIEW_REPEAT_INTERVAL_CONFIG_KEY,
            "复盘触发：重复间隔",
            "同一 Task Run 自动复盘之间至少间隔多少轮模型/工具循环",
            "Task Runner / Execution",
            "shared",
            None,
            "integer",
            json!(DEFAULT_TASK_RUNNER_REVIEW_REPEAT_INTERVAL),
            Some(1),
            Some(5000),
            &[],
            "next_run",
            &[],
            206,
            &now,
        ),
        definition(
            TASK_RUNNER_EXECUTION_TIMEOUT_CONFIG_KEY,
            "任务执行超时",
            "单次 Task Run 执行超时毫秒数",
            "Task Runner / Execution",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(7_200_000),
            Some(1000),
            Some(86_400_000),
            &[],
            "next_run",
            &[],
            210,
            &now,
        ),
        definition(
            TASK_RUNNER_EXECUTION_ENVIRONMENT_MODE_CONFIG_KEY,
            "任务执行环境模式",
            "控制 Task Run 默认在本地执行还是云端沙箱执行",
            "Task Runner / Execution",
            "service",
            Some("task-runner"),
            "enum",
            json!(default_task_runner_execution_environment_mode()),
            None,
            None,
            &["local", "cloud"],
            "next_run",
            &[],
            215,
            &now,
        ),
        definition(
            TASK_RUNNER_SUPPLY_CHAIN_BASELINE_REVISION_CONFIG_KEY,
            "Node.js 依赖基线修订号",
            "Task Runner 验收生成 Node.js 项目时使用的集中依赖基线修订号",
            "Task Runner / Supply Chain",
            "service",
            Some("task-runner"),
            "string",
            json!("baseline-2026-08"),
            None,
            None,
            &[],
            "next_run",
            &[],
            216,
            &now,
        ),
        definition(
            TASK_RUNNER_SUPPLY_CHAIN_NODE_AUDIT_LEVEL_CONFIG_KEY,
            "Node.js 审计阻断级别",
            "生成 Node.js 项目完成前必须执行的依赖审计阻断级别",
            "Task Runner / Supply Chain",
            "service",
            Some("task-runner"),
            "enum",
            json!("high"),
            None,
            None,
            &["high"],
            "next_run",
            &[],
            217,
            &now,
        ),
        definition(
            TASK_RUNNER_SUPPLY_CHAIN_INSTALL_SCRIPT_ALLOWLIST_CONFIG_KEY,
            "Node.js 安装脚本白名单",
            "允许在禁用默认生命周期脚本后单独执行 rebuild 的依赖包名称列表",
            "Task Runner / Supply Chain",
            "service",
            Some("task-runner"),
            "json",
            json!(["esbuild"]),
            None,
            None,
            &[],
            "next_run",
            &[],
            218,
            &now,
        ),
        definition(
            TASK_RUNNER_SUPPLY_CHAIN_NODE_DEPENDENCY_REQUIREMENTS_CONFIG_KEY,
            "Node.js 依赖版本基线",
            "生成 Node.js 项目使用的集中审核依赖版本要求；仅校验此映射中出现的包",
            "Task Runner / Supply Chain",
            "service",
            Some("task-runner"),
            "json",
            json!({
                "@types/node": "^26.1.1",
                "@types/react": "^19.2.17",
                "@types/react-dom": "^19.2.3",
                "@vitejs/plugin-react": "^6.0.3",
                "axios": "^1.18.1",
                "lucide-react": "^1.24.0",
                "react": "^19.2.7",
                "react-dom": "^19.2.7",
                "typescript": "^7.0.2",
                "vite": "^8.1.4",
                "vitest": "^4.1.10"
            }),
            None,
            None,
            &[],
            "next_run",
            &[],
            219,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_DISPATCH_MODE_CONFIG_KEY,
            "Run 调度模式",
            "Task Run 创建后必须进入 RabbitMQ 分发队列，禁止回退到数据库轮询",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "enum",
            json!("rabbitmq"),
            None,
            None,
            &["rabbitmq"],
            "restart_required",
            &["TASK_RUNNER_RUN_DISPATCH_MODE"],
            216,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_CALLBACK_DELIVERY_MODE_CONFIG_KEY,
            "回调投递模式",
            "控制 ChatOS 回调是由当前实例直接发送，还是进入 RabbitMQ 异步投递队列",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "enum",
            json!("rabbitmq"),
            None,
            None,
            &["inline", "rabbitmq"],
            "restart_required",
            &["TASK_RUNNER_CALLBACK_DELIVERY_MODE"],
            217,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RABBITMQ_URL_CONFIG_KEY,
            "RabbitMQ 连接地址",
            "Task Runner 队列模式连接 RabbitMQ 的 AMQP 地址",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!(DEFAULT_LOCAL_RABBITMQ_URL),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RABBITMQ_URL"],
            218,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RABBITMQ_EXCHANGE_CONFIG_KEY,
            "RabbitMQ Exchange",
            "Task Runner 队列模式使用的 RabbitMQ Exchange 名称",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RABBITMQ_EXCHANGE"],
            219,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RABBITMQ_RECONNECT_MS_CONFIG_KEY,
            "RabbitMQ 重连等待时间",
            "Task Runner 队列消费者连接中断后再次连接 RabbitMQ 的等待毫秒数",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(3_000),
            Some(100),
            Some(60_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RABBITMQ_RECONNECT_MS"],
            219,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_DISPATCH_QUEUE_CONFIG_KEY,
            "Run 调度队列名",
            "Task Runner 分发 queued run 给 worker 的 RabbitMQ 队列名",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.run.dispatch"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_DISPATCH_QUEUE"],
            220,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_DISPATCH_RETRY_QUEUE_CONFIG_KEY,
            "Run 调度延迟重试队列名",
            "执行通道暂不可用时暂存 Run 调度消息的 RabbitMQ 延迟队列名",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.run.dispatch.retry"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_DISPATCH_RETRY_QUEUE"],
            221,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_DISPATCH_RETRY_DELAY_MS_CONFIG_KEY,
            "Run 调度延迟重试时间",
            "执行通道暂不可用时由 RabbitMQ 延迟再次触发认领的等待毫秒数",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(1_000),
            Some(100),
            Some(60_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_DISPATCH_RETRY_DELAY_MS"],
            222,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_DISPATCH_OUTBOX_RECONCILE_MS_CONFIG_KEY,
            "Run 调度 Outbox 补偿间隔",
            "扫描异常遗留待发布 Run 调度事件的低频补偿间隔毫秒数，不用于业务任务发现",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_DISPATCH_OUTBOX_RECONCILE_MS"],
            223,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_DISPATCH_OUTBOX_BATCH_SIZE_CONFIG_KEY,
            "Run 调度 Outbox 补偿批次",
            "单轮最多补偿发布的待处理 Run 调度事件数量",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_DISPATCH_OUTBOX_BATCH_SIZE"],
            224,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_WORKER_CONTROL_QUEUE_PREFIX_CONFIG_KEY,
            "Worker 控制队列前缀",
            "每个 Task Runner Worker 实例共享的定向控制事件队列名称前缀",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.worker.control"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_WORKER_CONTROL_QUEUE_PREFIX"],
            225,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_QUEUE_CONFIG_KEY,
            "Run 后处理队列名",
            "成功 Run 的 Memory 总结和后续任务调度使用的共享 RabbitMQ 队列名",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.run.post_process"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_QUEUE"],
            226,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_RETRY_QUEUE_CONFIG_KEY,
            "Run 后处理延迟重试队列名",
            "Run 后处理失败后等待 RabbitMQ 重新投递的共享延迟队列名",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.run.post_process.retry"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_RETRY_QUEUE"],
            227,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_DEAD_LETTER_QUEUE_CONFIG_KEY,
            "Run 后处理死信队列名",
            "Run 后处理达到最大投递次数后保存毒消息的 RabbitMQ 队列名",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.run.post_process.dead"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_DEAD_LETTER_QUEUE"],
            228,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_MAX_DELIVERY_ATTEMPTS_CONFIG_KEY,
            "Run 后处理最大投递次数",
            "Run 后处理进入死信队列前允许的最大失败投递次数",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "integer",
            json!(8),
            Some(1),
            Some(100),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_MAX_DELIVERY_ATTEMPTS"],
            229,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_RETRY_DELAY_MS_CONFIG_KEY,
            "Run 后处理重试等待时间",
            "Run 后处理失败后由 RabbitMQ 延迟再次触发的等待毫秒数",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_RETRY_DELAY_MS"],
            228,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_OUTBOX_RECONCILE_MS_CONFIG_KEY,
            "Run 后处理 Outbox 补偿间隔",
            "低频补偿发布异常遗留的 Run 后处理和定向终端清理事件，不用于业务任务发现",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_OUTBOX_RECONCILE_MS"],
            229,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_OUTBOX_BATCH_SIZE_CONFIG_KEY,
            "Run 后处理 Outbox 补偿批次",
            "单轮最多补偿发布的 Run 后处理和定向终端清理事件数量",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_OUTBOX_BATCH_SIZE"],
            230,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_CALLBACK_DELIVERY_QUEUE_CONFIG_KEY,
            "回调投递队列名",
            "Task Runner 异步投递 ChatOS 回调时使用的 RabbitMQ 队列名",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.callback.delivery"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_CALLBACK_DELIVERY_QUEUE"],
            221,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_EVENTS_PUBLISH_MODE_CONFIG_KEY,
            "Run 事件发布模式",
            "持久化 Run 事件后必须通过 RabbitMQ 广播到各 API 实例",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "enum",
            json!("rabbitmq"),
            None,
            None,
            &["rabbitmq"],
            "restart_required",
            &["TASK_RUNNER_RUN_EVENTS_PUBLISH_MODE"],
            222,
            &now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_EVENTS_ROUTING_KEY_CONFIG_KEY,
            "Run 事件广播路由键",
            "Task Runner 发布 Run 事件、API 实例绑定临时消费队列时使用的 RabbitMQ 路由键",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.run.events.broadcast"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_EVENTS_ROUTING_KEY"],
            223,
            &now,
        ),
        definition(
            TASK_RUNNER_MCP_RESULT_QUEUE_PREFIX_CONFIG_KEY,
            "MCP 结果队列前缀",
            "Task Runner 按实例创建共享 MCP 结果消费队列使用的名称前缀",
            "Task Runner / MCP Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.mcp.results"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_MCP_RESULT_QUEUE_PREFIX"],
            225,
            &now,
        ),
        definition(
            TASK_RUNNER_PRESSURE_QUEUE_ELEVATED_MESSAGES_CONFIG_KEY,
            "Task Runner 队列升压阈值",
            "Task Runner 自有主队列 ready 消息总数达到该值时上报 elevated",
            "Task Runner / Pressure",
            "service",
            Some("task-runner"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000_000),
            &[],
            "hot_reload",
            &[],
            2251,
            &now,
        ),
        definition(
            TASK_RUNNER_PRESSURE_QUEUE_CRITICAL_MESSAGES_CONFIG_KEY,
            "Task Runner 队列临界阈值",
            "Task Runner 自有主队列 ready 消息总数达到该值时上报 critical",
            "Task Runner / Pressure",
            "service",
            Some("task-runner"),
            "integer",
            json!(1_000),
            Some(2),
            Some(100_000_000),
            &[],
            "hot_reload",
            &[],
            2252,
            &now,
        ),
        definition(
            TASK_RUNNER_PRESSURE_REPORT_INTERVAL_MS_CONFIG_KEY,
            "Task Runner 压力上报间隔",
            "Task Runner 刷新压力策略并上报自身队列压力信号的间隔",
            "Task Runner / Pressure",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "hot_reload",
            &[],
            2253,
            &now,
        ),
        definition(
            TASK_RUNNER_TOOL_RESULT_MAX_CHARS_CONFIG_KEY,
            "单工具结果字符上限",
            "单个工具结果进入模型上下文的最大字符数",
            "Task Runner / AI",
            "service",
            Some("task-runner"),
            "integer",
            json!(8000),
            Some(1),
            Some(10_000_000),
            &[],
            "next_run",
            &[],
            230,
            &now,
        ),
        definition(
            TASK_RUNNER_TOOL_RESULTS_TOTAL_MAX_CHARS_CONFIG_KEY,
            "工具结果总字符上限",
            "一轮所有工具结果进入模型上下文的总字符预算",
            "Task Runner / AI",
            "service",
            Some("task-runner"),
            "integer",
            json!(48000),
            Some(1),
            Some(100_000_000),
            &[],
            "next_run",
            &[],
            240,
            &now,
        ),
        definition(
            TASK_RUNNER_PLUGIN_CLOUD_BUNDLE_CACHE_MAX_ENTRIES_CONFIG_KEY,
            "Plugin Cloud Bundle 缓存条目上限",
            "Task Runner Worker 单实例缓存不可变 Plugin Cloud Bundle 的最大条目数",
            "Task Runner / Cache",
            "service",
            Some("task-runner"),
            "integer",
            json!(256),
            Some(1),
            Some(100_000),
            &[],
            "hot_reload",
            &[],
            2401,
            &now,
        ),
        definition(
            TASK_RUNNER_PLUGIN_CLOUD_BUNDLE_CACHE_MAX_BYTES_CONFIG_KEY,
            "Plugin Cloud Bundle 缓存字节上限",
            "Task Runner Worker 单实例缓存不可变 Plugin Cloud Bundle 正文的估算总字节预算",
            "Task Runner / Cache",
            "service",
            Some("task-runner"),
            "bytes",
            json!(64 * 1024 * 1024),
            Some(1024),
            Some(4_i64 * 1024 * 1024 * 1024),
            &[],
            "hot_reload",
            &[],
            2402,
            &now,
        ),
        definition(
            TASK_RUNNER_PROMPT_CACHE_ENABLED_CONFIG_KEY,
            "Prompt 缓存",
            "为 Task Runner 的同一 Run 设置稳定且隔离的模型 Prompt 缓存键",
            "Task Runner / AI",
            "shared",
            None,
            "boolean",
            json!(DEFAULT_TASK_RUNNER_PROMPT_CACHE_ENABLED),
            None,
            None,
            &[],
            "next_run",
            &[],
            241,
            &now,
        ),
        definition(
            TASK_RUNNER_PROMPT_CACHE_RETENTION_ENABLED_CONFIG_KEY,
            "Prompt 缓存保留",
            "启用 Responses API 的 24 小时 Prompt 缓存保留参数",
            "Task Runner / AI",
            "shared",
            None,
            "boolean",
            json!(DEFAULT_TASK_RUNNER_PROMPT_CACHE_RETENTION_ENABLED),
            None,
            None,
            &[],
            "next_run",
            &[],
            242,
            &now,
        ),
        definition(
            TASK_RUNNER_MEMORY_TIMEOUT_MS_CONFIG_KEY,
            "Memory Engine 请求超时",
            "Task Runner 调用 Memory Engine 时使用的请求超时毫秒数",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(30_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_MEMORY_TIMEOUT_MS"],
            245,
            &now,
        ),
        definition(
            TASK_RUNNER_SCHEDULER_POLL_MS_CONFIG_KEY,
            "Scheduler 轮询间隔",
            "Task Runner Scheduler 扫描待执行 Run 的轮询间隔毫秒数",
            "Task Runner / Scheduler",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(15_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_SCHEDULER_POLL_MS"],
            246,
            &now,
        ),
        definition(
            TASK_RUNNER_RUN_EVENT_RETENTION_DAYS_CONFIG_KEY,
            "Run 事件保留天数",
            "Task Runner 只保留终态 Run 在该天数内的事件；运行中 Run 不会被清理",
            "Task Runner / Retention",
            "service",
            Some("task-runner"),
            "integer",
            json!(30),
            Some(1),
            Some(3650),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_EVENT_RETENTION_DAYS"],
            2461,
            &now,
        ),
        definition(
            TASK_RUNNER_RUN_EVENT_CLEANUP_INTERVAL_MS_CONFIG_KEY,
            "Run 事件清理间隔",
            "Task Runner Scheduler 执行终态 Run 过期事件清理的间隔毫秒数",
            "Task Runner / Retention",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(3_600_000),
            Some(60_000),
            Some(86_400_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_EVENT_CLEANUP_INTERVAL_MS"],
            2462,
            &now,
        ),
        definition(
            TASK_RUNNER_RUN_EVENT_CLEANUP_BATCH_SIZE_CONFIG_KEY,
            "Run 事件清理批次",
            "单轮最多检查包含过期事件的 Run 数量，限制清理操作对 MongoDB 的压力",
            "Task Runner / Retention",
            "service",
            Some("task-runner"),
            "integer",
            json!(200),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_EVENT_CLEANUP_BATCH_SIZE"],
            2463,
            &now,
        ),
        definition(
            TASK_RUNNER_TERMINAL_LOG_MAX_ENTRIES_CONFIG_KEY,
            "终端日志条目上限",
            "单个 Task Runner 终端会话在内存中保留的最大日志条目数",
            "Task Runner / Terminal",
            "service",
            Some("task-runner"),
            "integer",
            json!(4_000),
            Some(100),
            Some(100_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_TERMINAL_LOG_MAX_ENTRIES"],
            2464,
            &now,
        ),
        definition(
            TASK_RUNNER_TERMINAL_MAX_SESSIONS_CONFIG_KEY,
            "终端会话实例上限",
            "单个 Task Runner 实例允许保留的运行中和未过期终端会话总数",
            "Task Runner / Terminal",
            "service",
            Some("task-runner"),
            "integer",
            json!(512),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_TERMINAL_MAX_SESSIONS"],
            2465,
            &now,
        ),
        definition(
            TASK_RUNNER_TERMINAL_EXITED_SESSION_RETENTION_SECONDS_CONFIG_KEY,
            "已退出终端保留时间",
            "终端进程退出后继续保留会话元数据和日志的秒数，过期后自动清理",
            "Task Runner / Terminal",
            "service",
            Some("task-runner"),
            "integer",
            json!(86_400),
            Some(60),
            Some(2_592_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_TERMINAL_EXITED_SESSION_RETENTION_SECONDS"],
            2466,
            &now,
        ),
        definition(
            TASK_RUNNER_TERMINAL_CLEANUP_INTERVAL_MS_CONFIG_KEY,
            "终端会话清理间隔",
            "Task Runner 扫描并移除过期已退出终端会话的间隔毫秒数",
            "Task Runner / Terminal",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(60_000),
            Some(1_000),
            Some(3_600_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_TERMINAL_CLEANUP_INTERVAL_MS"],
            2467,
            &now,
        ),
        definition(
            TASK_RUNNER_ASK_USER_PROMPT_RETENTION_DAYS_CONFIG_KEY,
            "审批记录保留天数",
            "只清理已完成回执投递且关联 Run 已终态的过期 Ask User 审批记录",
            "Task Runner / Retention",
            "service",
            Some("task-runner"),
            "integer",
            json!(90),
            Some(1),
            Some(3650),
            &[],
            "restart_required",
            &["TASK_RUNNER_ASK_USER_PROMPT_RETENTION_DAYS"],
            2468,
            &now,
        ),
        definition(
            TASK_RUNNER_ASK_USER_PROMPT_CLEANUP_INTERVAL_MS_CONFIG_KEY,
            "审批记录清理间隔",
            "Task Runner Scheduler 清理过期审批记录的间隔毫秒数",
            "Task Runner / Retention",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(3_600_000),
            Some(60_000),
            Some(86_400_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_ASK_USER_PROMPT_CLEANUP_INTERVAL_MS"],
            2469,
            &now,
        ),
        definition(
            TASK_RUNNER_ASK_USER_PROMPT_CLEANUP_BATCH_SIZE_CONFIG_KEY,
            "审批记录清理批次",
            "单轮最多删除的过期审批记录数量，用于限制 MongoDB 清理压力",
            "Task Runner / Retention",
            "service",
            Some("task-runner"),
            "integer",
            json!(200),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_ASK_USER_PROMPT_CLEANUP_BATCH_SIZE"],
            2470,
            &now,
        ),
        definition(
            TASK_RUNNER_AUTO_MEMORY_SUMMARY_CONFIG_KEY,
            "自动记忆总结",
            "Task Runner 在需要时自动触发 Memory Engine 总结",
            "Task Runner / Memory",
            "service",
            Some("task-runner"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_AUTO_MEMORY_SUMMARY"],
            247,
            &now,
        ),
        definition(
            "task_runner.sandbox.enabled",
            "启用任务沙箱",
            "允许 Task Runner 按策略申请沙箱",
            "Task Runner / Sandbox",
            "service",
            Some("task-runner"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "next_run",
            &["TASK_RUNNER_SANDBOX_ENABLED"],
            250,
            &now,
        ),
        definition(
            "task_runner.sandbox.manager_base_url",
            "沙箱管理服务地址",
            "Task Runner 访问 Sandbox Manager 的基础地址",
            "Task Runner / Sandbox",
            "service",
            Some("task-runner"),
            "string",
            json!("https://sandbox-manager-backend:8097"),
            None,
            None,
            &[],
            "next_run",
            &["TASK_RUNNER_SANDBOX_MANAGER_BASE_URL"],
            255,
            &now,
        ),
        definition(
            "task_runner.sandbox.lease_ttl_seconds",
            "沙箱租约 TTL",
            "Task Runner 沙箱租约默认秒数",
            "Task Runner / Sandbox",
            "service",
            Some("task-runner"),
            "integer",
            json!(7200),
            Some(60),
            Some(86400),
            &[],
            "next_run",
            &["TASK_RUNNER_SANDBOX_LEASE_TTL_SECONDS"],
            260,
            &now,
        ),
        definition(
            "task_runner.worker.concurrency",
            "Worker 并发数",
            "单个 Task Runner Worker 实例并发认领 Run 的上限；Run 在模型调用、环境准备等阶段也会占用槽位",
            "Task Runner / Worker",
            "service",
            Some("task-runner"),
            "integer",
            json!(5),
            Some(1),
            Some(256),
            &[],
            "restart_required",
            &["TASK_RUNNER_WORKER_CONCURRENCY"],
            260,
            &now,
        ),
        definition(
            "task_runner.worker.claim_ttl_ms",
            "Worker Claim TTL",
            "Worker 对 Run 的占用租约毫秒数",
            "Task Runner / Worker",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(120000),
            Some(1000),
            Some(3_600_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_WORKER_CLAIM_TTL_MS"],
            270,
            &now,
        ),
        definition(
            TASK_RUNNER_LOCAL_CONNECTOR_SERVICE_BASE_URL_CONFIG_KEY,
            "Local Connector Service Base URL",
            "Task Runner 调用 Local Connector 服务时使用的基础地址",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "string",
            json!("https://127.0.0.1:39232"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_LOCAL_CONNECTOR_SERVICE_BASE_URL"],
            281,
            &now,
        ),
        definition(
            TASK_RUNNER_USER_SERVICE_BASE_URL_CONFIG_KEY,
            "User Service Base URL",
            "Task Runner 调用 User Service 时使用的基础地址",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "string",
            json!("http://127.0.0.1:39190"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_USER_SERVICE_BASE_URL"],
            281,
            &now,
        ),
        definition(
            TASK_RUNNER_USER_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "User Service Request Timeout",
            "Task Runner 调用 User Service 时使用的请求超时毫秒数",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_USER_SERVICE_REQUEST_TIMEOUT_MS"],
            281,
            &now,
        ),
        definition(
            TASK_RUNNER_PROJECT_SERVICE_BASE_URL_CONFIG_KEY,
            "Project Service Base URL",
            "Task Runner 调用 Project Service 时使用的基础地址",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "string",
            json!("http://127.0.0.1:39210"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_PROJECT_SERVICE_BASE_URL"],
            281,
            &now,
        ),
        definition(
            TASK_RUNNER_PROJECT_SERVICE_INTERNAL_BASE_URL_CONFIG_KEY,
            "Project Service Internal Base URL",
            "Task Runner 调用 Project Service 内部接口时使用的强制 mTLS 地址",
            "Task Runner / Downstream Security",
            "service",
            Some("task-runner"),
            "string",
            json!("https://project-management-backend:39212"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_PROJECT_SERVICE_INTERNAL_BASE_URL"],
            281,
            &now,
        ),
        definition(
            TASK_RUNNER_PROJECT_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Project Service Request Timeout",
            "Task Runner 调用 Project Service 时使用的请求超时毫秒数",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_PROJECT_SERVICE_REQUEST_TIMEOUT_MS"],
            281,
            &now,
        ),
        definition(
            TASK_RUNNER_MEMORY_ENGINE_BASE_URL_CONFIG_KEY,
            "Memory Engine Base URL",
            "Task Runner 调用 Memory Engine 时使用的基础地址",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "string",
            json!("https://memory-engine-backend:7083/api/memory-engine/v1"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_MEMORY_ENGINE_BASE_URL"],
            281,
            &now,
        ),
        definition(
            TASK_RUNNER_SANDBOX_MANAGER_BASE_URL_CONFIG_KEY,
            "Sandbox Manager Base URL",
            "Task Runner 调用 Sandbox Manager 时使用的基础地址",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "string",
            json!("https://sandbox-manager-backend:8097"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_SANDBOX_MANAGER_BASE_URL"],
            281,
            &now,
        ),
        secret_definition(
            TASK_RUNNER_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Project Service Internal Secret",
            "Task Runner 调用 Project Service 内部接口时使用的共享密钥",
            "Task Runner / Downstream Security",
            "service",
            Some("task-runner"),
            json!("change_me_task_runner_project_service_secret"),
            "restart_required",
            &["TASK_RUNNER_PROJECT_SERVICE_INTERNAL_API_SECRET"],
            282,
            &now,
        ),
        secret_definition(
            TASK_RUNNER_PLUGIN_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "Plugin Management Internal Secret",
            "Task Runner 调用 Plugin Management 内部接口时使用的专用密钥",
            "Task Runner / Downstream Security",
            "service",
            Some("task-runner"),
            json!("change_me_plugin_management_task_runner_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_TASK_RUNNER_INTERNAL_API_SECRET"],
            282,
            &now,
        ),
        secret_definition(
            TASK_RUNNER_MEMORY_ENGINE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Memory Engine Internal Secret",
            "Task Runner 签发 Memory Engine 内部短期 token 时使用的调用方专属密钥",
            "Task Runner / Downstream Security",
            "service",
            Some("task-runner"),
            json!("change_me_task_runner_memory_engine_secret"),
            "restart_required",
            &["TASK_RUNNER_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            283,
            &now,
        ),
        secret_definition(
            TASK_RUNNER_LOCAL_CONNECTOR_INTERNAL_API_SECRET_CONFIG_KEY,
            "Local Connector Internal Secret",
            "Task Runner 调用 Local Connector 内部接口时使用的共享密钥",
            "Task Runner / Downstream Security",
            "service",
            Some("task-runner"),
            json!("change_me_task_runner_local_connector_secret"),
            "restart_required",
            &["TASK_RUNNER_LOCAL_CONNECTOR_INTERNAL_API_SECRET"],
            284,
            &now,
        ),
        secret_definition(
            TASK_RUNNER_SANDBOX_MANAGER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Sandbox Manager Internal Secret",
            "Task Runner 调用 Sandbox Manager 内部接口时使用的 client key",
            "Task Runner / Downstream Security",
            "service",
            Some("task-runner"),
            json!("change_me_task_runner_sandbox_manager_secret"),
            "restart_required",
            &["TASK_RUNNER_SANDBOX_MANAGER_INTERNAL_API_SECRET"],
            285,
            &now,
        ),
        secret_definition(
            TASK_RUNNER_PROJECT_SERVICE_CALLER_SECRET_CONFIG_KEY,
            "Project Service Caller Secret",
            "Task Runner 校验来自 Project Service 的内部请求时使用的共享密钥",
            "Task Runner / Security",
            "service",
            Some("task-runner"),
            json!("change_me_project_service_task_runner_secret"),
            "restart_required",
            &["PROJECT_SERVICE_TASK_RUNNER_INTERNAL_API_SECRET"],
            286,
            &now,
        ),
        secret_definition(
            TASK_RUNNER_CHATOS_INTERNAL_API_SECRET_CONFIG_KEY,
            "Chatos Internal Secret",
            "Task Runner 校验来自 Chatos Backend 的内部请求时使用的共享密钥",
            "Task Runner / Security",
            "service",
            Some("task-runner"),
            json!("change_me_chatos_task_runner_internal_secret"),
            "restart_required",
            &["CHATOS_TASK_RUNNER_INTERNAL_API_SECRET"],
            287,
            &now,
        ),
        secret_definition(
            TASK_RUNNER_MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "MCP Management Internal Secret",
            "Task Runner 校验来自 MCP Management 的内部请求时使用的共享密钥",
            "Task Runner / Security",
            "service",
            Some("task-runner"),
            json!("change_me_mcp_management_task_runner_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_TASK_RUNNER_INTERNAL_API_SECRET"],
            288,
            &now,
        ),
        secret_definition(
            TASK_RUNNER_USER_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "User Service Internal Secret",
            "Task Runner 校验来自 User Service 的内部签名请求时使用的共享密钥",
            "Task Runner / Security",
            "service",
            Some("task-runner"),
            json!("change_me_user_service_task_runner_secret"),
            "restart_required",
            &["USER_SERVICE_TASK_RUNNER_INTERNAL_API_SECRET"],
            289,
            &now,
        ),
        definition(
            TASK_RUNNER_LOCAL_CONNECTOR_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Local Connector Request Timeout",
            "Task Runner 调用 Local Connector 时使用的请求超时毫秒数",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_LOCAL_CONNECTOR_SERVICE_REQUEST_TIMEOUT_MS"],
            289,
            &now,
        ),
        definition(
            TASK_RUNNER_PLUGIN_RELAY_TIMEOUT_MS_CONFIG_KEY,
            "Plugin Relay Timeout",
            "Task Runner 通过 Local Connector 转发插件执行请求时的超时毫秒数",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(60_000),
            Some(1_000),
            Some(120_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_PLUGIN_RELAY_TIMEOUT_MS"],
            290,
            &now,
        ),
        definition(
            TASK_RUNNER_PLUGIN_HOOK_RELAY_TIMEOUT_MS_CONFIG_KEY,
            "Plugin Hook Relay Timeout",
            "Task Runner 转发插件 Hook 事件到 Local Connector 时的超时毫秒数",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(330_000),
            Some(45_000),
            Some(600_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_PLUGIN_HOOK_RELAY_TIMEOUT_MS"],
            291,
            &now,
        ),
        definition(
            TASK_RUNNER_PLUGIN_CONNECTOR_DISCOVERY_TIMEOUT_MS_CONFIG_KEY,
            "Plugin Connector Discovery Timeout",
            "Task Runner 查询 Local Connector 设备和工作区列表时的超时毫秒数",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(10_000),
            Some(1_000),
            Some(30_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_PLUGIN_CONNECTOR_DISCOVERY_TIMEOUT_MS"],
            292,
            &now,
        ),
        definition(
            TASK_RUNNER_CHATOS_CALLBACK_URL_CONFIG_KEY,
            "Chatos Callback URL",
            "Task Runner 回调 Chatos Backend 任务状态时使用的地址",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "string",
            json!("https://127.0.0.1:3999/api/agent/chat/task-runner/callback"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_CHATOS_CALLBACK_URL"],
            293,
            &now,
        ),
        definition(
            TASK_RUNNER_CALLBACK_TIMEOUT_MS_CONFIG_KEY,
            "回调请求超时",
            "Task Runner 调用 Chatos 回调接口时使用的请求超时毫秒数",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(10_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_CALLBACK_TIMEOUT_MS"],
            294,
            &now,
        ),
        definition(
            TASK_RUNNER_OTLP_ENDPOINT_CONFIG_KEY,
            "OTLP Endpoint",
            "Task Runner OpenTelemetry trace exporter 使用的 OTLP gRPC 地址",
            "Task Runner / Observability",
            "service",
            Some("task-runner"),
            "string",
            json!("http://tempo:4317"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_OTEL_EXPORTER_OTLP_ENDPOINT"],
            295,
            &now,
        ),
        definition(
            TASK_RUNNER_OTLP_TRACE_SAMPLE_RATIO_CONFIG_KEY,
            "Trace Sample Ratio",
            "Task Runner 根链路按 Trace ID 采样的比例",
            "Task Runner / Observability",
            "service",
            Some("task-runner"),
            "number",
            json!(0.1),
            Some(0),
            Some(1),
            &[],
            "restart_required",
            &["TASK_RUNNER_OTEL_TRACE_SAMPLE_RATIO"],
            296,
            &now,
        ),
        definition(
            TASK_RUNNER_OTLP_EXPORT_TIMEOUT_MS_CONFIG_KEY,
            "OTLP Export Timeout",
            "Task Runner 导出一批 trace 的超时毫秒数",
            "Task Runner / Observability",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(60_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_OTEL_EXPORT_TIMEOUT_MS"],
            297,
            &now,
        ),
        definition(
            TASK_RUNNER_HOST_CONFIG_KEY,
            "Host",
            "Task Runner HTTP 服务监听地址",
            "Task Runner / Runtime",
            "service",
            Some("task-runner"),
            "string",
            json!("127.0.0.1"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_HOST"],
            294,
            &now,
        ),
        definition(
            TASK_RUNNER_PORT_CONFIG_KEY,
            "Port",
            "Task Runner HTTP 服务监听端口",
            "Task Runner / Runtime",
            "service",
            Some("task-runner"),
            "integer",
            json!(39090),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["TASK_RUNNER_PORT"],
            294,
            &now,
        ),
        definition(
            TASK_RUNNER_INTERNAL_MTLS_PORT_CONFIG_KEY,
            "Internal mTLS Port",
            "Task Runner 内部控制面强制 mTLS 监听端口",
            "Task Runner / Runtime Security",
            "service",
            Some("task-runner"),
            "integer",
            json!(39092),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["TASK_RUNNER_INTERNAL_MTLS_PORT"],
            295,
            &now,
        ),
        secret_definition(
            TASK_RUNNER_DATABASE_URL_CONFIG_KEY,
            "Database URL",
            "Task Runner 连接存储后端时使用的数据库连接串",
            "Task Runner / Runtime",
            "service",
            Some("task-runner"),
            json!("mongodb://admin:admin@127.0.0.1:27018/task_runner_service?authSource=admin"),
            "restart_required",
            &["TASK_RUNNER_DATABASE_URL"],
            294,
            &now,
        ),
        definition(
            TASK_RUNNER_MONGODB_DATABASE_CONFIG_KEY,
            "MongoDB Database",
            "Task Runner 使用的 MongoDB database 名称",
            "Task Runner / Runtime",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner_service"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_MONGODB_DATABASE"],
            294,
            &now,
        ),
        definition(
            TASK_RUNNER_WORKSPACE_DIR_CONFIG_KEY,
            "Workspace Dir",
            "Task Runner 默认工作区根目录",
            "Task Runner / Runtime",
            "service",
            Some("task-runner"),
            "string",
            json!("."),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_WORKSPACE_DIR"],
            294,
            &now,
        ),
        definition(
            TASK_RUNNER_ADMIN_USERNAME_CONFIG_KEY,
            "Admin Username",
            "Task Runner 启动时自动确保存在的管理员用户名",
            "Task Runner / Bootstrap",
            "service",
            Some("task-runner"),
            "string",
            json!("admin"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_ADMIN_USERNAME"],
            294,
            &now,
        ),
        secret_definition(
            TASK_RUNNER_ADMIN_PASSWORD_CONFIG_KEY,
            "Admin Password",
            "Task Runner 启动时自动确保存在的管理员密码",
            "Task Runner / Bootstrap",
            "service",
            Some("task-runner"),
            json!("admin123456"),
            "restart_required",
            &["TASK_RUNNER_ADMIN_PASSWORD"],
            295,
            &now,
        ),
        definition(
            TASK_RUNNER_ADMIN_DISPLAY_NAME_CONFIG_KEY,
            "Admin Display Name",
            "Task Runner 启动时自动确保存在的管理员显示名称",
            "Task Runner / Bootstrap",
            "service",
            Some("task-runner"),
            "string",
            json!("System Admin"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_ADMIN_DISPLAY_NAME"],
            296,
            &now,
        ),
    ]
}
