use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            USER_SERVICE_PORT_CONFIG_KEY,
            "Port",
            "User Service HTTP 服务监听端口",
            "User Service / Runtime",
            "service",
            Some("user-service"),
            "integer",
            json!(39190),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["USER_SERVICE_PORT"],
            371,
            now,
        ),
        definition(
            USER_SERVICE_INTERNAL_MTLS_PORT_CONFIG_KEY,
            "Internal mTLS Port",
            "User Service 内部接口强制 mTLS 监听端口",
            "User Service / Runtime Security",
            "service",
            Some("user-service"),
            "integer",
            json!(39192),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["USER_SERVICE_INTERNAL_MTLS_PORT"],
            371,
            now,
        ),
        definition(
            USER_SERVICE_OTLP_ENDPOINT_CONFIG_KEY,
            "OTLP Endpoint",
            "User Service OpenTelemetry trace exporter 使用的 OTLP gRPC 地址",
            "User Service / Observability",
            "service",
            Some("user-service"),
            "string",
            json!("http://tempo:4317"),
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_OTEL_EXPORTER_OTLP_ENDPOINT"],
            372,
            now,
        ),
        definition(
            USER_SERVICE_OTLP_TRACE_SAMPLE_RATIO_CONFIG_KEY,
            "Trace Sample Ratio",
            "User Service 根链路按 Trace ID 采样的比例",
            "User Service / Observability",
            "service",
            Some("user-service"),
            "number",
            json!(0.1),
            Some(0),
            Some(1),
            &[],
            "restart_required",
            &["USER_SERVICE_OTEL_TRACE_SAMPLE_RATIO"],
            373,
            now,
        ),
        definition(
            USER_SERVICE_OTLP_EXPORT_TIMEOUT_MS_CONFIG_KEY,
            "OTLP Export Timeout",
            "User Service 导出一批 trace 的超时毫秒数",
            "User Service / Observability",
            "service",
            Some("user-service"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(60_000),
            &[],
            "restart_required",
            &["USER_SERVICE_OTEL_EXPORT_TIMEOUT_MS"],
            374,
            now,
        ),
        secret_definition(
            USER_SERVICE_JWT_SECRET_CONFIG_KEY,
            "JWT Secret",
            "User Service 签发和校验 JWT 时使用的共享密钥",
            "User Service / Security",
            "service",
            Some("user-service"),
            json!("change_me_user_service_secret"),
            "restart_required",
            &["USER_SERVICE_JWT_SECRET"],
            372,
            now,
        ),
        secret_definition(
            USER_SERVICE_SECRET_KEY_CONFIG_KEY,
            "Secret Key",
            "User Service 加解密站内敏感凭据时使用的主密钥",
            "User Service / Security",
            "service",
            Some("user-service"),
            json!("change_me_user_service_secret_key"),
            "restart_required",
            &["USER_SERVICE_SECRET_KEY"],
            373,
            now,
        ),
        nullable_secret_definition(
            USER_SERVICE_PREVIOUS_SECRET_KEYS_CONFIG_KEY,
            "Previous Secret Keys",
            "User Service 解密历史敏感凭据时允许尝试的旧密钥列表，支持逗号、分号或换行分隔",
            "User Service / Security",
            "service",
            Some("user-service"),
            Value::Null,
            "restart_required",
            &["USER_SERVICE_PREVIOUS_SECRET_KEYS"],
            3731,
            now,
        ),
        secret_definition(
            USER_SERVICE_PROJECT_SERVICE_INTERNAL_SECRET_CONFIG_KEY,
            "Project Service Internal Secret",
            "User Service 校验来自 Project Service 的内部请求时使用的共享密钥",
            "User Service / Security",
            "service",
            Some("user-service"),
            json!("change_me_project_service_user_service_secret"),
            "restart_required",
            &["PROJECT_SERVICE_USER_SERVICE_INTERNAL_API_SECRET"],
            374,
            now,
        ),
        secret_definition(
            USER_SERVICE_CHATOS_INTERNAL_SECRET_CONFIG_KEY,
            "ChatOS Internal Secret",
            "User Service 校验来自 Chatos Cloud Agent Worker 的用户模型运行配置请求时使用的共享密钥",
            "User Service / Security",
            "service",
            Some("user-service"),
            json!("change_me_chatos_user_service_secret"),
            "restart_required",
            &["CHATOS_USER_SERVICE_INTERNAL_API_SECRET"],
            3741,
            now,
        ),
        secret_definition(
            USER_SERVICE_MEMORY_ENGINE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Memory Engine Internal Secret",
            "User Service 签发 Memory Engine 内部短期 token 时使用的调用方专属密钥",
            "User Service / Downstream Security",
            "service",
            Some("user-service"),
            json!("change_me_user_service_memory_engine_secret"),
            "restart_required",
            &["USER_SERVICE_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            375,
            now,
        ),
        definition(
            USER_SERVICE_SUPER_ADMIN_USERNAME_CONFIG_KEY,
            "超级管理员用户名",
            "User Service 启动时自动确保存在的超级管理员用户名",
            "User Service / Bootstrap",
            "service",
            Some("user-service"),
            "string",
            json!("admin"),
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_SUPER_ADMIN_USERNAME"],
            37501,
            now,
        ),
        secret_definition(
            USER_SERVICE_SUPER_ADMIN_PASSWORD_CONFIG_KEY,
            "超级管理员密码",
            "User Service 启动时自动确保存在的超级管理员密码",
            "User Service / Bootstrap",
            "service",
            Some("user-service"),
            json!("admin123456"),
            "restart_required",
            &["USER_SERVICE_SUPER_ADMIN_PASSWORD"],
            37502,
            now,
        ),
        definition(
            USER_SERVICE_SUPER_ADMIN_DISPLAY_NAME_CONFIG_KEY,
            "超级管理员显示名",
            "User Service 启动时自动确保存在的超级管理员显示名称",
            "User Service / Bootstrap",
            "service",
            Some("user-service"),
            "string",
            json!("System Admin"),
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_SUPER_ADMIN_DISPLAY_NAME"],
            37503,
            now,
        ),
        definition(
            USER_SERVICE_JWT_ISSUER_CONFIG_KEY,
            "JWT Issuer",
            "User Service 签发 JWT 时使用的 issuer 字段",
            "User Service / Auth",
            "service",
            Some("user-service"),
            "string",
            json!("user_service"),
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_JWT_ISSUER"],
            37504,
            now,
        ),
        definition(
            USER_SERVICE_USER_AUDIENCE_CONFIG_KEY,
            "User Audience",
            "User Service 为终端用户访问令牌设置的 audience",
            "User Service / Auth",
            "service",
            Some("user-service"),
            "string",
            json!("user_service"),
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_USER_AUDIENCE"],
            37505,
            now,
        ),
        definition(
            USER_SERVICE_TASK_RUNNER_AUDIENCE_CONFIG_KEY,
            "Task Runner Audience",
            "User Service 为 Task Runner 访问令牌设置的 audience",
            "User Service / Auth",
            "service",
            Some("user-service"),
            "string",
            json!("task_runner"),
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_TASK_RUNNER_AUDIENCE"],
            37506,
            now,
        ),
        definition(
            USER_SERVICE_USER_ACCESS_TTL_SECONDS_CONFIG_KEY,
            "User Access Token TTL",
            "User Service 签发用户访问令牌的默认有效期，单位秒",
            "User Service / Auth",
            "service",
            Some("user-service"),
            "integer",
            json!(43_200),
            Some(60),
            Some(31_536_000),
            &[],
            "restart_required",
            &["USER_SERVICE_USER_ACCESS_TTL_SECONDS"],
            37507,
            now,
        ),
        definition(
            USER_SERVICE_TASK_RUNNER_ACCESS_TTL_SECONDS_CONFIG_KEY,
            "Task Runner Access Token TTL",
            "User Service 签发 Task Runner 访问令牌的默认有效期，单位秒",
            "User Service / Auth",
            "service",
            Some("user-service"),
            "integer",
            json!(3_600),
            Some(60),
            Some(31_536_000),
            &[],
            "restart_required",
            &["USER_SERVICE_TASK_RUNNER_ACCESS_TTL_SECONDS"],
            37508,
            now,
        ),
        definition(
            USER_SERVICE_REGISTER_CODE_TTL_SECONDS_CONFIG_KEY,
            "注册验证码有效期",
            "注册验证码从签发到失效的时间，单位秒",
            "User Service / Registration",
            "service",
            Some("user-service"),
            "integer",
            json!(600),
            Some(60),
            Some(86_400),
            &[],
            "restart_required",
            &["USER_SERVICE_REGISTER_CODE_TTL_SECONDS"],
            37509,
            now,
        ),
        definition(
            USER_SERVICE_REGISTER_CODE_RESEND_SECONDS_CONFIG_KEY,
            "注册验证码重发间隔",
            "同一邮箱再次发送注册验证码前必须等待的秒数",
            "User Service / Registration",
            "service",
            Some("user-service"),
            "integer",
            json!(60),
            Some(1),
            Some(86_400),
            &[],
            "restart_required",
            &["USER_SERVICE_REGISTER_CODE_RESEND_SECONDS"],
            37510,
            now,
        ),
        definition(
            USER_SERVICE_REGISTER_CODE_HOURLY_LIMIT_CONFIG_KEY,
            "注册验证码每小时上限",
            "单个邮箱每小时允许发送注册验证码的最大次数",
            "User Service / Registration",
            "service",
            Some("user-service"),
            "integer",
            json!(5),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["USER_SERVICE_REGISTER_CODE_HOURLY_LIMIT"],
            37511,
            now,
        ),
        definition(
            USER_SERVICE_REGISTER_CODE_MAX_ATTEMPTS_CONFIG_KEY,
            "注册验证码最大尝试次数",
            "单个验证码允许输入校验失败的最大次数",
            "User Service / Registration",
            "service",
            Some("user-service"),
            "integer",
            json!(5),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["USER_SERVICE_REGISTER_CODE_MAX_ATTEMPTS"],
            37512,
            now,
        ),
        definition(
            USER_SERVICE_LOGIN_MAX_FAILED_ATTEMPTS_CONFIG_KEY,
            "登录最大失败次数",
            "同一账户进入锁定前允许连续失败的登录次数",
            "User Service / Login",
            "service",
            Some("user-service"),
            "integer",
            json!(5),
            Some(0),
            Some(10_000),
            &[],
            "restart_required",
            &["USER_SERVICE_LOGIN_MAX_FAILED_ATTEMPTS"],
            37513,
            now,
        ),
        definition(
            USER_SERVICE_LOGIN_FAILURE_WINDOW_SECONDS_CONFIG_KEY,
            "登录失败统计窗口",
            "统计登录失败次数的滑动时间窗口，单位秒",
            "User Service / Login",
            "service",
            Some("user-service"),
            "integer",
            json!(300),
            Some(1),
            Some(86_400),
            &[],
            "restart_required",
            &["USER_SERVICE_LOGIN_FAILURE_WINDOW_SECONDS"],
            37514,
            now,
        ),
        definition(
            USER_SERVICE_LOGIN_LOCKOUT_SECONDS_CONFIG_KEY,
            "登录锁定时长",
            "超过失败阈值后账户被锁定的时长，单位秒",
            "User Service / Login",
            "service",
            Some("user-service"),
            "integer",
            json!(300),
            Some(1),
            Some(86_400),
            &[],
            "restart_required",
            &["USER_SERVICE_LOGIN_LOCKOUT_SECONDS"],
            37515,
            now,
        ),
        definition(
            USER_SERVICE_MEMORY_ENGINE_BASE_URL_CONFIG_KEY,
            "Memory Engine Base URL",
            "User Service 同步用户模型配置到 Memory Engine 内部控制面时使用的强制 mTLS 地址",
            "User Service / Runtime",
            "service",
            Some("user-service"),
            "string",
            json!("https://memory-engine-backend:7083/api/memory-engine/v1"),
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_MEMORY_ENGINE_BASE_URL"],
            3751,
            now,
        ),
        definition(
            USER_SERVICE_TASK_RUNNER_BASE_URL_CONFIG_KEY,
            "Task Runner Base URL",
            "User Service 同步用户模型配置到 Task Runner 内部控制面时使用的强制 mTLS 地址",
            "User Service / Runtime",
            "service",
            Some("user-service"),
            "string",
            json!("https://task-runner-backend:39092"),
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_TASK_RUNNER_BASE_URL"],
            3752,
            now,
        ),
        secret_definition(
            USER_SERVICE_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Task Runner Internal Secret",
            "User Service 调用 Task Runner 模型配置同步接口时使用的短期签名根密钥",
            "User Service / Downstream Security",
            "service",
            Some("user-service"),
            json!("change_me_user_service_task_runner_secret"),
            "restart_required",
            &["USER_SERVICE_TASK_RUNNER_INTERNAL_API_SECRET"],
            3753,
            now,
        ),
        definition(
            USER_SERVICE_DOWNSTREAM_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "下游请求超时（毫秒）",
            "User Service 调用 Memory Engine、Task Runner 等下游服务时使用的默认超时时间",
            "User Service / Runtime",
            "service",
            Some("user-service"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(60_000),
            &[],
            "restart_required",
            &["USER_SERVICE_DOWNSTREAM_REQUEST_TIMEOUT_MS"],
            3754,
            now,
        ),
        definition(
            USER_SERVICE_HARNESS_PROVISIONING_ENABLED_CONFIG_KEY,
            "启用 Harness 自动开通",
            "User Service 是否在注册/登录链路中自动为用户开通 Harness 资源",
            "User Service / Harness",
            "service",
            Some("user-service"),
            "boolean",
            json!(false),
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_HARNESS_PROVISIONING_ENABLED"],
            3755,
            now,
        ),
        nullable_definition(
            USER_SERVICE_HARNESS_BASE_URL_CONFIG_KEY,
            "Harness Base URL",
            "User Service 调用 Harness API 时使用的基础地址，留空表示关闭 Harness 下游调用",
            "User Service / Harness",
            "service",
            Some("user-service"),
            "string",
            Value::Null,
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_HARNESS_BASE_URL"],
            3756,
            now,
        ),
        definition(
            USER_SERVICE_HARNESS_SYNTHETIC_EMAIL_DOMAIN_CONFIG_KEY,
            "Harness 合成邮箱域名",
            "User Service 为 Harness 自动开通用户生成合成邮箱时使用的域名后缀",
            "User Service / Harness",
            "service",
            Some("user-service"),
            "string",
            json!("chatos.local"),
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_HARNESS_SYNTHETIC_EMAIL_DOMAIN"],
            3757,
            now,
        ),
        definition(
            USER_SERVICE_HARNESS_SPACE_PREFIX_CONFIG_KEY,
            "Harness 空间前缀",
            "User Service 为 Harness 自动开通用户生成空间标识时使用的前缀",
            "User Service / Harness",
            "service",
            Some("user-service"),
            "string",
            json!("u-"),
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_HARNESS_SPACE_PREFIX"],
            3758,
            now,
        ),
        definition(
            USER_SERVICE_HARNESS_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Harness 请求超时（毫秒）",
            "User Service 调用 Harness API 时使用的超时时间",
            "User Service / Harness",
            "service",
            Some("user-service"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(60_000),
            &[],
            "restart_required",
            &["USER_SERVICE_HARNESS_REQUEST_TIMEOUT_MS"],
            3759,
            now,
        ),
        definition(
            USER_SERVICE_HARNESS_PROJECT_PAT_PREFIX_CONFIG_KEY,
            "Harness PAT 前缀",
            "User Service 为 Harness 自动开通项目访问令牌时使用的标识前缀",
            "User Service / Harness",
            "service",
            Some("user-service"),
            "string",
            json!("chatos-project-import"),
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_HARNESS_PROJECT_PAT_PREFIX"],
            3760,
            now,
        ),
        nullable_definition(
            USER_SERVICE_SMTP_HOST_CONFIG_KEY,
            "SMTP 主机",
            "User Service 发送注册验证码邮件使用的 SMTP 主机地址",
            "User Service / Email",
            "service",
            Some("user-service"),
            "string",
            Value::Null,
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_SMTP_HOST"],
            360,
            now,
        ),
        definition(
            USER_SERVICE_SMTP_PORT_CONFIG_KEY,
            "SMTP 端口",
            "User Service 发送注册验证码邮件使用的 SMTP 端口",
            "User Service / Email",
            "service",
            Some("user-service"),
            "integer",
            json!(587),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["USER_SERVICE_SMTP_PORT"],
            362,
            now,
        ),
        nullable_definition(
            USER_SERVICE_SMTP_USERNAME_CONFIG_KEY,
            "SMTP 用户名",
            "User Service 发送注册验证码邮件使用的 SMTP 登录用户名",
            "User Service / Email",
            "service",
            Some("user-service"),
            "string",
            Value::Null,
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_SMTP_USERNAME"],
            364,
            now,
        ),
        nullable_secret_definition(
            USER_SERVICE_SMTP_PASSWORD_CONFIG_KEY,
            "SMTP 密码",
            "User Service 发送注册验证码邮件使用的 SMTP 登录密码",
            "User Service / Email",
            "service",
            Some("user-service"),
            Value::Null,
            "restart_required",
            &["USER_SERVICE_SMTP_PASSWORD"],
            365,
            now,
        ),
        nullable_definition(
            USER_SERVICE_EMAIL_FROM_CONFIG_KEY,
            "发件邮箱",
            "User Service 注册验证码邮件使用的发件邮箱地址",
            "User Service / Email",
            "service",
            Some("user-service"),
            "string",
            Value::Null,
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_EMAIL_FROM"],
            366,
            now,
        ),
        definition(
            USER_SERVICE_EMAIL_FROM_NAME_CONFIG_KEY,
            "发件人名称",
            "User Service 注册验证码邮件展示的发件人名称",
            "User Service / Email",
            "service",
            Some("user-service"),
            "string",
            json!("Chat OS"),
            None,
            None,
            &[],
            "restart_required",
            &["USER_SERVICE_EMAIL_FROM_NAME"],
            368,
            now,
        ),
    ]
}
