// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Required Notice: Copyright (c) 2025 AI Chat Team

import { useProjectExplorerPreviewPaneProps } from './useProjectExplorerPreviewPaneProps';
import { useProjectExplorerTreePaneProps } from './useProjectExplorerTreePaneProps';
import { useProjectExplorerWorkspaceInteractions } from './useProjectExplorerWorkspaceInteractions';
import { buildProjectRunSettingsProps } from './buildProjectRunSettingsProps';
import type { ProjectExplorerWorkspaceViewParams } from './workspaceViewTypes';

export const useProjectExplorerWorkspaceView = ({
  project,
  tree,
  search,
  preview,
  codeNav,
  run,
  interactions,
}: ProjectExplorerWorkspaceViewParams) => {
  const {
    openEntryContextMenu,
    handleDragStart,
    handleDragEnd,
    isContextRootEntry,
    contextMenuStyle,
  } = useProjectExplorerWorkspaceInteractions({
    projectRootPath: project.rootPath,
    contextMenu: tree.contextMenu,
    normalizePath: interactions.normalizePath,
    clearDragExpandTimer: interactions.clearDragExpandTimer,
    clearDragAutoScroll: interactions.clearDragAutoScroll,
    setSelectedPath: interactions.setSelectedPath,
    setSelectedFile: interactions.setSelectedFile,
    setContextMenu: interactions.setContextMenu,
    setDraggingEntryPath: interactions.setDraggingEntryPath,
    setDropTargetDirPath: interactions.setDropTargetDirPath,
    setMoveConflict: interactions.setMoveConflict,
  });

  const treePaneProps = useProjectExplorerTreePaneProps({
    project,
    treeWidth: tree.treeWidth,
    treeScrollRef: tree.treeScrollRef,
    entriesMap: tree.entriesMap,
    expandedPaths: tree.expandedPaths,
    loadingPaths: tree.loadingPaths,
    selectedPath: tree.selectedPath,
    selectedEntry: tree.selectedEntry,
    draggingEntryPath: tree.draggingEntryPath,
    dropTargetDirPath: tree.dropTargetDirPath,
    actionLoading: tree.actionLoading,
    actionReloadPath: tree.actionReloadPath,
    actionMessage: tree.actionMessage,
    actionError: tree.actionError,
    searchQuery: search.searchQuery,
    searchCaseSensitive: search.searchCaseSensitive,
    searchWholeWord: search.searchWholeWord,
    searchResults: search.searchResults,
    searchLoading: search.searchLoading,
    searchError: search.searchError,
    searchTruncated: search.searchTruncated,
    activeSearchHitId: search.activeSearchHitId,
    activeSearchHitIndex: search.activeSearchHitIndex,
    totalSearchHits: search.totalSearchHits,
    normalizePath: interactions.normalizePath,
    toExpandedKey: interactions.toExpandedKey,
    canDropToDirectory: interactions.canDropToDirectory,
    setSelectedPath: interactions.setSelectedPath,
    setSelectedFile: interactions.setSelectedFile,
    setDraggingEntryPath: interactions.setDraggingEntryPath,
    setDropTargetDirPath: interactions.setDropTargetDirPath,
    clearDragExpandTimer: interactions.clearDragExpandTimer,
    cancelDragExpandIfMatches: interactions.cancelDragExpandIfMatches,
    scheduleDragExpand: interactions.scheduleDragExpand,
    clearDragAutoScroll: interactions.clearDragAutoScroll,
    startDragAutoScroll: interactions.startDragAutoScroll,
    selectProjectRoot: interactions.selectProjectRoot,
    toggleDir: interactions.toggleDir,
    openFile: interactions.openFile,
    handleCreateDirectory: interactions.handleCreateDirectory,
    handleCreateFile: interactions.handleCreateFile,
    handleRefresh: interactions.handleRefresh,
    handleSearchQueryChange: interactions.handleSearchQueryChange,
    handleSearchCaseSensitiveChange: interactions.handleSearchCaseSensitiveChange,
    handleSearchWholeWordChange: interactions.handleSearchWholeWordChange,
    canOpenPreviousSearchHit: search.canOpenPreviousSearchHit,
    canOpenNextSearchHit: search.canOpenNextSearchHit,
    handleClearSearch: interactions.handleClearSearch,
    handleOpenSearchHit: interactions.handleOpenSearchHit,
    handleOpenPreviousSearchHit: interactions.handleOpenPreviousSearchHit,
    handleOpenNextSearchHit: interactions.handleOpenNextSearchHit,
    handleMoveEntryByDrop: interactions.handleMoveEntryByDrop,
    openEntryContextMenu,
    handleDragStart,
    handleDragEnd,
  });

  const previewPaneProps = useProjectExplorerPreviewPaneProps({
    projectRootPath: project.rootPath,
    selectedFile: preview.selectedFile,
    selectedPath: tree.selectedPath,
    selectedEntry: tree.selectedEntry,
    loadingFile: preview.loadingFile,
    error: preview.error,
    saveError: preview.saveError,
    savingFile: preview.savingFile,
    searchQuery: search.searchQuery,
    searchCaseSensitive: search.searchCaseSensitive,
    searchWholeWord: search.searchWholeWord,
    activeSearchHitIndex: search.activeSearchHitIndex,
    totalSearchHits: search.totalSearchHits,
    canOpenPreviousSearchHit: search.canOpenPreviousSearchHit,
    canOpenNextSearchHit: search.canOpenNextSearchHit,
    previewTargetLine: search.previewTargetLine,
    previewTargetLineRevision: search.previewTargetLineRevision,
    navCapabilities: codeNav.navCapabilities,
    navCapabilitiesError: codeNav.navCapabilitiesError,
    searchResults: search.searchResults,
    activeSearchHitId: search.activeSearchHitId,
    selectedToken: codeNav.selectedToken,
    navResult: codeNav.navResult,
    navRequestKind: codeNav.navRequestKind,
    navLoading: codeNav.navLoading,
    navError: codeNav.navError,
    activeNavLocationId: codeNav.activeNavLocationId,
    canGoBackFromNav: codeNav.canGoBackFromNav,
    documentSymbols: codeNav.documentSymbols,
    documentSymbolsLoading: codeNav.documentSymbolsLoading,
    documentSymbolsError: codeNav.documentSymbolsError,
    requestDocumentSymbols: codeNav.requestDocumentSymbols,
    handleTokenSelection: interactions.handleTokenSelection,
    clearTokenSelection: interactions.clearTokenSelection,
    requestDefinition: interactions.requestDefinition,
    requestReferences: interactions.requestReferences,
    handleSearchInProject: interactions.handleSearchInProject,
    handleOpenPreviousSearchHit: interactions.handleOpenPreviousSearchHit,
    handleOpenNextSearchHit: interactions.handleOpenNextSearchHit,
    handleActivateSearchHit: interactions.handleActivateSearchHit,
    handleOpenNavLocation: interactions.handleOpenNavLocation,
    goBackFromNav: interactions.goBackFromNav,
    handleOpenDocumentSymbol: interactions.handleOpenDocumentSymbol,
    handleSaveFile: interactions.handleSaveFile,
  });

  const projectSettingsProps = buildProjectRunSettingsProps(project, run);

  return {
    openEntryContextMenu,
    handleDragStart,
    handleDragEnd,
    contextMenuStyle,
    isContextRootEntry,
    treePaneProps,
    previewPaneProps,
    projectSettingsProps,
    handleCreateDirectory: interactions.handleCreateDirectory,
    handleCreateFile: interactions.handleCreateFile,
    handleDownloadSelected: interactions.handleDownloadSelected,
    handleDeleteSelected: interactions.handleDeleteSelected,
    handleCopyFilePath: interactions.handleCopyFilePath,
    handleCopyRelativeFilePath: interactions.handleCopyRelativeFilePath,
    handleIgnoreFile: interactions.handleIgnoreFile,
    handleIgnoreFolder: interactions.handleIgnoreFolder,
    handleIgnoreByExtension: interactions.handleIgnoreByExtension,
    handleOpenPathInDefaultProgram: interactions.handleOpenPathInDefaultProgram,
    handleRevealInFinder: interactions.handleRevealInFinder,
    handleOpenInCode: interactions.handleOpenInCode,
  };
};
