use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            TASK_RUNNER_USER_SERVICE_BASE_URL_CONFIG_KEY,
            "User Service Base URL",
            "Task Runner 调用 User Service 时使用的基础地址",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "string",
            json!("http://127.0.0.1:39190"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_USER_SERVICE_BASE_URL"],
            281,
            now,
        ),
        definition(
            TASK_RUNNER_USER_SERVICE_INTERNAL_BASE_URL_CONFIG_KEY,
            "User Service Internal Base URL",
            "Task Runner 读取权威模型目录时使用的 User Service 强制 mTLS 地址",
            "Task Runner / Downstream Security",
            "service",
            Some("task-runner"),
            "string",
            json!("https://user-service-backend:39192"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_USER_SERVICE_INTERNAL_BASE_URL"],
            281,
            now,
        ),
        definition(
            TASK_RUNNER_USER_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "User Service Request Timeout",
            "Task Runner 调用 User Service 时使用的请求超时毫秒数",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_USER_SERVICE_REQUEST_TIMEOUT_MS"],
            281,
            now,
        ),
        definition(
            TASK_RUNNER_PROJECT_SERVICE_BASE_URL_CONFIG_KEY,
            "Project Service Base URL",
            "Task Runner 调用 Project Service 时使用的基础地址",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "string",
            json!("http://127.0.0.1:39210"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_PROJECT_SERVICE_BASE_URL"],
            281,
            now,
        ),
        definition(
            TASK_RUNNER_PROJECT_SERVICE_INTERNAL_BASE_URL_CONFIG_KEY,
            "Project Service Internal Base URL",
            "Task Runner 调用 Project Service 内部接口时使用的强制 mTLS 地址",
            "Task Runner / Downstream Security",
            "service",
            Some("task-runner"),
            "string",
            json!("https://project-management-backend:39212"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_PROJECT_SERVICE_INTERNAL_BASE_URL"],
            281,
            now,
        ),
        definition(
            TASK_RUNNER_PROJECT_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "Project Service Request Timeout",
            "Task Runner 调用 Project Service 时使用的请求超时毫秒数",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_PROJECT_SERVICE_REQUEST_TIMEOUT_MS"],
            281,
            now,
        ),
        definition(
            TASK_RUNNER_MEMORY_ENGINE_BASE_URL_CONFIG_KEY,
            "Memory Engine Base URL",
            "Task Runner 调用 Memory Engine 时使用的基础地址",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "string",
            json!("https://memory-engine-backend:7083/api/memory-engine/v1"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_MEMORY_ENGINE_BASE_URL"],
            281,
            now,
        ),
        secret_definition(
            TASK_RUNNER_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Project Service Internal Secret",
            "Task Runner 调用 Project Service 内部接口时使用的共享密钥",
            "Task Runner / Downstream Security",
            "service",
            Some("task-runner"),
            json!("change_me_task_runner_project_service_secret"),
            "restart_required",
            &["TASK_RUNNER_PROJECT_SERVICE_INTERNAL_API_SECRET"],
            282,
            now,
        ),
        secret_definition(
            TASK_RUNNER_PLUGIN_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "Plugin Management Internal Secret",
            "Task Runner 调用 Plugin Management 内部接口时使用的专用密钥",
            "Task Runner / Downstream Security",
            "service",
            Some("task-runner"),
            json!("change_me_plugin_management_task_runner_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_TASK_RUNNER_INTERNAL_API_SECRET"],
            282,
            now,
        ),
        secret_definition(
            TASK_RUNNER_MEMORY_ENGINE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Memory Engine Internal Secret",
            "Task Runner 签发 Memory Engine 内部短期 token 时使用的调用方专属密钥",
            "Task Runner / Downstream Security",
            "service",
            Some("task-runner"),
            json!("change_me_task_runner_memory_engine_secret"),
            "restart_required",
            &["TASK_RUNNER_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            283,
            now,
        ),
        secret_definition(
            TASK_RUNNER_PROJECT_SERVICE_CALLER_SECRET_CONFIG_KEY,
            "Project Service Caller Secret",
            "Task Runner 校验来自 Project Service 的内部请求时使用的共享密钥",
            "Task Runner / Security",
            "service",
            Some("task-runner"),
            json!("change_me_project_service_task_runner_secret"),
            "restart_required",
            &["PROJECT_SERVICE_TASK_RUNNER_INTERNAL_API_SECRET"],
            286,
            now,
        ),
        secret_definition(
            TASK_RUNNER_CHATOS_INTERNAL_API_SECRET_CONFIG_KEY,
            "Chatos Internal Secret",
            "Task Runner 校验来自 Chatos Backend 的内部请求时使用的共享密钥",
            "Task Runner / Security",
            "service",
            Some("task-runner"),
            json!("change_me_chatos_task_runner_internal_secret"),
            "restart_required",
            &["CHATOS_TASK_RUNNER_INTERNAL_API_SECRET"],
            287,
            now,
        ),
        secret_definition(
            TASK_RUNNER_MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "MCP Management Internal Secret",
            "Task Runner 校验来自 MCP Management 的内部请求时使用的共享密钥",
            "Task Runner / Security",
            "service",
            Some("task-runner"),
            json!("change_me_mcp_management_task_runner_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_TASK_RUNNER_INTERNAL_API_SECRET"],
            288,
            now,
        ),
        secret_definition(
            TASK_RUNNER_USER_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "User Service Internal Secret",
            "Task Runner 校验来自 User Service 的内部签名请求时使用的共享密钥",
            "Task Runner / Security",
            "service",
            Some("task-runner"),
            json!("change_me_user_service_task_runner_secret"),
            "restart_required",
            &["USER_SERVICE_TASK_RUNNER_INTERNAL_API_SECRET"],
            289,
            now,
        ),
        definition(
            TASK_RUNNER_CHATOS_CALLBACK_URL_CONFIG_KEY,
            "Chatos Callback URL",
            "Task Runner 回调 Chatos Backend 任务状态时使用的地址",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "string",
            json!("https://127.0.0.1:3999/api/agent/chat/task-runner/callback"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_CHATOS_CALLBACK_URL"],
            293,
            now,
        ),
        definition(
            TASK_RUNNER_CALLBACK_TIMEOUT_MS_CONFIG_KEY,
            "回调请求超时",
            "Task Runner 调用 Chatos 回调接口时使用的请求超时毫秒数",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(10_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_CALLBACK_TIMEOUT_MS"],
            294,
            now,
        ),
        definition(
            TASK_RUNNER_OTLP_ENDPOINT_CONFIG_KEY,
            "OTLP Endpoint",
            "Task Runner OpenTelemetry trace exporter 使用的 OTLP gRPC 地址",
            "Task Runner / Observability",
            "service",
            Some("task-runner"),
            "string",
            json!("http://tempo:4317"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_OTEL_EXPORTER_OTLP_ENDPOINT"],
            295,
            now,
        ),
        definition(
            TASK_RUNNER_OTLP_TRACE_SAMPLE_RATIO_CONFIG_KEY,
            "Trace Sample Ratio",
            "Task Runner 根链路按 Trace ID 采样的比例",
            "Task Runner / Observability",
            "service",
            Some("task-runner"),
            "number",
            json!(0.1),
            Some(0),
            Some(1),
            &[],
            "restart_required",
            &["TASK_RUNNER_OTEL_TRACE_SAMPLE_RATIO"],
            296,
            now,
        ),
        definition(
            TASK_RUNNER_OTLP_EXPORT_TIMEOUT_MS_CONFIG_KEY,
            "OTLP Export Timeout",
            "Task Runner 导出一批 trace 的超时毫秒数",
            "Task Runner / Observability",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(60_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_OTEL_EXPORT_TIMEOUT_MS"],
            297,
            now,
        ),
    ]
}
