use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            TASK_RUNNER_MAX_ITERATIONS_CONFIG_KEY,
            "任务执行最大迭代次数",
            "单次 Task Run 允许的模型与工具循环总次数；最后两轮会自动关闭工具并强制收尾",
            "Task Runner / Execution",
            "shared",
            None,
            "integer",
            json!(DEFAULT_AGENT_MAX_ITERATIONS),
            Some(2),
            Some(5000),
            &[],
            "next_run",
            &[],
            200,
            &now,
        ),
        definition(
            TASK_RUNNER_REVIEW_READ_ONLY_ITERATIONS_CONFIG_KEY,
            "复盘触发：只读迭代次数",
            "Task Run 连续多少轮没有真实工程改动时触发一次自动复盘；不会禁用工具",
            "Task Runner / Execution",
            "shared",
            None,
            "integer",
            json!(DEFAULT_TASK_RUNNER_REVIEW_READ_ONLY_ITERATIONS),
            Some(1),
            Some(5000),
            &[],
            "next_run",
            &[],
            202,
            &now,
        ),
        definition(
            TASK_RUNNER_REVIEW_MISSING_READ_FAILURES_CONFIG_KEY,
            "复盘触发：缺失文件读取次数",
            "Task Run 连续读取不存在文件达到该次数时触发自动复盘；不会禁用读取工具",
            "Task Runner / Execution",
            "shared",
            None,
            "integer",
            json!(DEFAULT_TASK_RUNNER_REVIEW_MISSING_READ_FAILURES),
            Some(1),
            Some(5000),
            &[],
            "next_run",
            &[],
            204,
            &now,
        ),
        definition(
            TASK_RUNNER_REVIEW_REPEAT_INTERVAL_CONFIG_KEY,
            "复盘触发：重复间隔",
            "同一 Task Run 自动复盘之间至少间隔多少轮模型/工具循环",
            "Task Runner / Execution",
            "shared",
            None,
            "integer",
            json!(DEFAULT_TASK_RUNNER_REVIEW_REPEAT_INTERVAL),
            Some(1),
            Some(5000),
            &[],
            "next_run",
            &[],
            206,
            &now,
        ),
        definition(
            TASK_RUNNER_EXECUTION_TIMEOUT_CONFIG_KEY,
            "任务执行超时",
            "单次 Task Run 执行超时毫秒数",
            "Task Runner / Execution",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(7_200_000),
            Some(1000),
            Some(86_400_000),
            &[],
            "next_run",
            &[],
            210,
            &now,
        ),
        definition(
            TASK_RUNNER_EXECUTION_ENVIRONMENT_MODE_CONFIG_KEY,
            "任务执行环境模式",
            "控制 Task Run 默认在本地执行还是云端沙箱执行",
            "Task Runner / Execution",
            "service",
            Some("task-runner"),
            "enum",
            json!(default_task_runner_execution_environment_mode()),
            None,
            None,
            &["local", "cloud"],
            "next_run",
            &[],
            215,
            &now,
        ),
        definition(
            TASK_RUNNER_SUPPLY_CHAIN_BASELINE_REVISION_CONFIG_KEY,
            "Node.js 依赖基线修订号",
            "Task Runner 验收生成 Node.js 项目时使用的集中依赖基线修订号",
            "Task Runner / Supply Chain",
            "service",
            Some("task-runner"),
            "string",
            json!("baseline-2026-08"),
            None,
            None,
            &[],
            "next_run",
            &[],
            216,
            &now,
        ),
        definition(
            TASK_RUNNER_SUPPLY_CHAIN_NODE_AUDIT_LEVEL_CONFIG_KEY,
            "Node.js 审计阻断级别",
            "生成 Node.js 项目完成前必须执行的依赖审计阻断级别",
            "Task Runner / Supply Chain",
            "service",
            Some("task-runner"),
            "enum",
            json!("high"),
            None,
            None,
            &["high"],
            "next_run",
            &[],
            217,
            &now,
        ),
        definition(
            TASK_RUNNER_SUPPLY_CHAIN_INSTALL_SCRIPT_ALLOWLIST_CONFIG_KEY,
            "Node.js 安装脚本白名单",
            "允许在禁用默认生命周期脚本后单独执行 rebuild 的依赖包名称列表",
            "Task Runner / Supply Chain",
            "service",
            Some("task-runner"),
            "json",
            json!(["esbuild"]),
            None,
            None,
            &[],
            "next_run",
            &[],
            218,
            &now,
        ),
        definition(
            TASK_RUNNER_SUPPLY_CHAIN_NODE_DEPENDENCY_REQUIREMENTS_CONFIG_KEY,
            "Node.js 依赖版本基线",
            "生成 Node.js 项目使用的集中审核依赖版本要求；仅校验此映射中出现的包",
            "Task Runner / Supply Chain",
            "service",
            Some("task-runner"),
            "json",
            json!({
                "@types/node": "^26.1.1",
                "@types/react": "^19.2.17",
                "@types/react-dom": "^19.2.3",
                "@vitejs/plugin-react": "^6.0.3",
                "axios": "^1.18.1",
                "lucide-react": "^1.24.0",
                "react": "^19.2.7",
                "react-dom": "^19.2.7",
                "typescript": "^7.0.2",
                "vite": "^8.1.4",
                "vitest": "^4.1.10"
            }),
            None,
            None,
            &[],
            "next_run",
            &[],
            219,
            &now,
        ),
    ]
}
