use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            TASK_RUNNER_AI_READ_TIMEOUT_CONFIG_KEY,
            "AI 流读取超时",
            "Task Runner 等待模型流式响应下一批数据的最长时间（毫秒）；超过后中止本次模型请求",
            "Task Runner / AI",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(7_200_000),
            Some(1_000),
            Some(7_200_000),
            &[],
            "next_run",
            &[],
            225,
            &now,
        ),
        definition(
            TASK_RUNNER_TOOL_RESULT_MAX_CHARS_CONFIG_KEY,
            "单工具结果字符上限",
            "Task Runner 单个工具调用的通用文本预算，用于工具结果转换、进入模型上下文以及运行详情中的工具参数和结果展示",
            "Task Runner / AI",
            "service",
            Some("task-runner"),
            "integer",
            json!(8000),
            Some(1),
            Some(10_000_000),
            &[],
            "next_run",
            &[],
            230,
            &now,
        ),
        definition(
            TASK_RUNNER_TOOL_RESULTS_TOTAL_MAX_CHARS_CONFIG_KEY,
            "工具结果总字符上限",
            "一轮所有工具结果进入模型上下文的总字符预算",
            "Task Runner / AI",
            "service",
            Some("task-runner"),
            "integer",
            json!(48000),
            Some(1),
            Some(100_000_000),
            &[],
            "next_run",
            &[],
            240,
            &now,
        ),
        definition(
            TASK_RUNNER_PROMPT_CACHE_ENABLED_CONFIG_KEY,
            "Prompt 缓存",
            "为 Task Runner 的同一 Run 设置稳定且隔离的模型 Prompt 缓存键",
            "Task Runner / AI",
            "shared",
            None,
            "boolean",
            json!(DEFAULT_TASK_RUNNER_PROMPT_CACHE_ENABLED),
            None,
            None,
            &[],
            "next_run",
            &[],
            241,
            &now,
        ),
        definition(
            TASK_RUNNER_PROMPT_CACHE_RETENTION_ENABLED_CONFIG_KEY,
            "Prompt 缓存保留",
            "启用 Responses API 的 24 小时 Prompt 缓存保留参数",
            "Task Runner / AI",
            "shared",
            None,
            "boolean",
            json!(DEFAULT_TASK_RUNNER_PROMPT_CACHE_RETENTION_ENABLED),
            None,
            None,
            &[],
            "next_run",
            &[],
            242,
            &now,
        ),
        definition(
            TASK_RUNNER_MEMORY_TIMEOUT_MS_CONFIG_KEY,
            "Memory Engine 请求超时",
            "Task Runner 调用 Memory Engine 时使用的请求超时毫秒数",
            "Task Runner / Downstream",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(30_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_MEMORY_TIMEOUT_MS"],
            245,
            &now,
        ),
        definition(
            TASK_RUNNER_SCHEDULER_POLL_MS_CONFIG_KEY,
            "Scheduler 轮询间隔",
            "Task Runner Scheduler 扫描待执行 Run 的轮询间隔毫秒数",
            "Task Runner / Scheduler",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(15_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_SCHEDULER_POLL_MS"],
            246,
            &now,
        ),
        definition(
            TASK_RUNNER_RUN_EVENT_RETENTION_DAYS_CONFIG_KEY,
            "Run 事件保留天数",
            "Task Runner 只保留终态 Run 在该天数内的事件；运行中 Run 不会被清理",
            "Task Runner / Retention",
            "service",
            Some("task-runner"),
            "integer",
            json!(30),
            Some(1),
            Some(3650),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_EVENT_RETENTION_DAYS"],
            2461,
            &now,
        ),
        definition(
            TASK_RUNNER_RUN_EVENT_CLEANUP_INTERVAL_MS_CONFIG_KEY,
            "Run 事件清理间隔",
            "Task Runner Scheduler 执行终态 Run 过期事件清理的间隔毫秒数",
            "Task Runner / Retention",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(3_600_000),
            Some(60_000),
            Some(86_400_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_EVENT_CLEANUP_INTERVAL_MS"],
            2462,
            &now,
        ),
        definition(
            TASK_RUNNER_RUN_EVENT_CLEANUP_BATCH_SIZE_CONFIG_KEY,
            "Run 事件清理批次",
            "单轮最多检查包含过期事件的 Run 数量，限制清理操作对 MongoDB 的压力",
            "Task Runner / Retention",
            "service",
            Some("task-runner"),
            "integer",
            json!(200),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_EVENT_CLEANUP_BATCH_SIZE"],
            2463,
            &now,
        ),
        definition(
            TASK_RUNNER_TERMINAL_LOG_MAX_ENTRIES_CONFIG_KEY,
            "终端日志条目上限",
            "单个 Task Runner 终端会话在内存中保留的最大日志条目数",
            "Task Runner / Terminal",
            "service",
            Some("task-runner"),
            "integer",
            json!(4_000),
            Some(100),
            Some(100_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_TERMINAL_LOG_MAX_ENTRIES"],
            2464,
            &now,
        ),
        definition(
            TASK_RUNNER_TERMINAL_MAX_SESSIONS_CONFIG_KEY,
            "终端会话实例上限",
            "单个 Task Runner 实例允许保留的运行中和未过期终端会话总数",
            "Task Runner / Terminal",
            "service",
            Some("task-runner"),
            "integer",
            json!(512),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_TERMINAL_MAX_SESSIONS"],
            2465,
            &now,
        ),
        definition(
            TASK_RUNNER_TERMINAL_EXITED_SESSION_RETENTION_SECONDS_CONFIG_KEY,
            "已退出终端保留时间",
            "终端进程退出后继续保留会话元数据和日志的秒数，过期后自动清理",
            "Task Runner / Terminal",
            "service",
            Some("task-runner"),
            "integer",
            json!(86_400),
            Some(60),
            Some(2_592_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_TERMINAL_EXITED_SESSION_RETENTION_SECONDS"],
            2466,
            &now,
        ),
        definition(
            TASK_RUNNER_TERMINAL_CLEANUP_INTERVAL_MS_CONFIG_KEY,
            "终端会话清理间隔",
            "Task Runner 扫描并移除过期已退出终端会话的间隔毫秒数",
            "Task Runner / Terminal",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(60_000),
            Some(1_000),
            Some(3_600_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_TERMINAL_CLEANUP_INTERVAL_MS"],
            2467,
            &now,
        ),
        definition(
            TASK_RUNNER_ASK_USER_PROMPT_RETENTION_DAYS_CONFIG_KEY,
            "审批记录保留天数",
            "只清理已完成回执投递且关联 Run 已终态的过期 Ask User 审批记录",
            "Task Runner / Retention",
            "service",
            Some("task-runner"),
            "integer",
            json!(90),
            Some(1),
            Some(3650),
            &[],
            "restart_required",
            &["TASK_RUNNER_ASK_USER_PROMPT_RETENTION_DAYS"],
            2468,
            &now,
        ),
        definition(
            TASK_RUNNER_ASK_USER_PROMPT_CLEANUP_INTERVAL_MS_CONFIG_KEY,
            "审批记录清理间隔",
            "Task Runner Scheduler 清理过期审批记录的间隔毫秒数",
            "Task Runner / Retention",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(3_600_000),
            Some(60_000),
            Some(86_400_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_ASK_USER_PROMPT_CLEANUP_INTERVAL_MS"],
            2469,
            &now,
        ),
        definition(
            TASK_RUNNER_ASK_USER_PROMPT_CLEANUP_BATCH_SIZE_CONFIG_KEY,
            "审批记录清理批次",
            "单轮最多删除的过期审批记录数量，用于限制 MongoDB 清理压力",
            "Task Runner / Retention",
            "service",
            Some("task-runner"),
            "integer",
            json!(200),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_ASK_USER_PROMPT_CLEANUP_BATCH_SIZE"],
            2470,
            &now,
        ),
        definition(
            TASK_RUNNER_AUTO_MEMORY_SUMMARY_CONFIG_KEY,
            "自动记忆总结",
            "Task Runner 在需要时自动触发 Memory Engine 总结",
            "Task Runner / Memory",
            "service",
            Some("task-runner"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_AUTO_MEMORY_SUMMARY"],
            247,
            &now,
        ),
        definition(
            "task_runner.worker.concurrency",
            "Worker 并发数",
            "单个 Task Runner Worker 实例并发认领 Run 的上限；Run 在模型调用、环境准备等阶段也会占用槽位",
            "Task Runner / Worker",
            "service",
            Some("task-runner"),
            "integer",
            json!(5),
            Some(1),
            Some(256),
            &[],
            "restart_required",
            &["TASK_RUNNER_WORKER_CONCURRENCY"],
            260,
            &now,
        ),
        definition(
            "task_runner.worker.claim_ttl_ms",
            "Worker Claim TTL",
            "Worker 对 Run 的占用租约毫秒数",
            "Task Runner / Worker",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(120000),
            Some(1000),
            Some(3_600_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_WORKER_CLAIM_TTL_MS"],
            270,
            &now,
        ),
    ]
}
