use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            TASK_RUNNER_QUEUE_CALLBACK_DELIVERY_MODE_CONFIG_KEY,
            "回调投递模式",
            "控制 ChatOS 回调是由当前实例直接发送，还是进入 RabbitMQ 异步投递队列",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "enum",
            json!("rabbitmq"),
            None,
            None,
            &["inline", "rabbitmq"],
            "restart_required",
            &["TASK_RUNNER_CALLBACK_DELIVERY_MODE"],
            217,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RABBITMQ_URL_CONFIG_KEY,
            "RabbitMQ 连接地址",
            "Task Runner 队列模式连接 RabbitMQ 的 AMQP 地址",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!(DEFAULT_LOCAL_RABBITMQ_URL),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RABBITMQ_URL"],
            218,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RABBITMQ_EXCHANGE_CONFIG_KEY,
            "RabbitMQ Exchange",
            "Task Runner 队列模式使用的 RabbitMQ Exchange 名称",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RABBITMQ_EXCHANGE"],
            219,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RABBITMQ_RECONNECT_MS_CONFIG_KEY,
            "RabbitMQ 重连等待时间",
            "Task Runner 队列消费者连接中断后再次连接 RabbitMQ 的等待毫秒数",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(3_000),
            Some(100),
            Some(60_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RABBITMQ_RECONNECT_MS"],
            219,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_EVENT_OUTBOX_RECONCILE_MS_CONFIG_KEY,
            "事件 Outbox 补偿间隔",
            "扫描异常遗留待发布取消、终态和交互事件的低频补偿间隔毫秒数",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_EVENT_OUTBOX_RECONCILE_MS"],
            223,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_EVENT_OUTBOX_BATCH_SIZE_CONFIG_KEY,
            "事件 Outbox 补偿批次",
            "单轮最多补偿发布的取消、终态和交互事件数量",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_EVENT_OUTBOX_BATCH_SIZE"],
            224,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_WORKER_CONTROL_QUEUE_PREFIX_CONFIG_KEY,
            "Worker 控制队列前缀",
            "每个 Task Runner Worker 实例共享的定向控制事件队列名称前缀",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.worker.control"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_WORKER_CONTROL_QUEUE_PREFIX"],
            225,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_QUEUE_CONFIG_KEY,
            "Run 后处理队列名",
            "成功 Run 的 Memory 总结和后续任务调度使用的共享 RabbitMQ 队列名",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.run.post_process"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_QUEUE"],
            226,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_RETRY_QUEUE_CONFIG_KEY,
            "Run 后处理延迟重试队列名",
            "Run 后处理失败后等待 RabbitMQ 重新投递的共享延迟队列名",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.run.post_process.retry"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_RETRY_QUEUE"],
            227,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_DEAD_LETTER_QUEUE_CONFIG_KEY,
            "Run 后处理死信队列名",
            "Run 后处理达到最大投递次数后保存毒消息的 RabbitMQ 队列名",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.run.post_process.dead"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_DEAD_LETTER_QUEUE"],
            228,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_MAX_DELIVERY_ATTEMPTS_CONFIG_KEY,
            "Run 后处理最大投递次数",
            "Run 后处理进入死信队列前允许的最大失败投递次数",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "integer",
            json!(8),
            Some(1),
            Some(100),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_MAX_DELIVERY_ATTEMPTS"],
            229,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_RETRY_DELAY_MS_CONFIG_KEY,
            "Run 后处理重试等待时间",
            "Run 后处理失败后由 RabbitMQ 延迟再次触发的等待毫秒数",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_RETRY_DELAY_MS"],
            228,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_OUTBOX_RECONCILE_MS_CONFIG_KEY,
            "Run 后处理 Outbox 补偿间隔",
            "低频补偿发布异常遗留的 Run 后处理和定向终端清理事件，不用于业务任务发现",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_OUTBOX_RECONCILE_MS"],
            229,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_POST_PROCESS_OUTBOX_BATCH_SIZE_CONFIG_KEY,
            "Run 后处理 Outbox 补偿批次",
            "单轮最多补偿发布的 Run 后处理和定向终端清理事件数量",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_POST_PROCESS_OUTBOX_BATCH_SIZE"],
            230,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_CALLBACK_DELIVERY_QUEUE_CONFIG_KEY,
            "回调投递队列名",
            "Task Runner 异步投递 ChatOS 回调时使用的 RabbitMQ 队列名",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.callback.delivery"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_CALLBACK_DELIVERY_QUEUE"],
            221,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_EVENTS_PUBLISH_MODE_CONFIG_KEY,
            "Run 事件发布模式",
            "持久化 Run 事件后必须通过 RabbitMQ 广播到各 API 实例",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "enum",
            json!("rabbitmq"),
            None,
            None,
            &["rabbitmq"],
            "restart_required",
            &["TASK_RUNNER_RUN_EVENTS_PUBLISH_MODE"],
            222,
            now,
        ),
        definition(
            TASK_RUNNER_QUEUE_RUN_EVENTS_ROUTING_KEY_CONFIG_KEY,
            "Run 事件广播路由键",
            "Task Runner 发布 Run 事件、API 实例绑定临时消费队列时使用的 RabbitMQ 路由键",
            "Task Runner / Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.run.events.broadcast"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_RUN_EVENTS_ROUTING_KEY"],
            223,
            now,
        ),
        definition(
            TASK_RUNNER_MCP_RESULT_QUEUE_PREFIX_CONFIG_KEY,
            "MCP 结果队列前缀",
            "Task Runner 按实例创建共享 MCP 结果消费队列使用的名称前缀",
            "Task Runner / MCP Queue",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner.mcp.results"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_MCP_RESULT_QUEUE_PREFIX"],
            225,
            now,
        ),
        definition(
            TASK_RUNNER_PRESSURE_QUEUE_ELEVATED_MESSAGES_CONFIG_KEY,
            "Task Runner 队列升压阈值",
            "Task Runner 自有主队列 ready 消息总数达到该值时上报 elevated",
            "Task Runner / Pressure",
            "service",
            Some("task-runner"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000_000),
            &[],
            "hot_reload",
            &[],
            2251,
            now,
        ),
        definition(
            TASK_RUNNER_PRESSURE_QUEUE_CRITICAL_MESSAGES_CONFIG_KEY,
            "Task Runner 队列临界阈值",
            "Task Runner 自有主队列 ready 消息总数达到该值时上报 critical",
            "Task Runner / Pressure",
            "service",
            Some("task-runner"),
            "integer",
            json!(1_000),
            Some(2),
            Some(100_000_000),
            &[],
            "hot_reload",
            &[],
            2252,
            now,
        ),
        definition(
            TASK_RUNNER_PRESSURE_REPORT_INTERVAL_MS_CONFIG_KEY,
            "Task Runner 压力上报间隔",
            "Task Runner 刷新压力策略并上报自身队列压力信号的间隔",
            "Task Runner / Pressure",
            "service",
            Some("task-runner"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "hot_reload",
            &[],
            2253,
            now,
        ),
    ]
}
