use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            TASK_RUNNER_HOST_CONFIG_KEY,
            "Host",
            "Task Runner HTTP 服务监听地址",
            "Task Runner / Runtime",
            "service",
            Some("task-runner"),
            "string",
            json!("127.0.0.1"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_HOST"],
            294,
            now,
        ),
        definition(
            TASK_RUNNER_PORT_CONFIG_KEY,
            "Port",
            "Task Runner HTTP 服务监听端口",
            "Task Runner / Runtime",
            "service",
            Some("task-runner"),
            "integer",
            json!(39090),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["TASK_RUNNER_PORT"],
            294,
            now,
        ),
        definition(
            TASK_RUNNER_INTERNAL_MTLS_PORT_CONFIG_KEY,
            "Internal mTLS Port",
            "Task Runner 内部控制面强制 mTLS 监听端口",
            "Task Runner / Runtime Security",
            "service",
            Some("task-runner"),
            "integer",
            json!(39092),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["TASK_RUNNER_INTERNAL_MTLS_PORT"],
            295,
            now,
        ),
        secret_definition(
            TASK_RUNNER_DATABASE_URL_CONFIG_KEY,
            "Database URL",
            "Task Runner 连接存储后端时使用的数据库连接串",
            "Task Runner / Runtime",
            "service",
            Some("task-runner"),
            json!("mongodb://admin:admin@127.0.0.1:27018/task_runner_service?authSource=admin"),
            "restart_required",
            &["TASK_RUNNER_DATABASE_URL"],
            294,
            now,
        ),
        definition(
            TASK_RUNNER_MONGODB_DATABASE_CONFIG_KEY,
            "MongoDB Database",
            "Task Runner 使用的 MongoDB database 名称",
            "Task Runner / Runtime",
            "service",
            Some("task-runner"),
            "string",
            json!("task_runner_service"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_MONGODB_DATABASE"],
            294,
            now,
        ),
        definition(
            TASK_RUNNER_WORKSPACE_DIR_CONFIG_KEY,
            "Workspace Dir",
            "Task Runner 默认工作区根目录",
            "Task Runner / Runtime",
            "service",
            Some("task-runner"),
            "string",
            json!("."),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_WORKSPACE_DIR"],
            294,
            now,
        ),
        definition(
            TASK_RUNNER_ADMIN_USERNAME_CONFIG_KEY,
            "Admin Username",
            "Task Runner 启动时自动确保存在的管理员用户名",
            "Task Runner / Bootstrap",
            "service",
            Some("task-runner"),
            "string",
            json!("admin"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_ADMIN_USERNAME"],
            294,
            now,
        ),
        secret_definition(
            TASK_RUNNER_ADMIN_PASSWORD_CONFIG_KEY,
            "Admin Password",
            "Task Runner 启动时自动确保存在的管理员密码",
            "Task Runner / Bootstrap",
            "service",
            Some("task-runner"),
            json!("admin123456"),
            "restart_required",
            &["TASK_RUNNER_ADMIN_PASSWORD"],
            295,
            now,
        ),
        definition(
            TASK_RUNNER_ADMIN_DISPLAY_NAME_CONFIG_KEY,
            "Admin Display Name",
            "Task Runner 启动时自动确保存在的管理员显示名称",
            "Task Runner / Bootstrap",
            "service",
            Some("task-runner"),
            "string",
            json!("System Admin"),
            None,
            None,
            &[],
            "restart_required",
            &["TASK_RUNNER_ADMIN_DISPLAY_NAME"],
            296,
            now,
        ),
    ]
}
