import type { ChatMessage, DemoProject, DemoTask } from './types';

export const demoProjects: DemoProject[] = [
  {
    id: 'personal-website',
    name: '我的个人网站',
    subtitle: '作品、简历与个人主页',
    status: 'running',
    progress: 68,
    accent: '#7a4b35',
    updatedAt: '刚刚',
    summary: '用户创建的个人网站项目，包含首页、作品集、博客和个人介绍。',
    files: ['首页设计稿', '作品集资料', '博客内容'],
  },
  {
    id: 'travel-planner',
    name: '旅行计划助手',
    subtitle: '行程、预算与地图资料',
    status: 'planning',
    progress: 42,
    accent: '#526b63',
    updatedAt: '12 分钟前',
    summary: '用户为下一次旅行建立的项目，AI 正在整理路线、住宿和每日计划。',
    files: ['路线草案', '酒店清单', '预算表'],
  },
  {
    id: 'home-renovation',
    name: '新家改造',
    subtitle: '空间、家具与采购记录',
    status: 'idle',
    progress: 84,
    accent: '#8b6d4d',
    updatedAt: '昨天',
    summary: '用户保存的装修计划，包含房间尺寸、家具清单和施工时间安排。',
    files: ['客厅方案', '家具尺寸', '采购清单'],
  },
  {
    id: 'photo-album',
    name: '家庭影像馆',
    subtitle: '照片整理与数字相册',
    status: 'idle',
    progress: 91,
    accent: '#6c5550',
    updatedAt: '3 天前',
    summary: '用户自己的家庭照片整理项目，AI 协助分类、补充说明并生成相册。',
    files: ['2025 年照片', '家庭成员', '待整理影像'],
  },
  {
    id: 'reading-notes',
    name: '年度阅读计划',
    subtitle: '书单、笔记与阅读进度',
    status: 'running',
    progress: 57,
    accent: '#526577',
    updatedAt: '5 天前',
    summary: '用户维护的年度阅读项目，AI 帮助整理书单、摘录、读后感和主题索引。',
    files: ['年度书单', '读书摘录', '主题索引'],
  },
  {
    id: 'fitness-journal',
    name: '健身与饮食记录',
    subtitle: '训练计划、体测与菜谱',
    status: 'planning',
    progress: 33,
    accent: '#68724e',
    updatedAt: '1 周前',
    summary: '用户建立的健康管理项目，记录每周训练、身体数据和日常饮食安排。',
    files: ['本周训练', '身体数据', '饮食计划'],
  },
  {
    id: 'language-learning',
    name: '英语学习空间',
    subtitle: '词汇、听力与口语练习',
    status: 'running',
    progress: 49,
    accent: '#665676',
    updatedAt: '8 天前',
    summary: '用户的长期语言学习项目，集中保存词汇、听力材料、口语练习和复习计划。',
    files: ['核心词汇', '听力材料', '口语复盘'],
  },
  {
    id: 'family-budget',
    name: '家庭财务计划',
    subtitle: '预算、账单与储蓄目标',
    status: 'planning',
    progress: 28,
    accent: '#756344',
    updatedAt: '2 周前',
    summary: '用户创建的家庭财务项目，用来整理月度预算、固定账单和阶段性储蓄目标。',
    files: ['月度预算', '固定账单', '储蓄目标'],
  },
];

export const demoTasks: DemoTask[] = [
  {
    id: 'task-scene',
    title: '搭建写实 3D 房间',
    status: 'doing',
    progress: 72,
    detail: '正在调整镜头、窗景、桌面物件和低性能设备的渲染策略。',
    conversationId: 'demo-room',
    conversationTitle: '3D 工作空间改造',
    conversationTurnId: 'demo-turn-room',
    createdAt: '今天 09:10',
    updatedAt: '刚刚',
  },
  {
    id: 'task-chat',
    title: '同步 ChatOS 实时消息',
    status: 'doing',
    progress: 58,
    detail: '正在监听前端 WebSocket 事件，并同步聊天、任务和会话状态。',
    conversationId: 'demo-room',
    conversationTitle: '3D 工作空间改造',
    conversationTurnId: 'demo-turn-room',
    createdAt: '今天 09:18',
    updatedAt: '2 分钟前',
  },
  {
    id: 'task-assets',
    title: '优化场景素材体积',
    status: 'blocked',
    progress: 35,
    detail: '等待最终美术风格和模型精度确认。',
    conversationId: 'demo-room',
    conversationTitle: '3D 工作空间改造',
    conversationTurnId: 'demo-turn-room',
    createdAt: '昨天 18:40',
    updatedAt: '昨天',
  },
  {
    id: 'task-fallback',
    title: '经典模式回退',
    status: 'done',
    progress: 100,
    detail: '保留原有界面作为无 WebGL 和低性能设备的入口。',
    conversationId: 'demo-room',
    conversationTitle: '3D 工作空间改造',
    conversationTurnId: 'demo-turn-room',
    createdAt: '3 天前',
    updatedAt: '昨天',
    completedAt: '昨天 16:20',
  },
];

export const initialMessages: ChatMessage[] = [
  {
    id: 'welcome-user',
    role: 'user',
    content: '今天我们先把新的 3D 聊天主页做出来。',
    time: '09:41',
  },
  {
    id: 'welcome-assistant',
    role: 'assistant',
    content: '好。写实房间、左墙六项目书架和实时任务墙已经准备好了，小猫也在桌上等你。',
    time: '09:41',
  },
];
