use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            MEMORY_ENGINE_REQUIRE_SIGNED_INTERNAL_REQUESTS_CONFIG_KEY,
            "内部请求必须签名",
            "Memory Engine 是否必须校验来自内部服务的签名请求",
            "Memory Engine / Security",
            "service",
            Some("memory-engine"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_REQUIRE_SIGNED_INTERNAL_REQUESTS"],
            358,
            &now,
        ),
        secret_definition(
            MEMORY_ENGINE_CHATOS_INTERNAL_API_SECRET_CONFIG_KEY,
            "Chatos Internal Secret",
            "Memory Engine 校验来自 Chatos Backend 的内部签名请求时使用的共享密钥",
            "Memory Engine / Security",
            "service",
            Some("memory-engine"),
            json!("change_me_chatos_memory_engine_secret"),
            "restart_required",
            &["CHATOS_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            359,
            &now,
        ),
        secret_definition(
            MEMORY_ENGINE_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Task Runner Internal Secret",
            "Memory Engine 校验来自 Task Runner 的内部签名请求时使用的共享密钥",
            "Memory Engine / Security",
            "service",
            Some("memory-engine"),
            json!("change_me_task_runner_memory_engine_secret"),
            "restart_required",
            &["TASK_RUNNER_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            360,
            &now,
        ),
        secret_definition(
            MEMORY_ENGINE_USER_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "User Service Internal Secret",
            "Memory Engine 校验来自 User Service 的内部签名请求时使用的共享密钥",
            "Memory Engine / Security",
            "service",
            Some("memory-engine"),
            json!("change_me_user_service_memory_engine_secret"),
            "restart_required",
            &["USER_SERVICE_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            362,
            &now,
        ),
        secret_definition(
            MEMORY_ENGINE_CONFIGURATION_CENTER_INTERNAL_API_SECRET_CONFIG_KEY,
            "Configuration Center Internal Secret",
            "Memory Engine 校验来自 Configuration Center 队列运维请求时使用的专用密钥",
            "Memory Engine / Security",
            "service",
            Some("memory-engine"),
            json!("change_me_configuration_center_memory_engine_secret"),
            "restart_required",
            &["CONFIGURATION_CENTER_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            363,
            &now,
        ),
        secret_definition(
            MEMORY_ENGINE_PLUGIN_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "Plugin Management Internal Secret",
            "Memory Engine 调用 Plugin Management 内部接口时使用的专用密钥",
            "Memory Engine / Downstream Security",
            "service",
            Some("memory-engine"),
            json!("change_me_plugin_management_memory_engine_secret"),
            "restart_required",
            &["PLUGIN_MANAGEMENT_MEMORY_ENGINE_INTERNAL_API_SECRET"],
            363,
            &now,
        ),
        definition(
            MEMORY_ENGINE_HOST_CONFIG_KEY,
            "Host",
            "Memory Engine HTTP 服务监听地址",
            "Memory Engine / Runtime",
            "service",
            Some("memory-engine"),
            "string",
            json!("0.0.0.0"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_HOST"],
            3630,
            &now,
        ),
        definition(
            MEMORY_ENGINE_PORT_CONFIG_KEY,
            "Port",
            "Memory Engine HTTP 服务监听端口",
            "Memory Engine / Runtime",
            "service",
            Some("memory-engine"),
            "integer",
            json!(7081),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_PORT"],
            3630,
            &now,
        ),
        definition(
            MEMORY_ENGINE_INTERNAL_MTLS_PORT_CONFIG_KEY,
            "Internal mTLS Port",
            "Memory Engine 内部控制面强制 mTLS 监听端口",
            "Memory Engine / Runtime",
            "service",
            Some("memory-engine"),
            "integer",
            json!(7083),
            Some(1),
            Some(65535),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_INTERNAL_MTLS_PORT"],
            3630,
            &now,
        ),
        secret_definition(
            MEMORY_ENGINE_MONGODB_URI_CONFIG_KEY,
            "MongoDB URI",
            "Memory Engine 连接 MongoDB 使用的连接串",
            "Memory Engine / Runtime",
            "service",
            Some("memory-engine"),
            json!("mongodb://admin:admin@127.0.0.1:27018/admin"),
            "restart_required",
            &["MEMORY_ENGINE_MONGODB_URI"],
            3630,
            &now,
        ),
        definition(
            MEMORY_ENGINE_MONGODB_DATABASE_CONFIG_KEY,
            "MongoDB Database",
            "Memory Engine 使用的 MongoDB database 名称",
            "Memory Engine / Runtime",
            "service",
            Some("memory-engine"),
            "string",
            json!("memory_engine"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_MONGODB_DATABASE"],
            3630,
            &now,
        ),
        definition(
            MEMORY_ENGINE_USER_SERVICE_BASE_URL_CONFIG_KEY,
            "User Service Base URL",
            "Memory Engine 调用 User Service 时使用的基础地址",
            "Memory Engine / Downstream",
            "service",
            Some("memory-engine"),
            "string",
            json!("http://127.0.0.1:39190"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_USER_SERVICE_BASE_URL"],
            3631,
            &now,
        ),
        definition(
            MEMORY_ENGINE_USER_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "User Service 请求超时（毫秒）",
            "Memory Engine 调用 User Service 时使用的超时时间",
            "Memory Engine / Downstream",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(60_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_USER_SERVICE_REQUEST_TIMEOUT_MS"],
            3632,
            &now,
        ),
        definition(
            MEMORY_ENGINE_AI_REQUEST_TIMEOUT_SECS_CONFIG_KEY,
            "AI 请求超时（秒）",
            "Memory Engine 调用上游模型服务时使用的超时时间",
            "Memory Engine / AI",
            "service",
            Some("memory-engine"),
            "integer",
            json!(60),
            Some(5),
            Some(600),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_AI_TIMEOUT_SECS"],
            3633,
            &now,
        ),
        nullable_secret_definition(
            MEMORY_ENGINE_OPENAI_API_KEY_CONFIG_KEY,
            "OpenAI API Key",
            "Memory Engine 默认调用 OpenAI 兼容模型服务时使用的 API Key，留空表示仅使用用户自定义 profile key",
            "Memory Engine / AI",
            "service",
            Some("memory-engine"),
            Value::Null,
            "restart_required",
            &["MEMORY_ENGINE_OPENAI_API_KEY"],
            3634,
            &now,
        ),
        definition(
            MEMORY_ENGINE_OPENAI_BASE_URL_CONFIG_KEY,
            "OpenAI Base URL",
            "Memory Engine 默认调用的 OpenAI 兼容服务基础地址",
            "Memory Engine / AI",
            "service",
            Some("memory-engine"),
            "string",
            json!("https://api.openai.com/v1"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_OPENAI_BASE_URL"],
            3635,
            &now,
        ),
        definition(
            MEMORY_ENGINE_OPENAI_MODEL_CONFIG_KEY,
            "OpenAI 默认模型",
            "Memory Engine 默认使用的模型名称",
            "Memory Engine / AI",
            "service",
            Some("memory-engine"),
            "string",
            json!("gpt-4o-mini"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_OPENAI_MODEL"],
            3636,
            &now,
        ),
        definition(
            MEMORY_ENGINE_OPENAI_TEMPERATURE_CONFIG_KEY,
            "OpenAI Temperature",
            "Memory Engine 默认模型请求使用的 temperature 值，使用字符串形式保存小数",
            "Memory Engine / AI",
            "service",
            Some("memory-engine"),
            "string",
            json!("0.2"),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_OPENAI_TEMPERATURE"],
            3637,
            &now,
        ),
    ]
}
