use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            SANDBOX_MANAGER_REQUIRE_SIGNED_INTERNAL_REQUESTS_CONFIG_KEY,
            "内部请求必须签名",
            "Sandbox Manager 是否必须校验来自内部服务的签名请求",
            "Sandbox Manager / Security",
            "service",
            Some("sandbox-manager"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_REQUIRE_SIGNED_INTERNAL_REQUESTS"],
            364,
            &now,
        ),
        secret_definition(
            SANDBOX_MANAGER_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
            "Project Service Internal Secret",
            "Sandbox Manager 校验来自 Project Service 的内部签名请求时使用的共享密钥",
            "Sandbox Manager / Security",
            "service",
            Some("sandbox-manager"),
            json!("change_me_project_service_sandbox_manager_secret"),
            "restart_required",
            &["PROJECT_SERVICE_SANDBOX_MANAGER_INTERNAL_API_SECRET"],
            366,
            &now,
        ),
        secret_definition(
            SANDBOX_MANAGER_MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
            "MCP Management Internal Secret",
            "Sandbox Manager 校验来自 MCP Management 的内部签名请求时使用的共享密钥",
            "Sandbox Manager / Security",
            "service",
            Some("sandbox-manager"),
            json!("change_me_mcp_management_sandbox_manager_secret"),
            "restart_required",
            &["MCP_MANAGEMENT_SANDBOX_MANAGER_INTERNAL_API_SECRET"],
            367,
            &now,
        ),
        secret_definition(
            SANDBOX_MANAGER_AGENT_TOKEN_SECRET_CONFIG_KEY,
            "Sandbox Manager Agent Token Secret",
            "Sandbox Agent 与 Sandbox Manager 之间签发与校验代理 token 使用的共享密钥",
            "Sandbox Manager / Security",
            "service",
            Some("sandbox-manager"),
            json!(DEFAULT_SANDBOX_MANAGER_AGENT_TOKEN_SECRET),
            "restart_required",
            &["SANDBOX_MANAGER_AGENT_TOKEN_SECRET"],
            371,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_FRONTEND_PROXY_CLIENT_ID_CONFIG_KEY,
            "Sandbox Console Proxy Client ID",
            "Sandbox Manager 控制台反向代理使用的受管访问客户端标识",
            "Sandbox Manager / Frontend",
            "service",
            Some("sandbox-manager"),
            "string",
            json!("sandbox-manager-frontend"),
            None,
            None,
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_FRONTEND_PROXY_CLIENT_ID"],
            37101,
            &now,
        ),
        secret_definition(
            SANDBOX_MANAGER_FRONTEND_PROXY_CLIENT_KEY_CONFIG_KEY,
            "Sandbox Console Proxy Client Key",
            "Sandbox Manager 控制台反向代理使用的受管访问客户端密钥",
            "Sandbox Manager / Frontend",
            "service",
            Some("sandbox-manager"),
            json!("change_me_sandbox_manager_frontend_proxy_client_key"),
            "restart_required",
            &["SANDBOX_MANAGER_FRONTEND_PROXY_CLIENT_KEY"],
            37102,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_REQUIRE_AUTH_CONFIG_KEY,
            "启用接口认证",
            "Sandbox Manager 是否启用真实用户、权限受限 access client 与内部服务签名认证",
            "Sandbox Manager / Runtime",
            "service",
            Some("sandbox-manager"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_REQUIRE_AUTH"],
            3711,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_USER_SERVICE_BASE_URL_CONFIG_KEY,
            "User Service Base URL",
            "Sandbox Manager 调用 User Service 时使用的基础地址",
            "Sandbox Manager / Downstream",
            "service",
            Some("sandbox-manager"),
            "string",
            json!("http://127.0.0.1:39190"),
            None,
            None,
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_USER_SERVICE_BASE_URL"],
            3712,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_USER_SERVICE_REQUEST_TIMEOUT_MS_CONFIG_KEY,
            "User Service 请求超时（毫秒）",
            "Sandbox Manager 调用 User Service 时使用的超时时间",
            "Sandbox Manager / Downstream",
            "service",
            Some("sandbox-manager"),
            "duration_ms",
            json!(5_000),
            Some(300),
            Some(60_000),
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_USER_SERVICE_REQUEST_TIMEOUT_MS"],
            3713,
            &now,
        ),
        definition(
            SANDBOX_MANAGER_SYSTEM_CLIENT_MAX_LEASE_TTL_SECONDS_CONFIG_KEY,
            "System Client 最大租约 TTL（秒）",
            "Sandbox Manager 内置系统客户端能够申请的最大租约时长",
            "Sandbox Manager / Security",
            "service",
            Some("sandbox-manager"),
            "integer",
            json!(7_200),
            Some(60),
            Some(7 * 24 * 60 * 60),
            &[],
            "restart_required",
            &["SANDBOX_MANAGER_SYSTEM_CLIENT_MAX_LEASE_TTL_SECONDS"],
            3718,
            &now,
        ),
    ]
}
