use super::*;

pub(super) fn definitions(now: &str) -> Vec<ConfigDefinitionRecord> {
    vec![
        definition(
            MEMORY_ENGINE_WORKER_ENABLED_CONFIG_KEY,
            "启用 Worker",
            "Memory Engine 是否启用后台 worker 处理摘要与记忆任务",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "boolean",
            json!(true),
            None,
            None,
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_ENABLED"],
            3638,
            now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_INTERVAL_SECS_CONFIG_KEY,
            "Worker 恢复检查间隔（秒）",
            "Memory Engine worker 认领数据库待处理记录，并执行异常恢复检查的间隔",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(30),
            Some(3),
            Some(3600),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_INTERVAL_SECS"],
            3639,
            now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_MAX_THREADS_PER_TICK_CONFIG_KEY,
            "单轮最大线程数",
            "Memory Engine worker 每轮最多处理的线程数量",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(10),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_MAX_THREADS_PER_TICK"],
            3640,
            now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_SUMMARY_CONCURRENCY_CONFIG_KEY,
            "摘要并发数",
            "Memory Engine worker 处理 summary 任务时的并发数",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(4),
            Some(1),
            Some(1024),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_SUMMARY_CONCURRENCY"],
            3641,
            now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_PRESSURE_SUMMARY_CONCURRENCY_CONFIG_KEY,
            "压力状态摘要并发数",
            "平台压力为 elevated 或 critical 时 Memory Engine 保留的 summary 消费并发数",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(1),
            Some(1),
            Some(1024),
            &[],
            "hot_reload",
            &[],
            3642,
            now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_PRESSURE_REFRESH_INTERVAL_MS_CONFIG_KEY,
            "压力状态刷新间隔",
            "Memory Engine 从配置中心严格刷新平台压力状态的间隔",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "hot_reload",
            &[],
            3643,
            now,
        ),
        definition(
            MEMORY_ENGINE_PRESSURE_QUEUE_ELEVATED_MESSAGES_CONFIG_KEY,
            "Memory 队列升压阈值",
            "Memory Engine 自有主队列 ready 消息总数达到该值时上报 elevated",
            "Memory Engine / Pressure",
            "service",
            Some("memory-engine"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000_000),
            &[],
            "hot_reload",
            &[],
            3644,
            now,
        ),
        definition(
            MEMORY_ENGINE_PRESSURE_QUEUE_CRITICAL_MESSAGES_CONFIG_KEY,
            "Memory 队列临界阈值",
            "Memory Engine 自有主队列 ready 消息总数达到该值时上报 critical",
            "Memory Engine / Pressure",
            "service",
            Some("memory-engine"),
            "integer",
            json!(1_000),
            Some(2),
            Some(100_000_000),
            &[],
            "hot_reload",
            &[],
            3645,
            now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_ROLLUP_CONCURRENCY_CONFIG_KEY,
            "Rollup 并发数",
            "Memory Engine worker 处理 rollup 任务时的并发数",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(3),
            Some(1),
            Some(1024),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_ROLLUP_CONCURRENCY"],
            3646,
            now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_SUBJECT_MEMORY_CONCURRENCY_CONFIG_KEY,
            "Subject Memory 并发数",
            "Memory Engine worker 处理 subject memory 任务时的并发数",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(2),
            Some(1),
            Some(1024),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_SUBJECT_MEMORY_CONCURRENCY"],
            3647,
            now,
        ),
        definition(
            MEMORY_ENGINE_WORKER_RECONCILE_CONCURRENCY_CONFIG_KEY,
            "Reconcile 并发数",
            "Memory Engine worker 处理 reconcile 任务时的并发数",
            "Memory Engine / Worker",
            "service",
            Some("memory-engine"),
            "integer",
            json!(2),
            Some(1),
            Some(1024),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_WORKER_RECONCILE_CONCURRENCY"],
            3648,
            now,
        ),
        definition(
            MEMORY_ENGINE_CLOUD_AGENT_OUTBOX_RECONCILE_MS_CONFIG_KEY,
            "Cloud Agent Outbox 补偿间隔",
            "低频补偿发布异常遗留的 Memory Engine Cloud Agent 事件，不用于任务发现",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_CLOUD_AGENT_OUTBOX_RECONCILE_MS"],
            36471,
            now,
        ),
        definition(
            MEMORY_ENGINE_CLOUD_AGENT_OUTBOX_BATCH_SIZE_CONFIG_KEY,
            "Cloud Agent Outbox 补偿批次",
            "单轮最多补偿发布的 Memory Engine Cloud Agent 事件数量",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_CLOUD_AGENT_OUTBOX_BATCH_SIZE"],
            36472,
            now,
        ),
        definition(
            MEMORY_ENGINE_SUMMARY_MAX_DELIVERY_ATTEMPTS_CONFIG_KEY,
            "摘要最大投递次数",
            "摘要事件进入死信队列前允许的最大失败投递次数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(8),
            Some(1),
            Some(100),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUMMARY_MAX_DELIVERY_ATTEMPTS"],
            3650,
            now,
        ),
        definition(
            MEMORY_ENGINE_SUMMARY_RETRY_DELAY_MS_CONFIG_KEY,
            "摘要重试等待时间",
            "摘要执行失败后允许数据库 worker 再次认领的等待毫秒数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUMMARY_RETRY_DELAY_MS"],
            3651,
            now,
        ),
        definition(
            MEMORY_ENGINE_SUMMARY_OUTBOX_RECONCILE_MS_CONFIG_KEY,
            "摘要 Outbox 补偿间隔",
            "低频补偿发布异常遗留的摘要事件，不用于正常摘要任务发现",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(5_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUMMARY_OUTBOX_RECONCILE_MS"],
            3652,
            now,
        ),
        definition(
            MEMORY_ENGINE_SUMMARY_OUTBOX_BATCH_SIZE_CONFIG_KEY,
            "摘要 Outbox 补偿批次",
            "单轮最多补偿发布的摘要事件数量",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUMMARY_OUTBOX_BATCH_SIZE"],
            3653,
            now,
        ),
        definition(
            MEMORY_ENGINE_RECORD_SYNC_LEASE_TIMEOUT_SECS_CONFIG_KEY,
            "记录同步租约超时",
            "批量记录同步异常退出后，允许低频恢复流程接管计数修复的等待秒数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(300),
            Some(30),
            Some(86_400),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_RECORD_SYNC_LEASE_TIMEOUT_SECS"],
            3654,
            now,
        ),
        definition(
            MEMORY_ENGINE_ROLLUP_LOCK_TIMEOUT_SECS_CONFIG_KEY,
            "Rollup 抢占锁超时",
            "同一线程 rollup Worker 异常退出后允许其它事件重新认领的等待秒数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(300),
            Some(30),
            Some(86_400),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ROLLUP_LOCK_TIMEOUT_SECS"],
            3655,
            now,
        ),
        definition(
            MEMORY_ENGINE_ROLLUP_MAX_DELIVERY_ATTEMPTS_CONFIG_KEY,
            "Rollup 最大投递次数",
            "Rollup 事件进入死信队列前允许的最大失败投递次数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(8),
            Some(1),
            Some(100),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ROLLUP_MAX_DELIVERY_ATTEMPTS"],
            3659,
            now,
        ),
        definition(
            MEMORY_ENGINE_ROLLUP_RETRY_DELAY_MS_CONFIG_KEY,
            "Rollup 重试等待时间",
            "Rollup 执行失败后允许数据库 worker 再次认领的等待毫秒数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ROLLUP_RETRY_DELAY_MS"],
            3660,
            now,
        ),
        definition(
            MEMORY_ENGINE_ROLLUP_OUTBOX_RECONCILE_MS_CONFIG_KEY,
            "Rollup Outbox 补偿间隔",
            "低频补偿发布异常遗留的 Rollup 事件，不用于正常任务发现",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(30_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ROLLUP_OUTBOX_RECONCILE_MS"],
            3661,
            now,
        ),
        definition(
            MEMORY_ENGINE_ROLLUP_OUTBOX_BATCH_SIZE_CONFIG_KEY,
            "Rollup Outbox 补偿批次",
            "单轮最多补偿发布的 Rollup 事件数量",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_ROLLUP_OUTBOX_BATCH_SIZE"],
            3662,
            now,
        ),
        definition(
            MEMORY_ENGINE_SUBJECT_MEMORY_MAX_DELIVERY_ATTEMPTS_CONFIG_KEY,
            "主体记忆最大投递次数",
            "主体记忆事件进入死信队列前允许的最大失败投递次数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(8),
            Some(1),
            Some(100),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUBJECT_MEMORY_MAX_DELIVERY_ATTEMPTS"],
            3666,
            now,
        ),
        definition(
            MEMORY_ENGINE_SUBJECT_MEMORY_RETRY_DELAY_MS_CONFIG_KEY,
            "主体记忆重试等待时间",
            "主体记忆事件失败后允许数据库 worker 再次认领的等待毫秒数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(5_000),
            Some(100),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUBJECT_MEMORY_RETRY_DELAY_MS"],
            3667,
            now,
        ),
        definition(
            MEMORY_ENGINE_SUBJECT_MEMORY_OUTBOX_RECONCILE_MS_CONFIG_KEY,
            "主体记忆 Outbox 补偿间隔",
            "低频补偿异常遗留事件和跨文档扇出中断，不用于正常任务发现",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "duration_ms",
            json!(30_000),
            Some(1_000),
            Some(300_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUBJECT_MEMORY_OUTBOX_RECONCILE_MS"],
            3668,
            now,
        ),
        definition(
            MEMORY_ENGINE_SUBJECT_MEMORY_OUTBOX_BATCH_SIZE_CONFIG_KEY,
            "主体记忆 Outbox 补偿批次",
            "单轮最多补偿发布的主体记忆来源和 scope 事件数量",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(100),
            Some(1),
            Some(10_000),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUBJECT_MEMORY_OUTBOX_BATCH_SIZE"],
            3669,
            now,
        ),
        definition(
            MEMORY_ENGINE_SUBJECT_MEMORY_LOCK_TIMEOUT_SECS_CONFIG_KEY,
            "主体记忆 scope 抢占锁超时",
            "同一主体记忆 scope Worker 异常退出后允许其它事件重新认领的等待秒数",
            "Memory Engine / Queue",
            "service",
            Some("memory-engine"),
            "integer",
            json!(300),
            Some(30),
            Some(86_400),
            &[],
            "restart_required",
            &["MEMORY_ENGINE_SUBJECT_MEMORY_LOCK_TIMEOUT_SECS"],
            3670,
            now,
        ),
    ]
}
