// Generated by scripts/sync-daisyui-registry.mjs from the official daisyUI v5.7.28 documentation.
import type { UiComponentVariant } from './ui-library.js';
export const DAISYUI_OFFICIAL_COMPONENT_VARIANTS = {
  "Accordion": [
    {
      "id": "accordion-1",
      "label": "Accordion using radio inputs",
      "props": {
        "registryDemo": "accordion-1"
      }
    },
    {
      "id": "accordion-2",
      "label": "Accordion using details",
      "props": {
        "registryDemo": "accordion-2"
      }
    },
    {
      "id": "accordion-3",
      "label": "Accordion with arrow icon",
      "props": {
        "registryDemo": "accordion-3"
      }
    },
    {
      "id": "accordion-4",
      "label": "Accordion with plus/minus icon",
      "props": {
        "registryDemo": "accordion-4"
      }
    },
    {
      "id": "accordion-5",
      "label": "Using Accordion and Join together",
      "props": {
        "registryDemo": "accordion-5"
      }
    }
  ],
  "Alert": [
    {
      "id": "alert-1",
      "label": "Alert",
      "props": {
        "registryDemo": "alert-1"
      }
    },
    {
      "id": "alert-2",
      "label": "Info color",
      "props": {
        "registryDemo": "alert-2"
      }
    },
    {
      "id": "alert-3",
      "label": "Success color",
      "props": {
        "registryDemo": "alert-3"
      }
    },
    {
      "id": "alert-4",
      "label": "Warning color",
      "props": {
        "registryDemo": "alert-4"
      }
    },
    {
      "id": "alert-5",
      "label": "Error color",
      "props": {
        "registryDemo": "alert-5"
      }
    },
    {
      "id": "alert-6",
      "label": "Alert soft style",
      "props": {
        "registryDemo": "alert-6"
      }
    },
    {
      "id": "alert-7",
      "label": "Alert outline style",
      "props": {
        "registryDemo": "alert-7"
      }
    },
    {
      "id": "alert-8",
      "label": "Alert dash style",
      "props": {
        "registryDemo": "alert-8"
      }
    },
    {
      "id": "alert-9",
      "label": "Alert with buttons + responsive",
      "props": {
        "registryDemo": "alert-9"
      }
    },
    {
      "id": "alert-10",
      "label": "Alert with title and description",
      "props": {
        "registryDemo": "alert-10"
      }
    }
  ],
  "Aura": [
    {
      "id": "aura-1",
      "label": "Aura",
      "props": {
        "registryDemo": "aura-1"
      }
    },
    {
      "id": "aura-2",
      "label": "Aura around a button",
      "props": {
        "registryDemo": "aura-2"
      }
    },
    {
      "id": "aura-3",
      "label": "Aura dual",
      "props": {
        "registryDemo": "aura-3"
      }
    },
    {
      "id": "aura-4",
      "label": "Aura rainbow",
      "props": {
        "registryDemo": "aura-4"
      }
    },
    {
      "id": "aura-5",
      "label": "Aura holo",
      "props": {
        "registryDemo": "aura-5"
      }
    },
    {
      "id": "aura-6",
      "label": "Aura glow",
      "props": {
        "registryDemo": "aura-6"
      }
    },
    {
      "id": "aura-7",
      "label": "Aura gold",
      "props": {
        "registryDemo": "aura-7"
      }
    },
    {
      "id": "aura-8",
      "label": "Aura silver",
      "props": {
        "registryDemo": "aura-8"
      }
    },
    {
      "id": "aura-9",
      "label": "Aura with custom color",
      "props": {
        "registryDemo": "aura-9"
      }
    },
    {
      "id": "aura-10",
      "label": "Aura with custom color and custom background color",
      "props": {
        "registryDemo": "aura-10"
      }
    },
    {
      "id": "aura-11",
      "label": "Aura rainbow around a pricing card",
      "props": {
        "registryDemo": "aura-11"
      }
    },
    {
      "id": "aura-12",
      "label": "Aura sizes",
      "props": {
        "registryDemo": "aura-12"
      }
    },
    {
      "id": "aura-13",
      "label": "Aura with custom animation duration",
      "props": {
        "registryDemo": "aura-13"
      }
    }
  ],
  "Avatar": [
    {
      "id": "avatar-1",
      "label": "Avatar",
      "props": {
        "registryDemo": "avatar-1"
      }
    },
    {
      "id": "avatar-2",
      "label": "Avatar in custom sizes",
      "props": {
        "registryDemo": "avatar-2"
      }
    },
    {
      "id": "avatar-3",
      "label": "Avatar rounded",
      "props": {
        "registryDemo": "avatar-3"
      }
    },
    {
      "id": "avatar-4",
      "label": "Avatar with mask",
      "props": {
        "registryDemo": "avatar-4"
      }
    },
    {
      "id": "avatar-5",
      "label": "Avatar group",
      "props": {
        "registryDemo": "avatar-5"
      }
    },
    {
      "id": "avatar-6",
      "label": "Avatar group with counter",
      "props": {
        "registryDemo": "avatar-6"
      }
    },
    {
      "id": "avatar-7",
      "label": "Avatar with ring",
      "props": {
        "registryDemo": "avatar-7"
      }
    },
    {
      "id": "avatar-8",
      "label": "Avatar with presence indicator",
      "props": {
        "registryDemo": "avatar-8"
      }
    },
    {
      "id": "avatar-9",
      "label": "Avatar placeholder",
      "props": {
        "registryDemo": "avatar-9"
      }
    }
  ],
  "Badge": [
    {
      "id": "badge-1",
      "label": "Badge",
      "props": {
        "registryDemo": "badge-1"
      }
    },
    {
      "id": "badge-2",
      "label": "Badge sizes",
      "props": {
        "registryDemo": "badge-2"
      }
    },
    {
      "id": "badge-3",
      "label": "Badge with colors",
      "props": {
        "registryDemo": "badge-3"
      }
    },
    {
      "id": "badge-4",
      "label": "Badge with soft style",
      "props": {
        "registryDemo": "badge-4"
      }
    },
    {
      "id": "badge-5",
      "label": "Badge with outline style",
      "props": {
        "registryDemo": "badge-5"
      }
    },
    {
      "id": "badge-6",
      "label": "Badge with dash style",
      "props": {
        "registryDemo": "badge-6"
      }
    },
    {
      "id": "badge-7",
      "label": "neutral badge with outline or dash style",
      "props": {
        "registryDemo": "badge-7"
      }
    },
    {
      "id": "badge-8",
      "label": "Badge ghost",
      "props": {
        "registryDemo": "badge-8"
      }
    },
    {
      "id": "badge-9",
      "label": "Empty badge",
      "props": {
        "registryDemo": "badge-9"
      }
    },
    {
      "id": "badge-10",
      "label": "Badge with icon",
      "props": {
        "registryDemo": "badge-10"
      }
    },
    {
      "id": "badge-11",
      "label": "Badge in a text",
      "props": {
        "registryDemo": "badge-11"
      }
    },
    {
      "id": "badge-12",
      "label": "Badge in a button",
      "props": {
        "registryDemo": "badge-12"
      }
    }
  ],
  "Breadcrumbs": [
    {
      "id": "breadcrumbs-1",
      "label": "Breadcrumbs",
      "props": {
        "registryDemo": "breadcrumbs-1"
      }
    },
    {
      "id": "breadcrumbs-2",
      "label": "Breadcrumbs with icons",
      "props": {
        "registryDemo": "breadcrumbs-2"
      }
    },
    {
      "id": "breadcrumbs-3",
      "label": "Breadcrumbs with max-width",
      "props": {
        "registryDemo": "breadcrumbs-3"
      }
    }
  ],
  "Button": [
    {
      "id": "button-1",
      "label": "Button",
      "props": {
        "registryDemo": "button-1"
      }
    },
    {
      "id": "button-2",
      "label": "Button sizes",
      "props": {
        "registryDemo": "button-2"
      }
    },
    {
      "id": "button-3",
      "label": "Responsive button",
      "props": {
        "registryDemo": "button-3"
      }
    },
    {
      "id": "button-4",
      "label": "Buttons colors",
      "props": {
        "registryDemo": "button-4"
      }
    },
    {
      "id": "button-5",
      "label": "Soft buttons",
      "props": {
        "registryDemo": "button-5"
      }
    },
    {
      "id": "button-6",
      "label": "Outline buttons",
      "props": {
        "registryDemo": "button-6"
      }
    },
    {
      "id": "button-7",
      "label": "Dash buttons",
      "props": {
        "registryDemo": "button-7"
      }
    },
    {
      "id": "button-8",
      "label": "neutral button with outline or dash style",
      "props": {
        "registryDemo": "button-8"
      }
    },
    {
      "id": "button-9",
      "label": "Active buttons",
      "props": {
        "registryDemo": "button-9"
      }
    },
    {
      "id": "button-10",
      "label": "Buttons ghost and button link",
      "props": {
        "registryDemo": "button-10"
      }
    },
    {
      "id": "button-11",
      "label": "Wide button",
      "props": {
        "registryDemo": "button-11"
      }
    },
    {
      "id": "button-12",
      "label": "Buttons with any HTML tags",
      "props": {
        "registryDemo": "button-12"
      }
    },
    {
      "id": "button-13",
      "label": "Disabled buttons",
      "props": {
        "registryDemo": "button-13"
      }
    },
    {
      "id": "button-14",
      "label": "Square button and circle button",
      "props": {
        "registryDemo": "button-14"
      }
    },
    {
      "id": "button-15",
      "label": "Button with Icon",
      "props": {
        "registryDemo": "button-15"
      }
    },
    {
      "id": "button-16",
      "label": "Button block",
      "props": {
        "registryDemo": "button-16"
      }
    },
    {
      "id": "button-17",
      "label": "Button with loading spinner",
      "props": {
        "registryDemo": "button-17"
      }
    },
    {
      "id": "button-18",
      "label": "Login buttons",
      "props": {
        "registryDemo": "button-18"
      }
    }
  ],
  "Calendar": [
    {
      "id": "calendar-1",
      "label": "Cally calendar example",
      "props": {
        "registryDemo": "calendar-1"
      }
    },
    {
      "id": "calendar-2",
      "label": "Cally date picker example",
      "props": {
        "registryDemo": "calendar-2"
      }
    }
  ],
  "Card": [
    {
      "id": "card-1",
      "label": "Card",
      "props": {
        "registryDemo": "card-1"
      }
    },
    {
      "id": "card-2",
      "label": "Pricing Card",
      "props": {
        "registryDemo": "card-2"
      }
    },
    {
      "id": "card-3",
      "label": "Card sizes",
      "props": {
        "registryDemo": "card-3"
      }
    },
    {
      "id": "card-4",
      "label": "Card with a card-border",
      "props": {
        "registryDemo": "card-4"
      }
    },
    {
      "id": "card-5",
      "label": "Card with a dash border",
      "props": {
        "registryDemo": "card-5"
      }
    },
    {
      "id": "card-6",
      "label": "Card with badge",
      "props": {
        "registryDemo": "card-6"
      }
    },
    {
      "id": "card-7",
      "label": "Card with bottom image",
      "props": {
        "registryDemo": "card-7"
      }
    },
    {
      "id": "card-8",
      "label": "Card with centered content and paddings",
      "props": {
        "registryDemo": "card-8"
      }
    },
    {
      "id": "card-9",
      "label": "Card with image overlay",
      "props": {
        "registryDemo": "card-9"
      }
    },
    {
      "id": "card-10",
      "label": "Card with no image",
      "props": {
        "registryDemo": "card-10"
      }
    },
    {
      "id": "card-11",
      "label": "Card with custom color",
      "props": {
        "registryDemo": "card-11"
      }
    },
    {
      "id": "card-12",
      "label": "Centered card with neutral color",
      "props": {
        "registryDemo": "card-12"
      }
    },
    {
      "id": "card-13",
      "label": "Card with action on top",
      "props": {
        "registryDemo": "card-13"
      }
    },
    {
      "id": "card-14",
      "label": "Card with image on side",
      "props": {
        "registryDemo": "card-14"
      }
    },
    {
      "id": "card-15",
      "label": "Responsive card (vertical on small screen, horizontal on large screen)",
      "props": {
        "registryDemo": "card-15"
      }
    },
    {
      "id": "card-16",
      "label": "Selectable cards",
      "props": {
        "registryDemo": "card-16"
      }
    }
  ],
  "Carousel": [
    {
      "id": "carousel-1",
      "label": "Snap to start (default)",
      "props": {
        "registryDemo": "carousel-1"
      }
    },
    {
      "id": "carousel-2",
      "label": "Snap to center",
      "props": {
        "registryDemo": "carousel-2"
      }
    },
    {
      "id": "carousel-3",
      "label": "Snap to end",
      "props": {
        "registryDemo": "carousel-3"
      }
    },
    {
      "id": "carousel-4",
      "label": "Carousel with full width items",
      "props": {
        "registryDemo": "carousel-4"
      }
    },
    {
      "id": "carousel-5",
      "label": "Vertical carousel",
      "props": {
        "registryDemo": "carousel-5"
      }
    },
    {
      "id": "carousel-6",
      "label": "Carousel with half width items",
      "props": {
        "registryDemo": "carousel-6"
      }
    },
    {
      "id": "carousel-7",
      "label": "Full-bleed carousel",
      "props": {
        "registryDemo": "carousel-7"
      }
    },
    {
      "id": "carousel-8",
      "label": "Carousel with indicator buttons",
      "props": {
        "registryDemo": "carousel-8"
      }
    },
    {
      "id": "carousel-9",
      "label": "Carousel with next/prev buttons",
      "props": {
        "registryDemo": "carousel-9"
      }
    }
  ],
  "Chat": [
    {
      "id": "chat-1",
      "label": "chat-start and chat-end",
      "props": {
        "registryDemo": "chat-1"
      }
    },
    {
      "id": "chat-2",
      "label": "Chat with image",
      "props": {
        "registryDemo": "chat-2"
      }
    },
    {
      "id": "chat-3",
      "label": "Chat with image, header and footer",
      "props": {
        "registryDemo": "chat-3"
      }
    },
    {
      "id": "chat-4",
      "label": "Chat with header and footer",
      "props": {
        "registryDemo": "chat-4"
      }
    },
    {
      "id": "chat-5",
      "label": "Chat Bubble with colors",
      "props": {
        "registryDemo": "chat-5"
      }
    }
  ],
  "Checkbox": [
    {
      "id": "checkbox-1",
      "label": "Checkbox",
      "props": {
        "registryDemo": "checkbox-1"
      }
    },
    {
      "id": "checkbox-2",
      "label": "With fieldset and label",
      "props": {
        "registryDemo": "checkbox-2"
      }
    },
    {
      "id": "checkbox-3",
      "label": "Sizes",
      "props": {
        "registryDemo": "checkbox-3"
      }
    },
    {
      "id": "checkbox-4",
      "label": "Colors",
      "props": {
        "registryDemo": "checkbox-4"
      }
    },
    {
      "id": "checkbox-5",
      "label": "Disabled",
      "props": {
        "registryDemo": "checkbox-5"
      }
    },
    {
      "id": "checkbox-6",
      "label": "Indeterminate",
      "props": {
        "registryDemo": "checkbox-6"
      }
    },
    {
      "id": "checkbox-7",
      "label": "Checkbox with custom colors",
      "props": {
        "registryDemo": "checkbox-7"
      }
    }
  ],
  "Collapse": [
    {
      "id": "collapse-1",
      "label": "Collapse with focus",
      "props": {
        "registryDemo": "collapse-1"
      }
    },
    {
      "id": "collapse-2",
      "label": "Collapse with checkbox",
      "props": {
        "registryDemo": "collapse-2"
      }
    },
    {
      "id": "collapse-3",
      "label": "Collapse with checkbox and close on click outside",
      "props": {
        "registryDemo": "collapse-3"
      }
    },
    {
      "id": "collapse-4",
      "label": "Collapse using details and summary tag",
      "props": {
        "registryDemo": "collapse-4"
      }
    },
    {
      "id": "collapse-5",
      "label": "Without border and background color",
      "props": {
        "registryDemo": "collapse-5"
      }
    },
    {
      "id": "collapse-6",
      "label": "With arrow icon",
      "props": {
        "registryDemo": "collapse-6"
      }
    },
    {
      "id": "collapse-7",
      "label": "With arrow plus/minus icon",
      "props": {
        "registryDemo": "collapse-7"
      }
    },
    {
      "id": "collapse-8",
      "label": "Moving collapse icon to the start",
      "props": {
        "registryDemo": "collapse-8"
      }
    },
    {
      "id": "collapse-9",
      "label": "Force open",
      "props": {
        "registryDemo": "collapse-9"
      }
    },
    {
      "id": "collapse-10",
      "label": "Force close",
      "props": {
        "registryDemo": "collapse-10"
      }
    },
    {
      "id": "collapse-11",
      "label": "Custom colors for collapse that works with focus",
      "props": {
        "registryDemo": "collapse-11"
      }
    },
    {
      "id": "collapse-12",
      "label": "Custom colors for collapse that works with checkbox",
      "props": {
        "registryDemo": "collapse-12"
      }
    }
  ],
  "Countdown": [
    {
      "id": "countdown-1",
      "label": "Countdown",
      "props": {
        "registryDemo": "countdown-1"
      }
    },
    {
      "id": "countdown-2",
      "label": "Large text with 2 digits",
      "props": {
        "registryDemo": "countdown-2"
      }
    },
    {
      "id": "countdown-3",
      "label": "Clock countdown",
      "props": {
        "registryDemo": "countdown-3"
      }
    },
    {
      "id": "countdown-4",
      "label": "Clock countdown with colons",
      "props": {
        "registryDemo": "countdown-4"
      }
    },
    {
      "id": "countdown-5",
      "label": "Large text with labels",
      "props": {
        "registryDemo": "countdown-5"
      }
    },
    {
      "id": "countdown-6",
      "label": "Large text with labels under",
      "props": {
        "registryDemo": "countdown-6"
      }
    },
    {
      "id": "countdown-7",
      "label": "In boxes",
      "props": {
        "registryDemo": "countdown-7"
      }
    }
  ],
  "Diff": [
    {
      "id": "diff-1",
      "label": "Diff",
      "props": {
        "registryDemo": "diff-1"
      }
    },
    {
      "id": "diff-2",
      "label": "Diff text",
      "props": {
        "registryDemo": "diff-2"
      }
    }
  ],
  "Divider": [
    {
      "id": "divider-1",
      "label": "Divider",
      "props": {
        "registryDemo": "divider-1"
      }
    },
    {
      "id": "divider-2",
      "label": "Divider horizontal",
      "props": {
        "registryDemo": "divider-2"
      }
    },
    {
      "id": "divider-3",
      "label": "Divider with no text",
      "props": {
        "registryDemo": "divider-3"
      }
    },
    {
      "id": "divider-4",
      "label": "responsive (lg:divider-horizontal)",
      "props": {
        "registryDemo": "divider-4"
      }
    },
    {
      "id": "divider-5",
      "label": "Divider with colors",
      "props": {
        "registryDemo": "divider-5"
      }
    },
    {
      "id": "divider-6",
      "label": "Divider in different positions",
      "props": {
        "registryDemo": "divider-6"
      }
    },
    {
      "id": "divider-7",
      "label": "Divider in different positions (horizontal)",
      "props": {
        "registryDemo": "divider-7"
      }
    }
  ],
  "Dock": [
    {
      "id": "dock-1",
      "label": "Dock",
      "props": {
        "registryDemo": "dock-1"
      }
    },
    {
      "id": "dock-2",
      "label": "Dock Extra Small size",
      "props": {
        "registryDemo": "dock-2"
      }
    },
    {
      "id": "dock-3",
      "label": "Dock Small size",
      "props": {
        "registryDemo": "dock-3"
      }
    },
    {
      "id": "dock-4",
      "label": "Dock Medium size",
      "props": {
        "registryDemo": "dock-4"
      }
    },
    {
      "id": "dock-5",
      "label": "Dock Large size",
      "props": {
        "registryDemo": "dock-5"
      }
    },
    {
      "id": "dock-6",
      "label": "Dock Extra Large size",
      "props": {
        "registryDemo": "dock-6"
      }
    },
    {
      "id": "dock-7",
      "label": "Dock with custom colors",
      "props": {
        "registryDemo": "dock-7"
      }
    }
  ],
  "Drawer": [
    {
      "id": "drawer-1",
      "label": "Drawer sidebar",
      "props": {
        "registryDemo": "drawer-1"
      }
    },
    {
      "id": "drawer-2",
      "label": "Navbar menu for desktop + sidebar drawer for mobile",
      "props": {
        "registryDemo": "drawer-2"
      }
    },
    {
      "id": "drawer-3",
      "label": "Responsive: Sidebar is always visible on large screen, can be toggled on small screen",
      "props": {
        "registryDemo": "drawer-3"
      }
    },
    {
      "id": "drawer-4",
      "label": "Responsive collapsible Icon-only drawer sidebar. Using is-drawer-close and is-drawer-open",
      "props": {
        "registryDemo": "drawer-4"
      }
    },
    {
      "id": "drawer-5",
      "label": "Drawer sidebar that opens from right side of page",
      "props": {
        "registryDemo": "drawer-5"
      }
    }
  ],
  "Dropdown": [
    {
      "id": "dropdown-1",
      "label": "Dropdown using details and summary",
      "props": {
        "registryDemo": "dropdown-1"
      }
    },
    {
      "id": "dropdown-2",
      "label": "Dropdown using popover API and anchor positioning",
      "props": {
        "registryDemo": "dropdown-2"
      }
    },
    {
      "id": "dropdown-3",
      "label": "Dropdown menu",
      "props": {
        "registryDemo": "dropdown-3"
      }
    },
    {
      "id": "dropdown-4",
      "label": "Dropdown / aligns to start of button horizontally",
      "props": {
        "registryDemo": "dropdown-4"
      }
    },
    {
      "id": "dropdown-5",
      "label": "Dropdown / aligns to end of button horizontally",
      "props": {
        "registryDemo": "dropdown-5"
      }
    },
    {
      "id": "dropdown-6",
      "label": "Dropdown / aligns to center of button horizontally",
      "props": {
        "registryDemo": "dropdown-6"
      }
    },
    {
      "id": "dropdown-7",
      "label": "Dropdown top",
      "props": {
        "registryDemo": "dropdown-7"
      }
    },
    {
      "id": "dropdown-8",
      "label": "Dropdown top / aligns to center of button horizontally",
      "props": {
        "registryDemo": "dropdown-8"
      }
    },
    {
      "id": "dropdown-9",
      "label": "Dropdown top / aligns to end of button horizontally",
      "props": {
        "registryDemo": "dropdown-9"
      }
    },
    {
      "id": "dropdown-10",
      "label": "Dropdown bottom (default)",
      "props": {
        "registryDemo": "dropdown-10"
      }
    },
    {
      "id": "dropdown-11",
      "label": "Dropdown bottom (default) / aligns to center of button horizontally",
      "props": {
        "registryDemo": "dropdown-11"
      }
    },
    {
      "id": "dropdown-12",
      "label": "Dropdown bottom (default) / aligns to end of button horizontally",
      "props": {
        "registryDemo": "dropdown-12"
      }
    },
    {
      "id": "dropdown-13",
      "label": "Dropdown left",
      "props": {
        "registryDemo": "dropdown-13"
      }
    },
    {
      "id": "dropdown-14",
      "label": "Dropdown left / aligns to center of button vertically",
      "props": {
        "registryDemo": "dropdown-14"
      }
    },
    {
      "id": "dropdown-15",
      "label": "Dropdown left / aligns to end of button vertically",
      "props": {
        "registryDemo": "dropdown-15"
      }
    },
    {
      "id": "dropdown-16",
      "label": "Dropdown right",
      "props": {
        "registryDemo": "dropdown-16"
      }
    },
    {
      "id": "dropdown-17",
      "label": "Dropdown right / aligns to end of button vertically",
      "props": {
        "registryDemo": "dropdown-17"
      }
    },
    {
      "id": "dropdown-18",
      "label": "Dropdown right / aligns to center of button vertically",
      "props": {
        "registryDemo": "dropdown-18"
      }
    },
    {
      "id": "dropdown-19",
      "label": "Dropdown on hover",
      "props": {
        "registryDemo": "dropdown-19"
      }
    },
    {
      "id": "dropdown-20",
      "label": "Force open",
      "props": {
        "registryDemo": "dropdown-20"
      }
    },
    {
      "id": "dropdown-21",
      "label": "Force close",
      "props": {
        "registryDemo": "dropdown-21"
      }
    },
    {
      "id": "dropdown-22",
      "label": "Card as dropdown",
      "props": {
        "registryDemo": "dropdown-22"
      }
    },
    {
      "id": "dropdown-23",
      "label": "Dropdown in navbar",
      "props": {
        "registryDemo": "dropdown-23"
      }
    },
    {
      "id": "dropdown-24",
      "label": "Helper dropdown",
      "props": {
        "registryDemo": "dropdown-24"
      }
    }
  ],
  "Fab": [
    {
      "id": "fab-1",
      "label": "FAB and Speed Dial (vertical)",
      "props": {
        "registryDemo": "fab-1"
      }
    },
    {
      "id": "fab-2",
      "label": "FAB and Speed Dial with SVG icons",
      "props": {
        "registryDemo": "fab-2"
      }
    },
    {
      "id": "fab-3",
      "label": "FAB and Speed Dial with labels",
      "props": {
        "registryDemo": "fab-3"
      }
    },
    {
      "id": "fab-4",
      "label": "FAB and Speed Dial with rectangle buttons",
      "props": {
        "registryDemo": "fab-4"
      }
    },
    {
      "id": "fab-5",
      "label": "FAB and Speed Dial with labels and fab-close button",
      "props": {
        "registryDemo": "fab-5"
      }
    },
    {
      "id": "fab-6",
      "label": "FAB and Speed Dial with labels and fab-main-action Button",
      "props": {
        "registryDemo": "fab-6"
      }
    },
    {
      "id": "fab-7",
      "label": "A single FAB (Floating Action Button)",
      "props": {
        "registryDemo": "fab-7"
      }
    },
    {
      "id": "fab-8",
      "label": "FAB Flower and Speed Dial",
      "props": {
        "registryDemo": "fab-8"
      }
    },
    {
      "id": "fab-9",
      "label": "FAB Flower without a main action button",
      "props": {
        "registryDemo": "fab-9"
      }
    },
    {
      "id": "fab-10",
      "label": "FAB and Flower Speed Dial with SVG icons",
      "props": {
        "registryDemo": "fab-10"
      }
    },
    {
      "id": "fab-11",
      "label": "FAB and Flower Speed Dial with tooltip",
      "props": {
        "registryDemo": "fab-11"
      }
    }
  ],
  "Fieldset": [
    {
      "id": "fieldset-1",
      "label": "Fieldset fieldset-legend and label",
      "props": {
        "registryDemo": "fieldset-1"
      }
    },
    {
      "id": "fieldset-2",
      "label": "Fieldset with background and border",
      "props": {
        "registryDemo": "fieldset-2"
      }
    },
    {
      "id": "fieldset-3",
      "label": "Fieldset with multiple inputs",
      "props": {
        "registryDemo": "fieldset-3"
      }
    },
    {
      "id": "fieldset-4",
      "label": "Fieldset with multiple join items",
      "props": {
        "registryDemo": "fieldset-4"
      }
    },
    {
      "id": "fieldset-5",
      "label": "Login form with fieldset",
      "props": {
        "registryDemo": "fieldset-5"
      }
    }
  ],
  "FileInput": [
    {
      "id": "file-input-1",
      "label": "File input",
      "props": {
        "registryDemo": "file-input-1"
      }
    },
    {
      "id": "file-input-2",
      "label": "File input ghost",
      "props": {
        "registryDemo": "file-input-2"
      }
    },
    {
      "id": "file-input-3",
      "label": "With fieldset and label",
      "props": {
        "registryDemo": "file-input-3"
      }
    },
    {
      "id": "file-input-4",
      "label": "Sizes",
      "props": {
        "registryDemo": "file-input-4"
      }
    },
    {
      "id": "file-input-5",
      "label": "Primary color",
      "props": {
        "registryDemo": "file-input-5"
      }
    },
    {
      "id": "file-input-6",
      "label": "Disabled",
      "props": {
        "registryDemo": "file-input-6"
      }
    }
  ],
  "Filter": [
    {
      "id": "filter-1",
      "label": "Filter using HTML form, radio buttons and reset button",
      "props": {
        "registryDemo": "filter-1"
      }
    },
    {
      "id": "filter-2",
      "label": "Filter without HTML form",
      "props": {
        "registryDemo": "filter-2"
      }
    },
    {
      "id": "filter-3",
      "label": "Filter using HTML form, checkboxes, and a reset button",
      "props": {
        "registryDemo": "filter-3"
      }
    }
  ],
  "Footer": [
    {
      "id": "footer-1",
      "label": "Footer (vertical by default, horizontal for sm and up)",
      "props": {
        "registryDemo": "footer-1"
      }
    },
    {
      "id": "footer-2",
      "label": "Footer with a logo section",
      "props": {
        "registryDemo": "footer-2"
      }
    },
    {
      "id": "footer-3",
      "label": "Footer with a form",
      "props": {
        "registryDemo": "footer-3"
      }
    },
    {
      "id": "footer-4",
      "label": "Footer with logo and social icons",
      "props": {
        "registryDemo": "footer-4"
      }
    },
    {
      "id": "footer-5",
      "label": "Footer with copyright text",
      "props": {
        "registryDemo": "footer-5"
      }
    },
    {
      "id": "footer-6",
      "label": "Footer with copyright text and social icons",
      "props": {
        "registryDemo": "footer-6"
      }
    },
    {
      "id": "footer-7",
      "label": "Footer with links and social icons",
      "props": {
        "registryDemo": "footer-7"
      }
    },
    {
      "id": "footer-8",
      "label": "Footer with 2 rows",
      "props": {
        "registryDemo": "footer-8"
      }
    },
    {
      "id": "footer-9",
      "label": "Centered footer with logo and social icons",
      "props": {
        "registryDemo": "footer-9"
      }
    },
    {
      "id": "footer-10",
      "label": "Centered footer with social icons",
      "props": {
        "registryDemo": "footer-10"
      }
    },
    {
      "id": "footer-11",
      "label": "Two footer",
      "props": {
        "registryDemo": "footer-11"
      }
    }
  ],
  "Hero": [
    {
      "id": "hero-1",
      "label": "Centered hero",
      "props": {
        "registryDemo": "hero-1"
      }
    },
    {
      "id": "hero-2",
      "label": "Hero with figure",
      "props": {
        "registryDemo": "hero-2"
      }
    },
    {
      "id": "hero-3",
      "label": "Hero with figure but reverse order",
      "props": {
        "registryDemo": "hero-3"
      }
    },
    {
      "id": "hero-4",
      "label": "Hero with form",
      "props": {
        "registryDemo": "hero-4"
      }
    },
    {
      "id": "hero-5",
      "label": "Hero with overlay image",
      "props": {
        "registryDemo": "hero-5"
      }
    }
  ],
  "Hover3D": [
    {
      "id": "hover-3d-1",
      "label": "3D image hover effect",
      "props": {
        "registryDemo": "hover-3d-1"
      }
    },
    {
      "id": "hover-3d-2",
      "label": "3D card hover effect",
      "props": {
        "registryDemo": "hover-3d-2"
      }
    },
    {
      "id": "hover-3d-3",
      "label": "3D hover effect for image gallery",
      "props": {
        "registryDemo": "hover-3d-3"
      }
    }
  ],
  "HoverGallery": [
    {
      "id": "hover-gallery-1",
      "label": "Hover Gallery",
      "props": {
        "registryDemo": "hover-gallery-1"
      }
    },
    {
      "id": "hover-gallery-2",
      "label": "Hover Gallery in a card",
      "props": {
        "registryDemo": "hover-gallery-2"
      }
    }
  ],
  "Indicator": [
    {
      "id": "indicator-1",
      "label": "Status Indicator",
      "props": {
        "registryDemo": "indicator-1"
      }
    },
    {
      "id": "indicator-2",
      "label": "Badge as indicator",
      "props": {
        "registryDemo": "indicator-2"
      }
    },
    {
      "id": "indicator-3",
      "label": "for button",
      "props": {
        "registryDemo": "indicator-3"
      }
    },
    {
      "id": "indicator-4",
      "label": "for tab",
      "props": {
        "registryDemo": "indicator-4"
      }
    },
    {
      "id": "indicator-5",
      "label": "for avatar",
      "props": {
        "registryDemo": "indicator-5"
      }
    },
    {
      "id": "indicator-6",
      "label": "for an input",
      "props": {
        "registryDemo": "indicator-6"
      }
    },
    {
      "id": "indicator-7",
      "label": "A button as an indicator for a card",
      "props": {
        "registryDemo": "indicator-7"
      }
    },
    {
      "id": "indicator-8",
      "label": "in center of an image",
      "props": {
        "registryDemo": "indicator-8"
      }
    },
    {
      "id": "indicator-9",
      "label": "indicator-top (default) indicator-start",
      "props": {
        "registryDemo": "indicator-9"
      }
    },
    {
      "id": "indicator-10",
      "label": "indicator-top (default) indicator-center",
      "props": {
        "registryDemo": "indicator-10"
      }
    },
    {
      "id": "indicator-11",
      "label": "indicator-top (default) indicator-end (default)",
      "props": {
        "registryDemo": "indicator-11"
      }
    },
    {
      "id": "indicator-12",
      "label": "indicator-middle indicator-start",
      "props": {
        "registryDemo": "indicator-12"
      }
    },
    {
      "id": "indicator-13",
      "label": "indicator-middle indicator-center",
      "props": {
        "registryDemo": "indicator-13"
      }
    },
    {
      "id": "indicator-14",
      "label": "indicator-middle indicator-end (default)",
      "props": {
        "registryDemo": "indicator-14"
      }
    },
    {
      "id": "indicator-15",
      "label": "indicator-bottom indicator-start",
      "props": {
        "registryDemo": "indicator-15"
      }
    },
    {
      "id": "indicator-16",
      "label": "indicator-bottom indicator-center",
      "props": {
        "registryDemo": "indicator-16"
      }
    },
    {
      "id": "indicator-17",
      "label": "indicator-bottom indicator-end (default)",
      "props": {
        "registryDemo": "indicator-17"
      }
    },
    {
      "id": "indicator-18",
      "label": "multiple indicators",
      "props": {
        "registryDemo": "indicator-18"
      }
    },
    {
      "id": "indicator-19",
      "label": "Responsive",
      "props": {
        "registryDemo": "indicator-19"
      }
    }
  ],
  "Input": [
    {
      "id": "input-1",
      "label": "Text input",
      "props": {
        "registryDemo": "input-1"
      }
    },
    {
      "id": "input-2",
      "label": "Text input with text label inside",
      "props": {
        "registryDemo": "input-2"
      }
    },
    {
      "id": "input-3",
      "label": "Ghost style",
      "props": {
        "registryDemo": "input-3"
      }
    },
    {
      "id": "input-4",
      "label": "With fieldset and fieldset-legend",
      "props": {
        "registryDemo": "input-4"
      }
    },
    {
      "id": "input-5",
      "label": "With fieldset and label",
      "props": {
        "registryDemo": "input-5"
      }
    },
    {
      "id": "input-6",
      "label": "Input colors",
      "props": {
        "registryDemo": "input-6"
      }
    },
    {
      "id": "input-7",
      "label": "Sizes",
      "props": {
        "registryDemo": "input-7"
      }
    },
    {
      "id": "input-8",
      "label": "Disabled",
      "props": {
        "registryDemo": "input-8"
      }
    },
    {
      "id": "input-9",
      "label": "Text input with data list suggestion",
      "props": {
        "registryDemo": "input-9"
      }
    },
    {
      "id": "input-10",
      "label": "Date input",
      "props": {
        "registryDemo": "input-10"
      }
    },
    {
      "id": "input-11",
      "label": "Time input",
      "props": {
        "registryDemo": "input-11"
      }
    },
    {
      "id": "input-12",
      "label": "datetime-local input",
      "props": {
        "registryDemo": "input-12"
      }
    },
    {
      "id": "input-13",
      "label": "Username text input with icon and validator",
      "props": {
        "registryDemo": "input-13"
      }
    },
    {
      "id": "input-14",
      "label": "Search input with icon",
      "props": {
        "registryDemo": "input-14"
      }
    },
    {
      "id": "input-15",
      "label": "Email input with icon and validator",
      "props": {
        "registryDemo": "input-15"
      }
    },
    {
      "id": "input-16",
      "label": "Email input with icon, validator, button, join",
      "props": {
        "registryDemo": "input-16"
      }
    },
    {
      "id": "input-17",
      "label": "Password input with icon and validator",
      "props": {
        "registryDemo": "input-17"
      }
    },
    {
      "id": "input-18",
      "label": "Number input with validator",
      "props": {
        "registryDemo": "input-18"
      }
    },
    {
      "id": "input-19",
      "label": "Telephone number input with icon and validator",
      "props": {
        "registryDemo": "input-19"
      }
    },
    {
      "id": "input-20",
      "label": "URL with icon and validator",
      "props": {
        "registryDemo": "input-20"
      }
    }
  ],
  "Join": [
    {
      "id": "join-1",
      "label": "Join",
      "props": {
        "registryDemo": "join-1"
      }
    },
    {
      "id": "join-2",
      "label": "Group items vertically",
      "props": {
        "registryDemo": "join-2"
      }
    },
    {
      "id": "join-3",
      "label": "Responsive: it's vertical on small screen and horizontal on large screen",
      "props": {
        "registryDemo": "join-3"
      }
    },
    {
      "id": "join-4",
      "label": "With extra elements in the group",
      "props": {
        "registryDemo": "join-4"
      }
    },
    {
      "id": "join-5",
      "label": "Custom border radius",
      "props": {
        "registryDemo": "join-5"
      }
    },
    {
      "id": "join-6",
      "label": "Join radio inputs with btn style",
      "props": {
        "registryDemo": "join-6"
      }
    }
  ],
  "Kbd": [
    {
      "id": "kbd-1",
      "label": "Kbd",
      "props": {
        "registryDemo": "kbd-1"
      }
    },
    {
      "id": "kbd-2",
      "label": "Kbd sizes",
      "props": {
        "registryDemo": "kbd-2"
      }
    },
    {
      "id": "kbd-3",
      "label": "In text",
      "props": {
        "registryDemo": "kbd-3"
      }
    },
    {
      "id": "kbd-4",
      "label": "Key combination",
      "props": {
        "registryDemo": "kbd-4"
      }
    },
    {
      "id": "kbd-5",
      "label": "Function Keys",
      "props": {
        "registryDemo": "kbd-5"
      }
    },
    {
      "id": "kbd-6",
      "label": "A full keyboard",
      "props": {
        "registryDemo": "kbd-6"
      }
    },
    {
      "id": "kbd-7",
      "label": "Arrow Keys",
      "props": {
        "registryDemo": "kbd-7"
      }
    }
  ],
  "Label": [
    {
      "id": "label-1",
      "label": "Label for input",
      "props": {
        "registryDemo": "label-1"
      }
    },
    {
      "id": "label-2",
      "label": "Label for input at the end",
      "props": {
        "registryDemo": "label-2"
      }
    },
    {
      "id": "label-3",
      "label": "Label for select",
      "props": {
        "registryDemo": "label-3"
      }
    },
    {
      "id": "label-4",
      "label": "Label for date input",
      "props": {
        "registryDemo": "label-4"
      }
    },
    {
      "id": "label-5",
      "label": "Floating Label",
      "props": {
        "registryDemo": "label-5"
      }
    },
    {
      "id": "label-6",
      "label": "Floating Label with Different Sizes",
      "props": {
        "registryDemo": "label-6"
      }
    },
    {
      "id": "label-7",
      "label": "Responsive Size Floating Label",
      "props": {
        "registryDemo": "label-7"
      }
    }
  ],
  "Link": [
    {
      "id": "link-1",
      "label": "Link",
      "props": {
        "registryDemo": "link-1"
      }
    },
    {
      "id": "link-2",
      "label": "Link",
      "props": {
        "registryDemo": "link-2"
      }
    },
    {
      "id": "link-3",
      "label": "Primary color",
      "props": {
        "registryDemo": "link-3"
      }
    },
    {
      "id": "link-4",
      "label": "Secondary color",
      "props": {
        "registryDemo": "link-4"
      }
    },
    {
      "id": "link-5",
      "label": "Accent color",
      "props": {
        "registryDemo": "link-5"
      }
    },
    {
      "id": "link-6",
      "label": "Success color",
      "props": {
        "registryDemo": "link-6"
      }
    },
    {
      "id": "link-7",
      "label": "Info color",
      "props": {
        "registryDemo": "link-7"
      }
    },
    {
      "id": "link-8",
      "label": "Warning color",
      "props": {
        "registryDemo": "link-8"
      }
    },
    {
      "id": "link-9",
      "label": "Error color",
      "props": {
        "registryDemo": "link-9"
      }
    },
    {
      "id": "link-10",
      "label": "Show underline only on hover",
      "props": {
        "registryDemo": "link-10"
      }
    }
  ],
  "List": [
    {
      "id": "list-1",
      "label": "List (second column grows - default)",
      "props": {
        "registryDemo": "list-1"
      }
    },
    {
      "id": "list-2",
      "label": "List (third column grows)",
      "props": {
        "registryDemo": "list-2"
      }
    },
    {
      "id": "list-3",
      "label": "List (third column wraps to next row)",
      "props": {
        "registryDemo": "list-3"
      }
    }
  ],
  "Loading": [
    {
      "id": "loading-1",
      "label": "Loading spinner",
      "props": {
        "registryDemo": "loading-1"
      }
    },
    {
      "id": "loading-2",
      "label": "Loading dots",
      "props": {
        "registryDemo": "loading-2"
      }
    },
    {
      "id": "loading-3",
      "label": "Loading ring",
      "props": {
        "registryDemo": "loading-3"
      }
    },
    {
      "id": "loading-4",
      "label": "Loading ball",
      "props": {
        "registryDemo": "loading-4"
      }
    },
    {
      "id": "loading-5",
      "label": "Loading bars",
      "props": {
        "registryDemo": "loading-5"
      }
    },
    {
      "id": "loading-6",
      "label": "Loading infinity",
      "props": {
        "registryDemo": "loading-6"
      }
    },
    {
      "id": "loading-7",
      "label": "Loading with colors",
      "props": {
        "registryDemo": "loading-7"
      }
    }
  ],
  "Mask": [
    {
      "id": "mask-1",
      "label": "Squircle",
      "props": {
        "registryDemo": "mask-1"
      }
    },
    {
      "id": "mask-2",
      "label": "Heart",
      "props": {
        "registryDemo": "mask-2"
      }
    },
    {
      "id": "mask-3",
      "label": "Hexagon",
      "props": {
        "registryDemo": "mask-3"
      }
    },
    {
      "id": "mask-4",
      "label": "Hexagon-2 (horizontal hexagon)",
      "props": {
        "registryDemo": "mask-4"
      }
    },
    {
      "id": "mask-5",
      "label": "Decagon",
      "props": {
        "registryDemo": "mask-5"
      }
    },
    {
      "id": "mask-6",
      "label": "Pentagon",
      "props": {
        "registryDemo": "mask-6"
      }
    },
    {
      "id": "mask-7",
      "label": "Diamond",
      "props": {
        "registryDemo": "mask-7"
      }
    },
    {
      "id": "mask-8",
      "label": "Circle",
      "props": {
        "registryDemo": "mask-8"
      }
    },
    {
      "id": "mask-9",
      "label": "Star",
      "props": {
        "registryDemo": "mask-9"
      }
    },
    {
      "id": "mask-10",
      "label": "Star-2 (bold star)",
      "props": {
        "registryDemo": "mask-10"
      }
    },
    {
      "id": "mask-11",
      "label": "Triangle (pointing top)",
      "props": {
        "registryDemo": "mask-11"
      }
    },
    {
      "id": "mask-12",
      "label": "Triangle-2 (pointing down)",
      "props": {
        "registryDemo": "mask-12"
      }
    },
    {
      "id": "mask-13",
      "label": "Triangle-3 (pointing left)",
      "props": {
        "registryDemo": "mask-13"
      }
    },
    {
      "id": "mask-14",
      "label": "Triangle-4 (pointing right)",
      "props": {
        "registryDemo": "mask-14"
      }
    }
  ],
  "Megamenu": [
    {
      "id": "megamenu-1",
      "label": "Responsive megamenu with small vertical menus",
      "props": {
        "registryDemo": "megamenu-1"
      }
    },
    {
      "id": "megamenu-2",
      "label": "Megamenu with wide popovers and horizontal menus",
      "props": {
        "registryDemo": "megamenu-2"
      }
    },
    {
      "id": "megamenu-3",
      "label": "Megamenu with a menus and lots of links",
      "props": {
        "registryDemo": "megamenu-3"
      }
    },
    {
      "id": "megamenu-4",
      "label": "Megamenu in a navbar",
      "props": {
        "registryDemo": "megamenu-4"
      }
    },
    {
      "id": "megamenu-5",
      "label": "megamenu without arrows",
      "props": {
        "registryDemo": "megamenu-5"
      }
    },
    {
      "id": "megamenu-6",
      "label": "Megamenu in different sizes",
      "props": {
        "registryDemo": "megamenu-6"
      }
    }
  ],
  "Menu": [
    {
      "id": "menu-1",
      "label": "Menu",
      "props": {
        "registryDemo": "menu-1"
      }
    },
    {
      "id": "menu-2",
      "label": "Responsive: vertical on small screen, horizontal on large screen",
      "props": {
        "registryDemo": "menu-2"
      }
    },
    {
      "id": "menu-3",
      "label": "Paged menu with nested submenus",
      "props": {
        "registryDemo": "menu-3"
      }
    },
    {
      "id": "menu-4",
      "label": "Menu with icon only",
      "props": {
        "registryDemo": "menu-4"
      }
    },
    {
      "id": "menu-5",
      "label": "Menu with icon only (horizontal)",
      "props": {
        "registryDemo": "menu-5"
      }
    },
    {
      "id": "menu-6",
      "label": "Menu with icon only with tooltip",
      "props": {
        "registryDemo": "menu-6"
      }
    },
    {
      "id": "menu-7",
      "label": "Menu with icon only (horizontal) with tooltip",
      "props": {
        "registryDemo": "menu-7"
      }
    },
    {
      "id": "menu-8",
      "label": "Menu sizes",
      "props": {
        "registryDemo": "menu-8"
      }
    },
    {
      "id": "menu-9",
      "label": "Menu with disabled items",
      "props": {
        "registryDemo": "menu-9"
      }
    },
    {
      "id": "menu-10",
      "label": "Menu with icons",
      "props": {
        "registryDemo": "menu-10"
      }
    },
    {
      "id": "menu-11",
      "label": "Menu with icons and badge (responsive)",
      "props": {
        "registryDemo": "menu-11"
      }
    },
    {
      "id": "menu-12",
      "label": "Menu without padding and border radius",
      "props": {
        "registryDemo": "menu-12"
      }
    },
    {
      "id": "menu-13",
      "label": "Menu with title",
      "props": {
        "registryDemo": "menu-13"
      }
    },
    {
      "id": "menu-14",
      "label": "Menu with title as a parent",
      "props": {
        "registryDemo": "menu-14"
      }
    },
    {
      "id": "menu-15",
      "label": "Submenu",
      "props": {
        "registryDemo": "menu-15"
      }
    },
    {
      "id": "menu-16",
      "label": "Collapsible submenu",
      "props": {
        "registryDemo": "menu-16"
      }
    },
    {
      "id": "menu-17",
      "label": "Collapsible submenu that works with class names",
      "props": {
        "registryDemo": "menu-17"
      }
    },
    {
      "id": "menu-18",
      "label": "File tree",
      "props": {
        "registryDemo": "menu-18"
      }
    },
    {
      "id": "menu-19",
      "label": "Menu with active item",
      "props": {
        "registryDemo": "menu-19"
      }
    },
    {
      "id": "menu-20",
      "label": "Horizontal menu",
      "props": {
        "registryDemo": "menu-20"
      }
    },
    {
      "id": "menu-21",
      "label": "Horizontal submenu",
      "props": {
        "registryDemo": "menu-21"
      }
    },
    {
      "id": "menu-22",
      "label": "Mega menu with submenu (responsive)",
      "props": {
        "registryDemo": "menu-22"
      }
    },
    {
      "id": "menu-23",
      "label": "Collapsible with submenu (responsive)",
      "props": {
        "registryDemo": "menu-23"
      }
    }
  ],
  "MockupBrowser": [
    {
      "id": "mockup-browser-1",
      "label": "browser mockup with border",
      "props": {
        "registryDemo": "mockup-browser-1"
      }
    },
    {
      "id": "mockup-browser-2",
      "label": "browser mockup with background color",
      "props": {
        "registryDemo": "mockup-browser-2"
      }
    }
  ],
  "MockupCode": [
    {
      "id": "mockup-code-1",
      "label": "mockup code with line prefix",
      "props": {
        "registryDemo": "mockup-code-1"
      }
    },
    {
      "id": "mockup-code-2",
      "label": "Multi line",
      "props": {
        "registryDemo": "mockup-code-2"
      }
    },
    {
      "id": "mockup-code-3",
      "label": "Highlighted line",
      "props": {
        "registryDemo": "mockup-code-3"
      }
    },
    {
      "id": "mockup-code-4",
      "label": "Long line will scroll",
      "props": {
        "registryDemo": "mockup-code-4"
      }
    },
    {
      "id": "mockup-code-5",
      "label": "Without prefix",
      "props": {
        "registryDemo": "mockup-code-5"
      }
    },
    {
      "id": "mockup-code-6",
      "label": "With color",
      "props": {
        "registryDemo": "mockup-code-6"
      }
    }
  ],
  "MockupPhone": [
    {
      "id": "mockup-phone-1",
      "label": "iPhone mockup",
      "props": {
        "registryDemo": "mockup-phone-1"
      }
    },
    {
      "id": "mockup-phone-2",
      "label": "With color and wallpaper",
      "props": {
        "registryDemo": "mockup-phone-2"
      }
    }
  ],
  "MockupWindow": [
    {
      "id": "mockup-window-1",
      "label": "window mockup with border",
      "props": {
        "registryDemo": "mockup-window-1"
      }
    },
    {
      "id": "mockup-window-2",
      "label": "window mockup with background color",
      "props": {
        "registryDemo": "mockup-window-2"
      }
    }
  ],
  "Modal": [
    {
      "id": "modal-1",
      "label": "Dialog modal",
      "props": {
        "registryDemo": "modal-1"
      }
    },
    {
      "id": "modal-2",
      "label": "Dialog modal, closes when clicked outside",
      "props": {
        "registryDemo": "modal-2"
      }
    },
    {
      "id": "modal-3",
      "label": "Dialog modal with a close button at corner",
      "props": {
        "registryDemo": "modal-3"
      }
    },
    {
      "id": "modal-4",
      "label": "Dialog modal with custom width",
      "props": {
        "registryDemo": "modal-4"
      }
    },
    {
      "id": "modal-5",
      "label": "Responsive",
      "props": {
        "registryDemo": "modal-5"
      }
    },
    {
      "id": "modal-6",
      "label": "Popover modal",
      "props": {
        "registryDemo": "modal-6"
      }
    },
    {
      "id": "modal-7",
      "label": "Popover modal closes when clicked outside",
      "props": {
        "registryDemo": "modal-7"
      }
    },
    {
      "id": "modal-8",
      "label": "Modal using checkbox",
      "props": {
        "registryDemo": "modal-8"
      }
    },
    {
      "id": "modal-9",
      "label": "Modal that closes when clicked outside",
      "props": {
        "registryDemo": "modal-9"
      }
    },
    {
      "id": "modal-10",
      "label": "Modal using anchor link",
      "props": {
        "registryDemo": "modal-10"
      }
    }
  ],
  "Navbar": [
    {
      "id": "navbar-1",
      "label": "Navbar with title only",
      "props": {
        "registryDemo": "navbar-1"
      }
    },
    {
      "id": "navbar-2",
      "label": "Navbar with title and icon",
      "props": {
        "registryDemo": "navbar-2"
      }
    },
    {
      "id": "navbar-3",
      "label": "Navbar with icon at start and end",
      "props": {
        "registryDemo": "navbar-3"
      }
    },
    {
      "id": "navbar-4",
      "label": "Navbar with menu and submenu",
      "props": {
        "registryDemo": "navbar-4"
      }
    },
    {
      "id": "navbar-5",
      "label": "Navbar with search input and dropdown",
      "props": {
        "registryDemo": "navbar-5"
      }
    },
    {
      "id": "navbar-6",
      "label": "Navbar with icon, indicator and dropdown",
      "props": {
        "registryDemo": "navbar-6"
      }
    },
    {
      "id": "navbar-7",
      "label": "Navbar with dropdown, center logo and icon",
      "props": {
        "registryDemo": "navbar-7"
      }
    },
    {
      "id": "navbar-8",
      "label": "Responsive (dropdown menu on small screen, center menu on large screen)",
      "props": {
        "registryDemo": "navbar-8"
      }
    },
    {
      "id": "navbar-9",
      "label": "Responsive (collapse on small screen, full content on large screen)",
      "props": {
        "registryDemo": "navbar-9"
      }
    },
    {
      "id": "navbar-10",
      "label": "Navbar with colors",
      "props": {
        "registryDemo": "navbar-10"
      }
    }
  ],
  "Otp": [
    {
      "id": "otp-1",
      "label": "OTP",
      "props": {
        "registryDemo": "otp-1"
      }
    },
    {
      "id": "otp-2",
      "label": "OTP with 6 digits",
      "props": {
        "registryDemo": "otp-2"
      }
    },
    {
      "id": "otp-3",
      "label": "OTP joined",
      "props": {
        "registryDemo": "otp-3"
      }
    },
    {
      "id": "otp-4",
      "label": "OTP with different sizes",
      "props": {
        "registryDemo": "otp-4"
      }
    },
    {
      "id": "otp-5",
      "label": "OTP with different colors",
      "props": {
        "registryDemo": "otp-5"
      }
    }
  ],
  "Pagination": [
    {
      "id": "pagination-1",
      "label": "Pagination with an active button",
      "props": {
        "registryDemo": "pagination-1"
      }
    },
    {
      "id": "pagination-2",
      "label": "Sizes",
      "props": {
        "registryDemo": "pagination-2"
      }
    },
    {
      "id": "pagination-3",
      "label": "With a disabled button",
      "props": {
        "registryDemo": "pagination-3"
      }
    },
    {
      "id": "pagination-4",
      "label": "Extra small buttons",
      "props": {
        "registryDemo": "pagination-4"
      }
    },
    {
      "id": "pagination-5",
      "label": "Nex/Prev outline buttons with equal width",
      "props": {
        "registryDemo": "pagination-5"
      }
    },
    {
      "id": "pagination-6",
      "label": "Using radio inputs",
      "props": {
        "registryDemo": "pagination-6"
      }
    }
  ],
  "Progress": [
    {
      "id": "progress-1",
      "label": "Progress",
      "props": {
        "registryDemo": "progress-1"
      }
    },
    {
      "id": "progress-2",
      "label": "Primary color",
      "props": {
        "registryDemo": "progress-2"
      }
    },
    {
      "id": "progress-3",
      "label": "Secondary color",
      "props": {
        "registryDemo": "progress-3"
      }
    },
    {
      "id": "progress-4",
      "label": "Accent color",
      "props": {
        "registryDemo": "progress-4"
      }
    },
    {
      "id": "progress-5",
      "label": "Neutral color",
      "props": {
        "registryDemo": "progress-5"
      }
    },
    {
      "id": "progress-6",
      "label": "Info color",
      "props": {
        "registryDemo": "progress-6"
      }
    },
    {
      "id": "progress-7",
      "label": "Success color",
      "props": {
        "registryDemo": "progress-7"
      }
    },
    {
      "id": "progress-8",
      "label": "Warning color",
      "props": {
        "registryDemo": "progress-8"
      }
    },
    {
      "id": "progress-9",
      "label": "Error color",
      "props": {
        "registryDemo": "progress-9"
      }
    },
    {
      "id": "progress-10",
      "label": "Indeterminate (without value)",
      "props": {
        "registryDemo": "progress-10"
      }
    }
  ],
  "RadialProgress": [
    {
      "id": "radial-progress-1",
      "label": "Radial progress",
      "props": {
        "registryDemo": "radial-progress-1"
      }
    },
    {
      "id": "radial-progress-2",
      "label": "Different values",
      "props": {
        "registryDemo": "radial-progress-2"
      }
    },
    {
      "id": "radial-progress-3",
      "label": "Custom color",
      "props": {
        "registryDemo": "radial-progress-3"
      }
    },
    {
      "id": "radial-progress-4",
      "label": "With background color and border",
      "props": {
        "registryDemo": "radial-progress-4"
      }
    },
    {
      "id": "radial-progress-5",
      "label": "Custom size and custom thickness",
      "props": {
        "registryDemo": "radial-progress-5"
      }
    }
  ],
  "Radio": [
    {
      "id": "radio-1",
      "label": "Radio",
      "props": {
        "registryDemo": "radio-1"
      }
    },
    {
      "id": "radio-2",
      "label": "Radio sizes",
      "props": {
        "registryDemo": "radio-2"
      }
    },
    {
      "id": "radio-3",
      "label": "Neutral color",
      "props": {
        "registryDemo": "radio-3"
      }
    },
    {
      "id": "radio-4",
      "label": "Primary color",
      "props": {
        "registryDemo": "radio-4"
      }
    },
    {
      "id": "radio-5",
      "label": "Secondary color",
      "props": {
        "registryDemo": "radio-5"
      }
    },
    {
      "id": "radio-6",
      "label": "Accent color",
      "props": {
        "registryDemo": "radio-6"
      }
    },
    {
      "id": "radio-7",
      "label": "Success color",
      "props": {
        "registryDemo": "radio-7"
      }
    },
    {
      "id": "radio-8",
      "label": "Warning color",
      "props": {
        "registryDemo": "radio-8"
      }
    },
    {
      "id": "radio-9",
      "label": "Info color",
      "props": {
        "registryDemo": "radio-9"
      }
    },
    {
      "id": "radio-10",
      "label": "Error color",
      "props": {
        "registryDemo": "radio-10"
      }
    },
    {
      "id": "radio-11",
      "label": "Disabled",
      "props": {
        "registryDemo": "radio-11"
      }
    },
    {
      "id": "radio-12",
      "label": "Radio with custom colors",
      "props": {
        "registryDemo": "radio-12"
      }
    }
  ],
  "Range": [
    {
      "id": "range-1",
      "label": "Range",
      "props": {
        "registryDemo": "range-1"
      }
    },
    {
      "id": "range-2",
      "label": "With steps and measure",
      "props": {
        "registryDemo": "range-2"
      }
    },
    {
      "id": "range-3",
      "label": "Neutral color",
      "props": {
        "registryDemo": "range-3"
      }
    },
    {
      "id": "range-4",
      "label": "Primary color",
      "props": {
        "registryDemo": "range-4"
      }
    },
    {
      "id": "range-5",
      "label": "Secondary color",
      "props": {
        "registryDemo": "range-5"
      }
    },
    {
      "id": "range-6",
      "label": "Accent color",
      "props": {
        "registryDemo": "range-6"
      }
    },
    {
      "id": "range-7",
      "label": "Success color",
      "props": {
        "registryDemo": "range-7"
      }
    },
    {
      "id": "range-8",
      "label": "Warning color",
      "props": {
        "registryDemo": "range-8"
      }
    },
    {
      "id": "range-9",
      "label": "Info color",
      "props": {
        "registryDemo": "range-9"
      }
    },
    {
      "id": "range-10",
      "label": "Error color",
      "props": {
        "registryDemo": "range-10"
      }
    },
    {
      "id": "range-11",
      "label": "Sizes",
      "props": {
        "registryDemo": "range-11"
      }
    },
    {
      "id": "range-12",
      "label": "Range with custom color and no fill",
      "props": {
        "registryDemo": "range-12"
      }
    },
    {
      "id": "range-13",
      "label": "Vertical",
      "props": {
        "registryDemo": "range-13"
      }
    }
  ],
  "Rating": [
    {
      "id": "rating-1",
      "label": "Rating",
      "props": {
        "registryDemo": "rating-1"
      }
    },
    {
      "id": "rating-2",
      "label": "Read-only Rating",
      "props": {
        "registryDemo": "rating-2"
      }
    },
    {
      "id": "rating-3",
      "label": "mask-star-2 with warning color",
      "props": {
        "registryDemo": "rating-3"
      }
    },
    {
      "id": "rating-4",
      "label": "mask-heart with multiple colors",
      "props": {
        "registryDemo": "rating-4"
      }
    },
    {
      "id": "rating-5",
      "label": "mask-star-2 with green-500 color",
      "props": {
        "registryDemo": "rating-5"
      }
    },
    {
      "id": "rating-6",
      "label": "Sizes",
      "props": {
        "registryDemo": "rating-6"
      }
    },
    {
      "id": "rating-7",
      "label": "with rating-hidden",
      "props": {
        "registryDemo": "rating-7"
      }
    },
    {
      "id": "rating-8",
      "label": "half stars",
      "props": {
        "registryDemo": "rating-8"
      }
    }
  ],
  "Select": [
    {
      "id": "select-1",
      "label": "Select",
      "props": {
        "registryDemo": "select-1"
      }
    },
    {
      "id": "select-2",
      "label": "Ghost (no background)",
      "props": {
        "registryDemo": "select-2"
      }
    },
    {
      "id": "select-3",
      "label": "With fieldset and labels",
      "props": {
        "registryDemo": "select-3"
      }
    },
    {
      "id": "select-4",
      "label": "Primary color",
      "props": {
        "registryDemo": "select-4"
      }
    },
    {
      "id": "select-5",
      "label": "Secondary color",
      "props": {
        "registryDemo": "select-5"
      }
    },
    {
      "id": "select-6",
      "label": "Accent color",
      "props": {
        "registryDemo": "select-6"
      }
    },
    {
      "id": "select-7",
      "label": "Neutral color",
      "props": {
        "registryDemo": "select-7"
      }
    },
    {
      "id": "select-8",
      "label": "Info color",
      "props": {
        "registryDemo": "select-8"
      }
    },
    {
      "id": "select-9",
      "label": "Success color",
      "props": {
        "registryDemo": "select-9"
      }
    },
    {
      "id": "select-10",
      "label": "Warning color",
      "props": {
        "registryDemo": "select-10"
      }
    },
    {
      "id": "select-11",
      "label": "Error color",
      "props": {
        "registryDemo": "select-11"
      }
    },
    {
      "id": "select-12",
      "label": "Sizes",
      "props": {
        "registryDemo": "select-12"
      }
    },
    {
      "id": "select-13",
      "label": "Disabled",
      "props": {
        "registryDemo": "select-13"
      }
    },
    {
      "id": "select-14",
      "label": "Using OS native style for the options dropdown",
      "props": {
        "registryDemo": "select-14"
      }
    },
    {
      "id": "select-15",
      "label": "Select with custom dropdown height",
      "props": {
        "registryDemo": "select-15"
      }
    }
  ],
  "Skeleton": [
    {
      "id": "skeleton-1",
      "label": "Skeleton",
      "props": {
        "registryDemo": "skeleton-1"
      }
    },
    {
      "id": "skeleton-2",
      "label": "Skeleton - circle with content",
      "props": {
        "registryDemo": "skeleton-2"
      }
    },
    {
      "id": "skeleton-3",
      "label": "Skeleton - rectangle with content",
      "props": {
        "registryDemo": "skeleton-3"
      }
    },
    {
      "id": "skeleton-4",
      "label": "skeleton-text - animated gradient text",
      "props": {
        "registryDemo": "skeleton-4"
      }
    }
  ],
  "Stack": [
    {
      "id": "stack-1",
      "label": "3 divs in a stack",
      "props": {
        "registryDemo": "stack-1"
      }
    },
    {
      "id": "stack-2",
      "label": "stacked images",
      "props": {
        "registryDemo": "stack-2"
      }
    },
    {
      "id": "stack-3",
      "label": "stacked cards",
      "props": {
        "registryDemo": "stack-3"
      }
    },
    {
      "id": "stack-4",
      "label": "stacked cards (top direction)",
      "props": {
        "registryDemo": "stack-4"
      }
    },
    {
      "id": "stack-5",
      "label": "stacked cards (start direction)",
      "props": {
        "registryDemo": "stack-5"
      }
    },
    {
      "id": "stack-6",
      "label": "stacked cards (end direction)",
      "props": {
        "registryDemo": "stack-6"
      }
    },
    {
      "id": "stack-7",
      "label": "stacked cards with shadow",
      "props": {
        "registryDemo": "stack-7"
      }
    },
    {
      "id": "stack-8",
      "label": "stacked cards",
      "props": {
        "registryDemo": "stack-8"
      }
    }
  ],
  "Stat": [
    {
      "id": "stat-1",
      "label": "Stat",
      "props": {
        "registryDemo": "stat-1"
      }
    },
    {
      "id": "stat-2",
      "label": "Stat with icons or image",
      "props": {
        "registryDemo": "stat-2"
      }
    },
    {
      "id": "stat-3",
      "label": "Stat",
      "props": {
        "registryDemo": "stat-3"
      }
    },
    {
      "id": "stat-4",
      "label": "Centered items",
      "props": {
        "registryDemo": "stat-4"
      }
    },
    {
      "id": "stat-5",
      "label": "Vertical",
      "props": {
        "registryDemo": "stat-5"
      }
    },
    {
      "id": "stat-6",
      "label": "Responsive (vertical on small screen, horizontal on large screen)",
      "props": {
        "registryDemo": "stat-6"
      }
    },
    {
      "id": "stat-7",
      "label": "With custom colors and button",
      "props": {
        "registryDemo": "stat-7"
      }
    }
  ],
  "Status": [
    {
      "id": "status-1",
      "label": "Status",
      "props": {
        "registryDemo": "status-1"
      }
    },
    {
      "id": "status-2",
      "label": "Status sizes",
      "props": {
        "registryDemo": "status-2"
      }
    },
    {
      "id": "status-3",
      "label": "Status with colors",
      "props": {
        "registryDemo": "status-3"
      }
    },
    {
      "id": "status-4",
      "label": "Status with ping animation",
      "props": {
        "registryDemo": "status-4"
      }
    },
    {
      "id": "status-5",
      "label": "Status with bounce animation",
      "props": {
        "registryDemo": "status-5"
      }
    }
  ],
  "Steps": [
    {
      "id": "steps-1",
      "label": "Horizontal",
      "props": {
        "registryDemo": "steps-1"
      }
    },
    {
      "id": "steps-2",
      "label": "Vertical",
      "props": {
        "registryDemo": "steps-2"
      }
    },
    {
      "id": "steps-3",
      "label": "responsive (vertical on small screen, horizontal on large screen)",
      "props": {
        "registryDemo": "steps-3"
      }
    },
    {
      "id": "steps-4",
      "label": "With custom content in step-icon",
      "props": {
        "registryDemo": "steps-4"
      }
    },
    {
      "id": "steps-5",
      "label": "With data-content",
      "props": {
        "registryDemo": "steps-5"
      }
    },
    {
      "id": "steps-6",
      "label": "Custom colors",
      "props": {
        "registryDemo": "steps-6"
      }
    },
    {
      "id": "steps-7",
      "label": "With scrollable wrapper",
      "props": {
        "registryDemo": "steps-7"
      }
    }
  ],
  "Swap": [
    {
      "id": "swap-1",
      "label": "Swap text",
      "props": {
        "registryDemo": "swap-1"
      }
    },
    {
      "id": "swap-2",
      "label": "Swap volume icons",
      "props": {
        "registryDemo": "swap-2"
      }
    },
    {
      "id": "swap-3",
      "label": "Swap icons with rotate effect",
      "props": {
        "registryDemo": "swap-3"
      }
    },
    {
      "id": "swap-4",
      "label": "Hamburger button",
      "props": {
        "registryDemo": "swap-4"
      }
    },
    {
      "id": "swap-5",
      "label": "Swap icons with flip effect",
      "props": {
        "registryDemo": "swap-5"
      }
    },
    {
      "id": "swap-6",
      "label": "Activate using class name instead of checkbox",
      "props": {
        "registryDemo": "swap-6"
      }
    }
  ],
  "Tab": [
    {
      "id": "tab-1",
      "label": "tabs",
      "props": {
        "registryDemo": "tab-1"
      }
    },
    {
      "id": "tab-2",
      "label": "tabs-border",
      "props": {
        "registryDemo": "tab-2"
      }
    },
    {
      "id": "tab-3",
      "label": "tabs-lift",
      "props": {
        "registryDemo": "tab-3"
      }
    },
    {
      "id": "tab-4",
      "label": "tabs-box",
      "props": {
        "registryDemo": "tab-4"
      }
    },
    {
      "id": "tab-5",
      "label": "tabs-box using radio inputs",
      "props": {
        "registryDemo": "tab-5"
      }
    },
    {
      "id": "tab-6",
      "label": "Sizes",
      "props": {
        "registryDemo": "tab-6"
      }
    },
    {
      "id": "tab-7",
      "label": "radio tabs-border + tab content",
      "props": {
        "registryDemo": "tab-7"
      }
    },
    {
      "id": "tab-8",
      "label": "radio tabs-lift + tab content",
      "props": {
        "registryDemo": "tab-8"
      }
    },
    {
      "id": "tab-9",
      "label": "radio tabs-lift with icons + tab content",
      "props": {
        "registryDemo": "tab-9"
      }
    },
    {
      "id": "tab-10",
      "label": "radio tabs-lift + tab content on bottom",
      "props": {
        "registryDemo": "tab-10"
      }
    },
    {
      "id": "tab-11",
      "label": "radio tabs-box + tab content",
      "props": {
        "registryDemo": "tab-11"
      }
    },
    {
      "id": "tab-12",
      "label": "tabs-box with a horizontal scroll when there's no space",
      "props": {
        "registryDemo": "tab-12"
      }
    },
    {
      "id": "tab-13",
      "label": "Tabs with custom color",
      "props": {
        "registryDemo": "tab-13"
      }
    }
  ],
  "Table": [
    {
      "id": "table-1",
      "label": "Table",
      "props": {
        "registryDemo": "table-1"
      }
    },
    {
      "id": "table-2",
      "label": "Table with border and background",
      "props": {
        "registryDemo": "table-2"
      }
    },
    {
      "id": "table-3",
      "label": "Table with an active row",
      "props": {
        "registryDemo": "table-3"
      }
    },
    {
      "id": "table-4",
      "label": "Table with a row that highlights on hover",
      "props": {
        "registryDemo": "table-4"
      }
    },
    {
      "id": "table-5",
      "label": "Zebra",
      "props": {
        "registryDemo": "table-5"
      }
    },
    {
      "id": "table-6",
      "label": "Table with visual elements",
      "props": {
        "registryDemo": "table-6"
      }
    },
    {
      "id": "table-7",
      "label": "Table xs",
      "props": {
        "registryDemo": "table-7"
      }
    },
    {
      "id": "table-8",
      "label": "Table with pinned-rows",
      "props": {
        "registryDemo": "table-8"
      }
    },
    {
      "id": "table-9",
      "label": "Table with pinned-rows and pinned-cols",
      "props": {
        "registryDemo": "table-9"
      }
    }
  ],
  "TextRotate": [
    {
      "id": "text-rotate-1",
      "label": "Text Rotate",
      "props": {
        "registryDemo": "text-rotate-1"
      }
    },
    {
      "id": "text-rotate-2",
      "label": "Rotating 6 words",
      "props": {
        "registryDemo": "text-rotate-2"
      }
    },
    {
      "id": "text-rotate-3",
      "label": "Rotating words in a sentence",
      "props": {
        "registryDemo": "text-rotate-3"
      }
    },
    {
      "id": "text-rotate-4",
      "label": "Rotating 3 words with custom duration",
      "props": {
        "registryDemo": "text-rotate-4"
      }
    },
    {
      "id": "text-rotate-5",
      "label": "Custom line height",
      "props": {
        "registryDemo": "text-rotate-5"
      }
    }
  ],
  "Textarea": [
    {
      "id": "textarea-1",
      "label": "Textarea",
      "props": {
        "registryDemo": "textarea-1"
      }
    },
    {
      "id": "textarea-2",
      "label": "Ghost (no background)",
      "props": {
        "registryDemo": "textarea-2"
      }
    },
    {
      "id": "textarea-3",
      "label": "With form control and labels",
      "props": {
        "registryDemo": "textarea-3"
      }
    },
    {
      "id": "textarea-4",
      "label": "Textarea colors",
      "props": {
        "registryDemo": "textarea-4"
      }
    },
    {
      "id": "textarea-5",
      "label": "Sizes",
      "props": {
        "registryDemo": "textarea-5"
      }
    },
    {
      "id": "textarea-6",
      "label": "Disabled",
      "props": {
        "registryDemo": "textarea-6"
      }
    }
  ],
  "ThemeController": [
    {
      "id": "theme-controller-1",
      "label": "Theme Controller using a toggle",
      "props": {
        "registryDemo": "theme-controller-1"
      }
    },
    {
      "id": "theme-controller-2",
      "label": "Theme Controller using a checkbox",
      "props": {
        "registryDemo": "theme-controller-2"
      }
    },
    {
      "id": "theme-controller-3",
      "label": "Theme Controller using a swap",
      "props": {
        "registryDemo": "theme-controller-3"
      }
    },
    {
      "id": "theme-controller-4",
      "label": "Theme Controller using a toggle with text",
      "props": {
        "registryDemo": "theme-controller-4"
      }
    },
    {
      "id": "theme-controller-5",
      "label": "Theme Controller using a toggle with icons",
      "props": {
        "registryDemo": "theme-controller-5"
      }
    },
    {
      "id": "theme-controller-6",
      "label": "Theme Controller using a toggle with icons inside",
      "props": {
        "registryDemo": "theme-controller-6"
      }
    },
    {
      "id": "theme-controller-7",
      "label": "Theme Controller using a toggle with custom colors",
      "props": {
        "registryDemo": "theme-controller-7"
      }
    },
    {
      "id": "theme-controller-8",
      "label": "Theme Controller using a radio input",
      "props": {
        "registryDemo": "theme-controller-8"
      }
    },
    {
      "id": "theme-controller-9",
      "label": "Theme Controller using a radio button",
      "props": {
        "registryDemo": "theme-controller-9"
      }
    },
    {
      "id": "theme-controller-10",
      "label": "Theme Controller using a dropdown",
      "props": {
        "registryDemo": "theme-controller-10"
      }
    }
  ],
  "Timeline": [
    {
      "id": "timeline-1",
      "label": "Timeline with text on both sides and icon",
      "props": {
        "registryDemo": "timeline-1"
      }
    },
    {
      "id": "timeline-2",
      "label": "Timeline with bottom side only",
      "props": {
        "registryDemo": "timeline-2"
      }
    },
    {
      "id": "timeline-3",
      "label": "Timeline with top side only",
      "props": {
        "registryDemo": "timeline-3"
      }
    },
    {
      "id": "timeline-4",
      "label": "Timeline with different sides",
      "props": {
        "registryDemo": "timeline-4"
      }
    },
    {
      "id": "timeline-5",
      "label": "Timeline with colorful lines",
      "props": {
        "registryDemo": "timeline-5"
      }
    },
    {
      "id": "timeline-6",
      "label": "Timeline without icons",
      "props": {
        "registryDemo": "timeline-6"
      }
    },
    {
      "id": "timeline-7",
      "label": "Vertical timeline with text on both sides and icon",
      "props": {
        "registryDemo": "timeline-7"
      }
    },
    {
      "id": "timeline-8",
      "label": "Vertical timeline with right side only",
      "props": {
        "registryDemo": "timeline-8"
      }
    },
    {
      "id": "timeline-9",
      "label": "Vertical timeline with left side only",
      "props": {
        "registryDemo": "timeline-9"
      }
    },
    {
      "id": "timeline-10",
      "label": "Vertical timeline with different sides",
      "props": {
        "registryDemo": "timeline-10"
      }
    },
    {
      "id": "timeline-11",
      "label": "Vertical timeline with colorful lines",
      "props": {
        "registryDemo": "timeline-11"
      }
    },
    {
      "id": "timeline-12",
      "label": "Vertical timeline without icons",
      "props": {
        "registryDemo": "timeline-12"
      }
    },
    {
      "id": "timeline-13",
      "label": "Responsive: vertical by default, horizontal on large screen",
      "props": {
        "registryDemo": "timeline-13"
      }
    },
    {
      "id": "timeline-14",
      "label": "Timeline with icon snapped to the start",
      "props": {
        "registryDemo": "timeline-14"
      }
    }
  ],
  "Toast": [
    {
      "id": "toast-1",
      "label": "toast with alert inside",
      "props": {
        "registryDemo": "toast-1"
      }
    },
    {
      "id": "toast-2",
      "label": "toast-top toast-start",
      "props": {
        "registryDemo": "toast-2"
      }
    },
    {
      "id": "toast-3",
      "label": "toast-top toast-center",
      "props": {
        "registryDemo": "toast-3"
      }
    },
    {
      "id": "toast-4",
      "label": "toast-top toast-end",
      "props": {
        "registryDemo": "toast-4"
      }
    },
    {
      "id": "toast-5",
      "label": "toast-start toast-middle",
      "props": {
        "registryDemo": "toast-5"
      }
    },
    {
      "id": "toast-6",
      "label": "toast-center toast-middle",
      "props": {
        "registryDemo": "toast-6"
      }
    },
    {
      "id": "toast-7",
      "label": "toast-end toast-middle",
      "props": {
        "registryDemo": "toast-7"
      }
    },
    {
      "id": "toast-8",
      "label": "toast-start toast-bottom (default)",
      "props": {
        "registryDemo": "toast-8"
      }
    },
    {
      "id": "toast-9",
      "label": "toast-center toast-bottom (default)",
      "props": {
        "registryDemo": "toast-9"
      }
    },
    {
      "id": "toast-10",
      "label": "toast-end (default) toast-bottom (default)",
      "props": {
        "registryDemo": "toast-10"
      }
    }
  ],
  "Toggle": [
    {
      "id": "toggle-1",
      "label": "Toggle (switch)",
      "props": {
        "registryDemo": "toggle-1"
      }
    },
    {
      "id": "toggle-2",
      "label": "With fieldset and label",
      "props": {
        "registryDemo": "toggle-2"
      }
    },
    {
      "id": "toggle-3",
      "label": "Sizes",
      "props": {
        "registryDemo": "toggle-3"
      }
    },
    {
      "id": "toggle-4",
      "label": "Colors",
      "props": {
        "registryDemo": "toggle-4"
      }
    },
    {
      "id": "toggle-5",
      "label": "Disabled",
      "props": {
        "registryDemo": "toggle-5"
      }
    },
    {
      "id": "toggle-6",
      "label": "Indeterminate",
      "props": {
        "registryDemo": "toggle-6"
      }
    },
    {
      "id": "toggle-7",
      "label": "Toggle with icons inside",
      "props": {
        "registryDemo": "toggle-7"
      }
    },
    {
      "id": "toggle-8",
      "label": "Toggle with custom colors",
      "props": {
        "registryDemo": "toggle-8"
      }
    }
  ],
  "Tooltip": [
    {
      "id": "tooltip-1",
      "label": "Tooltip",
      "props": {
        "registryDemo": "tooltip-1"
      }
    },
    {
      "id": "tooltip-2",
      "label": "Tooltip with tooltip-content",
      "props": {
        "registryDemo": "tooltip-2"
      }
    },
    {
      "id": "tooltip-3",
      "label": "Force open",
      "props": {
        "registryDemo": "tooltip-3"
      }
    },
    {
      "id": "tooltip-4",
      "label": "Top",
      "props": {
        "registryDemo": "tooltip-4"
      }
    },
    {
      "id": "tooltip-5",
      "label": "Bottom",
      "props": {
        "registryDemo": "tooltip-5"
      }
    },
    {
      "id": "tooltip-6",
      "label": "Left",
      "props": {
        "registryDemo": "tooltip-6"
      }
    },
    {
      "id": "tooltip-7",
      "label": "Right",
      "props": {
        "registryDemo": "tooltip-7"
      }
    },
    {
      "id": "tooltip-8",
      "label": "Primary color",
      "props": {
        "registryDemo": "tooltip-8"
      }
    },
    {
      "id": "tooltip-9",
      "label": "Secondary color",
      "props": {
        "registryDemo": "tooltip-9"
      }
    },
    {
      "id": "tooltip-10",
      "label": "Accent color",
      "props": {
        "registryDemo": "tooltip-10"
      }
    },
    {
      "id": "tooltip-11",
      "label": "Info color",
      "props": {
        "registryDemo": "tooltip-11"
      }
    },
    {
      "id": "tooltip-12",
      "label": "Success color",
      "props": {
        "registryDemo": "tooltip-12"
      }
    },
    {
      "id": "tooltip-13",
      "label": "Warning color",
      "props": {
        "registryDemo": "tooltip-13"
      }
    },
    {
      "id": "tooltip-14",
      "label": "Error color",
      "props": {
        "registryDemo": "tooltip-14"
      }
    },
    {
      "id": "tooltip-15",
      "label": "Responsive tooltip. only show for large screen",
      "props": {
        "registryDemo": "tooltip-15"
      }
    },
    {
      "id": "tooltip-16",
      "label": "Responsive tooltip position",
      "props": {
        "registryDemo": "tooltip-16"
      }
    }
  ],
  "Validator": [
    {
      "id": "validator-1",
      "label": "Validator",
      "props": {
        "registryDemo": "validator-1"
      }
    },
    {
      "id": "validator-2",
      "label": "Validator and validator-hint",
      "props": {
        "registryDemo": "validator-2"
      }
    },
    {
      "id": "validator-3",
      "label": "Password requirement validator",
      "props": {
        "registryDemo": "validator-3"
      }
    },
    {
      "id": "validator-4",
      "label": "Username requirement validator",
      "props": {
        "registryDemo": "validator-4"
      }
    },
    {
      "id": "validator-5",
      "label": "Phone Number requirement validator",
      "props": {
        "registryDemo": "validator-5"
      }
    },
    {
      "id": "validator-6",
      "label": "URL input requirement validator",
      "props": {
        "registryDemo": "validator-6"
      }
    },
    {
      "id": "validator-7",
      "label": "Date input requirement validator",
      "props": {
        "registryDemo": "validator-7"
      }
    },
    {
      "id": "validator-8",
      "label": "Number input requirement validator",
      "props": {
        "registryDemo": "validator-8"
      }
    },
    {
      "id": "validator-9",
      "label": "Checkbox requirement validator",
      "props": {
        "registryDemo": "validator-9"
      }
    },
    {
      "id": "validator-10",
      "label": "Toggle requirement validator",
      "props": {
        "registryDemo": "validator-10"
      }
    },
    {
      "id": "validator-11",
      "label": "Select requirement validator",
      "props": {
        "registryDemo": "validator-11"
      }
    },
    {
      "id": "validator-12",
      "label": "Form requirement validator",
      "props": {
        "registryDemo": "validator-12"
      }
    }
  ]
} as const satisfies Record<string, readonly UiComponentVariant[]>;
