// Generated by scripts/sync-inspira-registry.mjs from official Inspira UI examples.
import type { UiComponentVariant } from './ui-library.js';
export const INSPIRA_OFFICIAL_COMPONENT_VARIANTS = {
  "AuroraBackground": [
    {
      "id": "inspira-aurora-background-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "aurora-background",
        "registryDemo": "inspira-aurora-background-basic"
      }
    }
  ],
  "BlackHoleBackground": [
    {
      "id": "inspira-black-hole-background-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "black-hole-background",
        "registryDemo": "inspira-black-hole-background-basic"
      }
    }
  ],
  "BubblesBg": [
    {
      "id": "inspira-bubbles-bg-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "bubbles-bg",
        "registryDemo": "inspira-bubbles-bg-basic"
      }
    },
    {
      "id": "inspira-bubbles-bg-bubbles-bg2",
      "label": "官方 · Bubbles Bg 2",
      "props": {
        "componentSlug": "bubbles-bg",
        "registryDemo": "inspira-bubbles-bg-bubbles-bg2"
      }
    }
  ],
  "CosmicPortal": [
    {
      "id": "inspira-cosmic-portal-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "cosmic-portal",
        "registryDemo": "inspira-cosmic-portal-basic"
      }
    }
  ],
  "FallingStars": [
    {
      "id": "inspira-falling-stars-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "falling-stars",
        "registryDemo": "inspira-falling-stars-basic"
      }
    }
  ],
  "FlickeringGrid": [
    {
      "id": "inspira-flickering-grid-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "flickering-grid",
        "registryDemo": "inspira-flickering-grid-basic"
      }
    }
  ],
  "InteractiveGridPattern": [
    {
      "id": "inspira-interactive-grid-pattern-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "interactive-grid-pattern",
        "registryDemo": "inspira-interactive-grid-pattern-basic"
      }
    },
    {
      "id": "inspira-interactive-grid-pattern-colored",
      "label": "官方 · Interactive Grid Pattern Colored",
      "props": {
        "componentSlug": "interactive-grid-pattern",
        "registryDemo": "inspira-interactive-grid-pattern-colored"
      }
    }
  ],
  "LampEffect": [
    {
      "id": "inspira-lamp-effect-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "lamp-effect",
        "registryDemo": "inspira-lamp-effect-basic"
      }
    }
  ],
  "LiquidBackground": [
    {
      "id": "inspira-liquid-background-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "liquid-background",
        "registryDemo": "inspira-liquid-background-basic"
      }
    }
  ],
  "NeuralBackground": [
    {
      "id": "inspira-neural-background-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "neural-background",
        "registryDemo": "inspira-neural-background-basic"
      }
    }
  ],
  "ParticleWhirlpoolBg": [
    {
      "id": "inspira-particle-whirlpool-bg-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "particle-whirlpool-bg",
        "registryDemo": "inspira-particle-whirlpool-bg-basic"
      }
    },
    {
      "id": "inspira-particle-whirlpool-bg-particle-whirlpool-bg2",
      "label": "官方 · Particle Whirlpool Bg 2",
      "props": {
        "componentSlug": "particle-whirlpool-bg",
        "registryDemo": "inspira-particle-whirlpool-bg-particle-whirlpool-bg2"
      }
    },
    {
      "id": "inspira-particle-whirlpool-bg-particle-whirlpool-bg3",
      "label": "官方 · Particle Whirlpool Bg 3",
      "props": {
        "componentSlug": "particle-whirlpool-bg",
        "registryDemo": "inspira-particle-whirlpool-bg-particle-whirlpool-bg3"
      }
    }
  ],
  "ParticlesBg": [
    {
      "id": "inspira-particles-bg-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "particles-bg",
        "registryDemo": "inspira-particles-bg-basic"
      }
    }
  ],
  "PatternBackground": [
    {
      "id": "inspira-pattern-background-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "pattern-background",
        "registryDemo": "inspira-pattern-background-basic"
      }
    },
    {
      "id": "inspira-pattern-background-big-dot",
      "label": "官方 · Pattern Background Big Dot",
      "props": {
        "componentSlug": "pattern-background",
        "registryDemo": "inspira-pattern-background-big-dot"
      }
    },
    {
      "id": "inspira-pattern-background-dot",
      "label": "官方 · Pattern Background Dot",
      "props": {
        "componentSlug": "pattern-background",
        "registryDemo": "inspira-pattern-background-dot"
      }
    },
    {
      "id": "inspira-pattern-background-grid",
      "label": "官方 · Pattern Background Grid",
      "props": {
        "componentSlug": "pattern-background",
        "registryDemo": "inspira-pattern-background-grid"
      }
    },
    {
      "id": "inspira-pattern-background-grid-small",
      "label": "官方 · Pattern Background Grid Small",
      "props": {
        "componentSlug": "pattern-background",
        "registryDemo": "inspira-pattern-background-grid-small"
      }
    }
  ],
  "RibbonBackground": [
    {
      "id": "inspira-ribbon-background-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "ribbon-background",
        "registryDemo": "inspira-ribbon-background-basic"
      }
    }
  ],
  "Ripple": [
    {
      "id": "inspira-ripple-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "ripple",
        "registryDemo": "inspira-ripple-basic"
      }
    },
    {
      "id": "inspira-ripple-blobed",
      "label": "官方 · Ripple Blobed",
      "props": {
        "componentSlug": "ripple",
        "registryDemo": "inspira-ripple-blobed"
      }
    },
    {
      "id": "inspira-ripple-lines-only",
      "label": "官方 · Ripple Lines Only",
      "props": {
        "componentSlug": "ripple",
        "registryDemo": "inspira-ripple-lines-only"
      }
    },
    {
      "id": "inspira-ripple-squared",
      "label": "官方 · Ripple Squared",
      "props": {
        "componentSlug": "ripple",
        "registryDemo": "inspira-ripple-squared"
      }
    }
  ],
  "SilkBackground": [
    {
      "id": "inspira-silk-background-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "silk-background",
        "registryDemo": "inspira-silk-background-basic"
      }
    }
  ],
  "SingularityBackground": [
    {
      "id": "inspira-singularity-background-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "singularity-background",
        "registryDemo": "inspira-singularity-background-basic"
      }
    }
  ],
  "SnowfallBg": [
    {
      "id": "inspira-snowfall-bg-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "snowfall-bg",
        "registryDemo": "inspira-snowfall-bg-basic"
      }
    }
  ],
  "Sparkles": [
    {
      "id": "inspira-sparkles-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "sparkles",
        "registryDemo": "inspira-sparkles-basic"
      }
    },
    {
      "id": "inspira-sparkles-full-page",
      "label": "官方 · Sparkles Full Page",
      "props": {
        "componentSlug": "sparkles",
        "registryDemo": "inspira-sparkles-full-page"
      }
    }
  ],
  "StarsBackground": [
    {
      "id": "inspira-stars-background-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "stars-background",
        "registryDemo": "inspira-stars-background-basic"
      }
    }
  ],
  "StractiumBackground": [
    {
      "id": "inspira-stractium-background-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "stractium-background",
        "registryDemo": "inspira-stractium-background-basic"
      }
    }
  ],
  "Tetris": [
    {
      "id": "inspira-tetris-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "tetris",
        "registryDemo": "inspira-tetris-basic"
      }
    }
  ],
  "ThunderstormBackground": [
    {
      "id": "inspira-thunderstorm-background-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "thunderstorm-background",
        "registryDemo": "inspira-thunderstorm-background-basic"
      }
    }
  ],
  "VideoText": [
    {
      "id": "inspira-video-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "video-text",
        "registryDemo": "inspira-video-text-basic"
      }
    }
  ],
  "Vortex": [
    {
      "id": "inspira-vortex-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "vortex",
        "registryDemo": "inspira-vortex-basic"
      }
    },
    {
      "id": "inspira-vortex-full-page",
      "label": "官方 · Vortex Full Page",
      "props": {
        "componentSlug": "vortex",
        "registryDemo": "inspira-vortex-full-page"
      }
    }
  ],
  "WarpBackground": [
    {
      "id": "inspira-warp-background-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "warp-background",
        "registryDemo": "inspira-warp-background-basic"
      }
    }
  ],
  "WavyBackground": [
    {
      "id": "inspira-wavy-background-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "wavy-background",
        "registryDemo": "inspira-wavy-background-basic"
      }
    }
  ],
  "GradientButton": [
    {
      "id": "inspira-gradient-button-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "gradient-button",
        "registryDemo": "inspira-gradient-button-basic"
      }
    }
  ],
  "InteractiveHoverButton": [
    {
      "id": "inspira-interactive-hover-button-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "interactive-hover-button",
        "registryDemo": "inspira-interactive-hover-button-basic"
      }
    }
  ],
  "RainbowButton": [
    {
      "id": "inspira-rainbow-button-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "rainbow-button",
        "registryDemo": "inspira-rainbow-button-basic"
      }
    }
  ],
  "RippleButton": [
    {
      "id": "inspira-ripple-button-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "ripple-button",
        "registryDemo": "inspira-ripple-button-basic"
      }
    }
  ],
  "ShimmerButton": [
    {
      "id": "inspira-shimmer-button-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "shimmer-button",
        "registryDemo": "inspira-shimmer-button-basic"
      }
    }
  ],
  "ThreeDCard": [
    {
      "id": "inspira-3d-card-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "3d-card",
        "registryDemo": "inspira-3d-card-basic"
      }
    },
    {
      "id": "inspira-3d-card-card2",
      "label": "官方 · Card 2",
      "props": {
        "componentSlug": "3d-card",
        "registryDemo": "inspira-3d-card-card2"
      }
    }
  ],
  "AppleCardCarousel": [
    {
      "id": "inspira-apple-card-carousel-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "apple-card-carousel",
        "registryDemo": "inspira-apple-card-carousel-basic"
      }
    }
  ],
  "CardSpotlight": [
    {
      "id": "inspira-card-spotlight-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "card-spotlight",
        "registryDemo": "inspira-card-spotlight-basic"
      }
    }
  ],
  "CardStack": [
    {
      "id": "inspira-card-stack-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "card-stack",
        "registryDemo": "inspira-card-stack-basic"
      }
    }
  ],
  "CubeCarousel": [
    {
      "id": "inspira-cube-carousel-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "cube-carousel",
        "registryDemo": "inspira-cube-carousel-basic"
      }
    }
  ],
  "DirectionAwareHover": [
    {
      "id": "inspira-direction-aware-hover-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "direction-aware-hover",
        "registryDemo": "inspira-direction-aware-hover-basic"
      }
    }
  ],
  "FeyCards": [
    {
      "id": "inspira-fey-cards-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "fey-cards",
        "registryDemo": "inspira-fey-cards-basic"
      }
    }
  ],
  "FlipCard": [
    {
      "id": "inspira-flip-card-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "flip-card",
        "registryDemo": "inspira-flip-card-basic"
      }
    },
    {
      "id": "inspira-flip-card-horizontal",
      "label": "官方 · Flip Card Horizontal",
      "props": {
        "componentSlug": "flip-card",
        "registryDemo": "inspira-flip-card-horizontal"
      }
    }
  ],
  "FloatingCard": [
    {
      "id": "inspira-floating-card-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "floating-card",
        "registryDemo": "inspira-floating-card-basic"
      }
    }
  ],
  "GlareCard": [
    {
      "id": "inspira-glare-card-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "glare-card",
        "registryDemo": "inspira-glare-card-basic"
      }
    },
    {
      "id": "inspira-glare-card-glare-multi-card",
      "label": "官方 · Glare Multi Card",
      "props": {
        "componentSlug": "glare-card",
        "registryDemo": "inspira-glare-card-glare-multi-card"
      }
    }
  ],
  "FluidCursor": [
    {
      "id": "inspira-fluid-cursor-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "fluid-cursor",
        "registryDemo": "inspira-fluid-cursor-basic"
      }
    }
  ],
  "ImageTrailCursor": [
    {
      "id": "inspira-image-trail-cursor-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "image-trail-cursor",
        "registryDemo": "inspira-image-trail-cursor-basic"
      }
    }
  ],
  "SleekLineCursor": [
    {
      "id": "inspira-sleek-line-cursor-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "sleek-line-cursor",
        "registryDemo": "inspira-sleek-line-cursor-basic"
      }
    }
  ],
  "SmoothCursor": [
    {
      "id": "inspira-smooth-cursor-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "smooth-cursor",
        "registryDemo": "inspira-smooth-cursor-basic"
      }
    }
  ],
  "TailedCursor": [
    {
      "id": "inspira-tailed-cursor-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "tailed-cursor",
        "registryDemo": "inspira-tailed-cursor-basic"
      }
    }
  ],
  "IphoneMockup": [
    {
      "id": "inspira-iphone-mockup-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "iphone-mockup",
        "registryDemo": "inspira-iphone-mockup-basic"
      }
    }
  ],
  "SafariMockup": [
    {
      "id": "inspira-safari-mockup-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "safari-mockup",
        "registryDemo": "inspira-safari-mockup-basic"
      }
    }
  ],
  "HtmlAscii": [
    {
      "id": "inspira-html-ascii-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "html-ascii",
        "registryDemo": "inspira-html-ascii-basic"
      }
    }
  ],
  "HtmlBlaze": [
    {
      "id": "inspira-html-blaze-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "html-blaze",
        "registryDemo": "inspira-html-blaze-basic"
      }
    }
  ],
  "HtmlChromatic": [
    {
      "id": "inspira-html-chromatic-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "html-chromatic",
        "registryDemo": "inspira-html-chromatic-basic"
      }
    }
  ],
  "HtmlCloth": [
    {
      "id": "inspira-html-cloth-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "html-cloth",
        "registryDemo": "inspira-html-cloth-basic"
      }
    }
  ],
  "HtmlDrag": [
    {
      "id": "inspira-html-drag-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "html-drag",
        "registryDemo": "inspira-html-drag-basic"
      }
    }
  ],
  "HtmlInCanvas": [
    {
      "id": "inspira-html-in-canvas-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "html-in-canvas",
        "registryDemo": "inspira-html-in-canvas-basic"
      }
    },
    {
      "id": "inspira-html-in-canvas-html-effect-surface",
      "label": "官方 · Html Effect Surface",
      "props": {
        "componentSlug": "html-in-canvas",
        "registryDemo": "inspira-html-in-canvas-html-effect-surface"
      }
    }
  ],
  "HtmlLiquid": [
    {
      "id": "inspira-html-liquid-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "html-liquid",
        "registryDemo": "inspira-html-liquid-basic"
      }
    }
  ],
  "BalanceSlider": [
    {
      "id": "inspira-balance-slider-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "balance-slider",
        "registryDemo": "inspira-balance-slider-basic"
      }
    }
  ],
  "ColorPicker": [
    {
      "id": "inspira-color-picker-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "color-picker",
        "registryDemo": "inspira-color-picker-basic"
      }
    }
  ],
  "FileUpload": [
    {
      "id": "inspira-file-upload-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "file-upload",
        "registryDemo": "inspira-file-upload-basic"
      }
    }
  ],
  "HaloSearch": [
    {
      "id": "inspira-halo-search-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "halo-search",
        "registryDemo": "inspira-halo-search-basic"
      }
    }
  ],
  "Input": [
    {
      "id": "inspira-input-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "input",
        "registryDemo": "inspira-input-basic"
      }
    }
  ],
  "PlaceholdersAndVanishInput": [
    {
      "id": "inspira-placeholders-and-vanish-input-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "placeholders-and-vanish-input",
        "registryDemo": "inspira-placeholders-and-vanish-input-basic"
      }
    }
  ],
  "AnimateGrid": [
    {
      "id": "inspira-animate-grid-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "animate-grid",
        "registryDemo": "inspira-animate-grid-basic"
      }
    }
  ],
  "AnimatedCircularProgressbar": [
    {
      "id": "inspira-animated-circular-progressbar-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "animated-circular-progressbar",
        "registryDemo": "inspira-animated-circular-progressbar-basic"
      }
    }
  ],
  "AnimatedList": [
    {
      "id": "inspira-animated-list-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "animated-list",
        "registryDemo": "inspira-animated-list-basic"
      }
    }
  ],
  "AnimatedModal": [
    {
      "id": "inspira-animated-modal-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "animated-modal",
        "registryDemo": "inspira-animated-modal-basic"
      }
    }
  ],
  "AnimatedTabs": [
    {
      "id": "inspira-animated-tabs-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "animated-tabs",
        "registryDemo": "inspira-animated-tabs-basic"
      }
    }
  ],
  "AnimatedTooltip": [
    {
      "id": "inspira-animated-tooltip-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "animated-tooltip",
        "registryDemo": "inspira-animated-tooltip-basic"
      }
    }
  ],
  "BentoGrid": [
    {
      "id": "inspira-bento-grid-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "bento-grid",
        "registryDemo": "inspira-bento-grid-basic"
      }
    },
    {
      "id": "inspira-bento-grid-bento-grid2",
      "label": "官方 · Bento Grid 2",
      "props": {
        "componentSlug": "bento-grid",
        "registryDemo": "inspira-bento-grid-bento-grid2"
      }
    }
  ],
  "Book": [
    {
      "id": "inspira-book-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "book",
        "registryDemo": "inspira-book-basic"
      }
    }
  ],
  "CircularGallery": [
    {
      "id": "inspira-circular-gallery-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "circular-gallery",
        "registryDemo": "inspira-circular-gallery-basic"
      }
    }
  ],
  "Compare": [
    {
      "id": "inspira-compare-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "compare",
        "registryDemo": "inspira-compare-basic"
      }
    },
    {
      "id": "inspira-compare-autoplay",
      "label": "官方 · Compare Autoplay",
      "props": {
        "componentSlug": "compare",
        "registryDemo": "inspira-compare-autoplay"
      }
    },
    {
      "id": "inspira-compare-custom-content",
      "label": "官方 · Compare Custom Content",
      "props": {
        "componentSlug": "compare",
        "registryDemo": "inspira-compare-custom-content"
      }
    },
    {
      "id": "inspira-compare-drag",
      "label": "官方 · Compare Drag",
      "props": {
        "componentSlug": "compare",
        "registryDemo": "inspira-compare-drag"
      }
    }
  ],
  "ContainerScroll": [
    {
      "id": "inspira-container-scroll-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "container-scroll",
        "registryDemo": "inspira-container-scroll-basic"
      }
    }
  ],
  "Dock": [
    {
      "id": "inspira-dock-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "dock",
        "registryDemo": "inspira-dock-basic"
      }
    },
    {
      "id": "inspira-dock-dock2",
      "label": "官方 · Dock 2",
      "props": {
        "componentSlug": "dock",
        "registryDemo": "inspira-dock-dock2"
      }
    }
  ],
  "ExpandableGallery": [
    {
      "id": "inspira-expandable-gallery-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "expandable-gallery",
        "registryDemo": "inspira-expandable-gallery-basic"
      }
    }
  ],
  "Float": [
    {
      "id": "inspira-float-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "float",
        "registryDemo": "inspira-float-basic"
      }
    }
  ],
  "ImagesSlider": [
    {
      "id": "inspira-images-slider-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "images-slider",
        "registryDemo": "inspira-images-slider-basic"
      }
    }
  ],
  "Lens": [
    {
      "id": "inspira-lens-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "lens",
        "registryDemo": "inspira-lens-basic"
      }
    },
    {
      "id": "inspira-lens-static-lens",
      "label": "官方 · Static Lens",
      "props": {
        "componentSlug": "lens",
        "registryDemo": "inspira-lens-static-lens"
      }
    }
  ],
  "LinkPreview": [
    {
      "id": "inspira-link-preview-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "link-preview",
        "registryDemo": "inspira-link-preview-basic"
      }
    }
  ],
  "Marquee": [
    {
      "id": "inspira-marquee-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "marquee",
        "registryDemo": "inspira-marquee-basic"
      }
    }
  ],
  "MediaText": [
    {
      "id": "inspira-media-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "media-text",
        "registryDemo": "inspira-media-text-basic"
      }
    }
  ],
  "MorphingTabs": [
    {
      "id": "inspira-morphing-tabs-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "morphing-tabs",
        "registryDemo": "inspira-morphing-tabs-basic"
      }
    }
  ],
  "MultiStepLoader": [
    {
      "id": "inspira-multi-step-loader-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "multi-step-loader",
        "registryDemo": "inspira-multi-step-loader-basic"
      }
    }
  ],
  "ParallaxFloat": [
    {
      "id": "inspira-parallax-float-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "parallax-float",
        "registryDemo": "inspira-parallax-float-basic"
      }
    }
  ],
  "PathMarquee": [
    {
      "id": "inspira-path-marquee-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "path-marquee",
        "registryDemo": "inspira-path-marquee-basic"
      }
    }
  ],
  "PhotoGallery": [
    {
      "id": "inspira-photo-gallery-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "photo-gallery",
        "registryDemo": "inspira-photo-gallery-basic"
      }
    }
  ],
  "ScrollIsland": [
    {
      "id": "inspira-scroll-island-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "scroll-island",
        "registryDemo": "inspira-scroll-island-basic"
      }
    }
  ],
  "ShaderToy": [
    {
      "id": "inspira-shader-toy-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "shader-toy",
        "registryDemo": "inspira-shader-toy-basic"
      }
    }
  ],
  "SvgMask": [
    {
      "id": "inspira-svg-mask-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "svg-mask",
        "registryDemo": "inspira-svg-mask-basic"
      }
    }
  ],
  "Timeline": [
    {
      "id": "inspira-timeline-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "timeline",
        "registryDemo": "inspira-timeline-basic"
      }
    }
  ],
  "TracingBeam": [
    {
      "id": "inspira-tracing-beam-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "tracing-beam",
        "registryDemo": "inspira-tracing-beam-basic"
      }
    }
  ],
  "AnimatedBeam": [
    {
      "id": "inspira-animated-beam-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "animated-beam",
        "registryDemo": "inspira-animated-beam-basic"
      }
    },
    {
      "id": "inspira-animated-beam-animated-beam2",
      "label": "官方 · Animated Beam 2",
      "props": {
        "componentSlug": "animated-beam",
        "registryDemo": "inspira-animated-beam-animated-beam2"
      }
    },
    {
      "id": "inspira-animated-beam-animated-beam3",
      "label": "官方 · Animated Beam 3",
      "props": {
        "componentSlug": "animated-beam",
        "registryDemo": "inspira-animated-beam-animated-beam3"
      }
    }
  ],
  "BorderBeam": [
    {
      "id": "inspira-border-beam-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "border-beam",
        "registryDemo": "inspira-border-beam-basic"
      }
    }
  ],
  "Confetti": [
    {
      "id": "inspira-confetti-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "confetti",
        "registryDemo": "inspira-confetti-basic"
      }
    },
    {
      "id": "inspira-confetti-confetti-basic",
      "label": "官方 · Confetti Basic",
      "props": {
        "componentSlug": "confetti",
        "registryDemo": "inspira-confetti-confetti-basic"
      }
    },
    {
      "id": "inspira-confetti-cannons",
      "label": "官方 · Confetti Cannons",
      "props": {
        "componentSlug": "confetti",
        "registryDemo": "inspira-confetti-cannons"
      }
    },
    {
      "id": "inspira-confetti-fireworks",
      "label": "官方 · Confetti Fireworks",
      "props": {
        "componentSlug": "confetti",
        "registryDemo": "inspira-confetti-fireworks"
      }
    },
    {
      "id": "inspira-confetti-random-direction",
      "label": "官方 · Confetti Random Direction",
      "props": {
        "componentSlug": "confetti",
        "registryDemo": "inspira-confetti-random-direction"
      }
    }
  ],
  "DitherShader": [
    {
      "id": "inspira-dither-shader-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "dither-shader",
        "registryDemo": "inspira-dither-shader-basic"
      }
    }
  ],
  "GlowBorder": [
    {
      "id": "inspira-glow-border-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "glow-border",
        "registryDemo": "inspira-glow-border-basic"
      }
    }
  ],
  "GlowingEffect": [
    {
      "id": "inspira-glowing-effect-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "glowing-effect",
        "registryDemo": "inspira-glowing-effect-basic"
      }
    }
  ],
  "ImagesBadge": [
    {
      "id": "inspira-images-badge-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "images-badge",
        "registryDemo": "inspira-images-badge-basic"
      }
    }
  ],
  "Meteors": [
    {
      "id": "inspira-meteors-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "meteors",
        "registryDemo": "inspira-meteors-basic"
      }
    }
  ],
  "NeonBorder": [
    {
      "id": "inspira-neon-border-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "neon-border",
        "registryDemo": "inspira-neon-border-basic"
      }
    }
  ],
  "ParticleImage": [
    {
      "id": "inspira-particle-image-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "particle-image",
        "registryDemo": "inspira-particle-image-basic"
      }
    }
  ],
  "ProgressiveBlur": [
    {
      "id": "inspira-progressive-blur-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "progressive-blur",
        "registryDemo": "inspira-progressive-blur-basic"
      }
    }
  ],
  "Scales": [
    {
      "id": "inspira-scales-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "scales",
        "registryDemo": "inspira-scales-basic"
      }
    }
  ],
  "ScratchToReveal": [
    {
      "id": "inspira-scratch-to-reveal-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "scratch-to-reveal",
        "registryDemo": "inspira-scratch-to-reveal-basic"
      }
    }
  ],
  "SpringCalendar": [
    {
      "id": "inspira-spring-calendar-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "spring-calendar",
        "registryDemo": "inspira-spring-calendar-basic"
      }
    }
  ],
  "AnimatedTestimonials": [
    {
      "id": "inspira-animated-testimonials-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "animated-testimonials",
        "registryDemo": "inspira-animated-testimonials-basic"
      }
    }
  ],
  "DesignTestimonials": [
    {
      "id": "inspira-design-testimonials-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "design-testimonials",
        "registryDemo": "inspira-design-testimonials-basic"
      }
    }
  ],
  "TestimonialSlider": [
    {
      "id": "inspira-testimonial-slider-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "testimonial-slider",
        "registryDemo": "inspira-testimonial-slider-basic"
      }
    }
  ],
  "ThreeDText": [
    {
      "id": "inspira-3d-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "3d-text",
        "registryDemo": "inspira-3d-text-basic"
      }
    }
  ],
  "BlurReveal": [
    {
      "id": "inspira-blur-reveal-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "blur-reveal",
        "registryDemo": "inspira-blur-reveal-basic"
      }
    }
  ],
  "BoxReveal": [
    {
      "id": "inspira-box-reveal-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "box-reveal",
        "registryDemo": "inspira-box-reveal-basic"
      }
    }
  ],
  "BreathingText": [
    {
      "id": "inspira-breathing-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "breathing-text",
        "registryDemo": "inspira-breathing-text-basic"
      }
    }
  ],
  "ColorfulText": [
    {
      "id": "inspira-colorful-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "colorful-text",
        "registryDemo": "inspira-colorful-text-basic"
      }
    }
  ],
  "ContainerTextFlip": [
    {
      "id": "inspira-container-text-flip-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "container-text-flip",
        "registryDemo": "inspira-container-text-flip-basic"
      }
    },
    {
      "id": "inspira-container-text-flip-hero",
      "label": "官方 · Container Text Flip Hero",
      "props": {
        "componentSlug": "container-text-flip",
        "registryDemo": "inspira-container-text-flip-hero"
      }
    },
    {
      "id": "inspira-container-text-flip-standard",
      "label": "官方 · Container Text Flip Standard",
      "props": {
        "componentSlug": "container-text-flip",
        "registryDemo": "inspira-container-text-flip-standard"
      }
    }
  ],
  "EncryptedText": [
    {
      "id": "inspira-encrypted-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "encrypted-text",
        "registryDemo": "inspira-encrypted-text-basic"
      }
    }
  ],
  "FlipWords": [
    {
      "id": "inspira-flip-words-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "flip-words",
        "registryDemo": "inspira-flip-words-basic"
      }
    }
  ],
  "Focus": [
    {
      "id": "inspira-focus-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "focus",
        "registryDemo": "inspira-focus-basic"
      }
    },
    {
      "id": "inspira-focus-auto",
      "label": "官方 · Focus Auto",
      "props": {
        "componentSlug": "focus",
        "registryDemo": "inspira-focus-auto"
      }
    },
    {
      "id": "inspira-focus-manual",
      "label": "官方 · Focus Manual",
      "props": {
        "componentSlug": "focus",
        "registryDemo": "inspira-focus-manual"
      }
    }
  ],
  "HighlightText": [
    {
      "id": "inspira-highlight-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "highlight-text",
        "registryDemo": "inspira-highlight-text-basic"
      }
    }
  ],
  "HyperText": [
    {
      "id": "inspira-hyper-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "hyper-text",
        "registryDemo": "inspira-hyper-text-basic"
      }
    }
  ],
  "LetterPullup": [
    {
      "id": "inspira-letter-pullup-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "letter-pullup",
        "registryDemo": "inspira-letter-pullup-basic"
      }
    }
  ],
  "LetterSwap": [
    {
      "id": "inspira-letter-swap-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "letter-swap",
        "registryDemo": "inspira-letter-swap-basic"
      }
    }
  ],
  "LineShadowText": [
    {
      "id": "inspira-line-shadow-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "line-shadow-text",
        "registryDemo": "inspira-line-shadow-text-basic"
      }
    }
  ],
  "MorphingText": [
    {
      "id": "inspira-morphing-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "morphing-text",
        "registryDemo": "inspira-morphing-text-basic"
      }
    }
  ],
  "NumberTicker": [
    {
      "id": "inspira-number-ticker-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "number-ticker",
        "registryDemo": "inspira-number-ticker-basic"
      }
    }
  ],
  "RadiantText": [
    {
      "id": "inspira-radiant-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "radiant-text",
        "registryDemo": "inspira-radiant-text-basic"
      }
    }
  ],
  "ScrewText": [
    {
      "id": "inspira-screw-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "screw-text",
        "registryDemo": "inspira-screw-text-basic"
      }
    }
  ],
  "ScrollSwapText": [
    {
      "id": "inspira-scroll-swap-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "scroll-swap-text",
        "registryDemo": "inspira-scroll-swap-text-basic"
      }
    }
  ],
  "SparklesText": [
    {
      "id": "inspira-sparkles-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "sparkles-text",
        "registryDemo": "inspira-sparkles-text-basic"
      }
    }
  ],
  "SpinningText": [
    {
      "id": "inspira-spinning-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "spinning-text",
        "registryDemo": "inspira-spinning-text-basic"
      }
    },
    {
      "id": "inspira-spinning-text-reverse",
      "label": "官方 · Spinning Text Reverse",
      "props": {
        "componentSlug": "spinning-text",
        "registryDemo": "inspira-spinning-text-reverse"
      }
    }
  ],
  "TextGenerateEffect": [
    {
      "id": "inspira-text-generate-effect-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "text-generate-effect",
        "registryDemo": "inspira-text-generate-effect-basic"
      }
    },
    {
      "id": "inspira-text-generate-effect-delayed",
      "label": "官方 · Text Generate Effect Delayed",
      "props": {
        "componentSlug": "text-generate-effect",
        "registryDemo": "inspira-text-generate-effect-delayed"
      }
    }
  ],
  "TextGlitch": [
    {
      "id": "inspira-text-glitch-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "text-glitch",
        "registryDemo": "inspira-text-glitch-basic"
      }
    }
  ],
  "TextHighlight": [
    {
      "id": "inspira-text-highlight-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "text-highlight",
        "registryDemo": "inspira-text-highlight-basic"
      }
    },
    {
      "id": "inspira-text-highlight-colors-from-css-variable",
      "label": "官方 · Text Highlight Colors From Css Variable",
      "props": {
        "componentSlug": "text-highlight",
        "registryDemo": "inspira-text-highlight-colors-from-css-variable"
      }
    },
    {
      "id": "inspira-text-highlight-delayed",
      "label": "官方 · Text Highlight Delayed",
      "props": {
        "componentSlug": "text-highlight",
        "registryDemo": "inspira-text-highlight-delayed"
      }
    },
    {
      "id": "inspira-text-highlight-rounded",
      "label": "官方 · Text Highlight Rounded",
      "props": {
        "componentSlug": "text-highlight",
        "registryDemo": "inspira-text-highlight-rounded"
      }
    },
    {
      "id": "inspira-text-highlight-text-color-change",
      "label": "官方 · Text Highlight Text Color Change",
      "props": {
        "componentSlug": "text-highlight",
        "registryDemo": "inspira-text-highlight-text-color-change"
      }
    }
  ],
  "TextHoverEffect": [
    {
      "id": "inspira-text-hover-effect-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "text-hover-effect",
        "registryDemo": "inspira-text-hover-effect-basic"
      }
    }
  ],
  "TextReveal": [
    {
      "id": "inspira-text-reveal-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "text-reveal",
        "registryDemo": "inspira-text-reveal-basic"
      }
    }
  ],
  "TextRevealCard": [
    {
      "id": "inspira-text-reveal-card-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "text-reveal-card",
        "registryDemo": "inspira-text-reveal-card-basic"
      }
    }
  ],
  "TextScrollReveal": [
    {
      "id": "inspira-text-scroll-reveal-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "text-scroll-reveal",
        "registryDemo": "inspira-text-scroll-reveal-basic"
      }
    }
  ],
  "TypewriterText": [
    {
      "id": "inspira-typewriter-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "typewriter-text",
        "registryDemo": "inspira-typewriter-text-basic"
      }
    }
  ],
  "UnderlineText": [
    {
      "id": "inspira-underline-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "underline-text",
        "registryDemo": "inspira-underline-text-basic"
      }
    }
  ],
  "VariableLetterText": [
    {
      "id": "inspira-variable-letter-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "variable-letter-text",
        "registryDemo": "inspira-variable-letter-text-basic"
      }
    }
  ],
  "VariableText": [
    {
      "id": "inspira-variable-text-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "variable-text",
        "registryDemo": "inspira-variable-text-basic"
      }
    }
  ],
  "BendingGallery": [
    {
      "id": "inspira-bending-gallery-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "bending-gallery",
        "registryDemo": "inspira-bending-gallery-basic"
      }
    }
  ],
  "CarousalThreeD": [
    {
      "id": "inspira-carousal-3d-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "carousal-3d",
        "registryDemo": "inspira-carousal-3d-basic"
      }
    }
  ],
  "FileTree": [
    {
      "id": "inspira-file-tree-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "file-tree",
        "registryDemo": "inspira-file-tree-basic"
      }
    }
  ],
  "GithubGlobe": [
    {
      "id": "inspira-github-globe-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "github-globe",
        "registryDemo": "inspira-github-globe-basic"
      }
    }
  ],
  "Globe": [
    {
      "id": "inspira-globe-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "globe",
        "registryDemo": "inspira-globe-basic"
      }
    }
  ],
  "IconCloud": [
    {
      "id": "inspira-icon-cloud-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "icon-cloud",
        "registryDemo": "inspira-icon-cloud-basic"
      }
    }
  ],
  "InfiniteGrid": [
    {
      "id": "inspira-infinite-grid-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "infinite-grid",
        "registryDemo": "inspira-infinite-grid-basic"
      }
    }
  ],
  "LightSpeed": [
    {
      "id": "inspira-light-speed-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "light-speed",
        "registryDemo": "inspira-light-speed-basic"
      }
    }
  ],
  "LiquidGlass": [
    {
      "id": "inspira-liquid-glass-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "liquid-glass",
        "registryDemo": "inspira-liquid-glass-basic"
      }
    }
  ],
  "LiquidLogo": [
    {
      "id": "inspira-liquid-logo-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "liquid-logo",
        "registryDemo": "inspira-liquid-logo-basic"
      }
    }
  ],
  "LogoCloud": [
    {
      "id": "inspira-logo-cloud-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "logo-cloud",
        "registryDemo": "inspira-logo-cloud-basic"
      }
    },
    {
      "id": "inspira-logo-cloud-animated-logo-cloud",
      "label": "官方 · Animated Logo Cloud",
      "props": {
        "componentSlug": "logo-cloud",
        "registryDemo": "inspira-logo-cloud-animated-logo-cloud"
      }
    },
    {
      "id": "inspira-logo-cloud-static-logo-cloud",
      "label": "官方 · Static Logo Cloud",
      "props": {
        "componentSlug": "logo-cloud",
        "registryDemo": "inspira-logo-cloud-static-logo-cloud"
      }
    }
  ],
  "LogoOrigami": [
    {
      "id": "inspira-logo-origami-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "logo-origami",
        "registryDemo": "inspira-logo-origami-basic"
      }
    }
  ],
  "Orbit": [
    {
      "id": "inspira-orbit-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "orbit",
        "registryDemo": "inspira-orbit-basic"
      }
    },
    {
      "id": "inspira-orbit-synchronized",
      "label": "官方 · Orbit Synchronized",
      "props": {
        "componentSlug": "orbit",
        "registryDemo": "inspira-orbit-synchronized"
      }
    }
  ],
  "Spline": [
    {
      "id": "inspira-spline-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "spline",
        "registryDemo": "inspira-spline-basic"
      }
    }
  ],
  "WorldMap": [
    {
      "id": "inspira-world-map-basic",
      "label": "官方基础示例",
      "props": {
        "componentSlug": "world-map",
        "registryDemo": "inspira-world-map-basic"
      }
    }
  ]
} as const satisfies Record<string, readonly UiComponentVariant[]>;
