// Generated by scripts/sync-magicui-registry.mjs from the official Magic UI registry.
import type { UiComponentVariant } from './ui-library.js';
export const MAGICUI_OFFICIAL_CATALOG = [
  {
    "slug": "magic-card",
    "title": "Magic Card",
    "description": "A spotlight effect that follows your mouse cursor and highlights borders on hover."
  },
  {
    "slug": "android",
    "title": "Android",
    "description": "A mockup of an Android device."
  },
  {
    "slug": "warp-background",
    "title": "Warp Background",
    "description": "A card with a time warping background effect."
  },
  {
    "slug": "line-shadow-text",
    "title": "Line Shadow Text",
    "description": "A text component with a moving line shadow."
  },
  {
    "slug": "aurora-text",
    "title": "Aurora Text",
    "description": "A beautiful aurora text effect"
  },
  {
    "slug": "morphing-text",
    "title": "Morphing Text",
    "description": "A dynamic text morphing component for Magic UI."
  },
  {
    "slug": "scroll-progress",
    "title": "Scroll Progress",
    "description": "Animated Scroll Progress for your pages"
  },
  {
    "slug": "lens",
    "title": "Lens",
    "description": "A interactive component that enables zooming into images, videos and other elements."
  },
  {
    "slug": "pointer",
    "title": "Pointer",
    "description": "A component that displays a pointer when hovering over an element"
  },
  {
    "slug": "smooth-cursor",
    "title": "smooth-cursor",
    "description": "A customizable, physics-based smooth cursor animation component with spring animations and rotation effects"
  },
  {
    "slug": "progressive-blur",
    "title": "Progressive Blur",
    "description": "The Progressive Blur component adds a smooth blur gradient effect to scrollable content, indicating more content below or above."
  },
  {
    "slug": "neon-gradient-card",
    "title": "Neon Gradient Card",
    "description": "A beautiful neon card effect"
  },
  {
    "slug": "meteors",
    "title": "Meteors",
    "description": "A meteor shower effect."
  },
  {
    "slug": "grid-pattern",
    "title": "Grid Pattern",
    "description": "A background grid pattern made with SVGs, fully customizable using Tailwind CSS."
  },
  {
    "slug": "striped-pattern",
    "title": "Striped Pattern",
    "description": "A background striped pattern made with SVGs, fully customizable using Tailwind CSS."
  },
  {
    "slug": "interactive-grid-pattern",
    "title": "Interactive Grid Pattern",
    "description": "A interactive background grid pattern made with SVGs, fully customizable using Tailwind CSS."
  },
  {
    "slug": "dot-pattern",
    "title": "Dot Pattern",
    "description": "A background dot pattern made with SVGs, fully customizable using Tailwind CSS."
  },
  {
    "slug": "flickering-grid",
    "title": "Flickering Grid",
    "description": "A flickering grid background made with SVGs, fully customizable using Tailwind CSS."
  },
  {
    "slug": "hero-video-dialog",
    "title": "Hero Video Dialog",
    "description": "A hero video dialog component."
  },
  {
    "slug": "code-comparison",
    "title": "Code Comparison",
    "description": "A component which compares two code snippets."
  },
  {
    "slug": "marquee",
    "title": "Marquee",
    "description": "An infinite scrolling component that can be used to display text, images, or videos."
  },
  {
    "slug": "glyph-matrix",
    "title": "Glyph Matrix",
    "description": "An animated grid of subtly shifting glyphs with fade effect and theme support."
  },
  {
    "slug": "globe",
    "title": "Globe",
    "description": "An autorotating, interactive, and highly performant globe made using WebGL."
  },
  {
    "slug": "shimmer-button",
    "title": "Shimmer Button",
    "description": "A button with a shimmering light which travels around the perimeter."
  },
  {
    "slug": "tweet-card",
    "title": "Tweet Card",
    "description": "A card that displays a tweet with the author's name, handle, and profile picture."
  },
  {
    "slug": "client-tweet-card",
    "title": "Client Tweet Card",
    "description": "A client-side version of the tweet card that displays a tweet with the author's name, handle, and profile picture."
  },
  {
    "slug": "bento-grid",
    "title": "Bento Grid",
    "description": "Bento grid is a layout used to showcase the features of a product in a simple and elegant way."
  },
  {
    "slug": "particles",
    "title": "Particles",
    "description": "Particles are a fun way to add some visual flair to your website. They can be used to create a sense of depth, movement, and interactivity."
  },
  {
    "slug": "number-ticker",
    "title": "Number Ticker",
    "description": "Animate numbers to count up or down to a target number"
  },
  {
    "slug": "ripple",
    "title": "Ripple",
    "description": "An animated ripple effect typically used behind elements to emphasize them."
  },
  {
    "slug": "retro-grid",
    "title": "Retro Grid",
    "description": "An animated scrolling retro grid effect"
  },
  {
    "slug": "animated-list",
    "title": "Animated List",
    "description": "A list that animates each item in sequence with a delay. Used to showcase notifications or events on your landing page."
  },
  {
    "slug": "animated-shiny-text",
    "title": "Animated Shiny Text",
    "description": "A light glare effect which pans across text making it appear as if it is shimmering."
  },
  {
    "slug": "animated-grid-pattern",
    "title": "Animated Grid Pattern",
    "description": "A animated background grid pattern made with SVGs, fully customizable using Tailwind CSS."
  },
  {
    "slug": "border-beam",
    "title": "Border Beam",
    "description": "An animated beam of light which travels along the border of its container."
  },
  {
    "slug": "animated-beam",
    "title": "Animated Beam",
    "description": "An animated beam of light which travels along a path. Useful for showcasing the integration features of a website."
  },
  {
    "slug": "text-reveal",
    "title": "Text Reveal",
    "description": "Fade in text as you scroll down the page."
  },
  {
    "slug": "hyper-text",
    "title": "Hyper Text",
    "description": "A text animation that scrambles letters before revealing the final text."
  },
  {
    "slug": "animated-gradient-text",
    "title": "Animated Gradient Text",
    "description": "An animated gradient background which transitions between colors for text."
  },
  {
    "slug": "orbiting-circles",
    "title": "Orbiting Circles",
    "description": "A collection of circles which move in orbit along a circular path"
  },
  {
    "slug": "dock",
    "title": "Dock",
    "description": "An implementation of the MacOS dock using react + tailwindcss + motion"
  },
  {
    "slug": "word-rotate",
    "title": "Word Rotate",
    "description": "A vertical rotation of words"
  },
  {
    "slug": "avatar-circles",
    "title": "Avatar Circles",
    "description": "Overlapping circles of avatars."
  },
  {
    "slug": "typing-animation",
    "title": "Typing Animation",
    "description": "Characters appearing in typed animation"
  },
  {
    "slug": "sparkles-text",
    "title": "Sparkles Text",
    "description": "A dynamic text that generates continuous sparkles with smooth transitions, perfect for highlighting text with animated stars."
  },
  {
    "slug": "spinning-text",
    "title": "Spinning Text",
    "description": "The Spinning Text component animates text in a circular motion with customizable speed, direction, color, and transitions for dynamic and engaging effects."
  },
  {
    "slug": "comic-text",
    "title": "Comic Text",
    "description": "Comic text animation"
  },
  {
    "slug": "icon-cloud",
    "title": "Icon Cloud",
    "description": "An interactive 3D tag cloud component"
  },
  {
    "slug": "text-animate",
    "title": "Text Animate",
    "description": "A text animation component that animates text using a variety of different animations."
  },
  {
    "slug": "scroll-based-velocity",
    "title": "Scroll Based Velocity",
    "description": "Scrolling text whose speed changes based on scroll speed"
  },
  {
    "slug": "shiny-button",
    "title": "Shiny Button",
    "description": "A shiny button component with dynamic styles in the dark mode or light mode."
  },
  {
    "slug": "shine-border",
    "title": "Shine Border",
    "description": "Shine border is an animated background border effect."
  },
  {
    "slug": "animated-circular-progress-bar",
    "title": "Animated Circular Progress Bar",
    "description": "Animated Circular Progress Bar is a component that displays a circular gauge with a percentage value."
  },
  {
    "slug": "confetti",
    "title": "Confetti",
    "description": "Confetti animations are best used to delight your users when something special happens"
  },
  {
    "slug": "animated-subscribe-button",
    "title": "Animated Subscribe Button",
    "description": "An animated subscribe button useful for showing a micro animation from intial to final result."
  },
  {
    "slug": "cool-mode",
    "title": "Cool Mode",
    "description": "Cool mode effect for buttons, links, and other DOMs"
  },
  {
    "slug": "pulsating-button",
    "title": "Pulsating Button",
    "description": "An animated pulsating button useful for capturing attention of users."
  },
  {
    "slug": "ripple-button",
    "title": "Ripple Button",
    "description": "An animated button with ripple useful for user engagement."
  },
  {
    "slug": "file-tree",
    "title": "File Tree",
    "description": "A component used to showcase the folder and file structure of a directory."
  },
  {
    "slug": "blur-fade",
    "title": "Blur Fade",
    "description": "Blur fade in and out animation. Used to smoothly fade in and out content."
  },
  {
    "slug": "safari",
    "title": "Safari",
    "description": "A safari browser mockup to showcase your website."
  },
  {
    "slug": "rainbow-button",
    "title": "Rainbow Button",
    "description": "An animated button with a rainbow effect."
  },
  {
    "slug": "interactive-hover-button",
    "title": "interactive-hover-button",
    "description": ""
  },
  {
    "slug": "terminal",
    "title": "Terminal",
    "description": "A terminal component"
  },
  {
    "slug": "video-text",
    "title": "Video Text",
    "description": "A component that displays text with a video playing in the background."
  },
  {
    "slug": "pixel-image",
    "title": "Pixel Image",
    "description": "A component that displays an image with a pixelated effect, creating a retro aesthetic."
  },
  {
    "slug": "highlighter",
    "title": "Highlighter",
    "description": "A text highlighter that mimics the effect of a human-drawn marker stroke."
  },
  {
    "slug": "animated-theme-toggler",
    "title": "Theme Toggler",
    "description": "A component for theme changing animation."
  }
] as const;
export const MAGICUI_OFFICIAL_COMPONENT_VARIANTS = {
  "MagicCard": [
    {
      "id": "magic-magic-card-magic-card-demo",
      "label": "Magic Card Demo",
      "props": {
        "componentSlug": "magic-card",
        "registryDemo": "magic-magic-card-magic-card-demo"
      }
    }
  ],
  "Android": [
    {
      "id": "magic-android-android-demo",
      "label": "Android Demo",
      "props": {
        "componentSlug": "android",
        "registryDemo": "magic-android-android-demo"
      }
    },
    {
      "id": "magic-android-android-demo-2",
      "label": "Android Demo 2",
      "props": {
        "componentSlug": "android",
        "registryDemo": "magic-android-android-demo-2"
      }
    },
    {
      "id": "magic-android-android-demo-3",
      "label": "Android Demo 3",
      "props": {
        "componentSlug": "android",
        "registryDemo": "magic-android-android-demo-3"
      }
    }
  ],
  "WarpBackground": [
    {
      "id": "magic-warp-background-warp-background-demo",
      "label": "Warp Background Demo",
      "props": {
        "componentSlug": "warp-background",
        "registryDemo": "magic-warp-background-warp-background-demo"
      }
    }
  ],
  "LineShadowText": [
    {
      "id": "magic-line-shadow-text-line-shadow-text-demo",
      "label": "Line Shadow Text Demo",
      "props": {
        "componentSlug": "line-shadow-text",
        "registryDemo": "magic-line-shadow-text-line-shadow-text-demo"
      }
    }
  ],
  "AuroraText": [
    {
      "id": "magic-aurora-text-aurora-text-demo",
      "label": "Aurora Text Demo",
      "props": {
        "componentSlug": "aurora-text",
        "registryDemo": "magic-aurora-text-aurora-text-demo"
      }
    }
  ],
  "MorphingText": [
    {
      "id": "magic-morphing-text-morphing-text-demo",
      "label": "Morphing Text Demo",
      "props": {
        "componentSlug": "morphing-text",
        "registryDemo": "magic-morphing-text-morphing-text-demo"
      }
    }
  ],
  "ScrollProgress": [
    {
      "id": "magic-scroll-progress-scroll-progress-demo",
      "label": "Scroll Progress Demo",
      "props": {
        "componentSlug": "scroll-progress",
        "registryDemo": "magic-scroll-progress-scroll-progress-demo"
      }
    }
  ],
  "Lens": [
    {
      "id": "magic-lens-lens-demo",
      "label": "Lens Demo",
      "props": {
        "componentSlug": "lens",
        "registryDemo": "magic-lens-lens-demo"
      }
    },
    {
      "id": "magic-lens-lens-demo-2",
      "label": "Lens Demo 2",
      "props": {
        "componentSlug": "lens",
        "registryDemo": "magic-lens-lens-demo-2"
      }
    },
    {
      "id": "magic-lens-lens-demo-3",
      "label": "Lens Demo 3",
      "props": {
        "componentSlug": "lens",
        "registryDemo": "magic-lens-lens-demo-3"
      }
    }
  ],
  "Pointer": [
    {
      "id": "magic-pointer-pointer-demo-1",
      "label": "Pointer Demo 1",
      "props": {
        "componentSlug": "pointer",
        "registryDemo": "magic-pointer-pointer-demo-1"
      }
    }
  ],
  "SmoothCursor": [
    {
      "id": "magic-smooth-cursor-smooth-cursor-demo",
      "label": "Smooth Cursor Demo",
      "props": {
        "componentSlug": "smooth-cursor",
        "registryDemo": "magic-smooth-cursor-smooth-cursor-demo"
      }
    }
  ],
  "ProgressiveBlur": [
    {
      "id": "magic-progressive-blur-progressive-blur-demo",
      "label": "Progressive Blur Demo",
      "props": {
        "componentSlug": "progressive-blur",
        "registryDemo": "magic-progressive-blur-progressive-blur-demo"
      }
    }
  ],
  "NeonGradientCard": [
    {
      "id": "magic-neon-gradient-card-neon-gradient-card-demo",
      "label": "Neon Gradient Card Demo",
      "props": {
        "componentSlug": "neon-gradient-card",
        "registryDemo": "magic-neon-gradient-card-neon-gradient-card-demo"
      }
    }
  ],
  "Meteors": [
    {
      "id": "magic-meteors-meteors-demo",
      "label": "Meteors Demo",
      "props": {
        "componentSlug": "meteors",
        "registryDemo": "magic-meteors-meteors-demo"
      }
    }
  ],
  "GridPattern": [
    {
      "id": "magic-grid-pattern-grid-pattern-demo",
      "label": "Grid Pattern Demo",
      "props": {
        "componentSlug": "grid-pattern",
        "registryDemo": "magic-grid-pattern-grid-pattern-demo"
      }
    },
    {
      "id": "magic-grid-pattern-grid-pattern-linear-gradient",
      "label": "Grid Pattern Linear Gradient",
      "props": {
        "componentSlug": "grid-pattern",
        "registryDemo": "magic-grid-pattern-grid-pattern-linear-gradient"
      }
    },
    {
      "id": "magic-grid-pattern-grid-pattern-dashed",
      "label": "Grid Pattern Dashed",
      "props": {
        "componentSlug": "grid-pattern",
        "registryDemo": "magic-grid-pattern-grid-pattern-dashed"
      }
    }
  ],
  "StripedPattern": [
    {
      "id": "magic-striped-pattern-striped-pattern-demo",
      "label": "Striped Pattern Demo",
      "props": {
        "componentSlug": "striped-pattern",
        "registryDemo": "magic-striped-pattern-striped-pattern-demo"
      }
    },
    {
      "id": "magic-striped-pattern-striped-pattern-left",
      "label": "Striped Pattern (Left)",
      "props": {
        "componentSlug": "striped-pattern",
        "registryDemo": "magic-striped-pattern-striped-pattern-left"
      }
    },
    {
      "id": "magic-striped-pattern-striped-pattern-right",
      "label": "Striped Pattern (Right)",
      "props": {
        "componentSlug": "striped-pattern",
        "registryDemo": "magic-striped-pattern-striped-pattern-right"
      }
    }
  ],
  "InteractiveGridPattern": [
    {
      "id": "magic-interactive-grid-pattern-interactive-grid-pattern-demo",
      "label": "Interactive Grid Pattern Demo",
      "props": {
        "componentSlug": "interactive-grid-pattern",
        "registryDemo": "magic-interactive-grid-pattern-interactive-grid-pattern-demo"
      }
    },
    {
      "id": "magic-interactive-grid-pattern-interactive-grid-pattern-demo-2",
      "label": "Interactive Grid Pattern Demo 2",
      "props": {
        "componentSlug": "interactive-grid-pattern",
        "registryDemo": "magic-interactive-grid-pattern-interactive-grid-pattern-demo-2"
      }
    }
  ],
  "DotPattern": [
    {
      "id": "magic-dot-pattern-dot-pattern-demo",
      "label": "Dot Pattern Demo",
      "props": {
        "componentSlug": "dot-pattern",
        "registryDemo": "magic-dot-pattern-dot-pattern-demo"
      }
    },
    {
      "id": "magic-dot-pattern-dot-pattern-linear-gradient",
      "label": "Dot Pattern Linear Gradient",
      "props": {
        "componentSlug": "dot-pattern",
        "registryDemo": "magic-dot-pattern-dot-pattern-linear-gradient"
      }
    },
    {
      "id": "magic-dot-pattern-dot-pattern-with-glow-effect",
      "label": "Dot Pattern with glow effect",
      "props": {
        "componentSlug": "dot-pattern",
        "registryDemo": "magic-dot-pattern-dot-pattern-with-glow-effect"
      }
    }
  ],
  "FlickeringGrid": [
    {
      "id": "magic-flickering-grid-flickering-grid-demo",
      "label": "Flickering Grid Demo",
      "props": {
        "componentSlug": "flickering-grid",
        "registryDemo": "magic-flickering-grid-flickering-grid-demo"
      }
    },
    {
      "id": "magic-flickering-grid-flickering-grid-rounded-demo",
      "label": "Flickering Grid Rounded Demo",
      "props": {
        "componentSlug": "flickering-grid",
        "registryDemo": "magic-flickering-grid-flickering-grid-rounded-demo"
      }
    }
  ],
  "HeroVideoDialog": [
    {
      "id": "magic-hero-video-dialog-hero-video-dialog-demo",
      "label": "Hero Video Dialog Demo",
      "props": {
        "componentSlug": "hero-video-dialog",
        "registryDemo": "magic-hero-video-dialog-hero-video-dialog-demo"
      }
    },
    {
      "id": "magic-hero-video-dialog-hero-video-dialog-demo-top-in-bottom-out",
      "label": "Hero Video Dialog Top In Bottom Out Demo",
      "props": {
        "componentSlug": "hero-video-dialog",
        "registryDemo": "magic-hero-video-dialog-hero-video-dialog-demo-top-in-bottom-out"
      }
    }
  ],
  "CodeComparison": [
    {
      "id": "magic-code-comparison-code-comparison-demo",
      "label": "Code Comparison Demo",
      "props": {
        "componentSlug": "code-comparison",
        "registryDemo": "magic-code-comparison-code-comparison-demo"
      }
    }
  ],
  "Marquee": [
    {
      "id": "magic-marquee-marquee-demo",
      "label": "Marquee Demo",
      "props": {
        "componentSlug": "marquee",
        "registryDemo": "magic-marquee-marquee-demo"
      }
    },
    {
      "id": "magic-marquee-marquee-demo-vertical",
      "label": "Marquee Vertical Demo",
      "props": {
        "componentSlug": "marquee",
        "registryDemo": "magic-marquee-marquee-demo-vertical"
      }
    },
    {
      "id": "magic-marquee-marquee-logos",
      "label": "Marquee Logos",
      "props": {
        "componentSlug": "marquee",
        "registryDemo": "magic-marquee-marquee-logos"
      }
    },
    {
      "id": "magic-marquee-marquee-3d",
      "label": "Marquee 3D",
      "props": {
        "componentSlug": "marquee",
        "registryDemo": "magic-marquee-marquee-3d"
      }
    },
    {
      "id": "magic-marquee-bento-demo",
      "label": "Bento Demo",
      "props": {
        "componentSlug": "marquee",
        "registryDemo": "magic-marquee-bento-demo"
      }
    }
  ],
  "GlyphMatrix": [
    {
      "id": "magic-glyph-matrix-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "glyph-matrix"
      }
    }
  ],
  "Globe": [
    {
      "id": "magic-globe-globe-demo",
      "label": "Globe Demo",
      "props": {
        "componentSlug": "globe",
        "registryDemo": "magic-globe-globe-demo"
      }
    }
  ],
  "ShimmerButton": [
    {
      "id": "magic-shimmer-button-shimmer-button-demo",
      "label": "Shimmer Button Demo",
      "props": {
        "componentSlug": "shimmer-button",
        "registryDemo": "magic-shimmer-button-shimmer-button-demo"
      }
    }
  ],
  "TweetCard": [
    {
      "id": "magic-tweet-card-tweet-card-demo",
      "label": "Tweet Card Demo",
      "props": {
        "componentSlug": "tweet-card",
        "registryDemo": "magic-tweet-card-tweet-card-demo"
      }
    },
    {
      "id": "magic-tweet-card-tweet-card-images",
      "label": "Tweet Card Images",
      "props": {
        "componentSlug": "tweet-card",
        "registryDemo": "magic-tweet-card-tweet-card-images"
      }
    },
    {
      "id": "magic-tweet-card-tweet-card-meta-preview",
      "label": "Tweet Card Meta Preview",
      "props": {
        "componentSlug": "tweet-card",
        "registryDemo": "magic-tweet-card-tweet-card-meta-preview"
      }
    }
  ],
  "ClientTweetCard": [
    {
      "id": "magic-client-tweet-card-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "client-tweet-card"
      }
    }
  ],
  "BentoGrid": [
    {
      "id": "magic-bento-grid-bento-demo",
      "label": "Bento Demo",
      "props": {
        "componentSlug": "bento-grid",
        "registryDemo": "magic-bento-grid-bento-demo"
      }
    },
    {
      "id": "magic-bento-grid-bento-demo-vertical",
      "label": "Bento Vertical Demo",
      "props": {
        "componentSlug": "bento-grid",
        "registryDemo": "magic-bento-grid-bento-demo-vertical"
      }
    }
  ],
  "Particles": [
    {
      "id": "magic-particles-particles-demo",
      "label": "Particles Demo",
      "props": {
        "componentSlug": "particles",
        "registryDemo": "magic-particles-particles-demo"
      }
    }
  ],
  "NumberTicker": [
    {
      "id": "magic-number-ticker-number-ticker-demo",
      "label": "Number Ticker Demo",
      "props": {
        "componentSlug": "number-ticker",
        "registryDemo": "magic-number-ticker-number-ticker-demo"
      }
    },
    {
      "id": "magic-number-ticker-number-ticker-demo-2",
      "label": "Number Ticker Demo 2",
      "props": {
        "componentSlug": "number-ticker",
        "registryDemo": "magic-number-ticker-number-ticker-demo-2"
      }
    },
    {
      "id": "magic-number-ticker-number-ticker-decimal-demo",
      "label": "Number Ticker Decimal Demo",
      "props": {
        "componentSlug": "number-ticker",
        "registryDemo": "magic-number-ticker-number-ticker-decimal-demo"
      }
    }
  ],
  "Ripple": [
    {
      "id": "magic-ripple-ripple-demo",
      "label": "Ripple Demo",
      "props": {
        "componentSlug": "ripple",
        "registryDemo": "magic-ripple-ripple-demo"
      }
    }
  ],
  "RetroGrid": [
    {
      "id": "magic-retro-grid-retro-grid-demo",
      "label": "Retro Grid Demo",
      "props": {
        "componentSlug": "retro-grid",
        "registryDemo": "magic-retro-grid-retro-grid-demo"
      }
    }
  ],
  "AnimatedList": [
    {
      "id": "magic-animated-list-animated-list-demo",
      "label": "Animated List Demo",
      "props": {
        "componentSlug": "animated-list",
        "registryDemo": "magic-animated-list-animated-list-demo"
      }
    }
  ],
  "AnimatedShinyText": [
    {
      "id": "magic-animated-shiny-text-animated-shiny-text-demo",
      "label": "Animated Shiny Text Demo",
      "props": {
        "componentSlug": "animated-shiny-text",
        "registryDemo": "magic-animated-shiny-text-animated-shiny-text-demo"
      }
    }
  ],
  "AnimatedGridPattern": [
    {
      "id": "magic-animated-grid-pattern-animated-grid-pattern-demo",
      "label": "Animated Grid Pattern Demo",
      "props": {
        "componentSlug": "animated-grid-pattern",
        "registryDemo": "magic-animated-grid-pattern-animated-grid-pattern-demo"
      }
    }
  ],
  "BorderBeam": [
    {
      "id": "magic-border-beam-border-beam-demo",
      "label": "Border Beam Demo",
      "props": {
        "componentSlug": "border-beam",
        "registryDemo": "magic-border-beam-border-beam-demo"
      }
    },
    {
      "id": "magic-border-beam-border-beam-demo-2",
      "label": "Border Beam Demo",
      "props": {
        "componentSlug": "border-beam",
        "registryDemo": "magic-border-beam-border-beam-demo-2"
      }
    },
    {
      "id": "magic-border-beam-border-beam-demo-3",
      "label": "Border Beam Demo 3",
      "props": {
        "componentSlug": "border-beam",
        "registryDemo": "magic-border-beam-border-beam-demo-3"
      }
    },
    {
      "id": "magic-border-beam-border-beam-demo-4",
      "label": "Border Beam Demo 4",
      "props": {
        "componentSlug": "border-beam",
        "registryDemo": "magic-border-beam-border-beam-demo-4"
      }
    }
  ],
  "AnimatedBeam": [
    {
      "id": "magic-animated-beam-animated-beam-demo",
      "label": "Animated Beam Demo",
      "props": {
        "componentSlug": "animated-beam",
        "registryDemo": "magic-animated-beam-animated-beam-demo"
      }
    },
    {
      "id": "magic-animated-beam-animated-beam-unidirectional",
      "label": "Animated Beam Unidirectional",
      "props": {
        "componentSlug": "animated-beam",
        "registryDemo": "magic-animated-beam-animated-beam-unidirectional"
      }
    },
    {
      "id": "magic-animated-beam-animated-beam-bidirectional",
      "label": "Animated Beam Bidirectional",
      "props": {
        "componentSlug": "animated-beam",
        "registryDemo": "magic-animated-beam-animated-beam-bidirectional"
      }
    },
    {
      "id": "magic-animated-beam-animated-beam-multiple-inputs",
      "label": "Animated Beam Multiple Inputs",
      "props": {
        "componentSlug": "animated-beam",
        "registryDemo": "magic-animated-beam-animated-beam-multiple-inputs"
      }
    },
    {
      "id": "magic-animated-beam-animated-beam-multiple-outputs",
      "label": "Animated Beam Multiple Outputs",
      "props": {
        "componentSlug": "animated-beam",
        "registryDemo": "magic-animated-beam-animated-beam-multiple-outputs"
      }
    }
  ],
  "TextReveal": [
    {
      "id": "magic-text-reveal-text-reveal-demo",
      "label": "Text Reveal Demo",
      "props": {
        "componentSlug": "text-reveal",
        "registryDemo": "magic-text-reveal-text-reveal-demo"
      }
    }
  ],
  "HyperText": [
    {
      "id": "magic-hyper-text-hyper-text-demo",
      "label": "Hyper Text Demo",
      "props": {
        "componentSlug": "hyper-text",
        "registryDemo": "magic-hyper-text-hyper-text-demo"
      }
    }
  ],
  "AnimatedGradientText": [
    {
      "id": "magic-animated-gradient-text-animated-gradient-text-demo",
      "label": "Animated Gradient Text Demo",
      "props": {
        "componentSlug": "animated-gradient-text",
        "registryDemo": "magic-animated-gradient-text-animated-gradient-text-demo"
      }
    },
    {
      "id": "magic-animated-gradient-text-animated-gradient-text-demo-2",
      "label": "Animated Gradient Text Demo 2",
      "props": {
        "componentSlug": "animated-gradient-text",
        "registryDemo": "magic-animated-gradient-text-animated-gradient-text-demo-2"
      }
    }
  ],
  "OrbitingCircles": [
    {
      "id": "magic-orbiting-circles-orbiting-circles-demo",
      "label": "Orbiting Circles Demo",
      "props": {
        "componentSlug": "orbiting-circles",
        "registryDemo": "magic-orbiting-circles-orbiting-circles-demo"
      }
    }
  ],
  "Dock": [
    {
      "id": "magic-dock-dock-demo",
      "label": "Dock Demo",
      "props": {
        "componentSlug": "dock",
        "registryDemo": "magic-dock-dock-demo"
      }
    },
    {
      "id": "magic-dock-dock-demo-2",
      "label": "Dock Demo 2",
      "props": {
        "componentSlug": "dock",
        "registryDemo": "magic-dock-dock-demo-2"
      }
    },
    {
      "id": "magic-dock-dock-demo-3",
      "label": "Dock Demo 3",
      "props": {
        "componentSlug": "dock",
        "registryDemo": "magic-dock-dock-demo-3"
      }
    }
  ],
  "WordRotate": [
    {
      "id": "magic-word-rotate-word-rotate-demo",
      "label": "Word Rotate Demo",
      "props": {
        "componentSlug": "word-rotate",
        "registryDemo": "magic-word-rotate-word-rotate-demo"
      }
    }
  ],
  "AvatarCircles": [
    {
      "id": "magic-avatar-circles-avatar-circles-demo",
      "label": "Avatar Circles Demo",
      "props": {
        "componentSlug": "avatar-circles",
        "registryDemo": "magic-avatar-circles-avatar-circles-demo"
      }
    }
  ],
  "TypingAnimation": [
    {
      "id": "magic-typing-animation-typing-animation-demo",
      "label": "Typing Animation Demo",
      "props": {
        "componentSlug": "typing-animation",
        "registryDemo": "magic-typing-animation-typing-animation-demo"
      }
    }
  ],
  "SparklesText": [
    {
      "id": "magic-sparkles-text-sparkles-text-demo",
      "label": "Sparkles Text Demo",
      "props": {
        "componentSlug": "sparkles-text",
        "registryDemo": "magic-sparkles-text-sparkles-text-demo"
      }
    }
  ],
  "SpinningText": [
    {
      "id": "magic-spinning-text-spinning-text-demo",
      "label": "Spinning Text Demo",
      "props": {
        "componentSlug": "spinning-text",
        "registryDemo": "magic-spinning-text-spinning-text-demo"
      }
    },
    {
      "id": "magic-spinning-text-spinning-text-demo-2",
      "label": "Spinning Text Demo 2",
      "props": {
        "componentSlug": "spinning-text",
        "registryDemo": "magic-spinning-text-spinning-text-demo-2"
      }
    }
  ],
  "ComicText": [
    {
      "id": "magic-comic-text-comic-text-demo",
      "label": "Comic Text Demo",
      "props": {
        "componentSlug": "comic-text",
        "registryDemo": "magic-comic-text-comic-text-demo"
      }
    }
  ],
  "IconCloud": [
    {
      "id": "magic-icon-cloud-icon-cloud-demo",
      "label": "Icon Cloud Demo",
      "props": {
        "componentSlug": "icon-cloud",
        "registryDemo": "magic-icon-cloud-icon-cloud-demo"
      }
    },
    {
      "id": "magic-icon-cloud-icon-cloud-demo-2",
      "label": "Icon Cloud Demo 2",
      "props": {
        "componentSlug": "icon-cloud",
        "registryDemo": "magic-icon-cloud-icon-cloud-demo-2"
      }
    },
    {
      "id": "magic-icon-cloud-icon-cloud-demo-3",
      "label": "Icon Cloud Demo 3",
      "props": {
        "componentSlug": "icon-cloud",
        "registryDemo": "magic-icon-cloud-icon-cloud-demo-3"
      }
    }
  ],
  "TextAnimate": [
    {
      "id": "magic-text-animate-text-animate-demo",
      "label": "Text Animate Demo",
      "props": {
        "componentSlug": "text-animate",
        "registryDemo": "magic-text-animate-text-animate-demo"
      }
    },
    {
      "id": "magic-text-animate-text-animate-demo-2",
      "label": "Text Animate Demo 2",
      "props": {
        "componentSlug": "text-animate",
        "registryDemo": "magic-text-animate-text-animate-demo-2"
      }
    },
    {
      "id": "magic-text-animate-text-animate-demo-3",
      "label": "Text Animate Demo 3",
      "props": {
        "componentSlug": "text-animate",
        "registryDemo": "magic-text-animate-text-animate-demo-3"
      }
    },
    {
      "id": "magic-text-animate-text-animate-demo-4",
      "label": "Text Animate Demo 4",
      "props": {
        "componentSlug": "text-animate",
        "registryDemo": "magic-text-animate-text-animate-demo-4"
      }
    },
    {
      "id": "magic-text-animate-text-animate-demo-5",
      "label": "Text Animate Demo 5",
      "props": {
        "componentSlug": "text-animate",
        "registryDemo": "magic-text-animate-text-animate-demo-5"
      }
    },
    {
      "id": "magic-text-animate-text-animate-demo-6",
      "label": "Text Animate Demo 6",
      "props": {
        "componentSlug": "text-animate",
        "registryDemo": "magic-text-animate-text-animate-demo-6"
      }
    },
    {
      "id": "magic-text-animate-text-animate-demo-7",
      "label": "Text Animate Demo 7",
      "props": {
        "componentSlug": "text-animate",
        "registryDemo": "magic-text-animate-text-animate-demo-7"
      }
    },
    {
      "id": "magic-text-animate-text-animate-demo-8",
      "label": "Text Animate Demo 8",
      "props": {
        "componentSlug": "text-animate",
        "registryDemo": "magic-text-animate-text-animate-demo-8"
      }
    },
    {
      "id": "magic-text-animate-text-animate-demo-9",
      "label": "Text Animate Demo 9",
      "props": {
        "componentSlug": "text-animate",
        "registryDemo": "magic-text-animate-text-animate-demo-9"
      }
    }
  ],
  "ScrollBasedVelocity": [
    {
      "id": "magic-scroll-based-velocity-scroll-based-velocity-demo",
      "label": "Scroll Based Velocity Demo",
      "props": {
        "componentSlug": "scroll-based-velocity",
        "registryDemo": "magic-scroll-based-velocity-scroll-based-velocity-demo"
      }
    },
    {
      "id": "magic-scroll-based-velocity-scroll-based-velocity-images-demo",
      "label": "Scroll Based Velocity Images",
      "props": {
        "componentSlug": "scroll-based-velocity",
        "registryDemo": "magic-scroll-based-velocity-scroll-based-velocity-images-demo"
      }
    }
  ],
  "ShinyButton": [
    {
      "id": "magic-shiny-button-shiny-button-demo",
      "label": "Shiny Button Demo",
      "props": {
        "componentSlug": "shiny-button",
        "registryDemo": "magic-shiny-button-shiny-button-demo"
      }
    }
  ],
  "ShineBorder": [
    {
      "id": "magic-shine-border-shine-border-demo",
      "label": "Shine Border Demo",
      "props": {
        "componentSlug": "shine-border",
        "registryDemo": "magic-shine-border-shine-border-demo"
      }
    },
    {
      "id": "magic-shine-border-shine-border-demo-2",
      "label": "Shine Border Demo 2",
      "props": {
        "componentSlug": "shine-border",
        "registryDemo": "magic-shine-border-shine-border-demo-2"
      }
    }
  ],
  "AnimatedCircularProgressBar": [
    {
      "id": "magic-animated-circular-progress-bar-animated-circular-316a341e",
      "label": "Animated Circular Progress Bar Demo",
      "props": {
        "componentSlug": "animated-circular-progress-bar",
        "registryDemo": "magic-animated-circular-progress-bar-animated-circular-316a341e"
      }
    }
  ],
  "Confetti": [
    {
      "id": "magic-confetti-confetti-demo",
      "label": "Confetti Demo",
      "props": {
        "componentSlug": "confetti",
        "registryDemo": "magic-confetti-confetti-demo"
      }
    },
    {
      "id": "magic-confetti-confetti-basic-cannon",
      "label": "Confetti Basic Cannon",
      "props": {
        "componentSlug": "confetti",
        "registryDemo": "magic-confetti-confetti-basic-cannon"
      }
    },
    {
      "id": "magic-confetti-confetti-random-direction",
      "label": "Confetti Random Direction",
      "props": {
        "componentSlug": "confetti",
        "registryDemo": "magic-confetti-confetti-random-direction"
      }
    },
    {
      "id": "magic-confetti-confetti-fireworks",
      "label": "Confetti Fireworks",
      "props": {
        "componentSlug": "confetti",
        "registryDemo": "magic-confetti-confetti-fireworks"
      }
    },
    {
      "id": "magic-confetti-confetti-stars",
      "label": "Confetti Stars",
      "props": {
        "componentSlug": "confetti",
        "registryDemo": "magic-confetti-confetti-stars"
      }
    },
    {
      "id": "magic-confetti-confetti-side-cannons",
      "label": "Confetti Side Cannons",
      "props": {
        "componentSlug": "confetti",
        "registryDemo": "magic-confetti-confetti-side-cannons"
      }
    },
    {
      "id": "magic-confetti-confetti-custom-shapes",
      "label": "Confetti Custom Shapes",
      "props": {
        "componentSlug": "confetti",
        "registryDemo": "magic-confetti-confetti-custom-shapes"
      }
    },
    {
      "id": "magic-confetti-confetti-emoji",
      "label": "Confetti Emoji",
      "props": {
        "componentSlug": "confetti",
        "registryDemo": "magic-confetti-confetti-emoji"
      }
    }
  ],
  "AnimatedSubscribeButton": [
    {
      "id": "magic-animated-subscribe-button-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "animated-subscribe-button"
      }
    }
  ],
  "CoolMode": [
    {
      "id": "magic-cool-mode-cool-mode-demo",
      "label": "Cool Mode Demo",
      "props": {
        "componentSlug": "cool-mode",
        "registryDemo": "magic-cool-mode-cool-mode-demo"
      }
    },
    {
      "id": "magic-cool-mode-cool-mode-custom",
      "label": "Cool Mode Custom",
      "props": {
        "componentSlug": "cool-mode",
        "registryDemo": "magic-cool-mode-cool-mode-custom"
      }
    }
  ],
  "PulsatingButton": [
    {
      "id": "magic-pulsating-button-pulsating-button-demo",
      "label": "Pulsating Button Demo",
      "props": {
        "componentSlug": "pulsating-button",
        "registryDemo": "magic-pulsating-button-pulsating-button-demo"
      }
    }
  ],
  "RippleButton": [
    {
      "id": "magic-ripple-button-ripple-button-demo",
      "label": "Ripple Button Demo",
      "props": {
        "componentSlug": "ripple-button",
        "registryDemo": "magic-ripple-button-ripple-button-demo"
      }
    }
  ],
  "FileTree": [
    {
      "id": "magic-file-tree-file-tree-demo",
      "label": "File Tree Demo",
      "props": {
        "componentSlug": "file-tree",
        "registryDemo": "magic-file-tree-file-tree-demo"
      }
    }
  ],
  "BlurFade": [
    {
      "id": "magic-blur-fade-blur-fade-demo",
      "label": "Blur Fade Demo",
      "props": {
        "componentSlug": "blur-fade",
        "registryDemo": "magic-blur-fade-blur-fade-demo"
      }
    },
    {
      "id": "magic-blur-fade-blur-fade-text-demo",
      "label": "Blur Fade Text Demo",
      "props": {
        "componentSlug": "blur-fade",
        "registryDemo": "magic-blur-fade-blur-fade-text-demo"
      }
    }
  ],
  "Safari": [
    {
      "id": "magic-safari-safari-demo",
      "label": "Safari Demo",
      "props": {
        "componentSlug": "safari",
        "registryDemo": "magic-safari-safari-demo"
      }
    },
    {
      "id": "magic-safari-safari-demo-2",
      "label": "Safari Demo 2",
      "props": {
        "componentSlug": "safari",
        "registryDemo": "magic-safari-safari-demo-2"
      }
    },
    {
      "id": "magic-safari-safari-demo-3",
      "label": "Safari Demo 3",
      "props": {
        "componentSlug": "safari",
        "registryDemo": "magic-safari-safari-demo-3"
      }
    },
    {
      "id": "magic-safari-safari-demo-4",
      "label": "Safari Demo 4",
      "props": {
        "componentSlug": "safari",
        "registryDemo": "magic-safari-safari-demo-4"
      }
    }
  ],
  "RainbowButton": [
    {
      "id": "magic-rainbow-button-rainbow-button-demo",
      "label": "Rainbow Button Demo",
      "props": {
        "componentSlug": "rainbow-button",
        "registryDemo": "magic-rainbow-button-rainbow-button-demo"
      }
    },
    {
      "id": "magic-rainbow-button-rainbow-button-demo-2",
      "label": "Rainbow Button Demo 2",
      "props": {
        "componentSlug": "rainbow-button",
        "registryDemo": "magic-rainbow-button-rainbow-button-demo-2"
      }
    }
  ],
  "InteractiveHoverButton": [
    {
      "id": "magic-interactive-hover-button-interactive-hover-button-demo",
      "label": "Interactive Hover Button Demo",
      "props": {
        "componentSlug": "interactive-hover-button",
        "registryDemo": "magic-interactive-hover-button-interactive-hover-button-demo"
      }
    }
  ],
  "Terminal": [
    {
      "id": "magic-terminal-terminal-demo",
      "label": "Terminal Demo",
      "props": {
        "componentSlug": "terminal",
        "registryDemo": "magic-terminal-terminal-demo"
      }
    }
  ],
  "VideoText": [
    {
      "id": "magic-video-text-video-text-demo",
      "label": "Video Text Demo",
      "props": {
        "componentSlug": "video-text",
        "registryDemo": "magic-video-text-video-text-demo"
      }
    }
  ],
  "PixelImage": [
    {
      "id": "magic-pixel-image-pixel-image-demo",
      "label": "Pixel Image Demo",
      "props": {
        "componentSlug": "pixel-image",
        "registryDemo": "magic-pixel-image-pixel-image-demo"
      }
    }
  ],
  "Highlighter": [
    {
      "id": "magic-highlighter-highlighter-demo",
      "label": "Highlighter Demo",
      "props": {
        "componentSlug": "highlighter",
        "registryDemo": "magic-highlighter-highlighter-demo"
      }
    }
  ],
  "AnimatedThemeToggler": [
    {
      "id": "magic-animated-theme-toggler-animated-theme-toggler-demo",
      "label": "Animated Theme Toggler Demo",
      "props": {
        "componentSlug": "animated-theme-toggler",
        "registryDemo": "magic-animated-theme-toggler-animated-theme-toggler-demo"
      }
    }
  ]
} as const satisfies Record<string, readonly UiComponentVariant[]>;
