// Generated by scripts/sync-spell-registry.mjs from the official Spell UI registry.
import type { UiComponentVariant } from './ui-library.js';
export const SPELL_OFFICIAL_COMPONENT_VARIANTS = {
  "Chart": [
    {
      "id": "spell-chart-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "chart"
      }
    }
  ],
  "BlurReveal": [
    {
      "id": "spell-blur-reveal-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "blur-reveal"
      }
    }
  ],
  "PerspectiveBook": [
    {
      "id": "spell-perspective-book-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "perspective-book"
      }
    }
  ],
  "Badge": [
    {
      "id": "spell-badge-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "badge"
      }
    }
  ],
  "ColorSelector": [
    {
      "id": "spell-color-selector-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "color-selector"
      }
    }
  ],
  "SpecialText": [
    {
      "id": "spell-special-text-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "special-text"
      }
    }
  ],
  "ShimmerText": [
    {
      "id": "spell-shimmer-text-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "shimmer-text"
      }
    }
  ],
  "HighlightedText": [
    {
      "id": "spell-highlighted-text-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "highlighted-text"
      }
    }
  ],
  "RichButton": [
    {
      "id": "spell-rich-button-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "rich-button"
      }
    }
  ],
  "Kbd": [
    {
      "id": "spell-kbd-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "kbd"
      }
    }
  ],
  "LabelInput": [
    {
      "id": "spell-label-input-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "label-input"
      }
    }
  ],
  "Spinner": [
    {
      "id": "spell-spinner-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "spinner"
      }
    }
  ],
  "BarsSpinner": [
    {
      "id": "spell-bars-spinner-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "bars-spinner"
      }
    }
  ],
  "FlowButton": [
    {
      "id": "spell-flow-button-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "flow-button"
      }
    }
  ],
  "SlideUpText": [
    {
      "id": "spell-slide-up-text-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "slide-up-text"
      }
    }
  ],
  "CopyButton": [
    {
      "id": "spell-copy-button-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "copy-button"
      }
    }
  ],
  "TextMarquee": [
    {
      "id": "spell-text-marquee-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "text-marquee"
      }
    }
  ],
  "WordsStagger": [
    {
      "id": "spell-words-stagger-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "words-stagger"
      }
    }
  ],
  "TiltCard": [
    {
      "id": "spell-tilt-card-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "tilt-card"
      }
    }
  ],
  "Marquee": [
    {
      "id": "spell-marquee-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "marquee"
      }
    }
  ],
  "Signature": [
    {
      "id": "spell-signature-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "signature"
      }
    }
  ],
  "RandomizedText": [
    {
      "id": "spell-randomized-text-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "randomized-text"
      }
    }
  ],
  "PopButton": [
    {
      "id": "spell-pop-button-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "pop-button"
      }
    }
  ],
  "Tweet": [
    {
      "id": "spell-tweet-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "tweet"
      }
    }
  ],
  "SpotifyCard": [
    {
      "id": "spell-spotify-card-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "spotify-card"
      }
    }
  ],
  "LightRays": [
    {
      "id": "spell-light-rays-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "light-rays"
      }
    }
  ],
  "AnimatedGradient": [
    {
      "id": "spell-animated-gradient-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "animated-gradient"
      }
    }
  ],
  "AnimatedCheckbox": [
    {
      "id": "spell-animated-checkbox-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "animated-checkbox"
      }
    }
  ],
  "ExplodingInput": [
    {
      "id": "spell-exploding-input-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "exploding-input"
      }
    }
  ],
  "GradientWaveText": [
    {
      "id": "spell-gradient-wave-text-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "gradient-wave-text"
      }
    }
  ],
  "LogosCarousel": [
    {
      "id": "spell-logos-carousel-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "logos-carousel"
      }
    }
  ],
  "QrCode": [
    {
      "id": "spell-qr-code-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "qr-code"
      }
    }
  ],
  "FallbackAvatar": [
    {
      "id": "spell-fallback-avatar-official-source",
      "label": "官方组件示例",
      "props": {
        "componentSlug": "fallback-avatar"
      }
    }
  ]
} as const satisfies Record<string, readonly UiComponentVariant[]>;
