import type React from 'react';

import { ProjectPreviewPane } from '../PreviewPane';
import type { UseProjectExplorerPreviewPanePropsParams } from './projectPreviewPanePropTypes';

export const buildProjectExplorerPreviewPaneProps = ({
  selectedFile,
  selectedPath,
  selectedEntry,
  loadingFile,
  error,
  searchQuery,
  searchCaseSensitive,
  searchWholeWord,
  activeSearchHitIndex,
  totalSearchHits,
  canOpenPreviousSearchHit,
  canOpenNextSearchHit,
  selectedLog,
  runStatus,
  runCatalogLoading,
  projectMembers,
  projectMembersLoading,
  runnerScriptExists,
  runnerScriptChecking,
  runnerScriptPath,
  runnerStartCommand,
  runnerStopCommand,
  runnerRestartCommand,
  starting,
  stopping,
  restarting,
  runnerMessage,
  runnerError,
  previewTargetLine,
  previewTargetLineRevision,
  navCapabilities,
  navCapabilitiesError,
  searchResults,
  activeSearchHitId,
  selectedToken,
  navResult,
  navRequestKind,
  navLoading,
  navError,
  activeNavLocationId,
  documentSymbols,
  documentSymbolsLoading,
  documentSymbolsError,
  handleTokenSelection,
  clearTokenSelection,
  requestDefinition,
  requestReferences,
  handleSearchInProject,
  handleOpenPreviousSearchHit,
  handleOpenNextSearchHit,
  handleActivateSearchHit,
  handleOpenNavLocation,
  handleOpenDocumentSymbol,
  handleRunnerStart,
  handleRunnerStop,
  handleRunnerRestart,
  refreshRunnerState,
  handleGenerateRunnerScriptForContact,
}: UseProjectExplorerPreviewPanePropsParams): React.ComponentProps<typeof ProjectPreviewPane> => ({
  selectedFile,
  selectedPath,
  selectedEntry,
  loadingFile,
  error,
  searchQuery,
  searchCaseSensitive,
  searchWholeWord,
  activeSearchHitIndex,
  totalSearchHits,
  canOpenPreviousSearchHit,
  canOpenNextSearchHit,
  selectedLog,
  runStatus,
  runCatalogLoading,
  projectMembers,
  projectMembersLoading,
  runnerScriptExists,
  runnerScriptChecking,
  runnerScriptPath,
  runnerStartCommand,
  runnerStopCommand,
  runnerRestartCommand,
  starting,
  stopping,
  restarting,
  runnerMessage,
  runnerError,
  targetLine: previewTargetLine,
  targetLineRevision: previewTargetLineRevision,
  navCapabilities,
  navCapabilitiesError,
  searchResults,
  activeSearchHitId,
  selectedToken,
  navResult,
  navRequestKind,
  navLoading,
  navError,
  activeNavLocationId,
  documentSymbols,
  documentSymbolsLoading,
  documentSymbolsError,
  onTokenSelection: handleTokenSelection,
  onClearTokenSelection: clearTokenSelection,
  onRequestDefinition: () => {
    void requestDefinition();
  },
  onRequestReferences: () => {
    void requestReferences();
  },
  onSearchInProject: handleSearchInProject,
  onOpenPreviousSearchHit: () => {
    void handleOpenPreviousSearchHit();
  },
  onOpenNextSearchHit: () => {
    void handleOpenNextSearchHit();
  },
  onActivateSearchHit: handleActivateSearchHit,
  onOpenNavLocation: (location) => {
    void handleOpenNavLocation(location);
  },
  onOpenDocumentSymbol: handleOpenDocumentSymbol,
  onRunnerStart: () => {
    void handleRunnerStart();
  },
  onRunnerStop: () => {
    void handleRunnerStop();
  },
  onRunnerRestart: () => {
    void handleRunnerRestart();
  },
  onRefreshRunnerState: () => {
    void refreshRunnerState();
  },
  onGenerateRunnerScriptForContact: handleGenerateRunnerScriptForContact,
});

export const buildProjectExplorerPreviewPanePropsDeps = ({
  activeNavLocationId,
  activeSearchHitId,
  activeSearchHitIndex,
  canOpenNextSearchHit,
  canOpenPreviousSearchHit,
  clearTokenSelection,
  documentSymbols,
  documentSymbolsError,
  documentSymbolsLoading,
  error,
  handleActivateSearchHit,
  handleGenerateRunnerScriptForContact,
  handleOpenDocumentSymbol,
  handleOpenNavLocation,
  handleOpenNextSearchHit,
  handleOpenPreviousSearchHit,
  handleRunnerRestart,
  handleRunnerStart,
  handleRunnerStop,
  handleSearchInProject,
  handleTokenSelection,
  loadingFile,
  navCapabilities,
  navCapabilitiesError,
  navError,
  navLoading,
  navRequestKind,
  navResult,
  previewTargetLine,
  previewTargetLineRevision,
  projectMembers,
  projectMembersLoading,
  requestDefinition,
  requestReferences,
  refreshRunnerState,
  restarting,
  runCatalogLoading,
  runStatus,
  runnerError,
  runnerMessage,
  runnerRestartCommand,
  runnerScriptChecking,
  runnerScriptExists,
  runnerScriptPath,
  runnerStartCommand,
  runnerStopCommand,
  searchCaseSensitive,
  searchQuery,
  searchResults,
  searchWholeWord,
  selectedEntry,
  selectedFile,
  selectedLog,
  selectedPath,
  selectedToken,
  starting,
  stopping,
  totalSearchHits,
}: UseProjectExplorerPreviewPanePropsParams): React.DependencyList => [
  activeNavLocationId,
  activeSearchHitId,
  activeSearchHitIndex,
  canOpenNextSearchHit,
  canOpenPreviousSearchHit,
  clearTokenSelection,
  documentSymbols,
  documentSymbolsError,
  documentSymbolsLoading,
  error,
  handleActivateSearchHit,
  handleGenerateRunnerScriptForContact,
  handleOpenDocumentSymbol,
  handleOpenNavLocation,
  handleOpenNextSearchHit,
  handleOpenPreviousSearchHit,
  handleRunnerRestart,
  handleRunnerStart,
  handleRunnerStop,
  handleSearchInProject,
  handleTokenSelection,
  loadingFile,
  navCapabilities,
  navCapabilitiesError,
  navError,
  navLoading,
  navRequestKind,
  navResult,
  previewTargetLine,
  previewTargetLineRevision,
  projectMembers,
  projectMembersLoading,
  requestDefinition,
  requestReferences,
  refreshRunnerState,
  restarting,
  runCatalogLoading,
  runStatus,
  runnerError,
  runnerMessage,
  runnerRestartCommand,
  runnerScriptChecking,
  runnerScriptExists,
  runnerScriptPath,
  runnerStartCommand,
  runnerStopCommand,
  searchCaseSensitive,
  searchQuery,
  searchResults,
  searchWholeWord,
  selectedEntry,
  selectedFile,
  selectedLog,
  selectedPath,
  selectedToken,
  starting,
  stopping,
  totalSearchHits,
];
