import type React from 'react';

import { ProjectPreviewPane } from '../PreviewPane';
import type { UseProjectExplorerPreviewPanePropsParams } from './projectPreviewPanePropTypes';

export const buildProjectExplorerPreviewPaneProps = ({
  selectedFile,
  selectedPath,
  selectedEntry,
  loadingFile,
  error,
  searchQuery,
  searchCaseSensitive,
  searchWholeWord,
  activeSearchHitIndex,
  totalSearchHits,
  canOpenPreviousSearchHit,
  canOpenNextSearchHit,
  previewTargetLine,
  previewTargetLineRevision,
  navCapabilities,
  navCapabilitiesError,
  searchResults,
  activeSearchHitId,
  selectedToken,
  navResult,
  navRequestKind,
  navLoading,
  navError,
  activeNavLocationId,
  canGoBackFromNav,
  documentSymbols,
  documentSymbolsLoading,
  documentSymbolsError,
  handleTokenSelection,
  clearTokenSelection,
  requestDefinition,
  requestReferences,
  goBackFromNav,
  handleSearchInProject,
  handleOpenPreviousSearchHit,
  handleOpenNextSearchHit,
  handleActivateSearchHit,
  handleOpenNavLocation,
  handleOpenDocumentSymbol,
}: UseProjectExplorerPreviewPanePropsParams): React.ComponentProps<typeof ProjectPreviewPane> => ({
  selectedFile,
  selectedPath,
  selectedEntry,
  loadingFile,
  error,
  searchQuery,
  searchCaseSensitive,
  searchWholeWord,
  activeSearchHitIndex,
  totalSearchHits,
  canOpenPreviousSearchHit,
  canOpenNextSearchHit,
  targetLine: previewTargetLine,
  targetLineRevision: previewTargetLineRevision,
  navCapabilities,
  navCapabilitiesError,
  searchResults,
  activeSearchHitId,
  selectedToken,
  navResult,
  navRequestKind,
  navLoading,
  navError,
  activeNavLocationId,
  canGoBackFromNav,
  documentSymbols,
  documentSymbolsLoading,
  documentSymbolsError,
  onTokenSelection: handleTokenSelection,
  onClearTokenSelection: clearTokenSelection,
  onRequestDefinition: () => {
    void requestDefinition();
  },
  onRequestReferences: () => {
    void requestReferences();
  },
  onGoBackFromNav: () => {
    void goBackFromNav();
  },
  onSearchInProject: handleSearchInProject,
  onOpenPreviousSearchHit: () => {
    void handleOpenPreviousSearchHit();
  },
  onOpenNextSearchHit: () => {
    void handleOpenNextSearchHit();
  },
  onActivateSearchHit: handleActivateSearchHit,
  onOpenNavLocation: (location) => {
    void handleOpenNavLocation(location);
  },
  onOpenDocumentSymbol: handleOpenDocumentSymbol,
});

export const buildProjectExplorerPreviewPanePropsDeps = ({
  activeNavLocationId,
  activeSearchHitId,
  activeSearchHitIndex,
  canOpenNextSearchHit,
  canOpenPreviousSearchHit,
  clearTokenSelection,
  documentSymbols,
  documentSymbolsError,
  documentSymbolsLoading,
  error,
  handleActivateSearchHit,
  handleOpenDocumentSymbol,
  handleOpenNavLocation,
  handleOpenNextSearchHit,
  handleOpenPreviousSearchHit,
  handleSearchInProject,
  handleTokenSelection,
  loadingFile,
  navCapabilities,
  navCapabilitiesError,
  navError,
  navLoading,
  navRequestKind,
  navResult,
  canGoBackFromNav,
  previewTargetLine,
  previewTargetLineRevision,
  requestDefinition,
  requestReferences,
  goBackFromNav,
  searchCaseSensitive,
  searchQuery,
  searchResults,
  searchWholeWord,
  selectedEntry,
  selectedFile,
  selectedPath,
  selectedToken,
  totalSearchHits,
}: UseProjectExplorerPreviewPanePropsParams): React.DependencyList => [
  activeNavLocationId,
  activeSearchHitId,
  activeSearchHitIndex,
  canOpenNextSearchHit,
  canOpenPreviousSearchHit,
  clearTokenSelection,
  documentSymbols,
  documentSymbolsError,
  documentSymbolsLoading,
  error,
  handleActivateSearchHit,
  handleOpenDocumentSymbol,
  handleOpenNavLocation,
  handleOpenNextSearchHit,
  handleOpenPreviousSearchHit,
  handleSearchInProject,
  handleTokenSelection,
  loadingFile,
  navCapabilities,
  navCapabilitiesError,
  navError,
  navLoading,
  navRequestKind,
  navResult,
  canGoBackFromNav,
  previewTargetLine,
  previewTargetLineRevision,
  requestDefinition,
  requestReferences,
  goBackFromNav,
  searchCaseSensitive,
  searchQuery,
  searchResults,
  searchWholeWord,
  selectedEntry,
  selectedFile,
  selectedPath,
  selectedToken,
  totalSearchHits,
];
