import type React from 'react';

import { ProjectTreePane } from '../TreePane';
import type { UseProjectExplorerTreePanePropsParams } from './projectTreePanePropTypes';

export const buildProjectExplorerTreePaneProps = ({
  project,
  treeWidth,
  treeScrollRef,
  entriesMap,
  expandedPaths,
  loadingPaths,
  selectedPath,
  selectedEntry,
  draggingEntryPath,
  dropTargetDirPath,
  actionLoading,
  actionReloadPath,
  canConfirmCurrent,
  showOnlyChanged,
  changeSummary,
  loadingSummary,
  summaryError,
  actionMessage,
  actionError,
  searchQuery,
  searchCaseSensitive,
  searchWholeWord,
  searchResults,
  searchLoading,
  searchError,
  searchTruncated,
  activeSearchHitId,
  activeSearchHitIndex,
  totalSearchHits,
  aggregatedChangeKindByPath,
  normalizePath,
  toExpandedKey,
  canDropToDirectory,
  setSelectedPath,
  setSelectedFile,
  setShowOnlyChanged,
  setDraggingEntryPath,
  setDropTargetDirPath,
  clearDragExpandTimer,
  cancelDragExpandIfMatches,
  scheduleDragExpand,
  clearDragAutoScroll,
  startDragAutoScroll,
  selectProjectRoot,
  toggleDir,
  openFile,
  handleCreateDirectory,
  handleCreateFile,
  handleRefresh,
  handleConfirmCurrentChanges,
  handleConfirmAllChanges,
  handleSearchQueryChange,
  handleSearchCaseSensitiveChange,
  handleSearchWholeWordChange,
  canOpenPreviousSearchHit,
  canOpenNextSearchHit,
  handleClearSearch,
  handleOpenSearchHit,
  handleOpenPreviousSearchHit,
  handleOpenNextSearchHit,
  handleMoveEntryByDrop,
  openEntryContextMenu,
  handleDragStart,
  handleDragEnd,
}: UseProjectExplorerTreePanePropsParams): React.ComponentProps<typeof ProjectTreePane> => ({
  project,
  treeWidth,
  treeScrollRef,
  entriesMap,
  expandedPaths,
  loadingPaths,
  selectedPath,
  selectedEntry,
  draggingEntryPath,
  dropTargetDirPath,
  actionLoading,
  actionReloadPath,
  canConfirmCurrent,
  showOnlyChanged,
  changeSummary,
  loadingSummary,
  summaryError,
  actionMessage,
  actionError,
  searchQuery,
  searchCaseSensitive,
  searchWholeWord,
  searchResults,
  searchLoading,
  searchError,
  searchTruncated,
  activeSearchHitId,
  activeSearchHitIndex,
  totalSearchHits,
  canOpenPreviousSearchHit,
  canOpenNextSearchHit,
  aggregatedChangeKindByPath,
  normalizePath,
  toExpandedKey,
  canDropToDirectory,
  onSelectProjectRoot: () => {
    void selectProjectRoot();
  },
  onToggleShowOnlyChanged: () => {
    setShowOnlyChanged((prev) => !prev);
  },
  onCreateDirectoryAtRoot: () => {
    void handleCreateDirectory(project.rootPath);
  },
  onCreateFileAtRoot: () => {
    void handleCreateFile(project.rootPath);
  },
  onRefresh: () => {
    void handleRefresh();
  },
  onConfirmCurrent: () => {
    void handleConfirmCurrentChanges();
  },
  onConfirmAll: () => {
    void handleConfirmAllChanges();
  },
  onSearchQueryChange: handleSearchQueryChange,
  onToggleSearchCaseSensitive: () => {
    handleSearchCaseSensitiveChange((prev) => !prev);
  },
  onToggleSearchWholeWord: () => {
    handleSearchWholeWordChange((prev) => !prev);
  },
  onClearSearch: handleClearSearch,
  onOpenPreviousSearchHit: () => {
    void handleOpenPreviousSearchHit();
  },
  onOpenNextSearchHit: () => {
    void handleOpenNextSearchHit();
  },
  onOpenContextMenu: openEntryContextMenu,
  onOpenSearchHit: (hit) => {
    void handleOpenSearchHit(hit);
  },
  onSelectDeletedPath: (path) => {
    setSelectedPath(path);
    setSelectedFile(null);
  },
  onSelectMarkedPath: (path) => {
    setSelectedPath(path);
    setSelectedFile(null);
  },
  onToggleDir: (entry) => {
    void toggleDir(entry);
  },
  onOpenFile: (entry) => {
    void openFile(entry);
  },
  onDragStart: handleDragStart,
  onDragEnd: handleDragEnd,
  onSetDropTargetDirPath: setDropTargetDirPath,
  onSetDraggingEntryPath: setDraggingEntryPath,
  onMoveEntryByDrop: (sourcePath, targetDirPath) => {
    void handleMoveEntryByDrop(sourcePath, targetDirPath);
  },
  onScheduleDragExpand: scheduleDragExpand,
  onCancelDragExpandIfMatches: cancelDragExpandIfMatches,
  onClearDragExpandTimer: clearDragExpandTimer,
  onStartDragAutoScroll: startDragAutoScroll,
  onClearDragAutoScroll: clearDragAutoScroll,
});

export const buildProjectExplorerTreePanePropsDeps = ({
  actionError,
  actionLoading,
  actionMessage,
  actionReloadPath,
  activeSearchHitId,
  activeSearchHitIndex,
  aggregatedChangeKindByPath,
  canOpenNextSearchHit,
  canOpenPreviousSearchHit,
  canConfirmCurrent,
  canDropToDirectory,
  cancelDragExpandIfMatches,
  changeSummary,
  clearDragAutoScroll,
  clearDragExpandTimer,
  draggingEntryPath,
  dropTargetDirPath,
  entriesMap,
  expandedPaths,
  handleConfirmAllChanges,
  handleConfirmCurrentChanges,
  handleCreateDirectory,
  handleCreateFile,
  handleClearSearch,
  handleDragEnd,
  handleDragStart,
  handleMoveEntryByDrop,
  handleOpenNextSearchHit,
  handleOpenPreviousSearchHit,
  handleOpenSearchHit,
  handleRefresh,
  handleSearchCaseSensitiveChange,
  handleSearchQueryChange,
  handleSearchWholeWordChange,
  loadingPaths,
  loadingSummary,
  normalizePath,
  openEntryContextMenu,
  openFile,
  project,
  scheduleDragExpand,
  searchCaseSensitive,
  searchError,
  searchLoading,
  searchQuery,
  searchResults,
  searchTruncated,
  searchWholeWord,
  selectProjectRoot,
  selectedEntry,
  selectedPath,
  setDraggingEntryPath,
  setDropTargetDirPath,
  setSelectedFile,
  setSelectedPath,
  setShowOnlyChanged,
  showOnlyChanged,
  startDragAutoScroll,
  summaryError,
  toExpandedKey,
  toggleDir,
  totalSearchHits,
  treeScrollRef,
  treeWidth,
}: UseProjectExplorerTreePanePropsParams): React.DependencyList => [
  actionError,
  actionLoading,
  actionMessage,
  actionReloadPath,
  activeSearchHitId,
  activeSearchHitIndex,
  aggregatedChangeKindByPath,
  canOpenNextSearchHit,
  canOpenPreviousSearchHit,
  canConfirmCurrent,
  canDropToDirectory,
  cancelDragExpandIfMatches,
  changeSummary,
  clearDragAutoScroll,
  clearDragExpandTimer,
  draggingEntryPath,
  dropTargetDirPath,
  entriesMap,
  expandedPaths,
  handleConfirmAllChanges,
  handleConfirmCurrentChanges,
  handleCreateDirectory,
  handleCreateFile,
  handleClearSearch,
  handleDragEnd,
  handleDragStart,
  handleMoveEntryByDrop,
  handleOpenNextSearchHit,
  handleOpenPreviousSearchHit,
  handleOpenSearchHit,
  handleRefresh,
  handleSearchCaseSensitiveChange,
  handleSearchQueryChange,
  handleSearchWholeWordChange,
  loadingPaths,
  loadingSummary,
  normalizePath,
  openEntryContextMenu,
  openFile,
  project,
  scheduleDragExpand,
  searchCaseSensitive,
  searchError,
  searchLoading,
  searchQuery,
  searchResults,
  searchTruncated,
  searchWholeWord,
  selectProjectRoot,
  selectedEntry,
  selectedPath,
  setDraggingEntryPath,
  setDropTargetDirPath,
  setSelectedFile,
  setSelectedPath,
  setShowOnlyChanged,
  showOnlyChanged,
  startDragAutoScroll,
  summaryError,
  toExpandedKey,
  toggleDir,
  totalSearchHits,
  treeScrollRef,
  treeWidth,
];
