use std::collections::HashSet;

use crate::services::task_manager::normalizer::normalize_task_drafts;
use crate::services::task_manager::types::TaskDraft;
use crate::services::task_service_client::TaskExecutionResultContractDto;

fn slugify_task_ref(raw: &str) -> String {
    let mut out = String::new();
    let mut last_sep = false;

    for ch in raw.trim().chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            last_sep = false;
            continue;
        }

        if (ch == '_' || ch == '-' || ch.is_whitespace()) && !out.is_empty() && !last_sep {
            out.push('_');
            last_sep = true;
        }
    }

    out.trim_matches('_').to_string()
}

fn ensure_unique_task_ref(base: &str, used_refs: &mut HashSet<String>) -> String {
    let normalized_base = base.trim();
    let base = if normalized_base.is_empty() {
        "task".to_string()
    } else {
        normalized_base.to_string()
    };

    if used_refs.insert(base.clone()) {
        return base;
    }

    let mut index = 2;
    loop {
        let candidate = format!("{}_{}", base, index);
        if used_refs.insert(candidate.clone()) {
            return candidate;
        }
        index += 1;
    }
}

fn infer_verification_capabilities(required_capabilities: &[String]) -> Vec<String> {
    let mut out = vec!["read".to_string()];

    for capability in ["terminal", "remote"] {
        if required_capabilities.iter().any(|item| item == capability) {
            out.push(capability.to_string());
        }
    }

    out
}

fn infer_task_kind_required_capabilities(task_kind: Option<&str>) -> &'static [&'static str] {
    match task_kind.map(str::trim) {
        Some("implementation") => &["write"],
        Some("migration") => &["write", "terminal"],
        Some("documentation") => &["write"],
        _ => &[],
    }
}

fn auto_complete_task_kind_capabilities(mut draft_tasks: Vec<TaskDraft>) -> Vec<TaskDraft> {
    for draft in &mut draft_tasks {
        for capability in infer_task_kind_required_capabilities(draft.task_kind.as_deref()) {
            if !draft
                .required_builtin_capabilities
                .iter()
                .any(|item| item == capability)
            {
                draft
                    .required_builtin_capabilities
                    .push((*capability).to_string());
            }
        }
    }

    draft_tasks
}

fn auto_complete_task_graph_drafts(mut draft_tasks: Vec<TaskDraft>) -> Vec<TaskDraft> {
    let mut used_refs = draft_tasks
        .iter()
        .filter_map(|draft| {
            draft
                .task_ref
                .as_deref()
                .map(str::trim)
                .filter(|value| !value.is_empty())
                .map(ToOwned::to_owned)
        })
        .collect::<HashSet<_>>();

    for (index, draft) in draft_tasks.iter_mut().enumerate() {
        if draft.task_kind.as_deref() != Some("implementation") {
            continue;
        }
        if draft
            .task_ref
            .as_deref()
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .is_some()
        {
            continue;
        }

        let title_slug = slugify_task_ref(draft.title.as_str());
        let base = if title_slug.is_empty() {
            format!("impl_{}", index + 1)
        } else {
            format!("impl_{}", title_slug)
        };
        draft.task_ref = Some(ensure_unique_task_ref(base.as_str(), &mut used_refs));
    }

    let implementation_snapshots = draft_tasks
        .iter()
        .filter(|draft| draft.task_kind.as_deref() == Some("implementation"))
        .filter_map(|draft| {
            draft.task_ref.as_ref().map(|task_ref| {
                (
                    task_ref.clone(),
                    draft.title.clone(),
                    draft.required_builtin_capabilities.clone(),
                    draft.required_context_assets.clone(),
                    draft.planned_context_assets.clone(),
                )
            })
        })
        .collect::<Vec<_>>();

    let mut autogenerated = Vec::new();
    for (
        implementation_ref,
        implementation_title,
        implementation_capabilities,
        implementation_required_assets,
        implementation_planned_assets,
    ) in implementation_snapshots
    {
        let has_verification = draft_tasks.iter().any(|candidate| {
            candidate.task_kind.as_deref() == Some("verification")
                && (candidate
                    .depends_on_refs
                    .iter()
                    .any(|item| item == &implementation_ref)
                    || candidate
                        .verification_of_refs
                        .iter()
                        .any(|item| item == &implementation_ref))
        });
        if has_verification {
            continue;
        }

        let verification_ref = ensure_unique_task_ref(
            format!("verify_{}", implementation_ref).as_str(),
            &mut used_refs,
        );
        autogenerated.push(TaskDraft {
            title: format!("验证：{}", implementation_title),
            details: format!(
                "验证任务“{}”是否已完成，执行至少一种可复现的检查，输出验证结果、剩余风险与建议。",
                implementation_title
            ),
            task_ref: Some(verification_ref),
            task_kind: Some("verification".to_string()),
            depends_on_refs: vec![implementation_ref.clone()],
            verification_of_refs: vec![implementation_ref],
            acceptance_criteria: vec![
                "至少完成一种可复现的验证方式".to_string(),
                "输出验证结果与剩余风险".to_string(),
            ],
            priority: "medium".to_string(),
            status: "pending_confirm".to_string(),
            tags: vec!["verification".to_string(), "auto_generated".to_string()],
            due_at: None,
            required_builtin_capabilities: infer_verification_capabilities(
                implementation_capabilities.as_slice(),
            ),
            required_context_assets: implementation_required_assets,
            planned_builtin_mcp_ids: Vec::new(),
            planned_context_assets: implementation_planned_assets,
            execution_result_contract: Some(TaskExecutionResultContractDto {
                result_required: true,
                preferred_format: None,
            }),
        });
    }

    draft_tasks.extend(autogenerated);
    draft_tasks
}

fn validate_task_graph_drafts(draft_tasks: &[TaskDraft]) -> Result<(), String> {
    let mut known_refs = HashSet::new();

    for draft in draft_tasks {
        if let Some(task_ref) = draft
            .task_ref
            .as_deref()
            .map(str::trim)
            .filter(|value| !value.is_empty())
        {
            if !known_refs.insert(task_ref.to_string()) {
                return Err(format!("duplicate task_ref detected: {}", task_ref));
            }
        }
    }

    for draft in draft_tasks {
        let current_ref = draft
            .task_ref
            .as_deref()
            .map(str::trim)
            .filter(|value| !value.is_empty());
        for dependency_ref in &draft.depends_on_refs {
            if !known_refs.contains(dependency_ref.as_str()) {
                return Err(format!(
                    "depends_on_refs references unknown task_ref: {}",
                    dependency_ref
                ));
            }
            if current_ref == Some(dependency_ref.as_str()) {
                return Err(format!("task_ref cannot depend on itself: {}", dependency_ref));
            }
        }
        for verification_ref in &draft.verification_of_refs {
            if !known_refs.contains(verification_ref.as_str()) {
                return Err(format!(
                    "verification_of_refs references unknown task_ref: {}",
                    verification_ref
                ));
            }
        }
    }

    for draft in draft_tasks {
        if draft.task_kind.as_deref() != Some("implementation") {
            continue;
        }
        let Some(task_ref) = draft
            .task_ref
            .as_deref()
            .map(str::trim)
            .filter(|value| !value.is_empty())
        else {
            return Err(format!(
                "implementation task '{}' must provide task_ref",
                draft.title
            ));
        };
        let has_verification = draft_tasks.iter().any(|candidate| {
            candidate.task_kind.as_deref() == Some("verification")
                && (candidate.depends_on_refs.iter().any(|item| item == task_ref)
                    || candidate
                        .verification_of_refs
                        .iter()
                        .any(|item| item == task_ref))
        });
        if !has_verification {
            return Err(format!(
                "implementation task '{}' must have a verification task that references task_ref={}",
                draft.title, task_ref
            ));
        }
    }

    Ok(())
}

pub(crate) fn prepare_task_drafts_for_creation(
    draft_tasks: Vec<TaskDraft>,
) -> Result<Vec<TaskDraft>, String> {
    let draft_tasks = normalize_task_drafts(draft_tasks)?;
    let draft_tasks = auto_complete_task_kind_capabilities(draft_tasks);
    let draft_tasks = auto_complete_task_graph_drafts(draft_tasks);
    validate_task_graph_drafts(draft_tasks.as_slice())?;
    Ok(draft_tasks)
}
