import { build } from 'esbuild';

const common = {
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node18',
  sourcemap: false,
  banner: {
    js: 'import { createRequire } from "node:module"; const require = createRequire(import.meta.url);'
  }
};

await Promise.all([
  build({ ...common, entryPoints: ['src/mcp-server.ts'], outfile: 'dist/mcp-server.mjs' }),
  build({ ...common, entryPoints: ['src/studio-server.ts'], outfile: 'dist/studio-server.mjs' }),
  build({ ...common, entryPoints: ['src/schema.ts'], outfile: 'dist/schema.test.mjs' }),
  build({ ...common, entryPoints: ['src/editor-model.ts'], outfile: 'dist/editor-model.test.mjs' }),
  build({ ...common, entryPoints: ['src/html-exporter.ts'], outfile: 'dist/html-exporter.test.mjs' }),
  build({ ...common, entryPoints: ['src/react-exporter.ts'], outfile: 'dist/react-exporter.test.mjs' }),
  build({ ...common, entryPoints: ['src/vue-exporter.ts'], outfile: 'dist/vue-exporter.test.mjs' }),
  build({ ...common, entryPoints: ['src/component-library.ts'], outfile: 'dist/component-library.test.mjs' }),
  build({ ...common, entryPoints: ['src/antd-library.ts'], outfile: 'dist/antd-library.test.mjs' }),
  build({ ...common, entryPoints: ['src/antd-slots.ts'], outfile: 'dist/antd-slots.test.mjs' }),
  build({ ...common, entryPoints: ['src/ui-library.ts'], outfile: 'dist/ui-library.test.mjs' }),
  build({ ...common, entryPoints: ['src/chakra-library.ts'], outfile: 'dist/chakra-library.test.mjs' }),
  build({ ...common, entryPoints: ['src/shadcn-library.ts'], outfile: 'dist/shadcn-library.test.mjs' }),
  build({ ...common, entryPoints: ['src/creative-library.ts'], outfile: 'dist/creative-library.test.mjs' }),
  build({ ...common, entryPoints: ['src/magicui-library.ts'], outfile: 'dist/magicui-library.test.mjs' }),
  build({ ...common, entryPoints: ['src/spell-library.ts'], outfile: 'dist/spell-library.test.mjs' }),
  build({ ...common, entryPoints: ['src/inspira-library.ts'], outfile: 'dist/inspira-library.test.mjs' }),
  build({ ...common, entryPoints: ['ui-src/library-runtime/inspira-registry.generated.ts'], outfile: 'dist/inspira-registry.test.mjs' }),
  build({ ...common, entryPoints: ['ui-src/library-runtime/vue-registry-adapter.ts'], outfile: 'dist/vue-registry-adapter.test.mjs' }),
  build({ ...common, entryPoints: ['ui-src/library-runtime/shadcn-registry.generated.ts'], outfile: 'dist/shadcn-registry.test.mjs' }),
  build({ ...common, entryPoints: ['ui-src/library-runtime/daisyui-registry.generated.ts'], outfile: 'dist/daisyui-registry.test.mjs' }),
  build({ ...common, entryPoints: ['src/daisyui-library.ts'], outfile: 'dist/daisyui-library.test.mjs' }),
  build({ ...common, entryPoints: ['src/ui-libraries.ts'], outfile: 'dist/ui-libraries.test.mjs' }),
  build({ ...common, entryPoints: ['src/library-slots.ts'], outfile: 'dist/library-slots.test.mjs' }),
  build({ ...common, entryPoints: ['src/viewport-presets.ts'], outfile: 'dist/viewport-presets.test.mjs' }),
  build({ ...common, entryPoints: ['src/templates.ts'], outfile: 'dist/templates.test.mjs' }),
  build({ ...common, entryPoints: ['src/document-store.ts'], outfile: 'dist/document-store.test.mjs' }),
  build({ ...common, entryPoints: ['src/runtime-scope.ts'], outfile: 'dist/runtime-scope.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/phase0-baseline.ts'], outfile: 'dist/v2-phase0-baseline.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/phase2-layout-benchmarks.ts'], outfile: 'dist/v2-phase2-layout-benchmarks.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/scene-html-renderer.ts'], outfile: 'dist/v2-scene-html-renderer.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/design-protocol.ts'], outfile: 'dist/v2-design-protocol.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/design-generation-executor.ts'], outfile: 'dist/v2-design-generation-executor.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/visual-quality.ts'], outfile: 'dist/v2-visual-quality.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/scoped-ai-transaction.ts'], outfile: 'dist/v2-scoped-ai-transaction.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/annotation-ai-protocol.ts'], outfile: 'dist/v2-annotation-ai-protocol.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/design-repair-executor.ts'], outfile: 'dist/v2-design-repair-executor.test.mjs' }),
  build({ ...common, entryPoints: ['ui-src/studio/workspace-shell-model.ts'], outfile: 'dist/workspace-shell-model.test.mjs' }),
  build({ ...common, entryPoints: ['ui-src/studio/render-boundaries.ts'], outfile: 'dist/render-boundaries.test.mjs' }),
  build({ ...common, entryPoints: ['ui-src/studio/infinite-canvas-model.ts'], outfile: 'dist/infinite-canvas-model.test.mjs' }),
  build({ ...common, entryPoints: ['ui-src/studio/inspector-model.ts'], outfile: 'dist/inspector-model.test.mjs' }),
  build({ ...common, entryPoints: ['ui-src/library-runtime/element-selection.ts'], outfile: 'dist/library-preview-pointer.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/baseline-capture.ts'], outfile: 'dist/v2-baseline-capture.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/scene-schema.ts'], outfile: 'dist/v2-scene-schema.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/scene-query.ts'], outfile: 'dist/v2-scene-query.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/scene-diff.ts'], outfile: 'dist/v2-scene-diff.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/scene-variables.ts'], outfile: 'dist/v2-scene-variables.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/responsive-scene.ts'], outfile: 'dist/v2-responsive-scene.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/grid-tracks.ts'], outfile: 'dist/v2-grid-tracks.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/grid-placement.ts'], outfile: 'dist/v2-grid-placement.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/layout-engine.ts'], outfile: 'dist/v2-layout-engine.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/layout-calibration.ts'], outfile: 'dist/v2-layout-calibration.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/scene-transaction.ts'], outfile: 'dist/v2-scene-transaction.test.mjs' }),
  build({ ...common, entryPoints: ['src/v2/scene-store.ts'], outfile: 'dist/v2-scene-store.test.mjs' })
]);
