// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Required Notice: Copyright (c) 2025 AI Chat Team

use std::collections::{BTreeMap, BTreeSet};

use chrono::Utc;
use mongodb::Client;
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use uuid::Uuid;

use chatos_config_sdk::ConfigSnapshot;
use chatos_service_runtime::{build_http_client, HttpClientTimeouts};

use crate::catalog::{
    builtin_definitions, CHATOS_LOCAL_PROJECT_CREATION_CONFIG_KEY,
    LEGACY_AGENT_MAX_ITERATIONS_CONFIG_KEYS, LOCAL_CONNECTOR_CHATOS_INTERNAL_API_SECRET_CONFIG_KEY,
    LOCAL_CONNECTOR_MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
    LOCAL_CONNECTOR_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
    LOCAL_CONNECTOR_REQUIRE_SIGNED_INTERNAL_REQUESTS_CONFIG_KEY,
    LOCAL_CONNECTOR_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
    MCP_MANAGEMENT_ALLOWED_INTERNAL_CALLERS_CONFIG_KEY,
    MCP_MANAGEMENT_ASYNC_TOOL_DISPATCH_MODE_CONFIG_KEY,
    MCP_MANAGEMENT_ASYNC_TOOL_DISPATCH_QUEUE_CONFIG_KEY,
    MCP_MANAGEMENT_ASYNC_TOOL_LOCAL_QUEUE_BUFFER_CONFIG_KEY,
    MCP_MANAGEMENT_ASYNC_TOOL_RABBITMQ_EXCHANGE_CONFIG_KEY,
    MCP_MANAGEMENT_ASYNC_TOOL_RABBITMQ_URL_CONFIG_KEY,
    MCP_MANAGEMENT_ASYNC_TOOL_WORKER_CONCURRENCY_CONFIG_KEY,
    MCP_MANAGEMENT_CHATOS_INTERNAL_API_SECRET_CONFIG_KEY,
    MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
    MCP_MANAGEMENT_LOCAL_CONNECTOR_INTERNAL_API_SECRET_CONFIG_KEY,
    MCP_MANAGEMENT_PLUGIN_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
    MCP_MANAGEMENT_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
    MCP_MANAGEMENT_REQUIRE_SIGNED_INTERNAL_REQUESTS_CONFIG_KEY,
    MCP_MANAGEMENT_RUNTIME_GRANT_SECRET_CONFIG_KEY,
    MCP_MANAGEMENT_RUNTIME_SESSION_ENCRYPTION_SECRET_CONFIG_KEY,
    MCP_MANAGEMENT_SANDBOX_MANAGER_INTERNAL_API_SECRET_CONFIG_KEY,
    MCP_MANAGEMENT_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
    MEMORY_ENGINE_CHATOS_INTERNAL_API_SECRET_CONFIG_KEY, MEMORY_ENGINE_OPERATOR_TOKEN_CONFIG_KEY,
    MEMORY_ENGINE_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
    MEMORY_ENGINE_REQUIRE_SIGNED_INTERNAL_REQUESTS_CONFIG_KEY,
    MEMORY_ENGINE_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
    MEMORY_ENGINE_USER_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
    PROJECT_SERVICE_CHATOS_INTERNAL_API_SECRET_CONFIG_KEY,
    PROJECT_SERVICE_MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
    PROJECT_SERVICE_MEMORY_ENGINE_OPERATOR_TOKEN_CONFIG_KEY,
    PROJECT_SERVICE_REQUIRE_SIGNED_INTERNAL_REQUESTS_CONFIG_KEY,
    PROJECT_SERVICE_SANDBOX_MANAGER_CLIENT_ID_CONFIG_KEY,
    PROJECT_SERVICE_SANDBOX_MANAGER_CLIENT_KEY_CONFIG_KEY,
    PROJECT_SERVICE_SELF_INTERNAL_API_SECRET_CONFIG_KEY, PROJECT_SERVICE_SYNC_SECRET_CONFIG_KEY,
    PROJECT_SERVICE_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
    PROJECT_SERVICE_TASK_RUNNER_INTERNAL_SECRET_CONFIG_KEY,
    PROJECT_SERVICE_USER_SERVICE_INTERNAL_SECRET_CONFIG_KEY,
    SANDBOX_MANAGER_AGENT_TOKEN_SECRET_CONFIG_KEY,
    SANDBOX_MANAGER_MCP_MANAGEMENT_INTERNAL_API_SECRET_CONFIG_KEY,
    SANDBOX_MANAGER_OPERATOR_TOKEN_CONFIG_KEY, SANDBOX_MANAGER_POOL_MAX_ACTIVE_CONFIG_KEY,
    SANDBOX_MANAGER_POOL_MAX_PENDING_CONFIG_KEY,
    SANDBOX_MANAGER_PROJECT_SERVICE_INTERNAL_API_SECRET_CONFIG_KEY,
    SANDBOX_MANAGER_REQUIRE_SIGNED_INTERNAL_REQUESTS_CONFIG_KEY,
    SANDBOX_MANAGER_SYSTEM_CLIENT_ID_CONFIG_KEY, SANDBOX_MANAGER_SYSTEM_CLIENT_KEY_CONFIG_KEY,
    SANDBOX_MANAGER_TASK_RUNNER_INTERNAL_API_SECRET_CONFIG_KEY,
    TASK_RUNNER_EXECUTION_ENVIRONMENT_MODE_CONFIG_KEY, TASK_RUNNER_MAX_ITERATIONS_CONFIG_KEY,
    TASK_RUNNER_TOOL_RESULTS_TOTAL_MAX_CHARS_CONFIG_KEY,
    TASK_RUNNER_TOOL_RESULT_MAX_CHARS_CONFIG_KEY, USER_PREFERENCE_CONFIG_KEYS,
    USER_SERVICE_EMAIL_FROM_CONFIG_KEY, USER_SERVICE_EMAIL_FROM_NAME_CONFIG_KEY,
    USER_SERVICE_SMTP_HOST_CONFIG_KEY, USER_SERVICE_SMTP_PORT_CONFIG_KEY,
    USER_SERVICE_SMTP_USERNAME_CONFIG_KEY,
};
use crate::config::AppConfig;
use crate::models::{
    ActiveReleaseRecord, AuditEventRecord, ConfigDefinitionRecord, ConfigDraftRecord,
    ConfigReleaseRecord, CurrentUser, CustomDefinitionRequest, EffectiveConfigResponse,
    ServiceInstanceRecord, ValidationResponse,
};
use crate::store::AppStore;

#[derive(Clone)]
pub struct AppState {
    pub config: AppConfig,
    pub store: AppStore,
    http: reqwest::Client,
}

mod consul;
mod initialization;
mod maintenance;
mod releases;
mod support;
#[cfg(test)]
mod tests;

use self::support::*;
