import { shallow } from 'zustand/shallow';

import type { ChatStore as SessionListStoreHook } from '../../lib/store/createChatStoreWithBackend';

export const useSessionListStoreState = (storeToUse: SessionListStoreHook) => {
  return storeToUse((state) => ({
    sessions: state.sessions,
    contacts: state.contacts,
    agents: state.agents,
    currentSession: state.currentSession,
    activePanel: state.activePanel,
    loadSessions: state.loadSessions,
    loadContacts: state.loadContacts,
    createContact: state.createContact,
    updateContactTaskRunnerConfig: state.updateContactTaskRunnerConfig,
    deleteContact: state.deleteContact,
    markContactsStale: state.markContactsStale,
    removeContactLocally: state.removeContactLocally,
    applyRealtimeContactSnapshot: state.applyRealtimeContactSnapshot,
    refreshContactById: state.refreshContactById,
    createSession: state.createSession,
    selectSession: state.selectSession,
    deleteSession: state.deleteSession,
    updateSession: state.updateSession,
    markSessionsStale: state.markSessionsStale,
    removeSessionLocally: state.removeSessionLocally,
    applyRealtimeSessionSnapshot: state.applyRealtimeSessionSnapshot,
    refreshSessionById: state.refreshSessionById,
    loadAgents: state.loadAgents,
    sessionChatState: state.sessionChatState,
    projects: state.projects,
    currentProject: state.currentProject,
    loadProjects: state.loadProjects,
    createProject: state.createProject,
    selectProject: state.selectProject,
    deleteProject: state.deleteProject,
    markProjectsStale: state.markProjectsStale,
    removeProjectLocally: state.removeProjectLocally,
    applyRealtimeProjectSnapshot: state.applyRealtimeProjectSnapshot,
    refreshProjectById: state.refreshProjectById,
    setActivePanel: state.setActivePanel,
    terminals: state.terminals,
    currentTerminal: state.currentTerminal,
    loadTerminals: state.loadTerminals,
    createTerminal: state.createTerminal,
    selectTerminal: state.selectTerminal,
    deleteTerminal: state.deleteTerminal,
    markTerminalsStale: state.markTerminalsStale,
    removeTerminalLocally: state.removeTerminalLocally,
    applyRealtimeTerminalSnapshot: state.applyRealtimeTerminalSnapshot,
    refreshTerminalById: state.refreshTerminalById,
    remoteConnections: state.remoteConnections,
    currentRemoteConnection: state.currentRemoteConnection,
    loadRemoteConnections: state.loadRemoteConnections,
    createRemoteConnection: state.createRemoteConnection,
    updateRemoteConnection: state.updateRemoteConnection,
    selectRemoteConnection: state.selectRemoteConnection,
    deleteRemoteConnection: state.deleteRemoteConnection,
    openRemoteSftp: state.openRemoteSftp,
    markRemoteConnectionsStale: state.markRemoteConnectionsStale,
    removeRemoteConnectionLocally: state.removeRemoteConnectionLocally,
    applyRealtimeRemoteConnectionSnapshot: state.applyRealtimeRemoteConnectionSnapshot,
    refreshRemoteConnectionById: state.refreshRemoteConnectionById,
  }), shallow);
};
