# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Required Notice: Copyright (c) 2025 AI Chat Team

**
!Cargo.lock
!crates
!crates/chatos_builtin_tools
!crates/chatos_builtin_tools/**
!crates/chatos_mcp_runtime
!crates/chatos_mcp_runtime/**
!sandbox_manager_service
!sandbox_manager_service/sandbox_mcp_server
!sandbox_manager_service/sandbox_mcp_server/**
